### ISSUE TITLE
namespace created with generate_name can't be used as data

### ISSUE THREAD

**Issue by mogul** [hashicorp/terraform-provider-kubernetes#1009]
### Terraform Version and Provider Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2

### Affected Resource(s)
- namespace

### Terraform Configuration Files
```hcl
provider "kubernetes" {
}

resource "kubernetes_namespace" "test" {
  metadata {
    generate_name = "test-"
  }
}

data "kubernetes_namespace" "test" {
  metadata {
    name = kubernetes_namespace.test.id
    # Also fails with
    # name = kubernetes_namespace.test.metadata[0].name
  }
}

```

### Debug Output
https://gist.github.com/mogul/3c8409268bf35e6520a19bc55ad34ef9

### Panic Output
[none]

### Expected Behavior
data.kubernetes_namespace.test should populate

### Actual Behavior

```
kubernetes_namespace.test: Creating...
kubernetes_namespace.test: Creation complete after 0s [id=test-579hz]
data.kubernetes_namespace.test: Reading...

Error: Invalid address to set: []string{"metadata", "0", "generate_name"}

  on test.tf line 10, in data "kubernetes_namespace" "test":
  10: data "kubernetes_namespace" "test" {
```

You cannot `terraform apply`, `terraform plan`, or `terraform destroy` from this point without getting a similar error. (You have to comment out the `data` block first.)

### Steps to Reproduce
1. terraform apply -auto-approve            

### Important Factoids
I found this when creating a namespace with generate_name in one module, then trying to read it back out as data in another, unrelated module... I only put both the resource and the data block together here to make the smallest possible reproduction case.

### References
- Seems very similar to https://github.com/hashicorp/terraform-provider-kubernetes/issues/588

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mogul** [comment]
I am working around this for now by using the `random_id` resource and explicitly specifying a name, rather than using `generate_name`:

```hcl
resource "random_id" "namespace" {
  prefix = "test-"
  byte_length = 5
}

resource "kubernetes_namespace" "test" {
  metadata {
    name = random_id.namespace.dec
  }
}

data "kubernetes_namespace" "test" {
  metadata {
    name = kubernetes_namespace.test.id
  }
}
```

**Comment by aareet** [comment]
@mogul we suspect you're encountering this issue because the data source is evaluated before the resource. If you separate it out into separate apply operations, it would work.

Out of curiosity, what are you trying to accomplish with this workflow? We don't usually see this usage.

**Comment by mogul** [comment]
I create a namespace with the kubernetes provider, and want to use it immediately for making a release using the helm provider (eg a single apply).

I'm makimg a Helm release in an underlying k8s "brokerable" via the OSB API. [This OSB API broker implementation](https://github.com/pivotal/cloud-service-broker) uses Terraform on the backend. The code has moved on a bit from where it was when I filled this, and as I think about using Dependency Injection to better help with chicken-and-egg concerns, but if you're interested [the source is open](https://github.com/GSA/template-brokerpak/tree/helm-prototype).

**Comment by mogul** [comment]
(Incidentally the next thing I'm taking on will be making a full EKS deployment brokerable.)

**Comment by dak1n1** [comment]
The usage pattern we usually see here is to refer to the resource itself, instead of a data source reading the resource. The data source can't be accessed during the same apply as the resource creation. But you can still refer to the resource like this:

```
[dakini@dax 20201007]$ cat main.tf 
resource "kubernetes_namespace" "test" {
  metadata {
    generate_name = "test"
  }
}

resource "kubernetes_secret" "test" {
  metadata {
    name      = "test"
    namespace = kubernetes_namespace.test.metadata.0.name
  }
}
```

The `terraform apply` creates both resources at once:

```
kubernetes_namespace.test: Creating...
kubernetes_namespace.test: Creation complete after 0s [id=testcsbc5]
kubernetes_secret.test: Creating...
kubernetes_secret.test: Creation complete after 0s [id=testcsbc5/test]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

[dakini@dax 20201007]$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   2m47s
kube-node-lease   Active   2m48s
kube-public       Active   2m48s
kube-system       Active   2m49s
testcsbc5         Active   32s

[dakini@dax 20201007]$ kubectl get secrets -n testcsbc5
NAME                  TYPE                                  DATA   AGE
default-token-58lxx   kubernetes.io/service-account-token   3      41s
test                  Opaque                                0      41s
```

Does this pattern work for your use case?

**Comment by mogul** [comment]
Yes, that would work. I'll close this now as it seems like enough of an edge case that others won't hit it commonly.
