### ISSUE TITLE
Use a configuration file instead of manually specifying authentication values

### ISSUE THREAD

**Issue by bizmate** [hashicorp/terraform-provider-kubernetes#1014]
### Description

Is it possible to use an arbitrary (not loaded under a fixed location) file for authentication as it can be done with the helm provider?

https://registry.terraform.io/providers/hashicorp/helm/latest/docs#authentication

### Potential Terraform Configuration

```hcl
provider "helm" {
  kubernetes {
    config_path = "../infra/kube_config_cluster.yml"
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@bizmate Yes, the same attribute is present in the Kubernetes provider. 
Have a look here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#config_path
