### ISSUE TITLE
Race condition in deployment make them instant regardless of wait_for_rollout

### ISSUE THREAD

**Issue by maur1th** [hashicorp/terraform-provider-kubernetes#1036]
### Terraform Version and Provider Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.10.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
```

### Affected Resource(s)
- kubernetes_deployment

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 1.13.0"
    }
  }
}

provider "kubernetes" {
  config_context = "demo"
}

resource "kubernetes_deployment" "example" {
  metadata {
    name = "terraform-example"
    labels = {
      test = "MyExampleApp"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        test = "MyExampleApp"
      }
    }

    template {
      metadata {
        labels = {
          test = "MyExampleApp"
        }
      }

      spec {
        container {
          image = "nginx:1.18"
          name  = "example"

          resources {
            limits {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests {
              cpu    = "250m"
              memory = "50Mi"
            }
          }
        }
      }
    }
  }
}
```

### Debug Output
https://gist.github.com/maur1th/8daf8d8d69ce13e8183476d8a18aae29

We can see here that TF doesn't check the correct RS: `terraform-example-787ff967cf` vs latest being:
```
❯ kubectl get rs -n default
NAME                           DESIRED   CURRENT   READY   AGE
terraform-example-5957847c9b   0         0         0       7m34s
terraform-example-64dc94fbb7   1         1         1       3m19s
terraform-example-787ff967cf   0         0         0       5m19s
terraform-example-8f6d585d6    0         0         0       6m27s
```

### Panic Output
N/A

### Expected Behavior
Terraform should have waited for the deployment to rollout.

### Actual Behavior
It didn't.

### Steps to Reproduce
1. Run Terraform on a server which has low latency with the K8s masters
2. Update a deployment

### Important Factoids
Latency between the server running Terraform and K8s masters (EKS) is very low as those are running within the same AWS region.

### References
- Seems related to https://github.com/hashicorp/terraform-provider-kubernetes/issues/785
- We were able to fix this issue by adding a `time.Sleep` in the code: https://github.com/change/terraform-provider-kubernetes/commit/9d429c94b20f1ae200fab41930bdf67f38e8003a doesn't seem to be a satisfactory fix though

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by eddy-curv** [comment]
We also suffer from this behaviour when running from our CI which is located in AWS us-east-1 or from [env0](https://www.env0.com/) that also runs in AWS us-east-1.

**Comment by Ghazgkull** [comment]
This defects in v2.0.2 of the provider. This is surprising behavior because the 2.0 upgrade documentation has a section which talks about unifying the behavior of the `wait_for_rollout` default to `true`. It seems unlikely that this was a major change in this release, but it doesn't seem to function.

Is there some other setting that required/forbidden in order for the TF provider to successfully wait for rollouts to complete?

**Comment by brandocorp** [comment]
I'm seeing a similar issue. Our deployment is updated in place, and the rollout check returns immediately despite one of the pods being in a crash loop.

**Comment by some-random-dude123** [comment]
Still have the issue where wait_for_rollout doesn't after the full deployment to complete
Using hashicorp/kubernetes v2.4.1 provider

The only way I've found to make it work is using a label in statefulset metadata
```
image_label = var.image_label
```
and then use this method right after the terraform apply 
```
kubectl wait --for=condition=ready pod -l name=XXX,image_label=$IMAGE_LABEL --timeout=300s
```

at least this makes the pipeline fails if the deployment is a failure

**Comment by TDanielsHL** [comment]
Piping in to report this issue as well. We have default `wait_for_rollout`, but our `terraform apply` will use the previous deployment's status to validate against in a RollingUpdate. We see our new pods pending while the old pods are kept available.

**Comment by jklipp** [comment]
Have run into this issue over the past week - we have updates to `kubernetes_deployment` resources that apply instantly, and then a second apply immediately after reports updated `resource_version` and sometimes `generation` metadata.  This has happened in GCP us-central1, both from our CI in the same region, and from my workstation which is ~70ms away.

I've built @davidfischer-ch 's branch from #1405 and that seems to have solved the issue so we will probably use that in the meantime but it would be great to have this merged.

For completeness, this is terraform 1.0.7 with hasicorp/kubernetes 2.6.1, on GKE 1.2.10-gke.1600.

**Comment by maur1th** [comment]
I also confirm #1405 seems to fix the issue.

**Comment by arybolovlev** [comment]
Thank you for reporting this issue @maur1th. @davidfischer-ch's PR has been merged into the main branch and changes will be available in the upcoming release. Please keep an eye on release notes.

I will go ahead and close this issue.

Thank you.
