### ISSUE TITLE
Add support for v1 APIs before Kubernetes version 1.22 is released

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform-provider-kubernetes#1049]
### Description

The following APIs are deprecated in Kubernetes 1.19 and will be removed in version 1.22:

```
certificates.k8s.io/v1beta1
storage.k8s.io/v1beta1
extensions/v1beta1
```

We need to support both the deprecated version and the new version up until we drop 1.19 support. Here are the new APIs:

```
certificates.k8s.io/v1
storage.k8s.io/v1
networking.k8s.io/v1
```

Test by ensuring these can be run without deprecation warnings:

```
TESTARGS="-run '^TestAccKubernetesCertificateSigningRequest'" make testacc
TESTARGS="-run '^TestAccKubernetesCSIDriver_basic'" make testacc
TESTARGS="-run '^TestAccKubernetesIngress_basic'" make testacc
```

### Potential Terraform Configuration

We could copy this function to determine API version supported by the server: 

https://github.com/hashicorp/terraform-provider-kubernetes/blob/47f2075bdfea4ce5817c6d14e6fb3d2eb9746f29/kubernetes/provider.go#L381

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment]
Related: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1056

**Comment by sftim** [comment]
Also see #1023

**Comment by sftim** [comment]
A blog article I wrote on this topic: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

**Comment by sftim** [comment]
Kubernetes v1.22 was [released](https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/) last week.

**Comment by trietsch** [comment]
Ah, I misread that then :) Nevertheless, the question still remains when this issue will be addressed?

**Comment by fikisipi** [comment]
It's impossible to create `Ingress` resources on new Kubernetes clusters (v1.22)

```
│ Error: Failed to create Ingress 'default/my_ingress_demo' because:
| the server could not find the requested resource (post ingresses.extensions)
│
│  238: resource "kubernetes_ingress" "ingress" {
```

As per kubernetes.io:

*The v1.22 release **will stop serving** the API versions we've listed immediately below.*
*The beta CustomResourceDefinition API (apiextensions.k8s.io/v1beta1)*
*All **beta Ingress APIs (the extensions/v1beta1 and networking.k8s.io/v1beta1 API versions)***

**Comment by sftim** [comment]
All supported Kubernetes versions (see https://kubernetes.io/releases/) provide the Ingress v1 API. However, any Kubernetes version before v1.19 is not compatible with the stable Ingress API.

I would make `kubernetes_ingress` work with the stable API, but that _might_ need a major version bump for the provider. So I'd do it something like this, and only for working with legacy clusters:
```hcl
provider "kubernetes" {
  config_path = "~/.kube/config"
  api_version_override {
     api              = "ingresses"
     group            = "networking.k8s.io"
     version_override = "v1beta1"
  }
}
```

**Comment by sftim** [comment]
Best case is to auto-detect what APIs the cluster offers and select the right one automatically.

**Comment by sftim** [comment]
See https://github.com/hashicorp/terraform-provider-kubernetes/pull/1408

**Comment by twittyc** [comment]
Any traction on this?

**Comment by curtbushko** [comment]
I believe this is addressed with:

[Add support for certificates/v1](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1473)
[Add support for storage/v1](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1457)
[Add support for networking/v1](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1049)
