### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rlewkowicz-rcd** [hashicorp/terraform-provider-kubernetes#1059]
```
Error: Post "https://2921626B5BEDFF3A9715C058B3628814.gr7.us-west-2.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": x509: certificate signed by unknown authority

  on ../../auth.tf line 85, in resource "kubernetes_config_map" "aws_auth_ignore_changes":
  85: resource "kubernetes_config_map" "aws_auth_ignore_changes" {
```

https://github.com/cloudposse/terraform-aws-eks-cluster

I'm running this if it matters ^

I think this is pretty simple. We do ssl intercept so it makes it a pain to do really anything with Kubernetes half the time. I need an ignore ssl flag in the provider.

**Comment by rlewkowicz** [comment]
```
sshuttle -vr [your-user]@[your-ip] 0/0 --ssh-cmd 'ssh -i [your-key-path]'
```

This is how I work around it. I wish I didn't have to. SSL is always a pain in the ass on corporate networks. sshuttle creates a trasparent proxy over ssh allowing you to bypass most corporate intercepts. I don't think the stock kubectl binary supports no ssl flag. Like you can put it in the config, but thats it.

**Comment by tatchley** [comment]
@rlewkowicz Does the existing [insecure](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#insecure) flag in the the `kubernetes` provider block not work for you?

**Comment by rlewkowicz** [comment]
@tatchley I had over looked it and tried searching for "SSL" but it looks like the key word was "TLS"
