### ISSUE TITLE
Allow using alternative kubectl commands

### ISSUE THREAD

**Issue by dkjii-g** [hashicorp/terraform-provider-kubernetes#1066]
### Description

I have a jump-point which has access to my kubernetes cluster, but my dev laptop does not and I can use kubectl with the alias 'alias kubectl="ssh jumppoint kubectl"' in order to access it.

There does not seem to be an option to change the kubectl command used by the kubernetes provider. Is that possible? If not, how feasable would it be to add it?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening an issue @dkjii-g. The provider doesn't actually use `kubectl` under the hood, it uses the Go client for Kubernetes, so there isn't a way to do the kind of wrapping you are talking about.

Your options here are either to run terraform directly on your jump box, or create an ssh tunnel through it to give the local machine access to the API server of the cluster.

**Comment by jrhouston** [comment]
I'm going to close this because this is not something we can support with the provider.
