### ISSUE TITLE
Documentation of csi in kubernetes_persistent_volume.persistent_volume_source

### ISSUE THREAD

**Issue by rolandg** [hashicorp/terraform-provider-kubernetes#1076]
## Terraform Version and Provider Version
latest

### Affected Resource(s)
- kubernetes_persistent_volume

csi should be listed here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/persistent_volume#persistent_volume_source

took me a while to figure out
thanks

**Comment by enummela** [comment]
@rolandg I am also having trouble figuring out how to use `csi`. Would you mind sharing what the correct way is here?

**Comment by rolandg** [comment]
@enummela 
It has to be in `spec.persistent_volume_source.csi` like this:
```
resource "kubernetes_persistent_volume" "backup" {
  ...
  spec {
    ...
    persistent_volume_source {
      csi {
```
