### ISSUE TITLE
The kubernetes job is not run after a modification

### ISSUE THREAD

**Issue by Michenux** [hashicorp/terraform-provider-kubernetes#1091]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 13.3
Kubernetes provider version: 1.13.3
Kubernetes version: EKS 1.8
```

### Affected Resource(s)
- kubernetes_job

### Steps to Reproduce
1. Create a kubernetes_job resource.
2. Apply the modification.
3. Check the job is deployed and executed.
4. Update the template of the kubernetes job.
5. Apply the modification
6. The job is updated but is not run again.

### Actual Behavior

From the point of view of Kubernetes, it is the correct behaviour: a job can be run only once.
But from the point of applying modifications on an infrastructure, we would like the job to be run again.

What we would like is an option "force_new" on the kubernetes_job.
When a change is detected on the job and option 'force_new' is true, the kubernetes provider would delete the job first, then recreate it to make it run again.

**Comment by acraven** [comment]
I don't see the behaviour @Michenux is seeing - the K8S TF provider is successfully applying a change to my job's container image but this change is not reflected in K8S.

According to [this question](https://stackoverflow.com/questions/56336067/updating-a-kubernetes-job-what-happens) the `spec.template` is immutable so I'm adding the version of my image to the job name which causes the job to be destroy, recreated and run.

**Comment by aareet** [comment]
@Michenux can you share your specific configuration that reproduces the issue please?

**Comment by Michenux** [comment]
I use always the same name for the job.
Including the revision or anything else in the name is a workaround that should work for me.
But i would prefer to keep the same name always and have an option to force the deletion.

**Comment by jrhouston** [comment]
@Michenux can you share the specifics of the modification you are making to the job? AFAIK changes to a job should force a replacement. I just tried to reproduce by changing the container command but it does a force replacement for me and I see the job being recreated and run.

**Comment by fernhtls** [comment]
Hi @jrhouston and @Michenux , I'm observing almost the same on our k8s job deployment, and in our case the only modification is the **image**. Actually there's no failure on pushing the resource, but no modification is pushed as well.
Versions:
```
Terraform v0.13.7
+ provider registry.terraform.io/gitlabhq/gitlab v3.1.0
+ provider registry.terraform.io/hashicorp/google v3.53.0
+ provider registry.terraform.io/hashicorp/google-beta v3.53.0
+ provider registry.terraform.io/hashicorp/helm v1.3.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
```

**Comment by bfanyuk** [comment]
Hello! 
These are my observations:
1. If I modify spec section of the job template (e.g. image, env variable, command) - job is recreated
2. If I modify metadata section (e.g. annotations) - job is not recreated.

Is it by design?

```
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/jfrog/artifactory v2.2.7

```
