### ISSUE TITLE
Namespace does not get created 

### ISSUE THREAD

**Issue by hostettler** [hashicorp/terraform-provider-kubernetes#1117]
This issue has been opened originally on the Aurerm provider. Here is the [link to the original issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10215). I created one in the K8S provider upon the advice of an azurerm committer (See comment)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
+ provider registry.terraform.io/hashicorp/helm v2.0.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/hashicorp/local v1.4.0

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.40"
    }

    local = {
      source = "hashicorp/local"
      version = "~>1.4"
    }
  }
}

provider "azurerm" {
  features {
   }
}




###############################################
#     Create Azure Resource Group for AKS     #
###############################################
resource "azurerm_resource_group" "aks-rd" {
    name     = "ns-test"
    location = "westeurope"

    tags = {
        Environment = "dev"
    }
}

###############################################
#             Create AKS cluster              #
###############################################
resource "azurerm_kubernetes_cluster" "aks-rd" {

    name                = "aks-ns-bug"
    location            = azurerm_resource_group.aks-rd.location
    resource_group_name = azurerm_resource_group.aks-rd.name
    dns_prefix          = "aks-ns-bug"

    role_based_access_control {
        enabled = true
    }

    default_node_pool {
        name            = "agentpool"
        node_count      = 1
        vm_size         = "Standard_D2_v2"
    }

    identity {
        type = "SystemAssigned"
    }

    addon_profile {
        kube_dashboard {
            enabled = true
        }
    }

    tags = {
        Environment = "dev"
    }

}

resource "local_file" "kube_config" {
  content = azurerm_kubernetes_cluster.aks-rd.kube_config_raw
  filename = "/tmp/cluster.conf"
  depends_on = [ azurerm_kubernetes_cluster.aks-rd]
}




###############################################
#             Load Provider helm              #
###############################################
 provider "helm" {
    kubernetes {
        config_path = "/tmp/cluster.conf"
    }
}


resource "kubernetes_namespace" "new-namespace-bug" {
  metadata {
    annotations = {
      name  = "new-namespace-bug"
    }
    labels = {
      mylabel = "new-namespace-bug"
    }
    name  = "new-namespace-bug"
  }

  depends_on = [ azurerm_kubernetes_cluster.aks-rd]
}
```

### Debug Output
https://gist.github.com/hostettler/1919668efbac3297f6975a6fe6571a57

### Expected Behaviour
A new namespace with name "new-namespace-bug" is created

### Actual Behaviour
The new namespace has not been created:
XXXX@XXXXXX-XX:~/terraform-ns-bug$ kubectl --kubeconfig /tmp/cluster.conf get namespaces
NAME              STATUS   AGE
default           Active   29m
kube-node-lease   Active   29m
kube-public       Active   29m
kube-system       Active   29m

### Steps to Reproduce

1. `az login`
2. `terraform init`
3. `terraform plan`
4. `terraform apply -auto-approve`

### Important Factoids
Running in a Azure

**Comment by aareet** [comment]
```
2021-01-16T21:06:48.975+0100 [DEBUG] plugin.terraform-provider-kubernetes_v1.13.3_x4: 2021/01/16 21:06:48 [INFO] Received namespace: &v1.Namespace{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"new-namespace-bug", GenerateName:"", Namespace:"", SelfLink:"/api/v1/namespaces/new-namespace-bug", UID:"6fad7973-4847-49c9-9811-6783369f869f", ResourceVersion:"5087532", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63746424408, loc:(*time.Location)(0x32e96c0)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"mylabel":"new-namespace-bug"}, Annotations:map[string]string{"name":"new-namespace-bug"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"HashiCorp", Operation:"Update", APIVersion:"v1", Time:(*v1.Time)(0xc000fdd8e0), FieldsType:"FieldsV1", FieldsV1:(*v1.FieldsV1)(0xc000fdd900)}}}, Spec:v1.NamespaceSpec{Finalizers:[]v1.FinalizerName{"kubernetes"}}, Status:v1.NamespaceStatus{Phase:"Active", Conditions:[]v1.NamespaceCondition(nil)}}
2021/01/16 21:06:48 [WARN] Provider "registry.terraform.io/hashicorp/kubernetes" produced an unexpected new value for kubernetes_namespace.new-namespace-bug, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .metadata[0].generate_name: was null, but now cty.StringVal("")
```

**Comment by alexsomesan** [comment]
Hi @hostettler, 

Is this the entire configuration you used at the time of the issue? I'm not seeing any kubernetes provider block setting credentials for the provider.

**Comment by alexsomesan** [comment]
My fear is that you're are targeting the wrong kubernetes cluster here, given the output from the provider:
It actually seems to call out to a host called `kubernetes.docker.internal`
```
2021-01-16T21:06:48.972+0100 [DEBUG] plugin.terraform-provider-kubernetes_v1.13.3_x4: Host: kubernetes.docker.internal:6443
```

**Comment by hostettler** [comment]
Thanks for the help, 
Will try the different options and will revert asap

**Comment by ameyaagashe** [comment]
Is anyone willing to assist me with my issues as to why I get the error "no such host"?
https://stackoverflow.com/questions/68140080/unable-to-create-a-namespace-for-aks-cluster-using-terraform-reports-no-such-hos
