### ISSUE TITLE
How to avoid kubernetes_deployment from always overriding the image field?

### ISSUE THREAD

**Issue by ZachGoldberg** [hashicorp/terraform-provider-kubernetes#1129]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.14.2
Kubernetes Provider version: 2.0.1
Kubernetes version: 1.17
```

## Question
In my terraform `.tf` code I have a `kubernetes_deployment` which specifies an `image` property on the container.  Right now it's `myservice:latest` inside terraform.  This works perfectly fine for an initial release.

Sometime later, our CI/CD process comes along, builds a new image, gives it an updated tag (say, `ABCD`) and pushes `ABCD` to the registry and then calls `kubectl set image deployment/foo myservice:ABCD`.  This also works as expected.  

The problem then comes in, the next time I run a terraform plan terraform sees that the image is `myservice:ABCD` instead of `myservice:latest` and it then plans an update to the image field to reset it to `myservice:latest` which is undesirable.  Is there anyway to have terraform ignore deltas in the `image` field after initial creation?

**Comment by aareet** [comment]
Have you looked into https://www.terraform.io/docs/configuration/meta-arguments/lifecycle.html#ignore_changes?

**Comment by ZachGoldberg** [comment]
I had not!  Somehow in my searching for an answer to this one I had not come across this.  Looks like exactly what I need!  Thanks a ton for the quick response.
