### ISSUE TITLE
Allow to specify HTTPS proxy specifically for k8s resources

### ISSUE THREAD

**Issue by DrPhil** [hashicorp/terraform-provider-kubernetes#1133]
### Description

While it is possible to run `terraform apply` with a `HTTP_PROXY` environment variable, that does not allow for cases when some of the providers might need a proxy and some wouldn't.

### Potential Terraform Configuration

```hcl
provider "kubernetes" {
  https_proxy = "localhost:8888"
}
```

### References

- This is up to each SDK: https://github.com/hashicorp/terraform/issues/17386#issuecomment-369800155
- How to use https proxy with `kubectl`: https://kubernetes.io/docs/tasks/extend-kubernetes/http-proxy-access-api/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
Looks like this will be closed by #1112
