### ISSUE TITLE
State is unable to track/update change made by kubectl if the resource is in a module

### ISSUE THREAD

**Issue by khumps** [hashicorp/terraform-provider-kubernetes#1136]
Terraform version: 0.14.5
Kubernetes provider version: 2.0.1
Kubernetes version:

### Affected Resource(s)
Tested with kubernetes_deployment and kubernetes_ingress that are in a module

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "planetside-tk" {
  metadata {
	name = var.name
	labels = {
	  app = var.name
	}
  }
  spec {
	replicas = 1
	selector {
	  match_labels = {
		app: var.name
	  }
	}
	template {
	  metadata {
		labels = {
		  app: var.name
		}
	  }
	  spec {
		container {
		  name = "nginx"
		  image = "nginx:latest"
		  port {
			container_port = var.container_port
		  }
		  volume_mount {
			mount_path = "/usr/share/nginx/html"
			sub_path = var.name
			name       = "html"
		  }
		}
		volume {
		  name = "html"
		  persistent_volume_claim {
			claim_name = var.name
		  }
		}
	  }
	}
  }
}
```

Module is defined in:
```hcl
module "planetside-tk" {
  source = "./planetside.tk"
  name = "planetside-tk"
  container_port = 80
  storage_class_name = kubernetes_storage_class.freenas.metadata[0].name
}
```

### Debug Output
https://gist.github.com/khumps/bf17b0af5c7d965452d3b218593c70cf

### Steps to Reproduce
1. `kubectl delete deployment/planetside-tk`
2. `terraform plan`

### Expected Behavior
Plan should acknowledge that the deployment is missing and try to recreate it

### Actual Behavior
Plan says it is up to date

### Important Factoids
These resources are in a module. If I move them out of the module the plan tries to create it but also delete it (this shouldn't happen since it no longer exists)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening this @khumps. This looks like a bug that was introduced in the upgrade to the new SDK, which deprecated the `Exists` function in favour of `Read`.  I have an PR with a fix incoming.

**Comment by khumps** [comment]
Thank you for this @jrhouston. Is this something that I need to pull from master to use? What is the release cycle like?

**Comment by aareet** [comment]
@khumps there should be a release going out today. We try to release every two weeks in general (if it makes sense to)
