### ISSUE TITLE
terraform x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by zayanic** [hashicorp/terraform-provider-kubernetes#1137]
Hi there,

When put the command Terraform init I received this error. Anyone could help me ?
What should i do ?

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azure: could not connect to registry.terraform.io: Failed to request
discovery document: Get
"https://registry.terraform.io/.well-known/terraform.json": x509: certificate
signed by unknown authority

**Comment by aareet** [comment]
@zayanic what environment are you running in? This is likely to be an issue with the environment

**Comment by alexsomesan** [comment]
Having thought a bit about this, it seems not related in any way to recent changes in the provider.
I think what you are seeing is the effect of missing certificate authority chains in you environment. Please confirm if that's the case and you were able to work around the issue or you need further assistance. 
Going to close this for now.
