### ISSUE TITLE
feat: changing `kubernetes_deployment.config_map` `items` to `item`

### ISSUE THREAD

**Issue by jun-sheaf** [hashicorp/terraform-provider-kubernetes#1153]
### Description

List objects such as `volume` in `kubernetes_deployment` resources use singular words to describe their k8s counterpart. The property `items` in the `config_map` object in a `volume` should respect this canon.

### Potential Terraform Configuration

```hcl
volume {
  name = "vault-sidecar-volume"
  config_map {
    name = "vault-configuration"
    item {
      key = "agent.cfg"
      path = "configs/agent.cfg"
    }
    item {
      key = "ca.crt"
      path = "certs/ca.crt"
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
To avoid a breaking change we can just duplicate the schema and flattener/expander code we already have for this so we can support `item` and `items` for now and remove it in a future release.
