### ISSUE TITLE
Error: Post request fails with EOF for creating any resource

### ISSUE THREAD

**Issue by sarahc-leeds** [hashicorp/terraform-provider-kubernetes#1155]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/google v3.55.0
+ provider registry.terraform.io/hashicorp/google-beta v3.55.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.0 (also tried v2.0.2)
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1
```

### Affected Resource(s)
Kubernetes cluster resources

### Terraform Configuration Files
I copy and pasted this direct from the kubernetes provider documentation to make sure it wasn't a misconfiguration issue. I've also tried with different, simple kubernetes resources. I have not tried with a different cluster though.

```
resource "kubernetes_namespace" "test" {
  metadata {
    name = "nginx"
  }
}

resource "kubernetes_secret" "example" {
  metadata {
    name = "basic-auth"
    namespace = kubernetes_namespace.test.metadata.0.name
  }

  data = {
    username = "admin"
    password = "******"
  }

  type = "kubernetes.io/basic-auth"
}
```

### Debug Output
Full Terraform Trace log here:
https://gist.github.com/sarahc-leeds/b6bbd0d98a885039a959ae9880de76ba

### Steps to Reproduce
terraform apply

### Expected Behavior
Create a kubernetes namespace called 'nginx' and a secret named 'basic-auth' on a GKE cluster, which has already been provisioned by Terraform and in the terraform state file. The Kubernetes config is working correctly - I can see in the log that is authenticates. 
To be sure this isn't an auth/mis config issue I have also done a post request with the same info direct to the Kubernetes API server, using the same access token as given in the provider details:

```
provider "kubernetes" {
  host = google_container_cluster.primary.endpoint
  config_path = "~/.kube/config"
}
```

### Actual Behavior
The resource tries to create but eventually stops with the following output on the terminal:

```
kubernetes_namespace.test: Creating...
kubernetes_namespace.test: Still creating... [10s elapsed]
kubernetes_namespace.test: Still creating... [20s elapsed]
kubernetes_namespace.test: Still creating... [30s elapsed]
kubernetes_namespace.test: Still creating... [40s elapsed]
kubernetes_namespace.test: Still creating... [50s elapsed]
kubernetes_namespace.test: Still creating... [1m0s elapsed]
kubernetes_namespace.test: Still creating... [1m10s elapsed]

Error: Post "http://<IP_REDACTED>/api/v1/namespaces": EOF
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
@sarahc-leeds could you post your full configuration and a [debug log](https://www.terraform.io/docs/internals/debugging.html) as a gist?

This looks to me like an authentication issue from a skim, so it would be useful to see the provider block and your traceback

**Comment by aareet** [comment]
@sarahc-leeds does the `apply` work if you perform it a second time (assuming you still have the cluster up)? From the traceback, it looks like you might be provisioning the GKE cluster in the same apply operation as the namespace and secret, is that right?

**Comment by sarahc-leeds** [comment]
> @sarahc-leeds does the `apply` work if you perform it a second time (assuming you still have the cluster up)? From the traceback, it looks like you might be provisioning the GKE cluster in the same apply operation as the namespace and secret, is that right?

Unfortunately not, it fails every time. The cluster is already provisioned by Terraform and online, so the TF state skips over the GKE cluster provisioning since it's already there.

**Comment by sarahcthekey** [comment]
This issue can be closed, it was in fact some sort of permissions or config issue. When I statically defined the host/token and ca cert it worked first time. I'll now go and scratch my head to find out where I went wrong, as the Google service account I'm using to provision Terraform resources has Owner permissions.

**Comment by jrhouston** [comment]
@sarahcthekey thanks for confirming, closing this now.
