### ISSUE TITLE
daemonset change due to kubernetes provider upgrade

### ISSUE THREAD

**Issue by LijieZhou** [hashicorp/terraform-provider-kubernetes#1164]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: Terraform v0.12.29
Kubernetes Provider version: provider.kubernetes v2.0.2
Kubernetes version: EKS 1.16
```
## Terraform configuration
```hcl
provider "kubernetes" {
  host = module.eks_cluster.hostname
  cluster_ca_certificate = base64decode(
    "${module.eks_cluster.certificate-authority-data}",
  )
  token            = data.aws_eks_cluster_auth.eks_cluster.token
  version          = ">=2.0"
}
```

## Question

We upgraded Terraform Kubernetes provider to 2.0 as above. We have seen changes as documented in the upgrade guide. However, there is one change we did not see in the guide and I am wondering if you have any documentation for explanation. 
Specifically, we see two attributes change (run_as_group and [run_as_user](https://registry.terraform.io/providers/hashicorp/kubernetes/1.13.3/docs/resources/daemonset#run_as_user)). Previously, it is a UID as documented here, and now the terraform plan shows this. 
```
 ~ security_context {
 allow_privilege_escalation = true
 privileged                 = false
 read_only_root_filesystem  = true
 - run_as_group               = "0" -> null
 run_as_non_root            = false
 - run_as_user                = "0" -> null
}
```

**Comment by aareet** [comment]
Hi @LijieZhou I believe this may be related to https://github.com/hashicorp/terraform-provider-kubernetes/issues/1139

**Comment by alexsomesan** [comment]
@LijieZhou This looks like a side-effect of some changes that happened in the provider version 2.0 and were unfortunately not mentioned in the upgrade guide.

The solution here should be to just do another apply and after that the state should reflect the correct values and not trigger a diff anymore.

**Comment by alexsomesan** [comment]
I'm going to go ahead and close this one but feel free to come back and re-open if the solution doesn't work for you.

We're updating the upgrade documentation to mention this situation explicitly.
