### ISSUE TITLE
StatefulSet with "OnDelete" update strategy now errors

### ISSUE THREAD

**Issue by d-shi** [hashicorp/terraform-provider-kubernetes#1166]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.13.5
Kubernetes provider version: 2.0.1
Kubernetes version: 1.18
```

### Affected Resource(s)

kubernetes_stateful_set

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Steps to Reproduce

Create a kubernetes_stateful_set resource with the following and apply:

```
    update_strategy {
      type = "OnDelete"
    }
```

### Expected Behavior
What should have happened?
The statefulset should be created.

### Actual Behavior
What actually happened?
Terraform errors with the following message:
```
Error: rollout status is only available for RollingUpdate strategy type
```

### Important Factoids

Reverting to the kubernetes provider version 1.13.3 allows this to succeed.

### References

I believe this change fixed one bug but introduced this bug: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1097/commits/3d2ed301b7794bdb2db834df0ac67dc7772491c5

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Thanks for reporting this. I can reproduce the issue and it looks like it's indeed a problem in the provider.

Note to fixer: it looks like we can't really use the polymorphic status viewers from kubectl for StatefulSets that are not using RollingUpdate strategy. 
Error comes from here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/cbe392a099bf3a6f7e9981e58cb53be0cdee97c6/vendor/k8s.io/kubectl/pkg/polymorphichelpers/rollout_status.go#L128

**Comment by alexsomesan** [comment]
You can temporarily work around this issue by setting  `wait_for_rollout = false` on the affected resource. For example:
```
resource "kubernetes_stateful_set" "test" {
  metadata {
    name = "test-1166"
  }
  wait_for_rollout = false
  spec {
...
```

**Comment by d-shi** [comment]
Ah, good to know. Thanks for the workaround!

**Comment by gibsonje** [comment]
Encountering this still, versions are:

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2

Kubernetes version 1.18
