### ISSUE TITLE
kubernetes_deployment example incorrect

### ISSUE THREAD

**Issue by Corendon-Jasper** [hashicorp/terraform-provider-kubernetes#1169]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v0.14.5
Kubernetes provider version: 
Kubernetes version:
```

### Affected Resource(s)
kubernetes_deployment 

### Terraform Configuration Files
Example code contains:
```
          resources {
            limits = {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests = {
              cpu    = "250m"
              memory = "50Mi"
            }
          }
```

### Output
An argument named "limits" is not expected here. Did you mean to define a
block of type "limits"?
An argument named "requests" is not expected here. Did you mean to define a
block of type "requests"?

### Steps to Reproduce
1. copy/past example from https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment
2. terraform plan

### Expected Behavior
Example code should be:
```
          resources {
            limits {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests {
              cpu    = "250m"
              memory = "50Mi"
            }
          }
```

### Actual Behavior
the limit and request block contain an erroneous "="

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
@Corendon-Jasper Thanks for finding this.  Do you intentend to submit a PR to fix it ?

**Comment by jrhouston** [comment]
@Corendon-Jasper are you using the 1.x version of the provider? In 2.x limits and requests were changed to a map so the `=` needs to be there.

**Comment by Corendon-Jasper** [comment]
@jrhouston I just checked this and you are correct. I was indeed using the 1.x version. I have updated to the 2.x provider. Thanks for pointing it out. Mistrake was on my end, no bugs to be found here.
