### ISSUE TITLE
Multiple providers don't work simultaneously

### ISSUE THREAD

**Issue by astorath** [hashicorp/terraform-provider-kubernetes#1170]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: Terraform v0.14.5
Kubernetes provider version: provider registry.terraform.io/hashicorp/kubernetes v2.0.2
Kubernetes version: v1.20.2
```

### Affected Resource(s)

any

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    kube-dev = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0.2"
    }
    kube-prod = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0.2"
    }
  }
  required_version = ">= 0.14"
}

provider "kube-dev" {
  config_path    = "~/.kube/config"
  config_context = "kind-kind1"
}

provider "kube-prod" {
  config_path    = "~/.kube/config"
  config_context = "kind-kind2"
}

data "kubernetes_secret" "sec1" {
  provider = kube-dev
  metadata {
    name      = "empty-secret1"
    namespace = "default"
  }
}

data "kubernetes_secret" "sec2" {
  provider = kube-prod
  metadata {
    name      = "empty-secret2"
    namespace = "default"
  }
}

output "empty-secret1" {
  value = data.kubernetes_secret.sec1.*.data
}

output "empty-secret2" {
  value = data.kubernetes_secret.sec2.*.data
}
```

### Debug Output

https://gist.github.com/astorath/3bef16448c2e6465a53c7eea91b8c63b

### Steps to Reproduce

1. `kind create cluster --name kind1`
2. `kind create cluster --name kind2`
3. `kubectl create secret generic empty-secret2 --context kind-kind2 -n default`
4. `kubectl create secret generic empty-secret1 --context kind-kind1 -n default`
5. `terraform plan`

### Expected Behavior
Outputs should contain both resources: `sec1` and `sec2`

### Actual Behavior
Only one resource is actually found. The log clearly shows that both `sec1` and `sec2` are queried from the same kubernetes instance. This behaviour is the same for remote clusters (GKE).

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi @astorath,

I believe you are trying to make use of a Terraform feature called provider aliases. If my assumption is correct, then there are some syntactical mistakes in the configuration you presented above.

I made some corrections and I got the following configuration to work as you expected:
```
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0.2"
    }
  }
  required_version = ">= 0.14"
}

provider "kubernetes" {
  alias          = "kube-dev"
  config_path    = "~/.kube/config"
  config_context = "kind-kind1"
}

provider "kubernetes" {
  alias          = "kube-prod"
  config_path    = "~/.kube/config"
  config_context = "kind-kind2"
}

data "kubernetes_secret" "sec1" {
  provider = kubernetes.kube-dev
  metadata {
    name      = "empty-secret1"
    namespace = "default"
  }
}

data "kubernetes_secret" "sec2" {
  provider = kubernetes.kube-prod
  metadata {
    name      = "empty-secret2"
    namespace = "default"
  }
}

output "empty-secret1" {
  value = data.kubernetes_secret.sec1.*.data
}

output "empty-secret2" {
  value = data.kubernetes_secret.sec2.*.data
}
```

You can read up on provider aliases and how to use them over here: https://www.terraform.io/docs/language/providers/configuration.html#alias-multiple-provider-configurations

I hope this answers your question. I'm going to close the issue, but feel free to re-open if my proposed solution doesn't fit your expectations.

**Comment by astorath** [comment]
@alexsomesan thanks! sorry to bother you with the stuff...
