### ISSUE TITLE
Omit default subject.namespace in kubernetes_cluster_role_binding

### ISSUE THREAD

**Issue by janschumann** [hashicorp/terraform-provider-kubernetes#1173]
The schema for rbac subjects define a default value `default` for the namespace attribute, although some of the objects kinds are non-namespace and will produce an error or unexpected behaviour when set.

From code comments:  
```	
// Namespace of the referenced object.  If the object kind is non-namespace, such as "User" or "Group", and this value is not empty
// the Authorizer should report an error.
```

The namespace attribute should either 
- do not define a default
- conditionally define a default depending on object kind

I would happily provide a PR once this issue is reviewed and approved.

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
Kubernetes version: 1.18
```

### Affected Resource(s)
- kubernetes_cluster_role_binding

### Terraform Configuration Files
```hcl
resource "kubernetes_cluster_role_binding" "test" {
  metadata {
    name = "test"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "edit"
  }
  subject {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Group"
    name      = "system:editors"
  }
}
```

### Expected Behavior

If the namespace attribute is not provided, it should be omitted or only set for objects that require a value.

### Actual Behavior

The provider adds the namespace attribute with "default".
https://github.com/hashicorp/terraform-provider-kubernetes/blob/cbe392a099bf3a6f7e9981e58cb53be0cdee97c6/kubernetes/schema_rbac.go#L84

### Workaround

Explicitly set the namespace with an empty string:

```
resource "kubernetes_cluster_role_binding" "test" {
  metadata {
    name = "test"
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "edit"
  }
  subject {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Group"
    name      = "system:editors"
    namespace = ""
  }
}
```

**Comment by dominik-lekse** [comment]
Agree, I would expect a Terraform provider not to set opinionated defaults.
