### ISSUE TITLE
API version mismatch using azure/kubelogin exec plugin

### ISSUE THREAD

**Issue by noahbirrer-8451** [hashicorp/terraform-provider-kubernetes#1176]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 0.13.6
Kubernetes provider version: 2.0.2
Kubernetes version: 1.18.14
Kubelogin version: 0.0.8
```

### Affected Resource(s)
NA

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  version = "=2.0.2"
  host        = data.azurerm_kubernetes_cluster.kubernetes_cluster.kube_config[0].host
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args = ["convert-kubeconfig", "-l", "spn"]
    command = "kubelogin"
    env = {
      KUBECONFIG = var.kubeconfig
      AAD_SERVICE_PRINCIPAL_CLIENT_ID = var.cluster_config_sp_client_id
      AAD_SERVICE_PRINCIPAL_CLIENT_SECRET = var.cluster_config_sp_secret
    }
  }
}

resource "kubernetes_namespace" "namespace" {
  metadata {
    name = "test"
  }
}
```

### Steps to Reproduce
1. Install [kubelogin](https://github.com/Azure/kubelogin)
2. Configure Kubernetes provider block as such
3. Run Terraform Init, Plan, and Apply

### Expected Behavior
Terraform should have successfully authenticated to the cluster using kubelogin, the kubeconfig supplied, and the service principal. A Terraform Apply should have been able to run.

### Actual Behavior
Running the exec plugin during Terraform Apply failed:
```
Error: Post "https://<redacted>/api/v1/namespaces": getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1beta1, plugin returned version client.authentication.k8s.io/__internal

```

### Important Factoids
I am attempting to [non-interactively authenticate](https://github.com/Azure/kubelogin#service-principal-login-flow-non-interactive) to an AAD Managed AKS cluster using a Service Principal and a secret via Azure's own Kubelogin tool. 
Using the same kubelogin binary locally outside of terraform (just from CLI) with the same environment variables works just fine.
It is worth noting that kubelogin runs successfully from the exec block of the kubernetes provider (successfully converts kubeconfig)

### References
Related to this issue: https://github.com/Azure/AKS/issues/1763

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@noahbirrer-8451 If you set `api_version` in the provider exec block to `client.authentication.k8s.io/__internal` does it work ? Seems to me that's what the error message is suggesting.

**Comment by noahbirrer-8451** [comment]
Hi @alexsomesan, When I set the ```api_version``` to ```client.authentication.k8s.io/__internal```, I receive this error:
```Error: Failed to configure client: exec plugin: invalid apiVersion "client.authentication.k8s.io/__internal```

**Comment by dak1n1** [comment]
hmm, I'm hitting this issue with GKE too. I was trying to update the [GKE example](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1269), but this issue is blocking that progress. EKS is still working though.

I'm suspecting a bug in one of the Kubernetes libraries. I was able to reproduce it using kubectl too.

```
$ kube --kubeconfig=./kubeconfig get pods
Fetching cluster endpoint and auth data.
kubeconfig entry generated for k8s-acc-5642.
Fetching cluster endpoint and auth data.
kubeconfig entry generated for k8s-acc-5642.
Fetching cluster endpoint and auth data.
kubeconfig entry generated for k8s-acc-5642.
Fetching cluster endpoint and auth data.
kubeconfig entry generated for k8s-acc-5642.
Fetching cluster endpoint and auth data.
kubeconfig entry generated for k8s-acc-5642.
Unable to connect to the server: getting credentials: exec plugin is configured to use API version client.authentication.k8s.io/v1alpha1, plugin returned version client.authentication.k8s.io/__internal
```

Here are the versions I'm using:
```
Kubernetes version: 1.18.17-gke.100
Kubectl version: v1.21.0
gcloud version: Google Cloud SDK 340.0.0
```

My GKE reproducer is here:
https://github.com/hashicorp/terraform-provider-kubernetes/pull/1271/commits/a40f780f6a20e9f74031c48a074bac8b47009c83

I'll try to make a reproducer that just uses the bare minimum kubernetes libraries (probably client-go) and see if I can open an issue upstream.

**Comment by aristosvo** [comment]
I would like to raise this a little bit. I’m looking into the possibility to implement [disable local accounts for AKS](https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts-preview) in the `azurerm` provider, but without this working it seems like authenticating from the Kubernetes provider would be impossible.

**Comment by aristosvo** [comment]
@noahbirrer-8451 I fixed it for my test setup by using config like below:
```
provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.default.kube_config.0.host
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.cluster_ca_certificate)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args = [
      "get-token",
      "--login",
      "azurecli", # spn if you want to use service principal, but requires use of env vars AAD_SERVICE_PRINCIPAL_CLIENT_ID and AAD_SERVICE_PRINCIPAL_CLIENT_SECRET
      "--environment",
      "AzurePublicCloud",
      "--tenant-id",
      data.azurerm_client_config.current.tenant_id,
      "--server-id",
      "6dae42f8-4368-4678-94ff-3960e28e3630",
      "|",
      "jq",
      ".status.token"
    ]
  }
}
```

Environment:
```
Terraform version: v1.0.5
Kubernetes provider version: v2.4.1
Kubernetes version: 1.20.9
Kubelogin version: 0.0.10
```
Does this solve your problem?

For the Terraform Provider for Azure the [last fix](https://github.com/hashicorp/terraform-provider-azurerm/issues/13248) is under way to be able to disable the use of local accounts at all, if you are interested.

**Comment by buildwithjz** [comment]
@aristosvo Thanks for testing this out. What exactly did you change from the initial example for kubelogin to work? We are using the same kubernetes provider version and still running into the same API version mismatch issue

**Comment by aristosvo** [comment]
Kubelogin version (0.0.10) makes probably the biggest difference here, k8s and k8s provider version might help as well.
