### ISSUE TITLE
Apple Silicon (darwin/arm64) support

### ISSUE THREAD

**Issue by billinghamj** [hashicorp/terraform-provider-kubernetes#1177]
### Description

Please could you add support for Apple Silicon (aka release `darwin/arm64` binaries) - this would require adopting Go 1.16

### References

Goes along with https://github.com/hashicorp/terraform/issues/27257

Equivalent to https://github.com/hashicorp/terraform-provider-aws/issues/16948

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
This is resolved in version 2.0.3 :) https://releases.hashicorp.com/terraform-provider-kubernetes/2.0.3/
