### ISSUE TITLE
Racing condition with namespace creation and applying limit range / resource quota

### ISSUE THREAD

**Issue by kemmemha** [hashicorp/terraform-provider-kubernetes#1181]
**Terraform version:** 0.14.5
**Kubernetes provider version:** 2.0.1
**Kubernetes version:** 1.19.6

Hello, during our terraform apply we face an issue. It seems to apply the limit ranges and resource quotas before the creation of the namespace has been finished.
The workaround is to simply re-run the terraform apply and everything is working. We have also tried to use `depends_on` to the namespace that is created without success.

Short: 
1. Create a namespace
2. Create resource quota (on the namespace from 1.) -> Fails with "Namespace not found"
3. Create limit range (on the namespace from 1.) -> Fails with "Namespace not found"

![namespace-not-found-censored](https://user-images.githubusercontent.com/77006366/109637707-7032ae80-7b4d-11eb-86bb-2bf5bd0b8e5c.png)

```
  resource "kubernetes_namespace" "namespace" {
    metadata {
      name = var.namespace_name
      labels = {
        name = var.namespace_name
      }
    }
  }
...
resource "kubernetes_resource_quota" "memory_and_cpu_quota" {
  metadata {
    name = "memory-and-cpu-quota"
    namespace = var.namespace_name
  }
  spec {
    hard = {
      "limits.cpu" = var.resource_quota_limit_cpu
      "limits.memory" = var.resource_quota_limit_memory
      "requests.cpu" = var.resource_quota_request_cpu
      "requests.memory" = var.resource_quota_request_memory
    }
  }
  
  depends_on = [
    kubernetes_namespace.namespace
  ]
}

resource "kubernetes_limit_range" "memory_and_cpu_limitrange" {
  metadata {
    name = "memory-and-cpu-limitrange"
    namespace = var.namespace_name
  }
  spec {
    limit {
      type = "Container"
      default = {
        cpu    = var.default_limit_cpu
        memory = var.default_limit_memory
      }
      default_request = {
        cpu    = var.default_request_cpu
        memory = var.default_request_memory
      }
    }
  }
  
  depends_on = [
    kubernetes_namespace.namespace
  ]
}
```

**Comment by dak1n1** [comment]
Thanks for filing this bug report! Can you try referencing the namespace like this?

```
namespace = kubernetes_namespace.namespace.metadata.0.name
```

This implicit dependency might work better than the `depends_on`, since it will wait for the metadata field to exist. I wasn't able to reproduce this in my testing offhand, so my first suspicion is a problem with `var.namespace_name` having an unexpected value.

This is what I used to test with, which also worked. It's pretty much the same as the reproducer in the first comment, but without any variables.

```
$ cat main.tf
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.0.1"
    }
  }
}

resource "kubernetes_namespace" "namespace" {
    metadata {
      name = "test"
  }
}

resource "kubernetes_resource_quota" "memory_and_cpu_quota" {
  metadata {
    name = "memory-and-cpu-quota"
    namespace = "test"
  }
  spec {
    hard = {
      "limits.cpu" = "2"
      "limits.memory" = "512m"
      "requests.cpu" = "1"
      "requests.memory" = "256m"
    }
  }

  depends_on = [
    kubernetes_namespace.namespace
  ]
}

resource "kubernetes_limit_range" "memory_and_cpu_limitrange" {
  metadata {
    name = "memory-and-cpu-limitrange"
    namespace = "test"
  }
  spec {
    limit {
      type = "Container"
      default = {
        cpu    = "2"
        memory = "512m"
      }
      default_request = {
        cpu    = "1"
        memory = "256m"
      }
    }
  }

  depends_on = [
    kubernetes_namespace.namespace
  ]
}
```

**Comment by kemmemha** [comment]
@dak1n1 Thanks for the detailed answer! I will try out your solution ASAP.

**Comment by kemmemha** [comment]
Issue seems to be resolved by your solution @dak1n1 . Thanks again for the help!
