### ISSUE TITLE
Allow kubernetes_namespace resource to ignore Istio istio.io/rev label

### ISSUE THREAD

**Issue by rvillane** [hashicorp/terraform-provider-kubernetes#1183]
### Description
Currently, kubernetes_namespace resource is ignoring any labels ending with whose key names end with kubernetes.io because those can be mutated.  When using Istio and particularly when upgrading Istio using [canary upgrades](https://istio.io/latest/docs/setup/upgrade/canary/), controlled during sidecar injection is based on the namespace label istio.io/rev and the value of this label is typically the new version of Istio being installed

example
istio.io/rev=1.9.0

then it keeps changing as the upgrades occur but terraform conflicts with the changing label value

can istio.io/rev label be ignored just like labels ending with "kubernetes.io" as both are affected by mutating values.

thanks

**Comment by arren-ru** [comment]
@rvillane you may want try to use this https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes

**Comment by rvillane** [comment]
thanks
