### ISSUE TITLE
kubernetes_service_account documentation incorrect about default setting of automount_service_account_token

### ISSUE THREAD

**Issue by obscurerichard** [hashicorp/terraform-provider-kubernetes#1191]
> automount_service_account_token - (Optional) Boolean, true to enable automatic mounting of the service account token. Defaults to true.

This is not the case, it defaults to `false`.

See the comments in [aws-load-balancer-controller/issues/1601](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1601#issuecomment-720709729).

### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v0.13.5
Kubernetes provider version: 2.0.2
Kubernetes version: 1.18
```

### Affected Resource(s)
- kubernetes_service_account

### Terraform Configuration Files
```hcl
resource "kubernetes_service_account" "example" {
  metadata {
    name = "terraform-example"
  }
  secret {
    name = "${kubernetes_secret.example.metadata.0.name}"
  }
}

resource "kubernetes_secret" "example" {
  metadata {
    name = "terraform-example"
  }
}
```

### Steps to Reproduce
apply any plan including a 

### Expected Behavior
What should have happened?

automount_service_account_token should have been true as the documentation states. Or the documentation should state that it should be false by default, either way please make these consistent.

### Actual Behavior
Leaving automount_service_account_token out made the value false.

### References
https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1601#issuecomment-720709729

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@obscurerichard The default value for this attribute is indeed `true`, as seen here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/048705ac7af9c75269edde3dff9ac9a335eaa5ef/kubernetes/resource_kubernetes_service_account.go#L69

This has been changed in provider version 2.0. Are you sure you're not running an older provider version by any chance?

**Comment by alexsomesan** [comment]
`automount_service_account_token` IS being set to true by default as the documentation states. I'm going to close this.
