### ISSUE TITLE
Cannot create ingress in a different namespace than the backend

### ISSUE THREAD

**Issue by goobysnack** [hashicorp/terraform-provider-kubernetes#1198]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.12.28
Kubernetes provider version: 2.02
Kubernetes version: 1.18.12
```

### Affected Resource(s)
- kubernetes_ingress

### Terraform Configuration Files

I removed the other data blocks as they are working fine.
```
data "kubernetes_service" "service" {
  metadata {
    name = "hellonode"
    namespace = "default"
  }
}

resource "kubernetes_ingress" "ingress" {
  depends_on = [google_compute_global_address.vs_address]
  wait_for_load_balancer = true
  metadata {
    name = "hello-test3-foo-io"
    //namespace = "edge" <-- I'd like to create the ingress in this namespace and use a backend service in default
    annotations = {
      "kubernetes.io/ingress.global-static-ip-name" = google_compute_global_address.vs_address.name
      "kubernetes.io/ingress.class" = "gce"  
    }
  }

  spec {
    backend {
      service_name = data.kubernetes_service.service.metadata.0.name
      service_port = 80
    }
  }
}
```

### Debug Output
no gist

### Panic Output
none

### Expected Behavior
ingress created in edge namespace with backend in default

### Actual Behavior
This error:
"Translation failed: invalid ingress spec: could not find service "edge/hellonode""
It's looking for the service name in the same namespace instead of using the default based on the data resource:

### Important Factoids
None

### References
None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by goobysnack** [comment]
If I put the namespace in the name, it gives this error:

```
service_name = "default/${data.kubernetes_service.service.metadata.0.name}"

Error: Failed to create Ingress 'edge/hello-test3-foo-io' because: Ingress.extensions "hello-test3-foo-io" is invalid: spec.backend.serviceName: Invalid value: "default/hellonode": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

**Comment by jrhouston** [comment]
Thanks for opening this @goobysnack – unfortunately this is not possible and is a limitation of this API. The [documentation](https://kubernetes.io/docs/concepts/services-networking/ingress/#resource-backend) says the backend must be in the same namespace as the ingress so this is not something we can change in Terraform. 

There is a closed issue about this on the Kubernetes repo for context: https://github.com/kubernetes/kubernetes/issues/17088
