### ISSUE TITLE
How to reference an external manifest or template file?

### ISSUE THREAD

**Issue by skupjoe** [hashicorp/terraform-provider-kubernetes#1209]
I like storing my k8s resource configuration in their own files to keep code DRY. Using the unofficial k8s provider, I was able to declare all my resource conf in a manifest .yml file and render it using:
```
resource "k8s_manifest" "appt" {
  content = data.template_file.app.rendered
}
```
I am seeing that in the `kubernetes-alpha` provider, a manifest can also be supplied from a rendered template_file statement in this fashion. But I am having trouble getting this to work similarly using the stable `kubernetes` provider.

Is there any way I can render the configuration for `resource "kubernetes_deployment" {}` using the `kubernetes` provider from a .yml file?

**Comment by jrhouston** [comment]
Thanks for opening this @skupjoe – this is not possible in the main `kubernetes` provider at the moment, and is the reason we are working on the `kubernetes-alpha` provider. This is maturing and will eventually make it's way into this repository, but for the moment if you want to use an external YAML file you will either need to use the helm provider and create a chart for it, or use `kubernetes-alpha`.
