### ISSUE TITLE
Timeout syntax could be described

### ISSUE THREAD

**Issue by eXpire163** [hashicorp/terraform-provider-kubernetes#1214]
In the kubernetes_job it says default is "1 minute" but it is "1m" 

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/job#timeouts

A sample with "time<unit>" would be helpfull

**Comment by jrhouston** [comment]
We should also check if this mistake has been copypasta'd to any other resources in the documentation.

**Comment by Sheetalsingh23** [comment]
@eXpire163 is this issue still unresolved?

**Comment by wangli1030** [comment]
I will work on this and submit PR later.
