### ISSUE TITLE
terraform plan failing with error "An argument named "load_config_file" is not expected here."

### ISSUE THREAD

**Issue by Divya1388** [hashicorp/terraform-provider-kubernetes#1223]
### Description
Hi I am trying to use the hashicorp/kubernetes provider to provision resources inside AKS and it errors out with "An argument named "load_config_file" is not expected here."

### Versions
Terraform version: 0.14.10
Kubernetes provider version: v2.0.3
Kubernetes version:1.17.13

### Terrform configuration
I have used the following terraform providers 
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.35.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 1.13.3" 
    }
    local = {
      source  = "hashicorp/local"
      version = ">=2.0.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0.0"
    }
  }
}

provider "azurerm" {
  features {}
}
provider "kubernetes" {
  load_config_file       = "false"
  host                   = azurerm_kubernetes_cluster.cluster.kube_config.0.host
  client_certificate     = base64decode(azurerm_kubernetes_cluster.cluster.kube_config.0.client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.cluster.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.cluster.kube_config.0.cluster_ca_certificate)
}

### Steps to Reproduce
terraform init and terraform plan
the init here pinned down to v2.0.3 of hashicorp/kubernetese

### Expected Behavior
should provide the terraform plan output

### Actual Behavior
throwing the following error:
![image](https://user-images.githubusercontent.com/47507148/113962579-96530a80-97ed-11eb-9897-35fa0b17b789.png)

### Important Factoids
When changed the terraform configuration to use v1.13.3 of hashicorp/kubernetes specifically the plan worked fine
kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "= 1.13.3" 
    }
So i suspect this is a bug caused in the latest version of the hashicorp/kubernetes provider. 

Any help with this issue will be very helpful

Thanks 
Divya

**Comment by alexsomesan** [comment]
@Divya1388 that attribute was removed in provider release 2.0.0. It's no longer supported in newer versions.
You can achieve the same effect by setting a value for the `config_path` attribute. If you set it to a path of a kubeconfig file it will load that file. Otherwise it will not try to load any kubeconfig files including the default one at (~/.kube/config).
