### ISSUE TITLE
Remove PodSecurityPolicy for kubernetes 1.25

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform-provider-kubernetes#1224]
### Description

PodSecurityPolicy will be removed from the Kubernetes API in version 1.25. We'll have to either remove this feature from the provider, or adapt it to only run against APIs < 1.25.

### References

https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Reopening this issue since this was not removed but not only marked as deprecated. This will be removed in the next major release of the provider.

**Comment by BBBmau** [comment]
marking as completed since this was removed on `v3-major-release` branch: https://github.com/hashicorp/terraform-provider-kubernetes/commit/dd37e9213775067f60dcd419a0be83939678abef
