### ISSUE TITLE
Implement topologySpreadConstraint in Controller Resources

### ISSUE THREAD

**Issue by krismolendyke** [hashicorp/terraform-provider-kubernetes#1226]
### Description

https://github.com/hashicorp/terraform-provider-kubernetes/issues/994 added PodTopologySpread for _pods_ but [as mentioned in this Kubernetes blog post](https://kubernetes.io/blog/2020/05/introducing-podtopologyspread/), it is supported by other resources, too:

> As this API is embedded in Pod's spec, you can use this feature in all the high-level workload APIs, such as Deployment, DaemonSet, StatefulSet, etc.

My immediate selfish interest is in supporting this in at least deployments.  Since I think most k8s users create pods with these controller resources I suspect that I'm not alone :smile:.

### Potential Terraform Configuration

I believe this looks identical to the [current configuration for a pod](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod#topology_spread_constraint) since the API is embedded in the higher level resources.

### References

- https://github.com/hashicorp/terraform-provider-kubernetes/issues/994
- https://kubernetes.io/blog/2020/05/introducing-podtopologyspread/
- https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#topologyspreadconstraint-v1-core

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you!

**Comment by DrFaust92** [comment]
Hi @krismolendyke this should be supported for all controller resources already as the changes was for the pod schema that is reused in all of those resources. can you check?

**Comment by krismolendyke** [comment]
:facepalm: I just realized that I've got [`2.0.2`](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md#202-february-02-2021) here and [`2.0.3`](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/CHANGELOG.md#203-march-17-2021) includes the poi topology spread constraint.  Upgrading to `2.0.3` works, thanks, sorry for the noise!
