### ISSUE TITLE
Actions towards GKE cluster fail

### ISSUE THREAD

**Issue by Hi-Fi** [hashicorp/terraform-provider-kubernetes#1229]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.14.10
Kubernetes provider version: v2.0.3
Kubernetes version: Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected Resource(s)

- namespace (at least, both creation and refresh)

### Terraform Configuration Files
https://github.com/hashicorp/learn-terraform-provision-gke-cluster with following additions
```hcl
data "google_client_config" "default" {
}

provider "kubernetes" {
  host     = google_container_cluster.primary.endpoint

  token = data.google_client_config.default.access_token

  # client_certificate     = google_container_cluster.primary.master_auth.0.client_certificate
  # client_key             = google_container_cluster.primary.master_auth.0.client_key
  cluster_ca_certificate = google_container_cluster.primary.master_auth.0.cluster_ca_certificate
}

resource "kubernetes_namespace" "monitoring" {
  metadata {
    name = "monitoring"
  }
}
```

to versions.tf:
```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.52.0"
    }
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.0.3"
    }
  }

  required_version = "~> 0.14"
}
```

### Debug Output

https://gist.github.com/Hi-Fi/9815733d8943409e58f7997948f4045c (both apply and refresh)
### Panic Output

No panic

#### Creation of namespace
1. For whole set: `terraform apply`
2. Debug taken with `terraform apply -target "kubernetes_namespace.monitoring"`

#### Importing of namespace to state
1. Debug taken with `terraform import "kubernetes_namespace.monitoring" monitoring`

### Expected Behavior
What should have happened?
Namespace get created/imported. With other things (when state is tried to refresh) things fail with same error than with import.

### Actual Behavior
What actually happened?
Very strange error. This works for some reason with AKS clusters.

With apply commands print out: `Error: Post "https://<master IP>/api/v1/namespaces": EOF`
With refresh command prints out: `Error: an error on the server ("") has prevented the request from succeeding (get namespaces monitoring)`

No clue of issue reason at the `kube-apiserver.log` that can be seen through proxy.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Hi-Fi** [comment]
Tested this a bit more.

When running with Mac directly, actions are successfull.
When using Terraform with Hashicorp's official Terraform container, error `Error: an error on the server ("") has prevented the request from succeeding (get namespaces monitoring)` is thrown.

Docker: 
```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Interesting part is that this error only is seen with GKE and this particular provider, not others.

**Comment by Hi-Fi** [comment]
Worked fine with Docker Desktop 2.5.0.1, so clearly issue with Docker. Closing this.

**Comment by mike-marcacci** [comment]
This has been plaguing several members of my team for the past few days, and I separately arrived at the same [docker-for-mac issue](https://github.com/docker/for-mac/issues/5568). I can verify that downgrading to docker `Docker Desktop 3.2.2` fixes this, although [that version might bet auto-upgraded](https://github.com/docker/roadmap/issues/183) at some point.
