### ISSUE TITLE
Error: failed to configure: execProvider and authProvider cannot be used in combination                                                                                                    

### ISSUE THREAD

**Issue by tachang** [hashicorp/terraform-provider-kubernetes#1239]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.14.3
Kubernetes provider version: v2.0.3
Kubernetes version: 
```

### Affected Resource(s)
- Provider itself

### Terraform Configuration Files

```
provider "kubernetes" {
  host                   = var.cluster_endpoint
  cluster_ca_certificate = base64decode(var.cluster_certificate_authority[0].data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", var.cluster_name, "--region", "us-east-1"]
  }
}
```

### Expected Behavior
What should have happened?

Everything should have been configured properly. Works on Terraform 13.4

### Actual Behavior
What actually happened?

Got an error:

Error: failed to configure: execProvider and authProvider cannot be used in combination                                                                                                    

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tachang** [comment]
It seems like I had a working `kubectx`. As soon as I switched it to another cluster it worked on my command line.

**Comment by alexsomesan** [comment]
@tachang is this still an issue for you or have you solved it?

**Comment by tachang** [comment]
I solved it so this can be closed. The issue was the kubectx was pointing to a valid cluster so it used that I assume? Weird but solved.
