### ISSUE TITLE
kubernetes_default_service_account does not fully manage automountServiceAccountToken

### ISSUE THREAD

**Issue by dhrapson** [hashicorp/terraform-provider-kubernetes#1247]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.14.10
Kubernetes provider version: 2.1.0
Kubernetes version: 1.17.17-gke.2800
```

### Affected Resource(s)

`kubernetes_default_service_account`

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
```terraform
resource "kubernetes_namespace" "default" {
  metadata {
    name   = "my-namespace"
  }

  depends_on = [google_container_node_pool.default]
}

resource "kubernetes_default_service_account" "default" {
  metadata {
    namespace = kubernetes_namespace.default.metadata.0.name
  }

  automount_service_account_token = false

  depends_on = [kubernetes_namespace.default]
}
```
### Debug Output

Not allowed to provide

### Steps to Reproduce

1. `terraform apply` against an existing cluster
2. kubectl get sa default -o yaml --namespace my-namespace
3. observe output looking for `automountServiceAccountToken` YAML element

### Expected Behavior
What should have happened?

Step 3. should be: observe: `automountServiceAccountToken: false` 

### Actual Behavior
Step 3. there was no  `automountServiceAccountToken` present, thereby taking the k8s default of `true`.

NB. If I subsequently patch the default SA to have `automountServiceAccountToken: true`, and then try to manage the setting via Terraform, it correctly updates the value to false. 
It is only the case whereby the `automountServiceAccountToken` YAML element is not present that this bug is observed.

### Important Factoids

I'm on GKE

### References

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Can confirm this is indeed a valid problem. The attributes of the kubernetes_default_service_account aren't being considered in the create function. We'll work on fix.

**Comment by alexsomesan** [comment]
If someone get to doing this before we do, we're happy to take the PR. Thank you!

**Comment by dhrapson** [comment]
I added tests expected them to fail but they didn't: https://github.com/dhrapson/terraform-provider-kubernetes/commits/main

**Comment by pdefreitas** [comment]
We're experiencing the same issue.
