### ISSUE TITLE
Ingress data source allows missing namespace attribute

### ISSUE THREAD

**Issue by wjam** [hashicorp/terraform-provider-kubernetes#1250]
Ingress data source documentation says that the namespace is required: https://github.com/hashicorp/terraform-provider-kubernetes/blob/c48b7d3b6f1ec3b41a5dbf399da11690b67e493c/website/docs/d/ingress.html.markdown#arguments but all resources have the namespace set to optional: https://github.com/hashicorp/terraform-provider-kubernetes/blob/c48b7d3b6f1ec3b41a5dbf399da11690b67e493c/kubernetes/schema_metadata.go#L93-L99

Either the documentation needs to be updated to say that it's optional, or the code needs to change to require the namespace.

**Comment by DrFaust92** [comment]
Hi @wjam. its optional as it defaults to the `default` namespace. same as running kubectl would. but it may be beneficial to reflect this behaviour in docs.
