### ISSUE TITLE
How to use kubernetes provider right after creating cluster?

### ISSUE THREAD

**Issue by acidos** [hashicorp/terraform-provider-kubernetes#1263]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: v0.15.1
Kubernetes Provider version: v2.1.0
Kubernetes version:1.20
```

I have simple workflow. Create a cluster, install ingress with helm and once it's ready, get load balancer's IP address to update CF dns records. It's all in one script.

After creating nginx-ingress controller, I was trying to get IP address of load balancer.

    resource "helm_release" "nginx_ingress" {
      name       = "ingress-nginx"
      ...
    }

    data "kubernetes_service" "this" {
      metadata {
        name = "ingress-nginx-controller"
        namespace = "ingress-nginx"
      }
      depends_on = [ helm_release.nginx_ingress ]
    }

This never worked for me and the reason was that it was trying to connect to localhost.
Then I found this limitation.

> WARNING When using interpolation to pass credentials to the Kubernetes
> provider from other resources, these resources SHOULD NOT be created
> in the same Terraform module where Kubernetes provider resources are
> also used. This will lead to intermittent and unpredictable errors
> which are hard to debug and diagnose. The root issue lies with the
> order in which Terraform itself evaluates the provider blocks vs.
> actual resources. Please refer to this section of Terraform docs for
> further explanation.

and moved `kubernetes` provider to another module.
However, I have now a new problem. 

    module "cluster" {
      source = "./modules/cluster"
      
      cluster_node_count = var.cluster_node_count
      age_path = var.age_path
    }
    
    
    module "network" {
      source = "./modules/network"
      
      host = module.cluster.host
      token = module.cluster.token
      cluster_ca_certificate = module.cluster.cert
      cloudflare_email = var.cloudflare_email
      cloudflare_api_key = var.cloudflare_api_key
      main_domain = var.main_domain
      cluster_subdomains = var.cluster_subdomains
    
      depends_on = [module.cluster]
    }

This also doesn't work and giving 

> Providers cannot be configured within modules using count, for_each or depends_on.

Without `depends_on` the `network` module is called at the same time as cluster, which of course leads to fail, since for the network module cluster should be ready.

So it's kind of dead-loop which I am not sure how to break.

**Comment by richardmcsong** [comment]
https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/gke this might be able to help?

**Comment by alexsomesan** [comment]
@acidos Use-cases when the cluster is created in the same apply operation as resources of the Kubernetes provider is generally not supported by Terraform itself. 

We always advise implementing this type of scenario as two different applies - first one creating the cluster and the second one the other resources inside the cluster.

**Comment by ebostijancic** [comment]
It's possible to create the cluster in the same apply and also configure the provider.

`provider "kubernetes" {
  host                   = module.k8s_cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(module.k8s_cluster.certificate_authority)
  token                  = module.k8s_cluster.cluster_token
}
`
The cluster creation is moved into a dedicated module. The provider will not be configured until the module has completed and the outputs will be available. @alexsomesan please correct me if I am wrong on this.
