### ISSUE TITLE
Opaque Error Message when applying k8s resources: Post "...localhost...": dial tcp [::1]:80: connection refused

### ISSUE THREAD

**Issue by vrichmond499** [hashicorp/terraform-provider-kubernetes#1272]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.13.6
Kubernetes provider version: v2.1.0
Kubernetes version: v1.19.7
```

### Affected Resource(s)
- kubernetes_secret
- (when provided) kubernetes_namespace

### Terraform Configuration Files

```hcl
resource "random_id" "my_secret" {
  byte_length = 48
}

resource "kubernetes_secret" "my_k8s_secret" {
  metadata {
    name = "my_k8s_secret"
  }

  data = {
    secret-key: "${random_id.my_secret.id}"
  }
}
```

### Debug Output

```
Error: Post "http://localhost/api/v1/namespaces/default/secrets": dial tcp [::1]:80: connect: connection refused

  on beagle_fusion_deployment/resources.tf line 57, in resource "kubernetes_secret" "csrf_secret":
  57: resource "kubernetes_secret" "csrf_secret" {
```

(Note that I also get an "Error" due to the keyring already being created, although I do not believe it is related.)

### Steps to Reproduce
1. `terraform apply`

### Expected & Actual Behavior
The k8s secret should have been created smoothly. Instead I got the error and it was not created.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening @vrichmond499 – can you share your provider {} block for this config?

**Comment by vrichmond499** [comment]
This config file itself does not have a `provider {}` block, but the modules I use for my GKE cluster has the following:

```hcl
terraform {
  required_providers {
    google = ">= 3.10.0"
  }
}
```

**Comment by dak1n1** [comment]
As of version 2.x of the kubernetes provider, you'll need an explicit kubernetes provider configuration, for example:

```
provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = "my-context"
}
```

This is done to ensure that the provider doesn't connect automatically to an unexpected cluster. There are more configuration options available here:

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs
