### ISSUE TITLE
Error: expected spec.0.cluster_ip to contain a valid IP, got: None

### ISSUE THREAD

**Issue by arohter** [hashicorp/terraform-provider-kubernetes#1291]
https://github.com/hashicorp/terraform-provider-kubernetes/pull/1273
missed the valid `None` value, and will likely break a whole lot of deployments when people start using the new release https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.3.0

`None` is valid in addition to IP address https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/resource_kubernetes_service.go#L61

```
Error: expected spec.0.cluster_ip to contain a valid IP, got: None

... in resource "kubernetes_service" "svc":
        cluster_ip = "None"
```

**Comment by jrhouston** [comment]
Thanks for reporting this @arohter – I have opened a PR with a fix and added a regression test for this. We'll cut a hotfix release shortly.
