### ISSUE TITLE
Filter well known annotations

### ISSUE THREAD

**Issue by Unichron** [hashicorp/terraform-provider-kubernetes#1296]
Hi!

https://github.com/hashicorp/terraform-provider-kubernetes/pull/1253 introduced for me quite some unwanted changes, didn't go through all because they are spread in different modules but for example the annotations `autoscaling.alpha.kubernetes.io/conditions` and `kubectl.kubernetes.io/restartedAt` came up.

TBH I don't think this change was very well thought out. How do you plan to keep this 'well-known' list up to date? Also what is considered well-known seems arbitrary. If I create my own mutating component I would have to create a PR for this provider? This seems a bit rough.

**Comment by dak1n1** [comment]
That's a good point about maintaining the list. I think we should pursue a more configurable list instead. That was the plan at one point:  https://github.com/hashicorp/terraform-provider-kubernetes/issues/746

I'm guessing the PR was accepted as a stop-gap measure to try and improve things before getting to the longer-term solution. But now I think we should consider reverting it...

**Comment by jrhouston** [comment]
Agreed – the reason we merged this was to support workflows where users actually specify labels and annotations with `kubernetes.io` in the key in their terraform config. It seems like there is a lot more of these annotations than anticipated and maintaining that list is going to be a significant maintenance burden. 

I'm going to revert this change for now.
