### ISSUE TITLE
Support non-preempting priority classes

### ISSUE THREAD

**Issue by therc** [hashicorp/terraform-provider-kubernetes#1299]
### Description

The feature has been in beta since 1.19.  It boils down to a new field,

PreemptionPolicy: PreemptLowerPriority (default) | Never

### References

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#non-preempting-priority-class

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pduboucher** [comment]
Is there a workaround to adding this to our cluster until this implemented?
I've tried adding a PriorityClass via terraform, then adding the PreemptionPolicy manually, to see if it could be imported, but I have not had any success.

**Comment by junaid-ali** [comment]
@pduboucher I'm currently using `kubectl_manifest` from this provider: [gavinbunney/kubectl](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest)

```hcl
resource "kubectl_manifest" "categorizer-priority" {
  yaml_body = yamlencode({
    apiVersion = "scheduling.k8s.io/v1"
    kind       = "PriorityClass"
    metadata = {
      name = var.priority_class_name
    }
    value            = 100
    preemptionPolicy = "Never"
    description      = "This priority class will not cause other pods to be preempted."
  })
}
```

**Comment by pduboucher** [comment]
> @pduboucher I'm currently using `kubectl_manifest` from this provider: [gavinbunney/kubectl](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest)
> 
> ```terraform
> resource "kubectl_manifest" "categorizer-priority" {
>   yaml_body = yamlencode({
>     apiVersion = "scheduling.k8s.io/v1"
>     kind       = "PriorityClass"
>     metadata = {
>       name = var.priority_class_name
>     }
>     value            = 100
>     preemptionPolicy = "Never"
>     description      = "This priority class will not cause other pods to be preempted."
>   })
> }
> ```

Great, thanks a lot for that - works well!
