### ISSUE TITLE
Unable to show resources with self_link in metadata

### ISSUE THREAD

**Issue by joe-a-t** [hashicorp/terraform-provider-kubernetes#1301]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.15.3
Kubernetes provider version: v2.3.1
```

### Affected Resource(s)

- `kubernetes_config_map`
- `kubernetes_namespace`
- Almost certainly others as well

### Terraform Configuration Files
```hcl
resource "kubernetes_config_map" "example" {
  metadata {
    name = "my-config"
  }
}
```

### Steps to Reproduce

1. Create a `kubernetes_config_map` with v2.3.0 (or earlier) of the Kubernetes provider
2. Run `terraform state show kubernetes_config_map.example` to verify it works
3. Upgrade the Kubernetes provider to v2.3.1
4. `terraform state show kubernetes_config_map.example` will no longer work with `unsupported attribute "self_link"` error message

### Expected Behavior
The resource should have been output.

### Actual Behavior
`unsupported attribute "self_link"` error message

### Important Factoids

This also causes errors if you try to open `terraform console` in any affected directories.

### References

It appears to stem from https://github.com/hashicorp/terraform-provider-kubernetes/pull/1294 cc @dak1n1 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by joe-a-t** [comment]
Unrelated but FYI I was just notified [issue_triage](https://github.com/hashicorp/terraform-provider-kubernetes/runs/2769539720) failed with `Error: Unable to resolve action `github/issue-labeler@v2`, unable to find version `v2``

**Comment by jrhouston** [comment]
Looks like we need a StateUpgrader to delete the `self_link` attribute from state for it to work with the `terraform state` command. I was able to reproduce and this doesn't seem to be affecting plan or apply.

A workaround here is run `terraform refresh` which will fix the state.

**Comment by dak1n1** [comment]
> Unrelated but FYI I was just notified [issue_triage](https://github.com/hashicorp/terraform-provider-kubernetes/runs/2769539720) failed with
> 
> ```
> Error: Unable to resolve action `github/issue-labeler@v2`, unable to find version `v2`
> ```

Thanks for letting us know! I added some fixes to my Github Workflow PR that's in progress here: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1300

**Comment by jeunii** [comment]
```
✗ tfp
╷
│ Error: Unsupported attribute
│
│   on ../../modules/cluster_vault/kms.tf line 17, in resource "google_kms_crypto_key" "vault_init":
│   17:   key_ring        = google_kms_key_ring.vault.self_link
│
│ This object has no argument, nested block, or exported attribute named "self_link".
```

Ive already tried `tf refresh` but no use.

Any idea how I can fix this ?

**Comment by jeunii** [comment]
Ok so i got hold of https://github.com/hashicorp/terraform-provider-google/pull/10424/files !

Found the fix. Replaced `self_link` with `id` in the code

**Comment by MeNsaaH** [comment]
Any solution for this? I'm getting this error after upgrading from 2.0.0 to 2.78: 
```
| Error decoding "module.az-devops-namespace_setup.kubernetes_secret.pull_secret[0]" from previous state:
│ unsupported attribute "self_link"
```

**Comment by tobamaestro** [comment]
@MeNsaaH similar issue here, version 2.11.0. Were you able to resolve it?

**Comment by MeNsaaH** [comment]
@tobamaestro no. I had to downgrade

**Comment by tobamaestro** [comment]
@MeNsaaH Thanks for quick reply! Did you try running `terraform refresh` maybe before downgrading?

**Comment by MeNsaaH** [comment]
@tobamaestro  I'm not sure I did.

**Comment by mbyio** [comment]
I encountered this issue, refreshing didn't help. I resolved it using `terraform state rm` to delete the offending resources, and then I re-imported them. Because I imported them using the latest Kubernetes provider version, it fixed the bad attributes.

**Comment by abdullahkhawer** [comment]
Happening with me on version 2.13.0.
```
Terraform will perform the following actions:

  # module.nexus_admin_user_password.kubernetes_secret.user_password will be updated in-place
  ~ resource "kubernetes_secret" "user_password" {
      ~ data      = (sensitive value)
        id        = "studio-ci/nexus-admin"
        # (2 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
