### ISSUE TITLE
Kubernetes secret's binary_data strips off new lines

### ISSUE THREAD

**Issue by dvidg** [hashicorp/terraform-provider-kubernetes#1302]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: Terraform version: 0.14.11
Kubernetes provider version: v2.2.0
Kubernetes version: v1.18.17-gke.100
```

### Affected Resource(s)
- kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "master-uat_aiven-credentials" {
  metadata {
    name      = "aiven-credentials"
    namespace = var.master_namespace
  }

  binary_data = {
    "client.keystore.p12"   = data.google_kms_secret.aiven-credentials-keystore-p12.plaintext
    "client.truststore.jks" = data.google_kms_secret.aiven-credentials-truststore-jks.plaintext
  }
}
```

### Debug Output
We looked through the debug output and could not find any [ERROR] messages related to this issue.

### Panic Output
N/A

### Steps to Reproduce
We took binary data, encrypted it. We base64 encoded it with a new line (ie using `echo <secret> | base64 -b 0` rather than `echo <secret -n | base64 -b 0`). This was loaded into the `kubernetes_secret` resources as above.

### Expected Behavior
I would expect terraform to throw an error, indicating that the secret was inappropriate.

### Actual Behavior
Every time `terraform apply` or `terraform plan` is run, the output suggests this secret will change. However, after applying, the secret is unchanged.

This is not a breaking issue, but it could be better documented as we have spent a fair bit of time debugging it. 

Thanks for creating the `binary_data` field, we really like it!

**Comment by GCHQDeveloper926** [comment]
Hi  @dvidg - did you find a workaround or a fix for this? I am having the same problem with a binary_data secret that is a JKS file. (base64 encoded)
