### ISSUE TITLE
ttl_seconds_after_finished is set to 0 for EKS 1.20

### ISSUE THREAD

**Issue by latikag** [hashicorp/terraform-provider-kubernetes#1310]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.12.26
Kubernetes provider version: 1.13.3
Kubernetes version: 1.20
```

### Affected Resource(s)

- kubernetes_job
### Terraform Configuration Files
```hcl
resource "kubernetes_job" "pi" { 
  metadata {
    name = "demo"
  }
  spec {
    template {
      metadata {}
      spec {
        container {
          name    = "pi"
          image   = "perl"
          command = ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        }
        restart_policy = "Never"
      }
    }
    backoff_limit = 4
  }
}
```

### Steps to Reproduce

This is only reproducible in eks cluster with kubernetes version 1.20
1. create an eks cluster and update it to version 1.20
2. create a terraform resource kubernetes_job, and do not specify ttl_seconds_after_finished.
3. run terraform apply
4. check job yaml and look for ttl_seconds_after_finished
5. kubectl get jobs -o yaml | grep ttl

### Expected Behavior
Since ttl_seconds_after_finished is not specified, its value should be ignored.

### Actual Behavior
What actually happened?
          f:ttlSecondsAfterFinished: {}
    ttlSecondsAfterFinished: 0
ttl_seconds_after_finished is getting set to 0

### Important Factoids

running in EKS, kubernetes version 1.20.
### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pit** [comment]
Check https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#job-v1-batch

ttlSecondsAfterFinished field has comment:

> This field is alpha-level and is only honored by servers that enable the TTLAfterFinished feature.

So most probably TTLAfterFinished is disabled so provider will not set this field value.

**Comment by alexsomesan** [comment]
Indeed, @pit correctly points out this is attribute is conditioned by an API feature gate which is off by default in K8s 1.20.
It seems that the API might send a value of 0 instead of "not set" when this feature is off, which would explain what you are reporting here.
If the API server returns a value for an attribute, the provider will collect this value in state. This is the correct provider behaviour. Unfortunately, in this case the API returns an unexpected value, but since we cannot determine from the provider side if the feature flag is off or on, we don't have enough information to tell if the value is the correct one or not.

**Comment by alexsomesan** [comment]
Can you try to upgrade the provider to the latest version and try this scenario again? There is a fix for this exact situation but the version you are using is too old to include that.

**Comment by juliangovender** [comment]
Same issue experienced in K8s v.1.21 (ttl_seconds_after_finished is implicitly set to 0).

**Comment by juliangovender** [comment]
Experienced the same issue as above with:

Terraform version: 0.13.x
Kubernetes provider version: 1.13.3
Kubernetes version: 1.21

@alexsomesan I upgraded the Kubernetes provider version to 2.8.0 and this solved the issue. 

Thank you
