### ISSUE TITLE
Allow setting job's `parallelism` to zero

### ISSUE THREAD

**Issue by msiemens** [hashicorp/terraform-provider-kubernetes#1313]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.0.0
Kubernetes provider version: v2.3.2
Kubernetes version: v1.20
```

### Affected Resource(s)

- kubernetes_job

### Terraform Configuration Files
```hcl
resource "kubernetes_job" "my_app" {
  metadata {
    labels = {
      app = "my-app"
    }

    name = "my-app"
  }

  spec {
    completions = 0
    parallelism = 1

    template {
      metadata {
        labels = {
          app = "my-app"
        }
        name = "my-app"
      }

      spec {
        container {
          name = "my-app"
          image = "alpine"
          // ...
        }
      }
    }
  }

  wait_for_completion = false
}
```

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
What should have happened?

- Terraform creating a job with `parallelism` of zero, effectively creating a paused job

### Actual Behavior
What actually happened?

- Got an error: `parallelsim must be greater than 0`

### Important Factoids

Kubernetes supports jobs with a `parallelism` of 0 according to [Jobs: Controlling parallelism](https://kubernetes.io/docs/concepts/workloads/controllers/job/#controlling-parallelism):

> The requested parallelism `(.spec.parallelism)` can be set to any non-negative value. If it is unspecified, it defaults to 1. If it is specified as 0, then the Job is effectively paused until it is increased.

Terraform on the other hand requires a positive integer, not just a non-negative one (see line 73): https://github.com/hashicorp/terraform-provider-kubernetes/blob/d5fbc23cf7186bc176663e15b55a5f106f8d5da0/kubernetes/schema_job_spec.go#L68-L75

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by therc** [comment]
Looks like this was merged and thus OK to close? It seems to work for me.
