### ISSUE TITLE
Immutable config_map and secret

### ISSUE THREAD

**Issue by chrisroat** [hashicorp/terraform-provider-kubernetes#1317]
### Description

I would like to request that config map and secret resources support the recent immutable argument, and would be happy to help if this would be a good first issue.

The [immutable config map](https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable) and [immutable secret](https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable) have become stable in 1.21 (alpha in 1.18, beta/enabled in 1.19).   A Google search had a top hit showing that the parameter is in the codebase: [config_map](https://github.com/hashicorp/terraform-provider-kubernetes/blob/d5fbc23cf7186bc176663e15b55a5f106f8d5da0/vendor/k8s.io/api/core/v1/types.go#L5950), [secret](https://github.com/hashicorp/terraform-provider-kubernetes/blob/d5fbc23cf7186bc176663e15b55a5f106f8d5da0/vendor/k8s.io/api/core/v1/types.go#L5810).  However, I do not think it is implemented or exposed as of yet.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by therc** [comment]
This was implemented for secrets in #1280, but not for config maps.
