### ISSUE TITLE
get secret as terraform data

### ISSUE THREAD

**Issue by peter-accedian** [hashicorp/terraform-provider-kubernetes#1321]
Using your provider; Is there a way to retrieve a k8s secret form a namespace/name/property so it can be used as a variable in tf?

**Comment by jrhouston** [comment]
I think you are looking for the [secret data source](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/secret).

**Comment by aareet** [comment]
Closing since it has been 10 days since last response
