### ISSUE TITLE
Plugin crashing while destroying cluster

### ISSUE THREAD

**Issue by fuster92** [hashicorp/terraform-provider-kubernetes#1323]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: Terraform v1.0.1
Kubernetes provider version: terraform-provider-k8s_v0.8.2
Kubernetes version: v1.19.8-rancher1-1
```

### Affected Resource(s)

- k8s_manifest
### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
I'm using this [quickstart guide](https://github.com/rancher/quickstart/tree/master/aws), and it uses this provider.

We've modified `data.tf` and `infra.tf`, [gist](https://gist.github.com/fuster92/472dce0e657f93b7a3d6a3b39661d9a3)
### Panic Output

[crash](https://gist.github.com/fuster92/472dce0e657f93b7a3d6a3b39661d9a3#file-crash-log
### Steps to Reproduce

1. Using the provided data.tf and infra.tf
2. `terraform apply`
3. Wait for cluster
4. `terraform destroy` 

It panics trying to remove resources

### Expected Behavior
What should have happened?

Removed resources
### Actual Behavior
What actually happened?
Crash
### Important Factoids

Running on an SLES AMI and installing rancher
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
The provider in your crash log is `terraform-provider-k8s` _not_ `terraform-provider-kubernetes` – you need to open this issue on their repository here: https://github.com/banzaicloud/terraform-provider-k8s
