### ISSUE TITLE
Create config map from directory

### ISSUE THREAD

**Issue by Oliver-Sellwood** [hashicorp/terraform-provider-kubernetes#1329]
### Description

Enable creating a configmap from a folder, this would be helpful when a folder contains arbitrarily many configuration files all of which need to be in the configmap and so many that it would become overly tedious to manually maintain the mapping between files in the folder and the configmap files listing.

### Potential Terraform Configuration

```hcl
resource "kubernetes_config_map" "directory-config" {
  metadata {
    name = "directory-config"
  }

  directory = "${path.module}/directory-config/")
}

```

**Comment by jrhouston** [comment]
Thanks for opening this @Oliver-Sellwood. You can actually do this with Terraform's expression syntax. Here's an example:

```hcl
locals {
  directory_config = "./directory-config"
}

resource "kubernetes_config_map" "example" {
  metadata {
    name = "test"
  }

  data = {
    for f in fileset(local.directory_config, "*.txt") :
    f => file(join("/", [local.directory_config, f]))
  }
}
```

We prefer not to add functionality to resources in the provider to read from the local filesystem if we can lean on Terraform's built-in functions to do that for us .

**Comment by Oliver-Sellwood** [comment]
Ah yes,  perfect. Thanks for that!

#399 referencing the only search result I was getting to help future tf noobs :)
