### ISSUE TITLE
Static provisioning of PVC not possible

### ISSUE THREAD

**Issue by aardbol** [hashicorp/terraform-provider-kubernetes#1331]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: Terraform v1.0.2
Kubernetes provider version: EKS
Kubernetes version:1.16
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "kubernetes_persistent_volume_claim" "nextcloud" {
  for_each = var.nextcloud_volumes

  metadata {
    name      = "nextcloud-${each.key}-pvc"
    namespace = "tools"
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    storage_class_name = ""
    resources {
      requests = {
        storage = "${each.value}Gi"
      }
    }
  }
}
```

### Expected Behavior
Empty storage class name should be respected for the PVC resource. The PV resource was created without one.

### Actual Behavior
Instead, the default storage class is set for the PVC after applying, even though this doesn't happen for the PV

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dak1n1** [comment]
Thanks for this bug report! I'll add it to the existing issue and close this one as a duplicate. This is a case we hope to cover in the near future. In the mean time, there are a couple work-arounds available in this bug: https://github.com/hashicorp/terraform-provider-kubernetes/issues/872#issuecomment-852275475
