### ISSUE TITLE
Add support for CustomResourceDefinition

### ISSUE THREAD

**Issue by dennisahlin** [hashicorp/terraform-provider-kubernetes#1336]
### Description

Missing CustomResourceDefinitions. Currently, to create custom resource definitions, you have to use kubectl provider and define the manifest. It would be great if it was possible to use `kubernetes_custom_resource_definition` instead.

### References
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by judgeaxl** [comment]
@dennisahlin This feature is being developed in a separate experimental provider: https://github.com/hashicorp/terraform-provider-kubernetes-alpha.

**Comment by jrhouston** [comment]
It's coming soon 😅  https://github.com/hashicorp/terraform-provider-kubernetes/pull/1337

Closing as this is a duplicate.
