### ISSUE TITLE
terraform 0.12 not supported with release 2.4.0

### ISSUE THREAD

**Issue by dschunack** [hashicorp/terraform-provider-kubernetes#1341]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: Terraform v0.12.31
+ provider.aws v3.52.0
+ provider.external v2.1.0
+ provider.helm v2.2.0
+ provider.kubernetes v2.4.0
+ provider.local v2.1.0
+ provider.null v3.1.0
+ provider.random v2.2.1
+ provider.template v2.2.0

Kubernetes provider version: 2.4.0
Kubernetes version: 1.20
```

### Affected Resource(s)

All kubernetes resources that use the kubernetes provider.

### Steps to Reproduce

Use terraform 0.12.31 

1. `terraform init`
2. `terraform  apply`

3: Output
Error: Incompatible terraform version

  on .terraform/modules/ebs-csi-driver/kubernetes.tf line 1, in provider "kubernetes":
   1: provider "kubernetes" {

**This provider requires Terraform v0.14.8 or above**

### Expected Behavior
Kubernetes provider 2.3.2 runs without problems.

### Actual Behavior
Error: Incompatible terraform version

  on .terraform/modules/ebs-csi-driver/kubernetes.tf line 1, in provider "kubernetes":
   1: provider "kubernetes" {

This provider requires Terraform v0.14.8 or above

**Comment by ifs-anthonylecarrer** [comment]
neither 0.12.x nor 0.13.x without any communication ......

**Comment by simonvanderveldt** [comment]
We're using
```
  required_providers {
    kubernetes = {
      version = ">= 2.0.0, < 3.0.0"
    }
  }
```
to make sure that allout breakage doesn't happen, but that assumes proper use of versions/tags by the provider (i.e. a bump of the major version in case of backwards incompatible changes).
Can this be fixed?

**Comment by jrhouston** [comment]
Sorry for the disruption folks. This version constraint was not intentional and was carried over when we merged the kubernetes-alpha code into this repository. 

We have a [hotfix](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1345) incoming.
