### ISSUE TITLE
kubernetes_secret not updated. 

### ISSUE THREAD

**Issue by motizzz** [hashicorp/terraform-provider-kubernetes#1342]
Hi, 
we start using Kubernetes provider version: 2.3.0 and we noticed that when we destroy random_password the kubernetes_secret data pass value wont changed to "". 

in Kubernetes provider version: 2.0.2 it works as expected 

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.15.5
Kubernetes provider version: 2.3.0 and higher  
Kubernetes version: 1.18
```

### Affected Resource(s)

- kubernetes_secret

### Terraform Configuration Files
```hcl
variable "pass" {}
variable "zone" {}
variable "project_id" {}
variable "cluster_name" {}


data "google_client_config" "default" {
}

data "google_container_cluster" "cluster" {
  name     = var.cluster_name
  location = var.zone
  project  = var.project_id
}

provider "kubernetes" {
  version                = "2.3.0"
  host                   = "https://${data.google_container_cluster.cluster.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
}

resource "random_password" "pass" {
  count = var.pass ? 1 : 0
  length = 16
}

resource "kubernetes_secret" "pass" {
  metadata {
    name = "pass"
  }
  data = {
    pass = element(concat(random_password.pass.*.result, tolist([""])), 0)
  }
}


```

### Steps to Reproduce

1.  terraform apply -var pass=true -var zone=us-central1-c -var project_id=my-project -var cluster_name=cluster-foo
2. terraform apply -var pass=false -var zone=us-central1-c -var project_id=my-project -var cluster_name=cluster-foo

### Expected Behavior
What should have happened?
kubernetes_secret pass should changed to empty string "" 

### Actual Behavior
What actually happened?
password stay in secret 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by omrihayun** [comment]
👍

**Comment by sambonbonne** [comment]
I am facing the same issue when adding a new key/value in a secret and trying to update with `terraform apply`. Terraform doesn't output any error and it exits with an OK code.
