### ISSUE TITLE
Can't enable the kubernetes_manifest on an EKS cluster

### ISSUE THREAD

**Issue by toddgardner** [hashicorp/terraform-provider-kubernetes#1347]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.0.3
Kubernetes provider version: v2.4.1
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-14T14:49:35Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  config_path = "~/.kube/config"
  config_context = "<Relevant context>"

  experiments {
    manifest_resource = true
  }
}
```

I also used a CRD from cert-manager, which is longer so I put it into a gist (second file in the gist)
https://gist.github.com/toddgardner/677cdb9288a3f62d79b987c7a1c9f06c

### Debug Output

First file in gist: https://gist.github.com/toddgardner/677cdb9288a3f62d79b987c7a1c9f06c

### Panic Output

Did not panic

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior

Since I've enabled the experiments, it should connect.

### Actual Behavior

It produces an error saying experiments are not on when they are.

### Important Factoids

This is using a (mostly empty) EKS cluster; I tried the exec block auth also, I removed it to just using the file for simplicity

kubectl works find with the same context name.

Digging through the provider code, I found I could force it past this check with `TF_X_KUBERNETES_MANIFEST_RESOURCE=1`; this fails for different reasons "cannot create REST client: no client config": https://gist.github.com/toddgardner/22766c5e54746a1c4acdcc03286869dd

But the auth things I have were working fine on kubernetes-alpha.

I put up a repo with my files to a branch (the repo is shared with some issues I found on the previous alpha provider: https://github.com/toddgardner/terraform_crash_repro/tree/2.4.1-kubernetes

### References

None directly

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi Todd!

Thank you for the very detailed report! I especially appreciate the debug log and the exact reproduction configuration.

I did apply the configuration you provided on an EKS 1.18 cluster and it worked as expected - applied successfully. This was using the `exec` type credentials in kubeconfig.

Unfortunately, this didn't match up with your report so I went and checked your debug log. I did find the following lines there:
```
2021-08-03T22:03:14.524-0400 [DEBUG] provider.terraform-provider-kubernetes_v2.4.1_x5: 2021/08/03 22:03:14 [WARN] Invalid provider configuration was supplied. Provider operations likely to fail: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
This is indicative of an empty provider block or no block at all in the applied configuration.

By contrast, when I applied the configuration you provided on EKS, I got this message in the debug log:
```
2021-08-04T08:22:47.056+0200 [DEBUG] provider.terraform-provider-kubernetes_v2.4.1_x5: 2021/08/04 08:22:47 [DEBUG] Using kubeconfig: /Users/alex/work/terraform-provider-kubernetes/kubernetes/test-infra/ek
s/kubeconfig_k8s-acc-8a82
2021-08-04T08:22:47.056+0200 [DEBUG] provider.terraform-provider-kubernetes_v2.4.1_x5: 2021/08/04 08:22:47 [DEBUG] Using custom current context: "eks_k8s-acc-8a82"
2021-08-04T08:22:47.056+0200 [DEBUG] provider.terraform-provider-kubernetes_v2.4.1_x5: 2021/08/04 08:22:47 [DEBUG] Using overidden context: api.Context{LocationOfOrigin:"", Cluster:"", AuthInfo:"", Namesp
ace:"", Extensions:map[string]runtime.Object(nil)}
```

Can you please confirm that this is indeed the exact configuration you attempted to use?
Was there any previous state present when you tried it?
Was this configuration contained in a module that was part of a larger TF config?

I would like to ask you to retry applying the above configuration in a clean directory with a clean shell environment (no Terraform or provider specific variables present) and report the results again (with debug logs).

Thanks again for your time!

**Comment by toddgardner** [comment]
This was the configuration, there's no tfstate or configued backend, and I specifically sliced it out of a larger configuration so it's self contained reproducer.

Here's a clean run in the new directory with no environment variables set; I do a grep on env to show the latter is true, and you can see the provider block in the head below. Is there some other way terraform is taking in configuration?

(just so it's not confusing as I have multiple branches in the crash repo, I uploaded the branch to a new repository: https://github.com/toddgardner/terraform_kub_manifest, it's the same files as above)

```
Todds-MBP-2:git todd$ git clone https://github.com/toddgardner/terraform_kub_manifest.git
Cloning into 'terraform_kub_manifest'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 17 (delta 4), reused 17 (delta 4), pack-reused 0
Receiving objects: 100% (17/17), 19.47 KiB | 1.39 MiB/s, done.
Resolving deltas: 100% (4/4), done.
Todds-MBP-2:git todd$ cd terraform_kub_manifest/
Todds-MBP-2:terraform_kub_manifest todd$ env | grep -i TF
LANG=en_US.UTF-8
Todds-MBP-2:terraform_kub_manifest todd$ head -n 10 contour.tf 
provider "kubernetes" {
  config_path = "~/.kube/config"
  config_context = "eks_fero-prod4"

  experiments {
    manifest_resource = true
  }
}

resource "kubernetes_manifest" "customresourcedefinition_certificaterequests_cert_manager_io" {
Todds-MBP-2:terraform_kub_manifest todd$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/template from the dependency lock file
- Installing hashicorp/kubernetes v2.4.1...
- Installed hashicorp/kubernetes v2.4.1 (signed by HashiCorp)
- Installing hashicorp/aws v3.52.0...
- Installed hashicorp/aws v3.52.0 (signed by HashiCorp)
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/local v2.1.0...
- Installed hashicorp/local v2.1.0 (signed by HashiCorp)
- Installing hashicorp/null v3.1.0...
- Installed hashicorp/null v3.1.0 (signed by HashiCorp)
- Installing hashicorp/template v2.2.0...
- Installed hashicorp/template v2.2.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Todds-MBP-2:terraform_kub_manifest todd$ terraform apply
╷
│ Error: Experimental feature not enabled.
│ 
│   with kubernetes_manifest.customresourcedefinition_certificaterequests_cert_manager_io,
│   on contour.tf line 10, in resource "kubernetes_manifest" "customresourcedefinition_certificaterequests_cert_manager_io":
│   10: resource "kubernetes_manifest" "customresourcedefinition_certificaterequests_cert_manager_io" {
│ 
│ The `kubernetes_manifest` resource is an experimental feature and must be explicitly enabled in the provider configuration block.
```

Here's a debug log: https://gist.github.com/toddgardner/22d346286c3dfa6b65777df9159e0f21

Here's showing the kube context and path are set correctly:

```
Todds-MBP-2:terraform_kub_manifest todd$ kubectl config current-context
eks_fero-prod4
Todds-MBP-2:terraform_kub_manifest todd$ echo $KUBECONFIG

Todds-MBP-2:terraform_kub_manifest todd$ ls ~/.kube/config
/Users/todd/.kube/config
```

Is this due to terraform 1.0.3?

**Comment by alexsomesan** [comment]
OK, I figured out what going on.

In your versions.tf file, you have this:
```
    kubernetes-alpha = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.4.1"
    }
```
The effect of that is to set the [local name](https://www.terraform.io/docs/language/providers/requirements.html#local-names) of the  `kubernetes` provider  to`kubernetes-alpha`. 

This in turn causes Terraform to expect a "kubernetes-alpha" block provider block and no longer considers your provided configuration for the Kubernetes provider. However, your resource doesn't refer to the (now renamed) provider by it's new name, and this causes Terraform to assume no configuration has been passed to the provider called `kubernetes`.

Since the kubernetes_manifest resource is now under the kubernetes provider, there is no need to mention kubernetes-alpha anywhere.

Change the above block to this and it should work as expected:
```
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.4.1"
    }
```

As a side note, using the local names feature you inadvertently discovered here, you could do something like the following:
```
terraform {
  required_providers {

    mykubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.4.1"
    }
  }

  required_version = "~> 1.0.3"
}

provider "mykubernetes" {
  experiments {
    manifest_resource = true
  }
}

resource "kubernetes_manifest" "customresourcedefinition_certificaterequests_cert_manager_io" {
  provider = mykubernetes
  manifest = {
  ...
  }
}
```

**Comment by toddgardner** [comment]
Wow thanks, I completely missed that. I can confirm the changes work -- excited to try the new provider code. Closing.
