### ISSUE TITLE
Error: context deadline exceeded with kubernetes_persistent_volume_claim resource

### ISSUE THREAD

**Issue by paleti5** [hashicorp/terraform-provider-kubernetes#1349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform version
Terraform v0.13.4
+ provider registry.terraform.io/gavinbunney/kubectl v1.11.2
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
### Affected Resource(s)

* `kubernetes_persistent_volume_claim`

### Terraform Configuration Files

```hcl
variable "spark_namespace" {
  type        = string
  description = "Namespace to create for spark and associated storage to be hosted in"
  default = "test"
}
# Creates Spark & associated storage namespace
resource "kubernetes_namespace" "sparkns" {
  metadata {
    name = var.spark_namespace
  }
}
resource "kubernetes_persistent_volume" "datalake" {
  metadata {
    name = "pv-data-lake"
  }
  spec {
    capacity = {
      storage = "800Gi"
    }
    access_modes                     = ["ReadWriteMany"]
    persistent_volume_reclaim_policy = "Retain"
    mount_options = [
      "-o allow_other",
      "--file-cache-timeout-in-seconds=120"
    ]
    persistent_volume_source {
      csi {
        driver        = "blob.csi.azure.com"
        read_only     = false
        volume_handle = "unique-volumeid"
        volume_attributes = {
          resource_group  = var.datalake_resource_group_name
          storage_account = var.target_datalake
          container_name  = "fiona"
        }
        node_stage_secret_ref {
          name      = "az-dl-connection"
          namespace = kubernetes_namespace.sparkns.metadata[0].name
        }
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim" "spark_pvc_dl" {
  metadata {
    name = "pvc-data-lake"
    namespace = kubernetes_namespace.sparkns.metadata[0].name
  }
  spec {
    access_modes = ["ReadWriteMany"]
    resources {
      requests = {
        storage = "10Gi"
      }
    }
    volume_name = kubernetes_persistent_volume.datalake.metadata[0].name
  }
}

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by you4su** [comment]
I have the same issue with trying to delete a namespace using the kubernetes provider and I get a context deadline error as well after 5 mins.
hashicorp/kubernetes v2.4.1 
Terraform v1.0.5
Need someone to look into this.

`module.argocd.kubernetes_namespace.argocd: Still destroying... [id=argocd, 4m50s elapsed]
╷
│ Error: context deadline exceeded`

**Comment by aleti-pavan** [comment]
@paleti5 is me with a different GitHub account. I solved that with a shell script as I couldn't find solution from terraform.

**Comment by torgebauer** [comment]
Think the issue is that the PVC can be either in the 
`Volume Binding Mode: WaitForFirstConsumer` or 
`Volume Binding Mode: Immediate`
If it is immediate this issue should not occur. If your volume claim is waiting on the first consumer then the status will never set to "Bound" and it will stay forever in "Pending". 

For me it worked to add "wait_until_bound = false" in your kubernetes_persistent_volume_claim. I have no other resources that are dependent on the PVC.

**Comment by jrisch** [comment]
@torgebauer I face the same issue, but have no PVC's at all. For me it's related to namespace deletion. It might be that TF is trying to delete the namespace before all the resources in it has been removed.

**Comment by SIRISHA-SHARON** [comment]
My terraform script creates a PVC for  IBM Redhat Openshift Cluster.

`resource "kubernetes_persistent_volume_claim" "pvc" {
  metadata {
    name = "exampleclaimname"
  }
  spec {
    access_modes = ["ReadWriteMany"]
    resources {
      requests = {
        storage = "16Gi"
      }
    }

    storage_class_name = "ibmc-vpc-block-retain-general-purpose"

  }
}`

I get this error on terraform apply-

`module.ocp_all_inclusive.module.observability_agents[0].helm_release.logdna_agent[0]: Creation complete after 31s [id=logdna-agent]
╷
│ Error: context deadline exceeded
│ 
│   with kubernetes_persistent_volume_claim.pvc,
│   on main.tf line 375, in resource "kubernetes_persistent_volume_claim" "pvc":
│  375: resource "kubernetes_persistent_volume_claim" "pvc" {`

Any pointers to fixing this issue?

**Comment by berserkbuddhist** [comment]
same issue here

`Terraform v1.4.5`
