### ISSUE TITLE
kubernetes_ingress data source returns error "Invalid address to set"

### ISSUE THREAD

**Issue by jrlonan-gt** [hashicorp/terraform-provider-kubernetes#1354]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.3
Kubernetes provider version:  hashicorp/kubernetes v2.4.1
Kubernetes version: 1.18
```

### Affected Resource(s)
- kubernetes_ingress

### Terraform Configuration Files
```
data "kubernetes_ingress" "eks_prometheus" {
  metadata {
    name = "kube-prometheus-stack-prometheus"
    namespace = "monitoring"
  }

}
```

### Debug Output
https://gist.github.com/jrlonan-gt/587a02d65faa9021c94b5c5da9c3829b

### Panic Output
N/A

### Steps to Reproduce
1. `terraform plan` 
2. `terraform plan --target kubernetes_ingress.eks_prometheus`
3. `terraform apply`

### Expected Behavior
Data source should read the existing Ingress object in k8s for use with other resources

### Actual Behavior
Terraform returns an error ```Error: Invalid address to set: []string{"spec", "0", "ingress_class_name"}```

### Important Factoids
- Kubernetes ingress is created via Helm
- I'm using terragrunt wrapper

### References
N/A

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrlonan-gt** [comment]
upgraded provider version to 2.4.1 and still see the same issue
```╷
│ Error: Invalid address to set: []string{"spec", "0", "ingress_class_name"}
│
│   with data.kubernetes_ingress.eks_prometheus,

**Comment by tensor5** [comment]
Same here.

**Comment by venc0r** [comment]
I'm facing almost the same problem with the kubernetes_pod datasource 
```
│ Error: Invalid address to set: []string{"spec", "0", "affinity", "0", "node_affinity", "0", "required_during_scheduling_ignored_during_execution", "0", "node_selector_term", "0", "match_fields"}
```

**Comment by cilindrox** [comment]
@jrlonan-gt did you create the ingress resource using `generate_name` by any chance? See #1954 , might be related.
