### ISSUE TITLE
Issue when attempting to create kubernetes secret 

### ISSUE THREAD

**Issue by sflaherty2009** [hashicorp/terraform-provider-kubernetes#1355]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.15.5
Kubernetes provider version: v2.4.1
Kubernetes version: 1.20.9_1547
```

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "wdp-dev-sa-token" {
  metadata {
    name = "wdp-dev-sa-token"
    namespace = kubernetes_namespace.wdp-dev.metadata[0].name
    annotations = {
      "kubernetes.io/service-account.name" = "wdp-secrets-sa"
    }
  }
  type = "kubernetes.io/service-account-token"
  depends_on = [kubernetes_namespace.wdp-dev]
}

resource "kubernetes_secret" "wdp-staging-sa-token" {
  metadata {
    name = "wdp-staging-sa-token"
    namespace = kubernetes_namespace.wdp-staging.metadata[0].name
    annotations = {
      "kubernetes.io/service-account.name" = "wdp-secrets-sa"
    }
  }
  type = "kubernetes.io/service-account-token"
  depends_on = [kubernetes_namespace.wdp-staging]
}
```

### Expected Behavior
Create a kubernetes secret for use with a new kubernetes service account

### Actual Behavior
terraform failure.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @sflaherty2009,

Do you still have this issue with the latest provider version? If so, please provide more details about the issue, like the error message you observe and debug output.

Thank you.
