### ISSUE TITLE
For "kubernetes_manifest" the provider is not checking the resource is destroyed

### ISSUE THREAD

**Issue by EcaterinaGr** [hashicorp/terraform-provider-kubernetes#1357]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v1.0.4
Kubernetes provider version: 2.4.1
Kubernetes version: 1.20
```

### Affected Resource(s)
- kubernetes_manifest

### Steps to Reproduce

1. `terraform destroy` 

### Expected Behavior
The provider should check if the resource created via ```kubernetes_manifest``` was really deleted. 

### Actual Behavior
The provider marks the resource as destroyed, even though the resource still exists.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mmingdai** [comment]
👍
