### ISSUE TITLE
deployment.kubernetes.io/revision annotation causes problems when successively applying kubernetes_manifest

### ISSUE THREAD

**Issue by nbraun-wolf** [hashicorp/terraform-provider-kubernetes#1370]
Hi I always get errors when re-applying some changes with the _kubernetes_manifest_ ,due to the _deployment.kubernetes.io/revision_ annotation. 

When I dont set it, I get an error saying that an unexpected annotation has been added (by kubernetes). 

```bash
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to kubernetes_manifest.um_deployment, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.metadata.annotations: new element
│ "deployment.kubernetes.io/revision" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

When I add it myself and set it to 1 on the inital apply, then the kubernetes API is complaining on the next apply.

```bash
╷
│ Error: API response status: Failure
│ 
│   with kubernetes_manifest.um_deployment,
│   on update-manager.tf line 37, in resource "kubernetes_manifest" "um_deployment":
│   37: resource "kubernetes_manifest" "um_deployment" {
│ 
│ Apply failed with 1 conflict: conflict with "kube-controller-manager" using apps/v1: .metadata.annotations.deployment.kubernetes.io/revision
```

I dont believe that this is unkown or I am the first one that finds this problem It must be common. I am probably overlooking something. 

Does someone know how to handle this?

```bash
$ terraform -v
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.72.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.4. You can update by downloading from https://www.terraform.io/downloads.html
````

Kubernetes version: 1.21.2

**Comment by alexsomesan** [comment]
Thanks for documenting this scenario, @nbraun-wolf. 

This is in fact a known limitation of the provider. We're actively working on a solution. 

Fundamentally, this is happening because a change after apply to an attribute which hasn't been planned for as "unknown" is not well tolerated by Terraform.
