### ISSUE TITLE
Google GKE Provider setup docs need updating

### ISSUE THREAD

**Issue by AmandaHassoun** [hashicorp/terraform-provider-kubernetes#1371]
### Affected Resource(s)
`google_container_cluster` provider example in the[ docs here ](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/getting-started#provider-setup)

### Expected Behavior
Since `zone` has been deprecated in favour of `location`, let's update the docs before someone else gets stuck on this for a bit like me..

**Comment by arybolovlev** [comment]
Fix: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1944
