### ISSUE TITLE
Terraform destroys kubernetes namespaces after reapplying it

### ISSUE THREAD

**Issue by sri53** [hashicorp/terraform-provider-kubernetes#1398]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.0.6. You can update by downloading from https://www.terraform.io/downloads.html

Kubernetes version : 1.20.9
```

### Affected Resource(s)
```
kubernetes_namespace
```
### Debug Output

```
terraform plan
kubernetes_namespace.example["default-1"]: Refreshing state... [id=default-1]
kubernetes_namespace.example["default-2"]: Refreshing state... [id=default-2]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # kubernetes_namespace.example["default-1"] will be destroyed
  - resource "kubernetes_namespace" "example" {
      - id = "default-1" -> null

      - metadata {
          - annotations      = {
              - "name" = "example-annotation"
            } -> null
          - generation       = 0 -> null
          - labels           = {
              - "mylabel" = "label-value"
            } -> null
          - name             = "default-1" -> null
          - resource_version = "45015" -> null
          - uid              = "992a7d22-xxxx-> null
        }
    }
```

### Expected Behavior
What should have happened?
After creating the namespace, while applying "terraform apply" command again terraform destroys the namespaces.

### Actual Behavior
No changes. Your infrastructure matches the configuration.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
@sri53 i notice in your output the namespace resource seems to be part of a for_each – can you share your config so we can reproduce?

**Comment by sri53** [comment]
@jrhouston Please find the config below.
```
resource "kubernetes_namespace" "example" {
  depends_on = [data.kubernetes_all_namespaces.allns ]
  
  for_each = toset([for ns in distinct(var.namespaces) : ns if !contains(data.kubernetes_all_namespaces.allns.namespaces, ns)])
  
  #temp fix
  lifecycle {
    ignore_changes = [metadata]
    prevent_destroy = true
  }
  metadata {
    annotations = {
      name = "example-annotation"
    }

    labels = {
      mylabel = "label-value"
    }

    name = each.key
  }
}
```

**Comment by sri53** [comment]
@jrhouston Please find the config

```
resource "kubernetes_namespace" "example" {
  depends_on = [data.kubernetes_all_namespaces.allns ]
  
  for_each = toset([for ns in distinct(var.namespaces) : ns if //some condition here])
  
  #temp fix
  lifecycle {
    ignore_changes = [metadata]
    prevent_destroy = true
  }
  metadata {
    annotations = {
      name = "example-annotation"
    }

    labels = {
      mylabel = "label-value"
    }

    name = each.key
  }
}
```

**Comment by jrhouston** [comment]
@sri53 It seems like it might be the condition in your for_each block that's causing one of the namespaces to be deleted – can you share what the conditional is?

**Comment by sri53** [comment]
@jrhouston Please find the condition below
```
  for_each = toset([for ns in distinct(var.namespaces) : ns if !contains(data.kubernetes_all_namespaces.allns.namespaces, ns)])
```
When I rerun terraform apply command it tried to destroy what are all namespaces created using that code.

If you see I created two namespaces. When I run terrafrom plan it tries to destroy both the namespaces. See the below sample output.

```
terraform plan
kubernetes_namespace.example["default-1"]: Refreshing state... [id=default-1]
kubernetes_namespace.example["default-2"]: Refreshing state... [id=default-2]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # kubernetes_namespace.example["default-1"] will be destroyed
  - resource "kubernetes_namespace" "example" {
      - id = "default-1" -> null

      - metadata {
          - annotations      = {
              - "name" = "example-annotation"
            } -> null
          - generation       = 0 -> null
          - labels           = {
              - "mylabel" = "label-value"
            } -> null
          - name             = "default-1" -> null
          - resource_version = "45015" -> null
          - uid              = "992a7d22-xxxx-> null
        }
    }
 # kubernetes_namespace.example["default-2"] will be destroyed
  - resource "kubernetes_namespace" "example" {
      - id = "default-2" -> null

      - metadata {
          - annotations      = {
              - "name" = "example-annotation"
            } -> null
          - generation       = 0 -> null
          - labels           = {
              - "mylabel" = "label-value"
            } -> null
          - name             = "default-2" -> null
          - resource_version = "45016" -> null
          - uid              = "992a7d22-xxxx-> null
        }
    }
```

**Comment by alexsomesan** [comment]
@sri53 I think there's a bit of misunderstanding here around how `for_each` works. It essentially adds as many copies of the resource that it's applied to into the terraform configuration.

In your example, if I understand it correctly, the expression on the right of for_each comiles a list of namespaces which are specified in the variable `namespace` but not yet present in the cluster. 

So, on the first apply the expression evalueates to the set of ["default-1", "default-2"] and thus two kubernetes_namespace instances are added to the configuration and eventually applied.

When you then run plan or apply again, the same expression will now evaluate to an empty set wich in turn causes for_each to add no instances of kubernetes_namespace to the configuration. This causes Terraform to plan for the removal of the two namespaces resources it sees in state, but not in configuration anymore. This is the same as if you had removed the two instances you previously had. 

Think of it like having two distinct `resource "kubernetes_namespace" "example" { .. }` blocks and commenting them out of the .tf file. This is the effect of for_each. It's not additive, it's always an absolute count.

I hope this makes sense and helps you reason with for_each expressions.

**Comment by sri53** [comment]
@alexsomesan Thanks for the response. Can you please explain with some examples or Please let me know how to fix this.

**Comment by sri53** [comment]
Closing
