### ISSUE TITLE
Kubernetes Manifest resource not working in EKS

### ISSUE THREAD

**Issue by refucktor** [hashicorp/terraform-provider-kubernetes#1399]
I'm facing a very frustrating issue. While running terraform in a CI/CD from Gitlab.

**Environment**
- Kubernetes distribution from AWS (EKS) with IRSA enabled
- The only resource failing is the `kubernetes_manifest`
- The cluster is already created before applying the `kubernetes_manifest`

Everywhere else (docker, local computers) is working except in the GitLab pipeline

### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.0.6
Kubernetes provider version: 2.4.1
Kubernetes version: 1.21
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
// Kubernetes provider config
provider "kubernetes" {
  host                   = data.aws_eks_cluster.target_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.target_cluster.certificate_authority.0.data)
  exec {
    api_version = "client.authentication.k8s.io/v1alpha1"
    args        = ["eks", "get-token", "--cluster-name", "${var.eks_cluster_name}"]
    command     = "aws"
  }
  experiments {
    manifest_resource = true
  }
}
```

### Steps to Reproduce
1. `terraform plan`

### Expected Behavior
Normal execution of the `plan` or `apply` commands

### Actual Behavior
What actually happened?
![image](https://user-images.githubusercontent.com/13856522/132375445-6b04b103-f599-4329-ade7-f21ca208bcb2.png)

**Comment by alexsomesan** [comment]
This sounds like a credentials issue. 
Does this provider configuration work with any of the other resources in the Kubernetes provider?

**Comment by refucktor** [comment]
@alexsomesan 
I can guarantee that is not a credential issue because the other 100+ resources are being created properly; the moment I introduce a `kubernetes_manifest` start throwing that error.

**Comment by alexsomesan** [comment]
Are you creating any other resources with the Kubernetes provider in the same CI/CD environment? Like for example "kubernetes_deployment" or "kubernetes_secret"? These are just examples, I'm interested if any other resources from the same provider are working in that environment?

**Comment by refucktor** [comment]
@alexsomesan yes, just to mention some of them:
- `kubernetes_namespace`
- `kubernetes_role`
- `kubernetes_role_binding`
- `kubernetes_config_map`
- `kubernetes_secret`

Also important to mention I'm using the helm provider with the exact same configuration (without the "experiments"), so it's definitely not a credentials issue

**Comment by alekc** [comment]
@refucktor I think it might be linked to https://github.com/hashicorp/terraform-provider-kubernetes/issues/1414 just for curiosity, if you place a .kube/config in pipelines, will it fix/change the error?

**Comment by refucktor** [comment]
@alekc unfortunately that doesn't fix it, we already tried with the explicit config file, but the error is the same

**Comment by alekc** [comment]
mm, are you using roles for your cicd (maybe mounted through the arn annotation?).  I am facing the same issue (pipelines not working, local machine does) and for now at least I am suspecting usage of the role mechanism.

**Comment by refucktor** [comment]
@alekc I think it's an obvious bug in the `kubernetes_manifest` resources, the moment I remove those resources and the experiments flag from the provider, everything is back to normal. Something is wrong with the authentication using OIDC which is a normal practice in EKS

**Comment by alekc** [comment]
@refucktor just "fixed" my bug with auth, turns out it was a permission issue.  Long explanation is in my linked issue above, and now following snippet is working for me:

```hcl
data "aws_eks_cluster" "hearth-dev" {
  name = var.k8s_cluster_name
}
data "aws_eks_cluster_auth" "cluster" {
  name = data.aws_eks_cluster.hearth-dev.name
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.hearth-dev.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.hearth-dev.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  experiments {
    manifest_resource = true
  }
}
resource "kubernetes_manifest" "test-configmap" {
  manifest = {
    "apiVersion" = "v1"
    "kind"       = "ConfigMap"
    "metadata" = {
      "name"      = "test-config"
      "namespace" = "default"
    }
    "data" = {
      "foo" = "bar"
    }
  }
}
```
