### ISSUE TITLE
With multiple clusters, Kubernetes provider dials to localhost instead of the actual cluster

### ISSUE THREAD

**Issue by DutchEllie** [hashicorp/terraform-provider-kubernetes#1425]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.3 (That's what's running in the Gitlab image)
Kubernetes provider version: 2.5.0
Kubernetes version: 1.21
```

### Affected Resource(s)

- provider kubernetes
- aws_eks_cluster
- aws_eks_cluster_auth

### Terraform Configuration Files
[not_working.zip](https://github.com/hashicorp/terraform-provider-kubernetes/files/7236866/not_working.zip)

### Steps to Reproduce
1. `terraform apply`

### Debug info
https://gist.github.com/DutchEllie/20f3875ee8ff203ef1f7af3f185f6ef2

### Error
```
│ Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.mastercluster.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/mastercluster/aws_auth.tf line 63, in resource "kubernetes_config_map" "aws_auth":
│   63: resource "kubernetes_config_map" "aws_auth" {
│ 
╵
╷
│ Error: Post "http://localhost/api/v1/namespaces/kube-system/configmaps": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with module.workercluster.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/workercluster/aws_auth.tf line 63, in resource "kubernetes_config_map" "aws_auth":
│   63: resource "kubernetes_config_map" "aws_auth" {
│ 
```

### Expected Behavior
The clusters should just be created and the config maps should be applied normally. 

### Actual Behavior
During the application of the config maps, Terraform actually dials to `localhost` instead of to the cluster endpoint. 

### Important Factoids
I am running this from Gitlab CI. The .gitlab-ci.yml file is also included in the zip file. The image it uses is also available. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Unfortunately, because of particularities in Terraform core itself, creating a cluster and operating resources on it in the same apply operation is not a supported use-case. 
You may have noticed this warning in the provider documentation addressing the issue: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources

**Comment by alexsomesan** [comment]
The preferred pattern is to split cluster creation and cluster resource operations in two (or more) different apply operations.

**Comment by DutchEllie** [comment]
As it stands, this kubernetes operation is a core part of the AWS EKS module. It is used to specifically to attach the nodes to the managed cluster itself. This is, of course, using [this module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest) This use case is working entirely as intended. My issue arises if I try to create multiple clusters.
