### ISSUE TITLE
Kubernetes provider : dial tcp 127.0.0.1:80: connect: connection refused when trying to authenticate with exported kubeconfig.

### ISSUE THREAD

**Issue by thcp** [hashicorp/terraform-provider-kubernetes#1430]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.0.7
Kubernetes Provider version: v2.5.0
Kubernetes version: 1.20.7
```
## Terraform configuration
```hcl
# TODO: Require further investigation
resource "local_file" "kubeconfig" {
 content = azurerm_kubernetes_cluster.k8.kube_config_raw
 filename = "~/.kube/test"
}

provider "kubernetes" {
  alias               = "general"
  config_path    = "~/.kube/test"
}


provider "helm" {
  alias = "general"
  kubernetes {
    config_path    = "~/.kube/test"
  }
}



locals {
  general_namespaces = [
    "namespace_1",
    "namespace_2",
    "namespace_3"
  ]
}
# Namespaces
resource "kubernetes_namespace" "general" {
  provider = kubernetes.general
  for_each = toset(local.general_namespaces)

  metadata {
    name = each.value
  }

  lifecycle {
    prevent_destroy = true
  }
}



```

## Question
Hi everyone,

Im struggling to understand why I cant use the exported kubeconfig value written on a local file to perform the authentication on my cluster  so i could proceed with resource creation ( namespaces for example). What I would expect is terraform to be able to correct authenticate on kubernetes and create the desired resources.

The actual result that im getting is:

```
╷
│ Error: Get "http://localhost/api/v1/namespaces/namespace_1": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_namespace.general["namespace_1"],
│   on aks-general-resources.tf line 9, in resource "kubernetes_namespace" "general":
│    9: resource "kubernetes_namespace" "general" {
│ 
╵
╷
│ Error: Get "http://localhost/api/v1/namespaces/namespace_2": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_namespace.general["namespace_2"],
│   on aks-general-resources.tf line 9, in resource "kubernetes_namespace" "general":
│    9: resource "kubernetes_namespace" "general" {
│ 
╵
╷
│ Error: Get "http://localhost/api/v1/namespaces/namespace_3": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_namespace.general["namespace_3"],
│   on aks-general-resources.tf line 9, in resource "kubernetes_namespace" "general":
│    9: resource "kubernetes_namespace" "general" {
│ 
╵
Releasing state lock. This may take a few moments..
```

Its important to notice that if i manually create the kubeconfig file, it works as expected.

**Comment by ak58588** [comment]
@thcp I am facing a similar error. Could you please clarify, what you mean by 'manually creating the kubeconfig file'? 
I am passing the pre-created kubeconfig file (`az aks get-credentials ...`)  as in the documentation: 
```
provider "kubernetes" { 
  config_path    = "~/.kube/config" 
  config_context = "my-context"
}
```
but still the same output

**Comment by curtbushko** [comment]
@thcp Kube contexts can be a little weird and I believe I know what is happening.

- The context created when you create a cluster using azurerm_kubernetes_cluster is different than the context that is created when you do `az aks get-credentials`.

- The azurerm_kubernetes_cluster kube config is a LOCAL context for the cluster itself and it is missing several default settings on purpose. I believe one of those settings is that it sets the host to local host (127.0.0.1). As it is set it is for internal kubernetes api usage. Your call is external.

- The `az aks get-credentails` kube config has several other things set as certs, the hostname, user name, password, access-token, etc that the other context does not have.

- I think you have access to the settings you need but have to set them in the provider. As per the Azure docs:

```
provider "kubernetes" {
  host                   = azurerm_kubernetes_cluster.main.kube_config.0.host
  username               = azurerm_kubernetes_cluster.main.kube_config.0.username
  password               = azurerm_kubernetes_cluster.main.kube_config.0.password
  client_certificate     = base64decode(azurerm_kubernetes_cluster.main.kube_config.0.client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.main.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.main.kube_config.0.cluster_ca_certificate)
}
```

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster

I hope that helps!

**Comment by curtbushko** [comment]
One more thing to add. My setup is Google Cloud specific but I am sure the same concepts apply to Azure.

- I create a Google Cloud Service account named terraform-robot that can create Google Cloud resources such as clusters, buckets, etc
- I give this service account the minimal permissions to create what it needs
- This service account creates my clusters themselves but also the Deployments, Services, etc, inside my kubernetes clusters.
- I have a wrapper script that is part of my CI system that logs into the service account before doing a terraform plan/apply. I use gitlab so the credentials are saved there as a CI variable for some security.
- All of these service accounts and permissions are created in terraform so I can change them as needed. 
- Everything that the service account does is logged and my Security Team is very happy about that. :)

I hope this helps.

**Comment by thcp** [comment]
Thanks for the feedback @curtbushko, "unfortunately" I'm on vacations and I will need to wait for picking this up again next week :(

**Comment by thcp** [comment]
solved with the latest provider
