### ISSUE TITLE
Separate ConfigMaps from 2 directories with files

### ISSUE THREAD

**Issue by menvol3** [hashicorp/terraform-provider-kubernetes#1450]
Hi,
Can someone help me with the resource "**kubernetes_config_map**"  configuration ?
I found mostly the same question that i have [https://github.com/hashicorp/terraform-provider-kubernetes/issues/1329](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1329)
But i need to do some additional configuration.

In my case I have **2** directories with files that i need to mount to pod using VolumeMounts (means every directory is a configmap, or maybe it is also possible to have 1 config map that include 2 separate directories ).
I can use answer from @jrhouston in #1329 but then i need to create 2 resources with configmap configuration, and I'd like to know how i can do the same but in one Terraform configmap resource ?
Thanks

**Comment by curtbushko** [comment]
@menvol3 Can you close this issue?
