### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by bruno-pison** [hashicorp/terraform-provider-kubernetes#1476]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.0.9
Kubernetes provider version: 2.6.1
Kubernetes version: latest
```

### Terraform Configuration Files
```hcl
https://zacharyloeber.com/blog/2020/04/02/kubernetes-app-deployments-with-terraform/ > Mostly part 2 of this, with a custom Docker image that is failing to launch
```

### Debug Output
```
│ Error: Plugin did not respond
│
│   with module.k8s.kubernetes_deployment.example,
│   on modules/k8s/k8s_deployment.tf line 34, in resource "kubernetes_deployment" "example":
│   34: resource "kubernetes_deployment" "example" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

```

### Panic Output
https://gist.github.com/bruno-pison/c5018db547d537074ea26b91e65c1a05

### Steps to Reproduce
1. `terraform apply`

**Comment by feloxx** [comment]
I have the same problem.

# Terraform Version, Provider Version and Kubernetes Version

```
Ubuntu 18.04.4 LTS
Terraform v1.0.10 on linux_amd64
provider registry.terraform.io/hashicorp/kubernetes v2.6.1
```

# Panic Output

https://gist.github.com/feloxx/924904f5531682565c1ccd92609ef667

**Comment by feloxx** [comment]
I looked at the source code.

In the `structures_container.go`, `fun expandContainerEnv` make `envs`.

This bug is triggered if an empty ENV is defined in the configuration of K8S.

Such as

```
...
...
          env {
            name = ""
          }
...
...
```

**Comment by francovp** [comment]
I can confirm that what @feloxx mentioned was my problem. I had an ENV with a empty string `""` value. When setting it some value this problem error stopped.

I had this problem using kubernetes provider `v2.6.1` and latest terraform `v1.0.10`. 
But I had another more older environment using kubernetes provider `v2.5.0` and terraform `v0.15.3` and I got the same error, so it's definitely not that new.

Thanks for the solution @feloxx!
