### ISSUE TITLE
Provider panic with CRD's and DynamicPseudoTypes after translating the rook package to terraform

### ISSUE THREAD

**Issue by josh-stableprice** [hashicorp/terraform-provider-kubernetes#1478]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.0.10
Kubernetes provider version: 2.6.1
Kubernetes version: v1.20.7-eks-d88609

```

### Affected Resource(s)
 - kubernetes_manifest

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
https://www.dropbox.com/s/wdxgij40jaf1w7m/cluster-storage.zip?dl=1

### Panic Output
https://gist.github.com/josh-stableprice/e99886f8476f43aa3298e2c529168ff9

### Steps to Reproduce
1. `terraform apply` 

### Expected Behavior
What should have happened?
I was expecting a rook cluster to be bootstrapped via CRD or to get an error explaining what i'd done wrong

### Actual Behavior
What actually happened?
panic in the provider

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by josh-stableprice** [comment]
I'd be lying if I said that I understood any of the panic message, but it seems that the provider maybe hasn't correctly handled the nullable aspect of the resources object

**Comment by josh-stableprice** [comment]
removing all references to `resources` from rook.tf allowed the manifest to complete

**Comment by alexsomesan** [comment]
Hi,

thanks for raising this. I was able to reproduce it and trace it back to the provider mechanism that enforces the OpenAPI resource schema on the user-supplied configuration. Fix is following shortly (linked PR).
