### ISSUE TITLE
kubernetes-manifest reports diff on variables of type list(object())

### ISSUE THREAD

**Issue by dmikalova** [hashicorp/terraform-provider-kubernetes#1482]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files

```hcl
# main.tf
module "main" {
  source = "./module"
  test = {
    results = [{
      name        = "test"
      description = "test"
    }]
  }
}
```

```hcl
# ./module/main.tf
variable "test" {
  type = object({
    results = list(object({
      name        = string
      description = string
    }))
    # results = any
  })
}

resource "kubernetes_manifest" "test" {
  manifest = {
    apiVersion = "tekton.dev/v1alpha1"
    kind       = "Task"
    metadata = {
      name      = "tekton-test"
      namespace = "default"
    }
    spec = {
      description = "test"
      results     = var.test.results
      steps = [{
        image     = "alpine"
        name      = "test"
        resources = {}
        script    = "echo test"
      }, ]
    }
  }
}
```

### Debug Output
```sh
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.javascript.module.main.kubernetes_manifest.task, provider
│ "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an
│ unexpected new value: .object: wrong final value type: incorrect object
│ attributes.
```

### Steps to Reproduce
- `terraform plan` and `terraform apply` the above config
- `terraform plan` again to see the diff.

### Expected Behavior
The apply should have succesfully run.

### Actual Behavior
This is a minimal repro, I have a module which accepts a var with a type of `list(object())`. When running plan and apply, the apply errors out, and a subsequent plan shows a diff for the `list(object())` value. Setting the type to `any`, or using `manifest = jsondecode(jsonencode({...}))` also resolves the diff.

Here's the more complicated [real module](https://gitlab.com/e91e63/terraform-tekton-pipelines/-/blob/b21537f528d2e8f1dbd2c1a64f1dd6e41844d18f/modules/tekton-task/main.tf) and [calling module](https://gitlab.com/e91e63/terraform-tekton-pipelines/-/blob/b21537f528d2e8f1dbd2c1a64f1dd6e41844d18f/modules/workflow-test-build-deploy/main.tf).

As a side note, sending manifests a value where `key = null` also causes a diff because kube seems to generally remove these keys completely. I'm not sure if this should be considered a bug in the provider, but if it is I can open an issue. This makes it a lot harder to use the new optional types.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi, this is indeed an issue in the provider, mainly caused by the fact tha the Tekton CRD doesn't have structural / schema information in it. In the absence of that, the provider assumes that lists are represented as tuples (as Terraform expects them). This is what's causing the type conflict.

You can work around this by making the `results` attribute be a tuple, like this
```
variable "test" {
  type = object({
    results = tuple(object({
```

**Comment by dmikalova** [comment]
Thanks for the explanation! I rewrote my configs to use tuple([list()]) and then flattened the tuples and it now works. I know tekton is working on getting a schema, so I'm fine with closing this issue unless there are plans to resolve this on the provider side and you want this for tracking.

**Comment by jbg** [comment]
Is there any way this error message could be more descriptive? `unexpected new value: .object: wrong final value type: incorrect object attributes` doesn't really help to find the problematic attribute, especially when the manifest is large.
