### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by esn89** [hashicorp/terraform-provider-kubernetes#1488]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.13.5
Kubernetes provider version: Not sure
Kubernetes version: Not sure
```

I have this set in my `providers.tf`:

```
terraform {
 required_providers {
   kubernetes = {
     version = ">= 1.13.2, <2.0"
   }
 }
}
```

### Affected Resource(s)
Affects all as the init/plan stage fails

### Debug Output
https://gist.github.com/esn89/4bd70ab153e0f3cb72cc77d6ff20cbf2

### Steps to Reproduce

1. `terragrunt apply` -->

### Expected Behavior
The plan should have happened

### Actual Behavior
I got the error that was described in the gist.

### Important Factoids
I'm using Terragrunt v0.25.5.  Nothing has changed in my `providers.tf` so I am not sure what is going on.

**Comment by alexsomesan** [comment]
Hi,

I was able to successfully init the provider using the constraints you specified. Here's what I got.
```
~/issue-1488 » terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/kubernetes versions matching ">= 1.13.2, < 2.0.*"...
- Installing hashicorp/kubernetes v1.13.4...
- Installed hashicorp/kubernetes v1.13.4 (self-signed, key ID 34365D9472D7468F)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/plugins/signing.html

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

~/issue-1488 » terraform version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4

Your version of Terraform is out of date! The latest version
is 1.0.11. You can update by downloading from https://www.terraform.io/downloads.html
```

I think we need a debug log to look further into this issue. Would you mind running the command again with the environment variable `TF_LOG=trace` enabled? Please share the output of that here.
