### ISSUE TITLE
ignore null values in manifests

### ISSUE THREAD

**Issue by dmikalova** [hashicorp/terraform-provider-kubernetes#1501]
### Terraform Version, Provider Version and Kubernetes Version

```
terraform version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2"
    }
  }
  required_version = "~> 1"
}

locals {
  do_pat_name = "digitalocean-personal-access-token"
}

resource "kubernetes_secret" "digitalocean_pat" {
  metadata {
    annotations = {}
    labels      = {}
    name        = local.do_pat_name
  }

  data = {
    (local.do_pat_name) = var.cert_issuer_conf.digitalocean_personal_access_token
  }
}

resource "kubernetes_manifest" "cert_manager_cluster_issuer_digitalocean" {
  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "ClusterIssuer"
    metadata = {
      name = "digitalocean"
    }
    spec = {
      acme = {
        email  = var.cert_issuer_conf.email
        server = "https://acme-v02.api.letsencrypt.org/directory"
        privateKeySecretRef = {
          name = "acme-account-key"
        }
        solvers = [
          {
            http01 = null
            dns01 = {
              digitalocean = {
                tokenSecretRef = {
                  key  = local.do_pat_name
                  name = local.do_pat_name
                }
              }
            }
          }
        ]
      }
    }
  }
}

```

### Debug Output
```
│ Error: Failed to morph manifest to OAPI type
│ 
│   with kubernetes_manifest.cert_manager_cluster_issuer_digitalocean,
│   on main.tf line 27, in resource "kubernetes_manifest" "cert_manager_cluster_issuer_digitalocean":
│   27: resource "kubernetes_manifest" "cert_manager_cluster_issuer_digitalocean" {
│ 
│ AttributeName("spec"): [AttributeName("spec")] failed to morph object
│ element into object element: AttributeName("spec").AttributeName("acme"):
│ [AttributeName("spec").AttributeName("acme")] failed to morph object
│ element into object element:
│ AttributeName("spec").AttributeName("acme").AttributeName("solvers"):
│ [AttributeName("spec").AttributeName("acme").AttributeName("solvers")]
│ failed to morph object element into object element:
│ AttributeName("spec").AttributeName("acme").AttributeName("solvers").ElementKeyInt(0):
│ [AttributeName("spec").AttributeName("acme").AttributeName("solvers").ElementKeyInt(0)]
│ failed to morph tuple element into list element:
│ AttributeName("spec").AttributeName("acme").AttributeName("solvers").ElementKeyInt(0).AttributeName("https01"):
│ [AttributeName("spec").AttributeName("acme").AttributeName("solvers").ElementKeyInt(0).AttributeName("https01")]
│ failed to morph object element into object element:
│ AttributeName("spec").AttributeName("acme").AttributeName("solvers").ElementKeyInt(0).AttributeName("https01"):
│ type is nil
╵
ERRO[0006] 1 error occurred:
        * exit status 1
```

### Panic Output
This is the panic that results if you also set `dns01 = null` - although I would not expect that to be valid, I would not expect a panic.
https://gist.github.com/dmikalova/3b61429361658bd62b2a7b9fe856942c

### Steps to Reproduce

1. `terraform apply` the above config

### Expected Behavior

When `http01 = null` I would expect that value to be ignored. This is especially useful with the new `optional()` type and `defaults()` function that's being experimented with, which can leave values as null in deeply nested objects.

### Actual Behavior
Terraform either errors out, or if completely invalids fields are passed like both `http01 = null` and `dns01 = null` then terraform panics.

### References
[Here's the docs on cert-issuer](https://cert-manager.io/docs/configuration/acme/http01/)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by iBrandyJackson** [comment]
hi @dmikalova thank you for bring this to our attention - we have a PR on the horizon that we suspect will solve this issue: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1499

Closing this issue, if you continue to run into this problem after #1499 has been merged/released - please feel free to reopen. Thanks!
