### ISSUE TITLE
Provider crashes when processing kubernetes_manifest for apps/v1 Deployment

### ISSUE THREAD

**Issue by tareks** [hashicorp/terraform-provider-kubernetes#1505]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
```
Also tested on:

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1`
```

### Affected Resource(s)
- `kubernetes_manifest`

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 1.0.0"

  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "kubernetes_manifest" "app_deployment" {
  manifest = {
    "apiVersion" = "apps/v1"
    "kind"       = "Deployment"
    "metadata" = {
      "name"      = "test"
      "namespace" = "default"
      "labels" = {
        "app" = "test"
      }
    }

    "spec" = {
      "replicas" = 1
      "selector" = {
        "matchLabels" = {
          "app" = "test"
        }
      }
      "template" = {
        "metadata" = {
          "labels" = {
            "app" = "test"
          }
        }
        "spec" = {
          "containers" = [
            {
              "name"  = "oauth2-proxy"
              "image" = "quay.io/oauth2-proxy/oauth2-proxy:latest"

            #   "readinessProbe" = {
            #     "httpGet" = {
            #       "path" = "/ping"
            #       "port" = 8080
            #     }

            #     "initialDelaySeconds" = "10"
            #     "periodSeconds"       = "10"
            #   }
            },
            {
              "name"  = "oauth2-proxy2"
              "image" = "quay.io/oauth2-proxy/oauth2-proxy:latest"

              #   "readinessProbe" = {
              #     "httpGet" = {
              #       "path" = "/ping"
              #       "port" = "8080"
              #     }

              #     "initialDelaySeconds" = "10"
              #     "periodSeconds"       = "10"
              #   }
            },
          ]
        }
      }
    }
  }
}
```

### Debug Output
See gist:
https://gist.github.com/tareks/079d4a8537a6629f515fa48a586a369c

### Panic Output
Provider stacktrace above.

### Steps to Reproduce
1. `terraform apply` 

### Expected Behavior
Provider should render plan output as expected.

### Actual Behavior
Provider crashes before apply prompt is presented.

### Important Factoids
This is probably not common due to the fact that this is trying to implement a `deployment` which has a separate resource, however, in this particular case, we are trying to use a field that is currently not supported by the `kubernetes_deployment` resource (specifically `secCompProfile`).

It appears that when a `livenessProbe` or `readinessProbe` are specified for a deployment with more than a single container, this results in a panic. It appears that the `port` field is the one causing the immediate crash. if the containers list only has a single container, there are no issues with the `readinessProbe` or `livenessProbe` sections being evaluated correctly (ie. no panic occurs).  Additionally, if both probe sections are removed, the plan output renders without issues.

It appears that specifying more than 1 container in conjunction with a probe section in one or the other results in this case. Can be mitigated by not specifying the probe sections in either container. Port can either be quoted or unquoted resulting in the same panic.

Note that whether the port number is removed or commented out, the panic will not occur but will render an invalid deployment error because the spec is missing a port number.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @tareks thanks for opening this. From looking at tftype error in the panic message, it looks as though one of the values for the `port` field in your readinessProbe is being turned into a DynamicPsuedoType. This can happen when you mix types in a list that can contain an int or a string. I was able to reproduce this and avoid the crash by specifying both port fields as an integer like this:

```terraform
resource "kubernetes_manifest" "deployment_nginx_deployment" {
  manifest = {
    "apiVersion" = "apps/v1"
    "kind"       = "Deployment"
    "metadata" = {
      "labels" = {
        "app" = "nginx"
      }
      "name" = "nginx-deployment"
      "namespace" = "default"
    }
    "spec" = {
      "replicas" = 3
      "selector" = {
        "matchLabels" = {
          "app" = "nginx"
        }
      }
      "template" = {
        "metadata" = {
          "labels" = {
            "app" = "nginx"
          }
        }
        "spec" = {
          "containers" = [
            {
              "image" = "nginx:1.14.2"
              "name"  = "nginx"
              "ports" = [
                {
                  "containerPort" = 80
                },
              ]
              "readinessProbe" = {
                "httpGet" = {
                  "path" = "/"
                  "port" = 80
                }
                "initialDelaySeconds" = "10"
                "periodSeconds"       = "10"
              }
            },
            {
              "env" = [
                {
                  "name"  = "NGINX_PORT"
                  "value" = "81"
                },
              ]
              "image" = "nginx:1.14.2"
              "name"  = "nginx2"
              "ports" = [
                {
                  "containerPort" = 81
                },
              ]
              "readinessProbe" = {
                "httpGet" = {
                  "path" = "/"
                  "port" = 81
                }
                "initialDelaySeconds" = "10"
                "periodSeconds"       = "10"
              }
            },
          ]
        }
      }
    }
  }
  ```
  
 This is a known issue that we are working on a fix for, and is the root cause of a number of other open issues.

**Comment by tareks** [comment]
Thanks @jrhouston ! That solved the panic for me. Good to know there's a workaround.

I'll go ahead and close this issue then if it's already being tracked elsewhere.

Cheers.
