### ISSUE TITLE
kubernetes_ingress_class Error: Unsupported argument An argument named "namespace" is not expected here

### ISSUE THREAD

**Issue by fyaretskiy** [hashicorp/terraform-provider-kubernetes#1516]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.0.7
Kubernetes provider version: v2.6.1
Kubernetes version: 1.21
```

### Affected Resource(s)
- kubernetes_ingress_class

> │ Error: Unsupported argument
│
│   on ../k8s/nginx-controller.tf line 601, in resource "kubernetes_ingress_class" "test":
│  601:     namespace = "test"
│
│ An argument named "namespace" is not expected here.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by TheBeege** [comment]
I think this is expected behavior. I did some reading. IngressClass resources don't belong to a namespace.

**Comment by fyaretskiy** [comment]
Seems you are correct, some documentation i was following had confused me.
