### ISSUE TITLE
Recreate `kubernetes_manifest` resource when `manifest.metadata.name` changed

### ISSUE THREAD

**Issue by Vlad1mir-D** [hashicorp/terraform-provider-kubernetes#1518]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.3
Kubernetes provider version: 2.6.1
Kubernetes version: v1.20.10-gke.1600
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
terraform {
  experiments = [module_variable_optional_attrs]
}

variable "kubernetes_manifests" {
  description = "A list of Kubernetes manifests."
  type = list(object({
     manifest        = string
     field_manager = optional(object({
      name            = string
      force_conflicts = bool
    }))
  }))
}

resource "kubernetes_manifest" "this" {
  for_each = { for key, value in var.kubernetes_manifests : key => value }

  manifest        = yamldecode(each.value.manifest)

  dynamic "field_manager" {
    for_each = each.value.field_manager != null ? [each.value.field_manager] : []
    content {
      name            = field_manager.value.name
      force_conflicts = field_manager.value.force_conflicts
    }
  }
}

```

### Debug Output

https://gist.github.com/Vlad1mir-D/c39b0031cc6cbad7492e2916554bf646

### Steps to Reproduce

1. Alter `manifest.metadata.name` for `kubernetes_manifest` resource
2. `terraform apply`

### Expected Behavior
```hcl
Terraform will perform the following actions:

  # kubernetes_manifest.this["0"] must be replaced
-/+ resource "kubernetes_manifest" "this" {
      ~ manifest = {
          ~ metadata   = {
              ~ name      = "redis-infra-prod-monitoring-node-redis-sentry-4" -> "redis-infra-prod-monitoring-node-redis-sentry-5" # forces replacement
```

### Actual Behavior
```hcl
Terraform will perform the following actions:

  # kubernetes_manifest.this["0"] will be updated in-place
  ~ resource "kubernetes_manifest" "this" {
      ~ manifest = {
          ~ metadata   = {
              ~ name      = "redis-infra-prod-monitoring-node-redis-sentry-4" -> "redis-infra-prod-monitoring-node-redis-sentry-5"
```
which leads to the creation of an additional resource with the new name and complete removal of an original resource from the Terraform state but not K8s (it will be completely ignored after `terraform apply` as it never exists).

### References

- https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/262

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BojanZelic** [comment]
Seeing the same behavior if metadata.namespace changes aswell. Which makes sense as it's also an unmutable resource.

**Comment by jbg** [comment]
A generic way to force recreation when certain attributes are changed (with immutable attributes in `metadata` included by default) would be useful. Custom resources often have immutable attributes too, and currently if you want to change them you have to taint the resource to get the provider to recreate it.
