### ISSUE TITLE
A kubernetes_secret resource will always change if binary_data contains newline characters

### ISSUE THREAD

**Issue by primeos-work** [hashicorp/terraform-provider-kubernetes#1520]
### Description

We read a large secret from Vault and the raw data is a Base64 encoded string with newline characters. E.g. the `base64` binary from the GNU coreutils inserts them by default `-w, --wrap=COLS: wrap encoded lines after COLS character (default 76).  Use 0 to disable line wrapping`. K8s will then remove these newlines / normalize the Base64 string when storing the secret. Because this provider doesn't normalize the data it will always detect a change when applying the (unchanged) configuration. This isn't a big deal and can easily be worked around but it might cause unexpected issues for users and can require a bit of time to figure out.

Proposed solution: Normalize the Base64 encoded string (ideally there would already be a Go function for it) or ignore newline characters (I'm not quite sure if that's already sufficient but it should definitely cover most cases).

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.0.11
Kubernetes provider version: v2.6.1
Kubernetes version: v1.21.5
```

### Affected Resource(s)

- kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "test" {
  metadata {
    name      = "test"
    namespace = "test"
  }
  binary_data = {
    # echo "bar" | base64 -w 3
    "foo" = "YmF\nyCg\n=="
    # Our fix/workaround:
    # "data" = replace(data.vault_generic_secret.ca.data.cacerts-base64, "\n", "")
  }
}
```

### Steps to Reproduce
0. `kubectl create namespace test`
1. `terraform apply`
2. `terraform apply` (or plan)

### Expected Behavior
What should have happened?

On the second apply:
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Actual Behavior
What actually happened?

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.test.kubernetes_secret.test will be updated in-place
  ~ resource "kubernetes_secret" "test" {
      ~ binary_data = (sensitive value)
        id          = "test/test"
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mmshin** [comment]
I also encountered the same issue.  since I started using data kms_secret to encrypt our keys and credentials. Tried your fix/workaround int he meantime and it also works for us.
