### ISSUE TITLE
kubernetes_manifest.config_maps "produced an unexpected new value" on v2.7.0 of provider

### ISSUE THREAD

**Issue by mattduguid** [hashicorp/terraform-provider-kubernetes#1521]
```
Terraform version: 1.0.4
Kubernetes provider version: 2.7.0 (broken) & 2.6.1 (rolled back to for workaround)
Kubernetes version: 1.20.9
```

### Affected Resource(s)
- kubernetes_manifest.config_maps 

### Terraform Config
```hcl
application_1_k8s_configmaps = [
  {
    name = "dt00helloworld" 
    data = {
      "key1" = "value1"
      "key2" = "value2"
      "key3" = "value3"
      "key4" = "value4"
      "key5" = "value5"
    }
  }
]
```

### Terraform HCL
```hcl
resource "kubernetes_manifest" "config_maps" {
  for_each = { for record in var.application_1_k8s_configmaps : record.name => record }
  manifest = {
    "apiVersion" = "v1"
    "kind" = "ConfigMap"
    "metadata" = {
      "name" = "${each.key}"
      "namespace" = "${var.application_1_name}" 
    }
    "data" = tomap(each.value.data) 
  }
}
```

### Terraform Plan Output
```hcl
# module.k8s-deployment-helloworld.kubernetes_manifest.config_maps["dt00helloworld"] will be updated in-place
  ~ resource "kubernetes_manifest" "config_maps" {
      ~ object   = {
          ~ data       = {
              - "key1" = "value1" -> null
              - "key2" = "value2" -> null
              - "key3" = "value3" -> null
              - "key4" = "value4" -> null
              - "key5" = "value5" -> null
            }
            # (5 unchanged elements hidden)
        }
        # (1 unchanged attribute hidden)
    }
```

### Error
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.k8s-deployment-helloworld.kubernetes_manifest.config_maps["dt00helloworld"],
│ provider
│ "module.k8s-deployment-helloworld.provider[\"registry.terraform.io/hashicorp/kubernetes\"]"
│ produced an unexpected new value: .object.data: was
│ cty.MapValEmpty(cty.String), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
Config maps created as normally did prior to the change in provide version

### Actual Behavior
They didn't create and we received the above error

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MarvinCai** [comment]
I'm getting similar error `Produced an unexpected new value: .object.stringData` with version 2.7.0 of provider.

**Comment by alexsomesan** [comment]
Where these resources created before 2.7.0 and then updated ?

**Comment by MarvinCai** [comment]
actually I tried both 2.7.0 and 2.6.1, getting the same error
it's a create action , a configmap with stringdata like this:

```
resource "kubernetes_manifest" "conf" {
  manifest = {
    "apiVersion" = "v1"
    "kind" = "Secret"
    "metadata" = {
      "name" = "prometheus-conf"
      "namespace" = "prometheus"
    }
    "stringData" = {
      "scrape.yaml" = <<-EOT
      - job_name: kubernetes-cadvisor
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - target_label: __address__
            replacement: kubernetes.default.svc.cluster.local:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            replacement: /api/v1/nodes/$${1}/proxy/metrics/cadvisor
            target_label: __metrics_path__
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
      EOT
    }
    "type" = "Opaque"
  }
}
```

**Comment by mattduguid** [comment]
> Where these resources created before 2.7.0 and then updated ?

In our case no changes to config or HCL, just a run of pipeline using 2.6.1 (works) then under 2.7.0 (error).

For time being we have hard set back to 2.6.1 and the issue resolves.

**Comment by alexsomesan** [comment]
@MarvinCai Your issue is different than the what is reported here. In your case, it has to do with the fact that `stringData` is a "write-only" attribute as defined by Kubernetes docs: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#secret-v1-core

Because of that, the API never returns the value set for stringData which causes terraform to raise that error. You can work around it easily by setting `stringData` as a computed field, like this:
```
resource "kubernetes_manifest" "conf" {
  computed_fields = ["stringData"]
  manifest = {
...
```

**Comment by mattduguid** [comment]
@alexsomesan updated the issue with the config

**Comment by alexsomesan** [comment]
@mattduguid Thanks for sharing the variable contents.

Could you please also share the output from the `plan` command which shows the "config_maps" resource?

**Comment by mattduguid** [comment]
@alexsomesan  updated the issue with plan output

**Comment by alexsomesan** [comment]
I can confirm this is indeed an issue. 
A dormant bug was exposed by collateral changes as part of v2.7.0

**Comment by alexsomesan** [comment]
PR #1525 should fix this.

**Comment by alexsomesan** [comment]
Release 2.7.1 went out with the fix for this issue. Hopefully that resolved the issue for everyone here.
If anyone still encounters difficulties, please open a specific new issue.
