### ISSUE TITLE
ELBs aren't managed by TF - fail to delete when calling tf destroy

### ISSUE THREAD

**Issue by dyasny** [hashicorp/terraform-provider-kubernetes#1534]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: Terraform v1.0.11
Kubernetes provider version: 
Kubernetes version: 1.21
```

### Affected Resource(s)

elb

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

Using the EKS example code, nothing added or changed (beside names). 

### Steps to Reproduce

1. terraform destroy
2. 

### Expected Behavior
What should have happened?

Entire setup go down

### Actual Behavior
What actually happened?

Timeout destroying. 

```
│ Error: error deleting subnet (subnet-0dd6c71e71d162573): timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 20m0s)
│ 
│ 
╵
╷
│ Error: error deleting subnet (subnet-04fdb38e19819489b): timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 20m0s)
│ 
│ 
╵
╷
│ Error: Error waiting for internet gateway (igw-00c73ffe0b73264a0) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)
```

Had to manually go in and delete the provisioned ELBs, which allowed for interfaces to be detached the the rest of the destroy flow to continue. 

Reproduced several times with different clusters. 

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @dyasny,

Could you please share the terraform code that you have an issue with? That will help us to reproduce the issue.

Thank you.

**Comment by dyasny** [comment]
On second thought, this might have been this example that I was using: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster

Not sure there's any difference really

**Comment by arybolovlev** [comment]
Thanks, @dyasny. Please correct me if I am wrong, but this sounds more like an issue for the AWS provider, not the Kubernetes one. I was testing today resource `kubernetes_service_v1` to create a load balancer and it works with no issues.
