### ISSUE TITLE
data.kubernetes_service attributes are null

### ISSUE THREAD

**Issue by shaunc** [hashicorp/terraform-provider-kubernetes#1535]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.11
Kubernetes provider version: 2.7
Kubernetes version: 1.21
```

### Affected Resource(s)

kubernetes_service

### Terraform Configuration Files
```hcl
data "kubernetes_service" "ingress_lb_dns" {
  metadata {
    name      = "nginx-ingress-controller"
    namespace = "ingress-nginx"
  }
}
```

### Debug Output

https://gist.github.com/shaunc/554a891a50d5b20152302d360155502c

### Steps to Reproduce
`terraform apply`

### Expected Behavior
What should have happened?

Output of kubectl:
```
$ kubectl -n ingress-nginx get service nginx-ingress-controller
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP                                                              PORT(S)                                                   AGE
nginx-ingress-controller   LoadBalancer   <SNIP>   <SNIP>.us-east-1.elb.amazonaws.com   80:30769/TCP,443:32718/TCP,11737:32026/TCP,22:31057/TCP   534d
```
### Actual Behavior
What actually happened?

All attributes of the service were null. Debug log shows service wasn't found.

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @shaunc,

Do you still have this issue? If so, could you please execute `kubectl` again and add `--v=9` at the end to get more details about the request. Could you please compare that request with the one that TF does? This is more about the target host.

Thank you!

**Comment by arybolovlev** [comment]
Hi @shaunc,

Unfortunately, there is not enough information to analyze this issue and we haven't heard from you for a while. I will go ahead and close this issue. Please feel free to re-open it if the issue is still active.

Thank you.

**Comment by treysidechain** [comment]
I just ran into this issue as well.
#### Terraform Configuration Files ####
```
data "kubernetes_service_v1" "ingress_nginx_controller_opal_server_github_webhooks" {
  metadata {
    name      = local.opal_server_github_webhooks_ingress_controller_name
    namespace = var.namespace
  }
}
```
then later I try to reference this data source using
```
data.kubernetes_service_v1.ingress_nginx_controller_opal_server_github_webhooks.spec.0.port
```
which returns
```
Error: Attempt to get attribute from null value
data.kubernetes_service_v1.ingress_nginx_controller_opal_server_github_webhooks.spec is null
```

This is my first time encountering this issue since previously I had instead imported the `kuberntes_service_v1` resource which then was able to reference the `spec` field with no problems
