### ISSUE TITLE
kubernetes_service with wait_for_load_balancer active blocks/waits forever to complete

### ISSUE THREAD

**Issue by EugenMayer** [hashicorp/terraform-provider-kubernetes#1536]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: Terraform v1.0.11
Kubernetes provider version: v1.22.4+rke2r1
Kubernetes version: 1.22.4
```

### Affected Resource(s)
kubernetes_service

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  config_path = "/...."
}
```

### Steps to Reproduce
1. have a `kubernetes_service` with `wait_for_load_balancer=true`
2. tf apply

### Expected Behavior
Should complete, since the service is active and has endpoints

### Actual Behavior
Waits forever for the service to complete, even though kubernetes already shows the services as active (with endpoints)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @EugenMayer,

I tried to reproduce this issue, but I couldn't. I was using an [example](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/service#example-using-aws-load-balancer) from our documentation.

Could you please share your terraform code you have an issue with if it still persist?

Thank you.

**Comment by EugenMayer** [comment]
Hello @arybolovlev thank you for following up. It's about 8 month later and i usually do not keep broken code as long as this. This said, i can no longer provide more insight then this issue already stated, since i simply forgot the details a half year later :)

**Comment by arybolovlev** [comment]
Thank you! I ran some tests on EKS and GKE clusters yesterday and it seems everything works well. Please raise a new issue if you face any other problems with this provider.

Have a great rest of the week!
