### ISSUE TITLE
Removing `spec.template.spec.container.resources` on `kubernetes_deployment` doesn't update anything

### ISSUE THREAD

**Issue by shuttleriiiz** [hashicorp/terraform-provider-kubernetes#1568]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.11
Kubernetes provider version: 2.7.1
```

### Affected Resource(s)

- `kubernetes_deployment`

### Steps to Reproduce

1. create `kubernetes_deployment` resources and specified the `spec.template.spec.container.resources.request.cpu`
2. `terraform apply`
3. remove `spec.template.spec.container.resources` blocks from terraform config
4. `terraform plan`
5. No change detected

### Expected Behavior
When `spec.template.spec.container.resources` block is removed from terraform, it should be able to detect the changes and update the actual deployment resource on 

### Actual Behavior
When `spec.template.spec.container.resources` blocks are removed from terraform config, running `terraform plan` will not detect any changes.

### References

- GH-754

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ppawlowski** [comment]
Actually I think this problem applies to all items defined in _PodSpec_ . 
I have tested on my end and I cannot remove _ imagePullSecrets_ defined at the beginning of my kubernetes deployment lifecycle.

**Comment by n1ngu** [comment]
Same with 
- terraform v1.6.6
- registry.terraform.io/hashicorp/kubernetes v2.25.2
- manifest_resource experiment on

Any change in the `spec` block goes undetected. Changing the `metadata` block `name` attribute triggers change detection for the `spec` block.

**Comment by n1ngu** [comment]
A workaround is to taint the terraform resources that need to change. Nonetheless this may be an unnecessarily disruptive approach. Plus, this is useless for drift detection.

My wish is this provider had never been introduced in my organization. I'll definitely plan to get rid of it.

**Comment by NelsonIg** [comment]
This actually a pretty big issue which makes the use of this provider questionable.
