### ISSUE TITLE
rule must be a list (rules)

### ISSUE THREAD

**Issue by mdevendr** [hashicorp/terraform-provider-kubernetes#1570]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 2.71
Kubernetes provider version: 1.19
Kubernetes version: 1.19
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
resource "kubernetes_cluster_role" "example" {
  metadata {
    name = "terraform-example"
  }

  rule {
    api_groups = [""]
    resources  = ["namespaces", "pods"]
    verbs      = ["get", "list", "watch"]
  }
}
### Expected Behavior
What should have happened?
resource "kubernetes_cluster_role" "example" {
  metadata {
    name = "terraform-example"
  }

  rules [ {
    api_groups = [""]
    resources  = ["namespaces", "pods"]
    verbs      = ["get", "list", "watch"]
  } ]
}
### Actual Behavior
What actually happened?
kubernetes creates cluster role with more then one rule but terraform construct does not allow this.

### References

- GH-1234
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/cluster_role
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hello!

The way to express multiple rule elements is to just repeat the `rule` block, like this: 
```
resource "kubernetes_cluster_role" "example" {
  metadata {
    name = "terraform-example"
  }

  rule {
    api_groups = [""]
    resources  = ["namespaces", "pods"]
    verbs      = ["get", "list", "watch"]
  }

  rule {
    api_groups = ["extensions/v1beta1"]
    resources  = ["ingress"]
    verbs      = ["get", "list", "watch"]
  }
}
```

The reason for this is historical decisions in the provider SDK.

**Comment by ZErdody** [comment]
Hello there,

I am interested in taking this issue.
