### ISSUE TITLE
"Provider produced inconsistent result after apply" with Fluxv2 installation attempt

### ISSUE THREAD

**Issue by queueburt** [hashicorp/terraform-provider-kubernetes#1572]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.1.3
Kubernetes provider version: 2.7.1
Kubernetes version: Client: v1.21.2  KubeAPI: v1.21.5-eks-bc4871b
```

### Affected Resource(s)

[kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest)

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    kubernetes = {
      version = "~> 2.7.1"
    }
}

resource "kubernetes_manifest" "test-error" {
  manifest = yamldecode(replace(file("kustomize-controller.yaml"), "/status:.*\\s +acceptedNames:.*\\s(.*\\s)*\\[\\]/", ""))
}
```
Gist for referenced YAML above: [kustomize-controller.yaml](https://gist.github.com/queueburt/99daaa5ab1c2ab67f1df4d25e6130bed)

### Debug Output

https://gist.github.com/queueburt/88cb871ef83361d82de0189b238eb964

### Steps to Reproduce

1. `kubectl create namespace flux-system`
2. `terraform apply`

### Expected Behavior
Terraform successfully creates a deployment with a '1000m' CPU limit.

### Actual Behavior
Terraform creates a deployment with a '1' CPU limit and no other obvious conflicts.  It returns the error in the above gist.

### Important Factoids

This is part of a more complicated set of Terraform and Kubernetes manifests generated by [Fluxv2's Terraform provider](https://github.com/fluxcd/terraform-provider-flux) for cluster bootstrapping.  In its initial design, it expects users to leverage the kubectl_manifest resource from [gavinbunney's kubectl provider](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest).  For a variety of reasons, we'd prefer to use a more flexible provider and not rely on kubeconfig mutations for cluster access, something that we had easily achieved using fluxv1 and the Helm provider which is unfortunately not an option for fluxv2.  The Flux installation provider generates (28) individual manifests including CRDs (the regex in the above code example should NOT impact the example manifest; it was hacked together quickly to strip [top-level 'status' keys](https://github.com/fluxcd/notification-controller/blob/d49181a7c46b25e9095b98e4e5be1343118b0427/config/crd/bases/notification.toolkit.fluxcd.io_alerts.yaml#L204) from CRDs, but I left it in the function for the sake of accuracy).  In our attempts to write a prototype using kubernetes_manifest, we stumbled onto this issue that impacts (4) different manifests, all of which have a similar format to the one linked in the kustomize-controller gist.  If all 4 are necessary for troubleshooting, I'm happy to provide them.

### References

- https://github.com/fluxcd/terraform-provider-flux/issues/208 for a bit of extra context.  It's orthogonal but related to the effort of enabling 'kubernetes_manifest' as an installation option for the flux Terraform provider.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
It looks like the value of `.object.spec.template.spec.containers[0].resources.limits["cpu"]` is changed by the API server during apply. This is something Terraform strives to protect against and thus throws the error you mentioned.
To work around this behaviour, define the offending resource field as "computed", like this:

```
resource "kubernetes_manifest" "test-error" {
  computed_fields = ["spec.template.spec.containers"]
  manifest = yamldecode(replace(file("kustomize-controller.yaml"), "/status:.*\\s +acceptedNames:.*\\s(.*\\s)*\\[\\]/", ""))
}
```

More info here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#computed-fields
