### ISSUE TITLE
Kubernetes provider for GKE fails to destroy namespaces, which were created successfully with Terraform

### ISSUE THREAD

**Issue by Przemek2907** [hashicorp/terraform-provider-kubernetes#1579]
Hi,

I think the issue: https://github.com/hashicorp/terraform-provider-kubernetes/issues/821 should be reopened. For the whole day I have been creating a GKE cluster and then I wanted to create namespaces in the cluster. Creating is fine, but when I try to destroy it afterwards, I get:
│ Error: Get "http://localhost/api/v1/namespaces/ingress": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_namespace.ingress,
│   on kubernetes_resources.tf line 67, in resource "kubernetes_namespace" "ingress":
│   67: resource "kubernetes_namespace" "ingress" {

I have split my Terraform config into 2 modules, one creates the GKE cluster and VPC resources, another one deploys resources to the GKE cluster itself, after authentication:

### My providers: 
```
Terraform v1.1.4
    google = {
      source  = "hashicorp/google"
      version = "3.52.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0.1"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.7.0"
    }
```

### Affected Resource(s)
```
resource "kubernetes_namespace" "ingress" {
 metadata {
  name = "ingress"
 }
}
resource "helm_release" "ingress" {
 name       = "ingress"
 namespace = kubernetes_namespace.ingress.metadata[0].name

 repository = "https://kubernetes.github.io/ingress-nginx"
 chart      = "ingress-nginx"

 set {
  name  = "controller.service.loadBalancerIP"
  value = module.gke_cluster.static_ip_address
 }

 depends_on = [module.gke_cluster.kubernetes_cluster_host]
}
```

### Terraform Configuration Files
```hcl
######################################################
# KUBERNETES AND HELM PROVIDER
######################################################

provider "kubernetes" {
 host  = "https://${module.gke_cluster.kubernetes_cluster_host}"
 token = module.gke_cluster.cluster_short_living_token
 cluster_ca_certificate = module.gke_cluster.kubernetes_ca_certificate
}

provider "helm" {
 kubernetes {
  host  = "https://${module.gke_cluster.kubernetes_cluster_host}"
  token = module.gke_cluster.cluster_short_living_token
  cluster_ca_certificate = module.gke_cluster.kubernetes_ca_certificate
 }
}

provider "kubectl" {
 apply_retry_count      = 10
 host  = "https://${module.gke_cluster.kubernetes_cluster_host}"
 token = module.gke_cluster.cluster_short_living_token
 cluster_ca_certificate = module.gke_cluster.kubernetes_ca_certificate
 load_config_file       = false
}
```

### Steps to Reproduce
1. `terraform apply var-file=my_vars.tfvars`
2. ` terraform apply -destroy var-file=my_vars.tfvars`

### Expected Behavior
Terraform should destroy all the resources created a while ago

### Actual Behavior
I got an Error: Get "http://localhost/api/v1/namespaces/ingress": dial tcp 127.0.0.1:80: connect: connection refused
I am forced to remove resources manually and remove tfstate files
**This happends all the time, the issue is not intermittent**

### Important Factoids
I am running Terraform commands from my local machine, tfstate files are kept local

### References
- GH-821

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi! 
I suspect the problem here is that there is no direct dependency in Terraform between the module that supplies the values for the provider 'kubernetes" block and the actual kubernetes resources managed by the kubernetes provider. Because Terraform cannot establish this dependency, they get scheduled for destroy in the wrong order and the cluster resources seems to get destroyed before the namespace one gets it's turn.

You might be able to work around this by setting explicit `depends_on` statements on the kubernetes resources, pointing back to the cluster module. 

The safest way to make sure this doesn't happen is to split the resources into two different batches of operations. First run one destroy for all the Kubernetes resources, then a second destroy for the cluster itself.
