### ISSUE TITLE
Unable to apply kubernetes_manifest - provider produced an unexpected new value

### ISSUE THREAD

**Issue by nivimorbgp** [hashicorp/terraform-provider-kubernetes#1587]
### Terraform Version, Provider Version and Kubernetes Version
```
- Terraform version: 1.12
- Kubernetes version: 1.20
- Kubernetes provider version: 2.7.1
- Cloud-provider/provisioner: EKS
- cert-manager version: 1.7.0
- Install method: static manifests

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "certificate" {
  depends_on = [kubernetes_manifest.selfsigned_cluster_issuer]
  for_each = {
    for certificate in local.certificates :
    "${certificate.cert_name}-${certificate.namespace}" => certificate
    if var.certificates_config[certificate.cert_name].enabled == true
  }
  manifest = {
    "apiVersion" = "cert-manager.io/v1"
    "kind"       = "Certificate"
    "metadata" = {
      "name"      = each.value.cert_name
      "namespace" = each.value.namespace
    }
    "spec" = {
      "dnsNames" = [
        "example.com",
      ]
      "duration" = "2160h"
      "isCA"     = false
      "issuerRef" = {
        "group" = "cert-manager.io"
        "kind"  = "ClusterIssuer"
        "name"  = "selfsigned-cluster-issuer"
      }
      "privateKey" = {
        "algorithm" = "RSA"
        "encoding"  = "PKCS1"
        "size"      = 2048
      }
      "renewBefore" = "360h"
      "secretName"  = each.value.cert_name
      "subject" = {
        "organizations" = [
          "myorg",
        ]
      }
      "usages" = [
        "server auth",
        "client auth",
      ]
    }
  }
}
```

### Debug Output
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.eks.kubernetes_manifest.certificate["cert_name"], provider
│ "module.eks.provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.spec.duration: was cty.StringVal("2160h"), but
│ now cty.StringVal("2160h0m0s").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.eks.kubernetes_manifest.certificate["cert_name"], provider
│ "module.eks.provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.spec.isCA: was cty.False, but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce
* Install cert-manager.io helm chart
* Create a self-signed cluster issuer
* Create a certificate using the manifest above

### Expected Behavior
A certificate should be created in the designated namespace.

### Actual Behavior
A certificate is created but Terraform fails.

### Important Factoids
None

### References
None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
The issue here is that the attributes `spec.duration` and `spec.isCA` are changing their defined value after apply.

Terraform by default doesn't tolerate values changing between configuration and apply results.
Users are required to declare these tolerable exceptions explicitly. 

With a kubernetes_manifest resource, you can achieve this by using the `computed_fields` meta-attribute. In your specific example, this would look like this:
```hcl
resource "kubernetes_manifest" "certificate" {
  depends_on = [kubernetes_manifest.selfsigned_cluster_issuer]

  computed_fields = ["spec.duration", "spec.isCA"]

  for_each = ...
```

You can read more about the `computed_fields` attribute here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#computed-fields

**Comment by thomas-riccardi** [comment]
A possibly better solution for such one-time changes (that don't change the semantic, it's just different representations of the same thing) would be to update the `kubernetes_manifest` resource so it matches what the system converges toward: `2160h` -> `2160h0m0s`

**Comment by nivimorbgp** [comment]
@alexsomesan thanks!
