### ISSUE TITLE
Error: Unsupported block type Using timeouts block on kubernetes_stateful_set resource

### ISSUE THREAD

**Issue by Arreadi** [hashicorp/terraform-provider-kubernetes#1592]
I am getting:

```
Error: Unsupported block type

  on main.tf line 111, in resource "kubernetes_stateful_set" "mysql":
 111:   timeouts {

Blocks of type "timeouts" are not expected here.
```

Code as follows:
```
resource "kubernetes_stateful_set" "mysql" {

  wait_for_rollout = var.wait
  metadata {
    name = local.mysql_name
    namespace = var.namespace
    labels = {
      environment = var.env
      app = var.app
      service = "mysql"
      business = var.business
      version = var.ref
      active = var.active_ref
    }
  }

  timeouts {
    create = "10m"
    read   = "10m"
    update = "10m"
    delete = "10m"
  }
  <etc>
}
```
Versions:
```
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.52.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

Documentation I'm following:
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/stateful_set

Thank you

**Comment by Arreadi** [comment]
Using 
- Using previously-installed hashicorp/kubernetes v2.7.1

same behaviour

**Comment by arybolovlev** [comment]
Hi @Arreadi,

Could you please do the following to make sure that the timeout configuration is not nested into any of the resource arguments?

1. Detele the timeout configuration section from your resource `kubernetes_stateful_set.mysql`.
2. Run `terraform validate` and make sure you get the `Success! The configuration is valid.` output.
3. Add the timeout configuration section back to your resource `kubernetes_stateful_set.mysql`, but make sure it goes before any resource arguments:
```
resource "kubernetes_stateful_set" "mysql" {

  timeouts {
    create = "10m"
    read   = "10m"
    update = "10m"
    delete = "10m"
  }

  wait_for_rollout = var.wait

  metadata {
    <YOUR CODE>
  }

  spec {
    <YOUR CODE>
  }
}
```
4. Run `terraform validate`. What is the output now?

Thank you.

**Comment by Arreadi** [comment]
Thank you for your quick response, here is the log of the recommended steps:
```
juan@localhost:> grep timeouts ../../../modules/mysql-cluster/main.tf 
  #timeouts {
juan@localhost:> terraform013 validate                                
Success! The configuration is valid.
```

```
juan@localhost:> vi ../../../modules/mysql-cluster/main.tf 
juan@localhost:> grep kubernetes_stateful_set -A 20 ../../../modules/mysql-cluster/main.tf 
resource "kubernetes_stateful_set" "mysql" {

  timeouts {
    create = "30m"
    read   = "10m"
    update = "10m"
    delete = "10m"
  }
  
  depends_on = [kubernetes_config_map.mysqlscripts,kubernetes_config_map.servercnf,kubernetes_storage_class.mysql,kubernetes_config_map.mysql]
  wait_for_rollout = var.wait
  metadata {
    name = local.mysql_name
    namespace = var.namespace
    labels = {
      environment = var.env
      app = var.app
      service = "mysql"
      business = var.business
      version = var.ref
      active = var.active_ref

juan@localhost:/devOps/devOps/cu/Waterworks/repos/waterworks-infrastructure/kubernetes/terraform/magento/prod/db-cluster> terraform013 validate
Error: Unsupported block type

  on ../../../modules/mysql-cluster/main.tf line 96, in resource "kubernetes_stateful_set" "mysql":
  96:   timeouts {

Blocks of type "timeouts" are not expected here.


Error: Unsupported block type

  on ../../../modules/mysql-cluster/main.tf line 96, in resource "kubernetes_stateful_set" "mysql":
  96:   timeouts {

Blocks of type "timeouts" are not expected here.

```

**Comment by Arreadi** [comment]
1. With block #timeouts commented out, is valid
2. with block #timeouts with syntax according to documentation and at the beginning of the resource, it is not valid anymore.

**Comment by Arreadi** [comment]
Also, worth mentioning that the validate is not reporting any other issue besides the timeouts block on my files

**Comment by arybolovlev** [comment]
Thank you for trying all the suggested steps. There is one more thing I want to ask you to verify. In the initial message, you have mentioned that the provider version is `1.13.4` and this version doesn't support the timeout option. It was introduced in `2.0.0` -- [v2.0.0 changelog](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v2.0.0).

Could you please also share the output of the following command `terraform013 version` to double-check that the current provider version is `2.7.1` as you mentioned after that?

Thank you.

**Comment by Arreadi** [comment]
Apologies for all the time wasted, and thank you for driving my attention to the right direction. 

It looks like the upgrade of the provider to 2.7.1 never happened, and it was still using the all one.

It is all good now with 2.7.1, I'll close this.
