### ISSUE TITLE
Terraform 1.1.0+ upgrade uses different datatype for kubernetes_manifest value

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-kubernetes#1594]
We upgraded from Terraform 1.04. to Terraform 1.1.4. This caused a change in a datatype for us that lead to an issue (https://github.com/Azure/aad-pod-identity/issues/529) causing a lot of trouble for our Kubernetes Cluster.

A value that was applied as Integer (with TF 1.04.) was written as String (with TF 1.1.4) after the upgrade.

### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.04 -> upgraded to 1.1.4
Kubernetes provider version: 2.71
Kubernetes version: 1.21.9
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "azure_identity" {
  manifest = {
    "apiVersion" = "aadpodidentity.k8s.io/v1"
    "kind"       = "AzureIdentity"
    "metadata" = {
      "name"      = "id-${kubernetes_namespace.namespace.metadata.0.name}"
      "namespace" = kubernetes_namespace.namespace.metadata.0.name
      "annotations" = {
        "aadpodidentity.k8s.io/Behavior" = "namespaced"
      }
    }
    "spec" = {
      "type" = "0" <-- this causes the issue
      "resourceID" = var.azure_identity_resource_id
      "clientID" = var.azure_identity_client_id
    }
  }
}
```

### Steps to Reproduce
1.  `terraform apply` with Terraform 1.0.4 --> Writes an Integer 0 to spec.type

```
    "spec" = {
      "type" = 0
```

2. Upgrade to Terraform 1.1.4 and `terraform apply` --> Writes a string "0" to spec.type

```
    "spec" = {
      "type" = "0"
```

Not sure what the "fix" for this issue would be to be honest. I only know that changing datatypes is very unexpected.

EDIT: We were not able to reproduce this internally again. We changed the value explicitly to Integer to fix the issue.

**Comment by alexsomesan** [comment]
Hello! This is indeed strange. I will try to reproduce this and indentify what causes this.

However, we have just recently merged a change that introduces transparent type migrations to the provider. This will, we believe, prevent this entire class of issues going forward. The next provider release will include this change.

I'll get back to you with the root cause of this issue and confirmation weather above mentioned migration will cover it.

**Comment by mkemmerz** [comment]
Thanks for the reply @alexsomesan. We tried to reproduce this issue again but were not able to do so. We are running the same configuration for multiple Kubernetes clusters and the datatype differs only for one cluster. We are completely confused on how this datatype change happened. Luckily we found a fix for this.
