### ISSUE TITLE
When there will be release 2.7.2

### ISSUE THREAD

**Issue by mkyc** [hashicorp/terraform-provider-kubernetes#1596]
## Question

There is [this issue](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1533) and [related PR](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1541). Those are required to make AWS ALB ssl redirect [mechanism work](https://stackoverflow.com/a/70928651/641071). I wasn't able to ask in those two because conversations are restricted but [asked in discuss](https://discuss.hashicorp.com/t/when-2-7-2-release-of-terraform-provider-kubernetes/35416) and was redirected back here. 

When is it planned to release `2.7.2` provider version?

**Comment by alexsomesan** [comment]
Release v2.8.0 went out yesterday.

**Comment by mkyc** [comment]
Tested it today and it works. Thank you!
