### ISSUE TITLE
Incorrect code

### ISSUE THREAD

**Issue by bsteveb** [hashicorp/terraform-provider-kubernetes#1598]
There is an issue with the code in the following hashicorp tutorial - it refers to nginx:1.7.8 which is no longer valid, I updated it to nginx:1.20.2 in my own lab environment and your tutorial then worked fine.
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment

    spec {
        container {
          image = "nginx:1.7.8"
          name  = "example"

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:
Kubernetes provider version:
Kubernetes version:
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening this @bsteveb – doing a search for `nginx` on the repo it looks like there's a few places we need to update this.

**Comment by bsteveb** [comment]
cool.  let me know if I can help - you have some great resources and it's
always good to have them up to date...I wonder if we can just use

:latest instead of a specific version of nginx??

best,
steve
