### ISSUE TITLE
Cordon a node from Terraform

### ISSUE THREAD

**Issue by beyondbill** [hashicorp/terraform-provider-kubernetes#1601]
Does kubernetes provider support the equivalence of `kubectl cordon ...`? It involves `GET+PATCH` `/api/v1/nodes/node-name` . I also do not see any resource / data source related to nodes in kubernetes provider today.

**Comment by alexsomesan** [comment]
Right now the provider doesn't support any operations on Node objects. We are exploring the Cluster API and ways we can integrate it into Terraform, are we are planning to revisit the Node objects as well.

You might be able to achieve the effect you are after by importing the Nodes as `kubernetes_manifest` resources.
Here's an example of how to do that:
```
kubectl get nodes <my-node-name> -oyaml | tfk8s -s > node.tf
terraform import kubernetes_manifest.node_<my-node-name> "apiVersion=v1,kind=Node,name=<my-node-name>"
```
After that you can make the necessary changes to the resulting Terraform resource and run `apply`.

The `tfk8s` tool is found [here](https://github.com/jrhouston/tfk8s)

**Comment by beyondbill** [comment]
@alexsomesan Thanks for the response!
