### ISSUE TITLE
Please take a look at this issue and PR

### ISSUE THREAD

**Issue by simonvanderveldt** [hashicorp/terraform-provider-kubernetes#1606]
Hi!

There was an issue #945 with a PR to fix it #948.
Unfortunately it went without any feedback and now both the issue and the PR are closed without the issue being fixed.
Can a maintainer please have a look at them and reply? If there are issues with the PR or the concept please just let us know so we can look at how to address them.
Thanks

**Comment by iBrandyJackson** [comment]
hi @simonvanderveldt 

Thanks for raising this issue back to the surface for the team to review.  (this is exactly what we hope to see when a stale issue gets closed that still contains value to be explored) 

The number one factor we look at when deciding what issues to look at is your 👍 [reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue/PR description as these can be easily discovered.  Thanks for bringing this back up to our attention, we will add this to our queue for further review. And will aim to give an explanation of our plan moving forward wrt to this topic. 

Thanks

**Comment by iBrandyJackson** [comment]
@simonvanderveldt 

For now, I have reopened the original ticket, however, we encourage members to please open a new issue and complete the issue template for any similar issues related to closed issues/PRs. 

I hope this helps to understand why a PR might not get immediate attention - more can be found here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/_about/FAQ.md
