### ISSUE TITLE
Support schedulerName for Pods

### ISSUE THREAD

**Issue by slobo** [hashicorp/terraform-provider-kubernetes#1607]
### Description

I would like to be able to supply `schedulerName` in my pod / deployment `spec`

### References

It has been available since at least kubrenetes 1.19 https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#podspec-v1-core

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
I will be closing this issue since we recently merged #2026 which adds the `schedulerName` attribute for both Pods and Deployments
