### ISSUE TITLE
Kubernetes Provider 2.0.1 "Unauthorized

### ISSUE THREAD

**Issue by nicolas-gagnon** [hashicorp/terraform-provider-kubernetes#1614]
Hi 
im facing Error: Unauthorized when i do a plan,  my file are remote  on bitbucket  i think my kubenetes token are expire after 15 min
this is my provider setup

version 2.0.1
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  token                  = data.aws_eks_cluster_auth.cluster.token
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
                                               
}

When i switch my version for 1.11.1 i receveive this error instead 
Error: Get http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth: dial tcp 127.0.0.1:80: connect: connection refused

Please anybody got some advice

**Comment by alexsomesan** [comment]
Provider version 2.0.1 is more than a year old and many versions behind our current release.
Is there any technical reason stopping you from upgrading.

We're going to need additional information here. Can you please post the output of 
```
terraform state show data.aws_eks_cluster.cluster
```
and also retry the plan operation with the environment variable `TF_LOG=trace` enabled?
```
TF_LOG=trace terraform plan
```
