### ISSUE TITLE
Cronjob using batch/v1beta1

### ISSUE THREAD

**Issue by felskov** [hashicorp/terraform-provider-kubernetes#1629]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.1.7
Kubernetes provider version: v2.8.0
Kubernetes version: 1.21.10
```

### Affected Resource(s)

- cron_job_v1

### Terraform Configuration Files
```hcl
resource "kubernetes_cron_job_v1" "this" {
  metadata {
    name = "housekeeping"
  }

  spec {
    concurrency_policy            = "Replace"
    schedule                      = "@midnight"
    starting_deadline_seconds     = 3600

    job_template {
      metadata {}

      spec {
        backoff_limit              = 2
        ttl_seconds_after_finished = 0

        template {
          metadata {
            labels = {
              job = "housekeeping"
            }
          }

          spec {
            container {
              name = "nodejs"
              image = "my.private.registry.com/repo/jobs/housekeeping:latest"

              resources {
                limits = {
                  memory = "64Mi"
                  cpu = "50m"
                }
              }

              security_context {
                allow_privilege_escalation = false
                read_only_root_filesystem = true
              }
            }
          }
        }
      }
    }
  }
}

```

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
From what I can tell, the cron_job_v1 resource, should create the job under the batch/v1 apiVersion (https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/cron_job_v1)

### Actual Behavior
The job is added under batch/v1beta1

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @felskov,

Could you please share the following `kubectl` output?
- `kubectl api-resources --api-group=batch`
- `kubectl get cronjob <NAME> -o yaml` # Only `apiVersion` and `kind` from this output. `<NAME>` is the name of the CronJob that you have created via Terraform

Thank you!

**Comment by felskov** [comment]
Hi @arybolovlev 

I just found out that the kubernetes cluster was having issues - an automatic update had failed in the control plane, and things were behaving weirdly. We'd previously created the job using the legacy cron_job resource, but had reconfigured and didn't understand why it still reported as batch/v1beta1 - turns out it's correctly updated after all. Although we still don't fully understand what went wrong, it's definitely not an issue with the Kubernetes provider, it was something on our end.

Sorry for the inconvenience, but thank you for the fast reply.
