### ISSUE TITLE
Failed to create kubernetes resource from docker container

### ISSUE THREAD

**Issue by Jahadul-Rakib** [hashicorp/terraform-provider-kubernetes#1630]
provider and resource is getting created from local machine, but in containerized environment it Failed. 
ERROR:
```xml
???
??? Error: Post "https://04BE42781BD7528D569B68A81B59D8B6.gr7.ap-south-1.eks.amazonaws.com/apis/storage.k8s.io/v1beta1/csidrivers": getting credentials: exec: executable aws failed with exit code 255
??? 
???   with kubernetes_csi_driver.KCSYSTEMCREATEDEKSCLUSTER6EDAB4C3F5E74C06AD22AA8D0C730228_kccsidriver_D85E6BBA,
???   on cdk.tf.json line 73, in resource.kubernetes_csi_driver.KCSYSTEMCREATEDEKSCLUSTER6EDAB4C3F5E74C06AD22AA8D0C730228_kccsidriver_D85E6BBA:

??? Error: Post "https://04BE42781BD7528D569B68A81B59D8B6.gr7.ap-south-1.eks.amazonaws.com/api/v1/namespaces": getting credentials: exec: executable aws failed with exit code 255
??? 
???   with kubernetes_namespace.KCSYSTEMCREATEDEKSCLUSTER6EDAB4C3F5E74C06AD22AA8D0C730228_np1_1A5D7548,
???   on cdk.tf.json line 86, in resource.kubernetes_namespace.KCSYSTEMCREATEDEKSCLUSTER6EDAB4C3F5E74C06AD22AA8D0C730228_np1_1A5D7548:
???   86:       }
```

Code: 
```java
      KubernetesProvider.Builder.create (this, "kubernetes")
                .host (clusterInformationDTO.getClusterEndPoint ())
                .clusterCaCertificate (Fn.base64decode (clusterInformationDTO.getClusterCA ()))
//                .insecure (true)
                .exec (KubernetesProviderExec.builder ()
                        .apiVersion ("client.authentication.k8s.io/v1alpha1")
                        .args (List.of ("eks", "get-token", "--cluster-name", clusterInformationDTO.getClusterName ()))
                        .command ("aws")
                        .build ())
                .build ();


       Namespace.Builder.create (this, "np1")
                .metadata (NamespaceMetadata.builder()
                        .name ("test-np1")
                        .build())
                .build ();

````

**Comment by arybolovlev** [comment]
Hi @Jahadul-Rakib,

The issue doesn't seem to be related to the Kubernetes provider. The error message you can see in your output says that there is an issue with getting credentials: `getting credentials: exec: executable aws failed with exit code 255`. I can assume, based on your code, that you are using an analog of `aws eks get-token --cluster-name <NAME>` and it doesn't return you a token and that seems to be a root cause here.

Please, make sure that that issue is addressed first.

Thank you.

**Comment by Jahadul-Rakib** [comment]
Thank you for your response sir,

when i run the same descriptor from my machine its can assume access token but from docker container its can not. how can i fix this issue ?

**Comment by arybolovlev** [comment]
Hi @Jahadul-Rakib,

Please, don't create [a duplicate issue](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1633). It will be helpful for everyone to keep all relevant messages within one discussion. In this case, if someone else faces the same issue they will be able to read everything here. Thank you for understanding.

Now, back to your original issue.

Could you please try one of the following solutions?
- Set environment variable `AWS_EC2_METADATA_DISABLED=true` in your container.
- Define AWS region explicitly, for instance, via environment variable `AWS_DEFAULT_REGION`.

Please, let me know if that helps.

Thank you.
