### ISSUE TITLE
datasources for kubernetes resources

### ISSUE THREAD

**Issue by andel7** [hashicorp/terraform-provider-kubernetes#1631]
## Question
```
Are there any plans to to have datasources like kubernetes_all_namespaces but for other resources ? (for example kubernetes_all_ingresses or kubernetes_all_services )

Alternatively I think it can be useful to supporting regex/wildcard in metadata name  in current datasource for Kubernetes resources instead of specifying explicit name.
```

**Comment by alexsomesan** [comment]
Hi! Thanks for the suggestion. This feels like a useful feature to have. We're going to look into how to expose it and propose a solution.

Thanks a lot for the suggestion!

**Comment by andel7** [comment]
Resolved by this resource:
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/resources
