### ISSUE TITLE
Asking about the next release 2.8.1

### ISSUE THREAD

**Issue by Omar-laz** [hashicorp/terraform-provider-kubernetes#1639]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.1.6
Kubernetes Provider version: 2.8.0
Kubernetes version: 1.21
```

## Question
```
This is just a question about the next release "2.8.1" as it will contain a fix related to the CSI volumes, when can we expect it ?
Thank you.
```

**Comment by jrhouston** [comment]
Thanks for opening this @Omar-laz – we are just doing some testing before our next release, you can expect to see one next week. The next release will be v2.9.0.
