### ISSUE TITLE
Configuration data source

### ISSUE THREAD

**Issue by 0x2b3bfa0** [hashicorp/terraform-provider-kubernetes#1641]
### Description

A `kubernetes_config` data source exposing the data from [`kubectl config view --raw`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-view-em-) ([source](https://github.com/kubernetes/kubectl/blob/ce2c05b6e953ff29854e73c326af97418f082d60/pkg/cmd/config/view.go#L1)) would allow the retrieval of configuration values, like the `server` address for the current cluster.

### Potential Terraform Configuration

```hcl
data "kubernetes_config" "example" {}

output "configuration" {
  value     = data.kubernetes_config.example
  sensitive = true
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Can you provide a more elaborate example of what a use-case of this feature would look like?

Also, this carries a set of serious security concerns.

**Comment by 0x2b3bfa0** [comment]
## Use Case — Service Account

If I recall correctly, the `server` address can only be retrieved from the `kubeconfig` file. This address is necessary to create a new standalone `kubeconfig` file for a service account.

<details><summary>Actual...</summary>

```hcl
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.8.0"
    }
  }
}

provider "kubernetes" {
  config_path = pathexpand("~/.kube/config")
}

resource "kubernetes_service_account" "example" {
  metadata {
    name = "example"
  }
}

data "kubernetes_secret" "example" {
  metadata {
    name = kubernetes_service_account.example.default_secret_name
  }
}
output "kubeconfig_data" {
  sensitive = true

  value = yamlencode({
    apiVersion        = "v1"
    kind              = "Config"
    "current-context" = "cluster"

    clusters = [{
      name = "cluster"
      cluster = {
        "certificate-authority-data" = base64encode(data.kubernetes_secret.example.data["ca.crt"])
        server                       = { for cluster in yamldecode(file(pathexpand("~/.kube/config")))["clusters"] : cluster["name"] => cluster["cluster"] }[{ for context in yamldecode(file(pathexpand("~/.kube/config")))["contexts"] : context["name"] => context["context"]["cluster"] }[yamldecode(file(pathexpand("~/.kube/config")))["current-context"]]]["server"]
      }
    }]

    contexts = [{
      name = "cluster"
      context = {
        cluster   = "cluster"
        namespace = data.kubernetes_secret.example.data["namespace"]
        user      = kubernetes_service_account.example.metadata.0.name
      }
    }]

    users = [{
      name = kubernetes_service_account.example.metadata.0.name
      user = {
        token = data.kubernetes_secret.example.data["token"]
      }
    }]
  })
}
```

</details>
<details><summary>Desired...</summary>

```hcl
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.8.0"
    }
  }
}

provider "kubernetes" {
  config_path = pathexpand("~/.kube/config")
}

resource "kubernetes_service_account" "example" {
  metadata {
    name = "example"
  }
}

data "kubernetes_secret" "example" {
  metadata {
    name = kubernetes_service_account.example.default_secret_name
  }
}

data "kubernetes_config" "example" {}

output "kubeconfig_data" {
  sensitive = true

  value = yamlencode({
    apiVersion        = "v1"
    kind              = "Config"
    "current-context" = "cluster"

    clusters = [{
      name = "cluster"
      cluster = {
        "certificate-authority-data" = base64encode(data.kubernetes_secret.example.data["ca.crt"])
        server                       = data.kubernetes_config.example.clusters[data.kubernetes_config.example["contexts"][data.kubernetes_config.example["current-context"]]]["server"]
      }
    }]

    contexts = [{
      name = "cluster"
      context = {
        cluster   = "cluster"
        namespace = data.kubernetes_secret.example.data["namespace"]
        user      = kubernetes_service_account.example.metadata.0.name
      }
    }]

    users = [{
      name = kubernetes_service_account.example.metadata.0.name
      user = {
        token = data.kubernetes_secret.example.data["token"]
      }
    }]
  })
}
```

</details>

**Comment by 0x2b3bfa0** [comment]
> _Also, this carries a set of serious security concerns_

I'm particularly interested in the security implications of this feature. What kind of concerns do you have in mind?

**Comment by 0x2b3bfa0** [comment]
> [_In the interest of security, the maintainers will not approve data sources that provide the ability to reference or export the AWS credentials of the running provider._](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md#aws-credential-exfiltration) — AWS provider documentation

This feature request is potentially similar in risk. Would it be better to filter out secrets from the output?
