### ISSUE TITLE
Please make context a property of the kubernetes resources rather than the provider

### ISSUE THREAD

**Issue by bcarlock-emerge** [hashicorp/terraform-provider-kubernetes#1644]
### Description

Currently you have to create one provider per context despite the fact that all contexts are defined in the same config. It would be immensely helpful if we were able to change context as a property of the resource rather than having to define an entirely new provider.  
This feature would primarily be useful in the definition of related environments such as multi-region federated clusters and would allow for simplified iteration for identical resources needed in both clusters.

### Potential Terraform Configuration

```hcl
resource "kubernetes_namespace" "namespace" {
  for_each        = var.config
  context         = each.value.context
  metadata {
    name          = each.value.name
    labels        = each.value.labels
    annotations   = each.value.annotations
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
This mechanism needs to be implemented in Terraform itself. You can follow the progress of that work here: https://github.com/hashicorp/terraform/issues/19932

In the mean time, you can actually achieve similar results by using multiple provider block instances and reference them in the resource with a provider alias. Here's how that works: https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations

**Comment by mjuarez** [comment]
Agreed that upstream Terraform needs to solve dynamic provider problem, but your proposed workaround only works if you aren't creating those clusters dynamically in the same plan. I have a use case where I have a data source populating a module with `for_each`. Module configures `google_container_cluster` but need to do last-mile config with kubernetes provider on that cluster. While it seems to work on initial creation, it fails spectacularly at update/deletion.

I would have to go with a terragrunt/templated provider approach if I wanted to configure multiple provider aliases in the same workspace.

By providing context as an attribute in resources, I could at least attempt to use a `null_resource` to setup kubeconfig from the attributes of google_container_cluster. `context` feels like it would be the right balance between exposing all of the provider attributes on every resource.

I feel the google provider has provided a similar workaround by allowing `project` to be defined either at the provider or resource level.
