### ISSUE TITLE
Kubernetes Manifest Terraform Virtual Node AWS AppMesh Says Field is nil.

### ISSUE THREAD

**Issue by gallowaystorm** [hashicorp/terraform-provider-kubernetes#1654]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.2
Kubernetes provider version: v2.8.0
Kubernetes version: 1.21
```

### Affected Resource(s)

kubernetes_manifest

### Terraform Configuration Files
```hcl
# Virtual Node Creation --------------------------------
resource "kubernetes_manifest" "service_virtual_node" {
  manifest = {
    "apiVersion" = "appmesh.k8s.aws/v1beta2"
    "kind"       = "VirtualNode"
    "metadata" = {
      "name"      = "${var.team_name}-${var.service_name}-virtual-node"
      "namespace" = "${var.kubernetes_namespace}"
    }
    "spec" = {
      "podSelector" = {
        "matchLabels" = {
          "app" = "${var.service_name}"
        }
      }
      "listeners" = [{
        "portMapping" = {
          "port"     = "${var.appmesh_port}"
          "protocol" = "${var.service_protocol}"
        }
        "timeout" = {
          "http" = {
            "idle" = {
              "value" = "90"
              "unit"  = "s"
            }
            "perRequest" = {
              "value" = "90"
              "unit"  = "s"
            }
          }
        }
      }]
      "serviceDiscovery" = {
        "dns" = {
          "hostname"     = var.load_balancer_type == "internal" ? "${var.service_name}.${var.dns_zone_name}" : "${var.service_name}-external.${var.dns_zone_name}"
          "responseType" = "${var.service_discovery_response_type}"
        }
      }
      logging = {
        accessLog = {
          file = {
            path = "/dev/stdout"
          }
        }
      }
    }
  }
}
```

### Steps to Reproduce

1. 'terraform apply'

### Expected Behavior
The variable under serviceDiscovery -> dns -> responseType should be evaluated and set to default variable config of "ENDPOINTS".  

### Actual Behavior
You get an error message saying that the field is nil.  Even if I remove the variable and add "ENDPOINTS" directly into the field, it does the same thing.
Error Message:
```bash
│ Error: Failed to morph manifest to OAPI type
│ 
│   with module.services.module.accounts-api.module.appmesh.kubernetes_manifest.service_virtual_node,
│   on .terraform/modules/services.accounts-api.appmesh/kubernetes_manifest.tf line 2, in resource "kubernetes_manifest" "service_virtual_node":
│    2: resource "kubernetes_manifest" "service_virtual_node" {
│ 
│ AttributeName("spec"): [AttributeName("spec")] failed to morph object element into object element: AttributeName("spec").AttributeName("serviceDiscovery"):
│ [AttributeName("spec").AttributeName("serviceDiscovery")] failed to morph object element into object element: AttributeName("spec").AttributeName("serviceDiscovery").AttributeName("dns"):
│ [AttributeName("spec").AttributeName("serviceDiscovery").AttributeName("dns")] failed to morph object element into object element:
│ AttributeName("spec").AttributeName("serviceDiscovery").AttributeName("dns").AttributeName("responseType"):
│ [AttributeName("spec").AttributeName("serviceDiscovery").AttributeName("dns").AttributeName("responseType")] failed to morph object element into object element:
│ AttributeName("spec").AttributeName("serviceDiscovery").AttributeName("dns").AttributeName("responseType"): type is nil
```

### Important Factoids

I have used this same configuration on other EKS clusters with the same exact setup (version, security groups, etc...) and do not get the error.

### References

- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1603

- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1563

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by vbyrd** [comment]
I have encountered the same issue as described above. Any updates?

**Comment by gallowaystorm** [comment]
Any updates on this?

**Comment by gallowaystorm** [comment]
We are using the appmesh controller helm chart:

https://github.com/aws/eks-charts/tree/master/stable/appmesh-controller


I updated to the latest version with still no luck

**Comment by vbyrd** [comment]
This was due to outdated AppMesh Controller CRD definitions on the cluster. Once we ran the following, everything worked as expected.

```kubectl apply -k "github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master"```
