### ISSUE TITLE
`kubernetes_ingress_v1` resource needs `timeouts`

### ISSUE THREAD

**Issue by kriswuollett** [hashicorp/terraform-provider-kubernetes#1672]
Creating a new ingress load balancer in GKE sometimes takes more than 20 minutes, which is the [default Terraform timeout](https://github.com/hashicorp/terraform-plugin-sdk/blob/4d65183b8f000d0fbed7f048773fcbed0b293bbf/helper/schema/resource_data.go#L415) that is used since `timeouts` does not seem to be in the [`kubernetes_ingress_v1` schema](https://github.com/hashicorp/terraform-provider-kubernetes/blob/e1c111d211bf56b62cf0cdd86f24fda2d546f931/kubernetes/resource_kubernetes_ingress_v1.go#L31-L165). Not sure how the code works, but it looks like this is how it gets added to the deployment schema: https://github.com/hashicorp/terraform-provider-kubernetes/blob/e1c111d211bf56b62cf0cdd86f24fda2d546f931/kubernetes/resource_kubernetes_deployment.go#L36-L40

Although specifically asking for the ingress resource, in general I think having customizable timeouts on any resource type would be very useful.

**Comment by kahirokunn** [comment]
Same issue here.
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1755
