### ISSUE TITLE
add `default_namespace` argument to kubernetes provider

### ISSUE THREAD

**Issue by aidanmelen** [hashicorp/terraform-provider-kubernetes#1675]
### Description

A `default_namespace` argument for the provider would set the default namespace for all kubernetes resources. This would work similar to `kubens` if you are familiar with that. A resource that specifies the `metadata.namespace` would override this default.

When the `default_namespace = null` the current provider behavior would be used.

### Potential Terraform Configuration

```hcl
provider "kubernetes" {
  config_path       = "~/.kube/config"
  config_context    = "my-context"
  default_namespace = "my-namespace"
}

resource "kubernetes_config_map_v1" "use_provider_default_namespace" {
  metadata {
    name = "my-config"
  }

  data = { api_host  = "myhost:443" }
}

resource "kubernetes_config_map_v1" "override_provider_default_namespace" {
  metadata {
    name = "my-other-config"
    name = "my-other-namespace"
  }

  data = { api_host = "myhost:443" }
}
```

### References

- https://github.com/ahmetb/kubectx#what-are-kubectx-and-kubens

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening this @aidanmelen. This has been requested before a few times and our preference is for the namespace to be set explicitly at the resource level. Setting namespace in the provider block opens up the possibility for configurations to be more brittle and for confusion to arise in configurations that make use of multiple namespaces – I definitely see the utility in your request, but we'd prefer to err on the side of explicitness. 

You can make use of variables if you want a single place to control the namespace for all of the resources in your config.

**Comment by aidanmelen** [comment]
That is fair. Thanks for your response
