### ISSUE TITLE
Difference between apps/v1 resources, some end in v1 and some don't

### ISSUE THREAD

**Issue by burgerjeffrey** [hashicorp/terraform-provider-kubernetes#1682]
## Question
```
I am finding it hard to determine the difference between these data resources in the documentation.  I am running Kubernetes 1.21.
kubernetes_daemonset   vs.    kubernetes_daemon_set_v1
kubernetes_deployment   vs    kubernetes_deployment_v1
kubernetes_stateful_set    vs.    kubernetes_stateful_set_v1

But for the most part: why cannot I figure this out in the documentation, unless I am just not getting it.  There are many resources that are duplicated and some end in v1 and some don't.  Thanks in advance!
```

**Comment by jrhouston** [comment]
Hi @burgerjeffrey we have a page explaining our rationale for adding the version numbers to the resource names here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources

We have plans to deprecate and remove the unversioned resource names, so where you see resource with a version suffix you should use that.

**Comment by burgerjeffrey** [comment]
Thanks, that makes sense now that I have read it over and over several times and with your shortened to the point summary as well.  I still don't understand though what v1 is referencing, do you have more insight on that?

**Comment by alexsomesan** [comment]
The `v1` references the version part of the `apiVersion` field that every Kubernetes resource manifest has to specify.
