### ISSUE TITLE
kubernetes_manifest: Secret, `stringData` Error

### ISSUE THREAD

**Issue by nicraMarcin** [hashicorp/terraform-provider-kubernetes#1684]
Hi,
With `stringData` in manifest, kubernetes changes it to base64 data key and return null value for `stringData`

**manifest.tf**
```terraform
resource "kubernetes_manifest" "secret_nicram_db_postgres_postgres_secret" {
  manifest = {
    "apiVersion" = "v1"
    "kind" = "Secret"
    "metadata" = {
      "name" = "mypostgres-secret"
      "namespace" = kubernetes_manifest.namespace_nicram_db_postgres.manifest.metadata.name
    }
    "stringData" = {
      "replicationUserPassword" = "repPassword"
      "superUserPassword" = "superUserPassword"
    }
    "type" = "Opaque"
  }
}
```

produces error:

```terraform
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to kubernetes_manifest.secret_nicram_db_postgres_postgres_secret, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected
│ new value: .object.stringData: was cty.MapVal(map[string]cty.Value{"replicationUserPassword":cty.StringVal("repPassword"), "superUserPassword":cty.StringVal("superUserPassword")}),
│ but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by alexsomesan** [comment]
Hello! The attribute `stringData` is always write-only. It will return nil and the actual data passed in will be exposed under the `data` attribute.

Terraform doesn't automatically tolerate attributes changing values between plan and apply return. To counter that, you have to define the attribute as "computed", like this:
```
resource "kubernetes_manifest" "secret_nicram_db_postgres_postgres_secret" {
  computed_fields = ["stringData"]
  manifest = {
...
  }
}
```

**Comment by jbg** [comment]
In general, use `kubernetes_secret`/`kubernetes_secret_v1` if you want a resource that understands how Secret works. (And similarly for other resources.)

`kubernetes_manifest` is generic, so you have to handle special behaviours like this yourself.

I think that if you use `stringData` + `computed_fields` this way, you'll have no drift detection. It would thus be better to set `data` and base64-encode.
