### ISSUE TITLE
kubernetes_manifest fails terraform plan due to not yet created namespace

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-kubernetes#1692]
```
Terraform version: 1.1.4
Kubernetes provider version: 2.8.0 (same error with 2.7.1)
Kubernetes version: 1.22.6
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "namespace" {
  metadata {
    name = var.namespace_name
    labels = {
      name = var.namespace_name // used for enforcing network policies
    }
  }
}

resource "kubernetes_manifest" "azure_identity" {
  manifest = {
    "apiVersion" = "aadpodidentity.k8s.io/v1"
    "kind"       = "AzureIdentity"
    "metadata" = {
      "name"      = "id-${kubernetes_namespace.namespace.metadata.0.name}"
      "namespace" = kubernetes_namespace.namespace.metadata.0.name
      "annotations" = {
        "aadpodidentity.k8s.io/Behavior" = "namespaced"
      }
    }
    "spec" = {
      "type" = 0
      "resourceID" = var.azure_identity_resource_id
      "clientID" = var.azure_identity_client_id
    }
  }
}
```

### Debug Output
```
terraform plan '-var-file=./input.tfvars.json' '--out=plan.out'

Warning: This custom resource does not have an associated OpenAPI schema.

  with module.xxx-kubernetes.kubernetes_manifest.azure_identity,
  on .terraform/modules/xxx-kubernetes/main.tf line 97, in resource "kubernetes_manifest" "azure_identity":
  97: resource "kubernetes_manifest" "azure_identity" {

We could not find an OpenAPI schema for this custom resource. Updates to
this resource will cause a forced replacement.
Error: Dry-run failed for non-structured resource

  with module.namespace-kubernetes.kubernetes_manifest.azure_identity,
  on .terraform/modules/xxx-kubernetes/main.tf line 97, in resource "kubernetes_manifest" "azure_identity":
  97: resource "kubernetes_manifest" "azure_identity" {

A dry-run apply was performed for this resource but was unsuccessful:
namespaces "xxx" not found
```

### Steps to Reproduce
1. `terraform plan` -->

### Expected Behavior
Terraform plan should display the resources to be created later.
Terraform creates a new Kubernetes namespace.
Terraform calls the k8s and creates an AzureIdentity object.

We just recently upgraded from k8s 1.21 to 1.22, not sure if this is important.

### Actual Behavior
Terraform stops its process.

### References
- https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/57
- https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/57#issuecomment-642785183

**Comment by jbg** [comment]
This is more of a design limitation than a bug. `kubernetes_manifest` uses the API server for planning, which will fail if the namespace ([or, somewhat similarly, the CRD](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1367)) doesn't exist yet.

The workaround/solution is to plan & apply twice, either in the first stage with the `kubernetes_manifest.azure_identity` resource not added to your config yet, or in the first stage using `-target` to target only the namespace.

**Comment by jbg** [comment]
Those warnings are about a different issue, but one which manifests in a similar way (needing connectivity to the cluster at plan time). In your case, if Azure had included a schema in that CRD, you shouldn't have hit this specific problem.

Something weird though is that schema was actually [added to the aad-pod-identity CRDs in April 2021](https://github.com/Azure/aad-pod-identity/commit/38c46a4b050ef906cef18740c3f19331a6039c6b). So unless you're using a really old version of the CRDs, it should have already worked without needing to do a dry-run apply at plan time.

**Comment by mkemmerz** [comment]
Thanks again, I will have a look on the CRDs, maybe this resolves our issue

**Comment by mkemmerz** [comment]
as addition on how I fixed it on the cluster:

- Run `kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity/crds/crd.yaml` once on the cluster to update the CRDs

The core issue was that we missed to update the [CRD of the AAD Pod Identity](https://azure.github.io/aad-pod-identity/docs/#v180) after upgrading to version 1.8.0.

[This was introduced on our cluster by upgrading the Helm Chart from version 4.0.0 to 4.1.0.](https://artifacthub.io/packages/helm/aad-pod-identity/aad-pod-identity#helm-chart-and-aad-pod-identity-versions)

**Comment by jbg** [comment]
Note that you can use the `kubernetes_manifest` resource to manage the CRDs in Terraform, rather than manually applying manifests, which may help to keep track of CRDs in your cluster and avoid missing updates in future.

**Comment by mkemmerz** [comment]
Do you have some doumentation about how to do this? Sounds very good

**Comment by jbg** [comment]
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest

You can use a tool like https://github.com/jrhouston/tfk8s to convert YAML manifests (even files containing multiple objects) to HCL.
