### ISSUE TITLE
data kubernetes_persistent_volume_claim spec[0].volume_name now waiting for dependency

### ISSUE THREAD

**Issue by wasap** [hashicorp/terraform-provider-kubernetes#1693]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.8
Kubernetes provider version: 2.10.0
Kubernetes version: 1.21
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
data "kubernetes_persistent_volume_claim" "pvc" {
  metadata {
    name = "redis-data-0"
  }
  depends_on = [
    helm_release.redis
    ]
}

resource "aws_dlm_lifecycle_policy" "features" {
  count = 1
  description        = "redis dev features DLM lifecycle policy"
  execution_role_arn = aws_iam_role.dlm_lifecycle_role.arn
  state              = "ENABLED"

  policy_details {
    resource_types = ["VOLUME"]

    schedule {
      name = "2 weeks of daily snapshots for redis"

      create_rule {
        interval      = 24
        interval_unit = "HOURS"
        times         = ["23:45"]
      }

      retain_rule {
        count = 14
      }

      tags_to_add = {
        SnapshotCreator = "DLM"
      }

      copy_tags = false
    }

    target_tags = {
      CSIVolumeName = data.kubernetes_persistent_volume_claim.pvc.spec[0].volume_name
    }
  }
  depends_on = [
    helm_release.redis
  ]
}

### Debug Output

The given key does not identify an element in this collection value: the collection has no elements.
### Expected Behavior
What should have happened?
terraform plan should not fail on spec[0].volume_name because it has to wait for helm_release.redis to apply, which creates pvc
### Actual Behavior
What actually happened?
error that data.kubernetes_persistent_volume_claim.pvc.spec is empty array
### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @wasap,

It looks like the data source didn't find the PVC you are referring to.

Do you see the PVC name that you have mentioned in the data source listed once the H
elm release has finished? Could you please paste the output of the following command: `kubectl get pvc redis-data-0`?

Thank you.

**Comment by wasap** [comment]
hi, the problem is reproduced on first deploy when pvc not exists yet. pvc is created by helm_release.redis. data depends_on helm_release.redis.
so first time it fails, but if i apply second time when redis is already created, it works fine
