### ISSUE TITLE
Get namespace fails with connection refused on Cloud Composer GKE resource update plan

### ISSUE THREAD

**Issue by lwsanty** [hashicorp/terraform-provider-kubernetes#1695]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: v1.1.7
Kubernetes Provider version: v2.9.0
Kubernetes version: 1.21.9-gke.1002
```
## Terraform configuration
```hcl
terraform {
  required_providers {
    google      = "4.15.0"
    google-beta = "4.15.0"
    kubernetes  = "2.9.0"
  }
}

locals {
  labels_all = {
    environment       = var.name
    vanta-no-alert    = "non-prod"
    vanta-owner       = "johnny"
    vanta-description = "test-composer-env"
  }
}

resource "google_composer_environment" "test" {
  name   = "test-composer-env-tf-c2"
  region = var.google_region_global

  labels = local.labels_all
  ...
}

data "google_container_cluster" "cluster" {
  name     = basename(google_composer_environment.test.config[0].gke_cluster)
  location = var.google_region_global

  depends_on = [google_composer_environment.test]
}

// NOTE: you must be logged into gcloud https://github.com/GoogleCloudPlatform/terraform-google-examples/tree/master/example-gke-k8s-helm
data "google_client_config" "current" {}

provider "kubernetes" {
  host                   = "https://${data.google_container_cluster.cluster.endpoint}"
  token                  = data.google_client_config.current.access_token
  client_certificate     = base64decode(data.google_container_cluster.cluster.master_auth.0.client_certificate)
  client_key             = base64decode(data.google_container_cluster.cluster.master_auth.0.client_key)
  cluster_ca_certificate = base64decode(data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
}

resource "kubernetes_namespace" "namespace" {
  metadata {
    name = "precomputer"
  }
  depends_on = [google_composer_environment.test]
}
```

## Steps
1) run terraform apply and the creation will succeed
2) all the consecutive applies will work
3) change one of the labels, for example `vanta-no-alert` to `non-prod1`
4) run plan
**result:**
```hcl
╷
│ Error: Get "http://localhost/api/v1/namespaces/precomputer": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│   with kubernetes_namespace.namespace,
│   on k8s.tf line 21, in resource "kubernetes_namespace" "namespace":
│   21: resource "kubernetes_namespace" "namespace" {
│ 
╵
```
6) rollback `vanta-no-alert` to `non-prod`
7) run apply
**result:** no errors, infrastructure is up to date

## Question
Is there any way to work this around? Intuitively there's some de-sync/validation at the level of GKE credentials propagation.

## References
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/1579
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/821

**Comment by m00lecule** [comment]
Faced the same issue

**Comment by alexsomesan** [comment]
So, it seems that changing the labels set will cause the `google_composer_environment` resource to be recreated (unable to tell with 100% certainty without a plan output), which in turn causes the data-source that provides the provider configuration to become unknown. This is causing the Kubernetes provider to fail to contact the API.

The only solution here is to split the cluster creation and the kubernetes provider specific resources into different apply operations.

**Comment by nyxi** [comment]
Also affected by this, though to be fair it is clearly stated in the [documentation for the Terraform Kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources).

If I interpret the docs correctly and the official GKE example at https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/gke it seems the easy solution is to have configuration of K8S resources in one module and creation of the K8S cluster in another module.

A very temporary workaround when encountering this is to first run `terraform apply -target='google_composer_environment.composer'` and then a normal apply/plan without `-target`.
