### ISSUE TITLE
AttributeName("spec").AttributeName("topologyKeys")] failed to morph object element into object element

### ISSUE THREAD

**Issue by mattduguid** [hashicorp/terraform-provider-kubernetes#1702]
We have recently upgraded from kubernetes 1.21 to 1.22 and a pipeline that has had no changes was running fine prior has just started failing with the following error,

```
│ Error: Failed to morph manifest to OAPI type
│ 
│   with module.<MODULE_NAME>.kubernetes_manifest.service,
│   on ../../modules/<MODULE_NAME>/main.tf line 436, in resource "kubernetes_manifest" "service":
│  436: resource "kubernetes_manifest" "service" {
│ 
│ AttributeName("spec"): [AttributeName("spec")] failed to morph object
│ element into object element:
│ AttributeName("spec").AttributeName("topologyKeys"):
│ [AttributeName("spec").AttributeName("topologyKeys")] failed to morph
│ object element into object element:
│ AttributeName("spec").AttributeName("topologyKeys"): type is nil
```

The kubernetes provider hasn't changed and is still,
- Installing hashicorp/kubernetes v2.10.0...
- Installed hashicorp/kubernetes v2.10.0 (signed by HashiCorp)

Terraform version hasn't changed and is still,
- 1.1.7

The only hit we can get on "topologyKeys" is in this article https://kubernetes.io/docs/concepts/services-networking/service-topology/ where it mentions the feature is depreciated from v1.21,

```
"FEATURE STATE: Kubernetes v1.21 [deprecated]", 
```

looking at the YAML on that page **we have never used that attribute within our spec** so is this a case of the provider schema lagging behind a change in the kubernetes version or similar?

```
 "topologyKeys" = [
      "kubernetes.io/hostname",
      "topology.kubernetes.io/zone",
      "topology.kubernetes.io/region",
      "*",
 ]
```

**Comment by alexsomesan** [comment]
The `topologyKeys` mechanism has been deprecated. See my response here: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1701#issuecomment-1111241186

**Comment by mattduguid** [comment]
Hi @alexsomesan we also saw it was depreciated but we arent using that in our spec at all, havent changed code, provider, or terraform versions and only upgraded the cluster, what we are keen to understand is how to resolve the issue as we cannot successfully apply the terraform with the current issue and downgrading the cluster isnt an option, are you able to advise any workarounds?

**Comment by alexsomesan** [comment]
The feature gate belongs to the Kubernetes API server (and has to be set on the command line when launching the server). The provider has no ability to influence feature gates.

Also, the `experiments { manifest_resource = true }` is not necessary anymore, it is always enabled. This was just used while manifest was in beta state.

I suspect you might have that attribute present in the state from previous operations on the older cluster version. To confirm that, can you post the state of this Service resource?
You can use `terraform state list` to identify the path of the resource and then `terraform state show <resource-path-from-list>`. Please post that state here, that would help us figure out what's going on.

**Comment by mattduguid** [comment]
@alexsomesan yes the attribute was sitting in the state although we never directly added which is odd, we manually removed the problem attribute and the pipeline now progresses, thanks for the insights
