### ISSUE TITLE
Horizontal Pod Autoscaling - Container resource metrics

### ISSUE THREAD

**Issue by JoshDanielWalker** [hashicorp/terraform-provider-kubernetes#1705]
### Description

Could support for the `Container resource metrics` be added to the `kubernetes_horizontal_pod_autoscaler` resource? 

### Potential Terraform Configuration

See Kubernetes Horizontal Pod Autoscaling Docs in the References.

```hcl
    metric {
      type      = "Resource"
      container = "example"
      resource {
        name = "cpu"
        target {
          type                = "Utilization"
          average_utilization = tostring(var.target_cpu_utilization_percentage)
        }
      }
    }
```

### References

Kubernetes Horizontal Pod Autoscaling Docs
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#container-resource-metrics

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
This feature is till in alpha state, according to the documentation you quoted. We have a policy of not implementing alpa state features in the provider, but we will definitely consider it once it passes onto beta.

**Comment by JoshDanielWalker** [comment]
No worries @alexsomesan. Thank you for your quick reply.
