### ISSUE TITLE
Getting   'Call to function "list" failed: the "list" function was deprecated in'   in Terraform v0.15.5

### ISSUE THREAD

**Issue by ovidiu-trandafir-kbc-be** [hashicorp/terraform-provider-kubernetes#1709]
Hello,

Upgrading from Terraform v014 to v015 causes the following error on running terragrunt run-all plan

Terraform version:  v0.15.5
Kubernetes provider version:  2.11.0
Kubernetes version: v1.19.15
OS: darwin_amd64
Terragrunt: v0.35.10

#### Output
 terragrunt run-all plan
....
 Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 3, in output "cluster_id":
│    3:   value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
╵
╷
│ Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 11, in output "cluster_arn":
│   11:   value       = element(concat(aws_eks_cluster.this.*.arn, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
╵
╷
│ Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 16, in output "cluster_certificate_authority_data":
│   16:   value       = element(concat(aws_eks_cluster.this[*].certificate_authority[0].data, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
╵
╷
│ Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 21, in output "cluster_endpoint":
│   21:   value       = element(concat(aws_eks_cluster.this.*.endpoint, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
╵
╷
│ Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 26, in output "cluster_version":
│   26:   value       = element(concat(aws_eks_cluster.this[*].version, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
╵
╷
│ Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 61, in output "cloudwatch_log_group_name":
│   61:   value       = element(concat(aws_cloudwatch_log_group.this[*].name, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
╵
╷
│ Error: Error in function call
│
│   on .terraform/modules/kubernetes.eks_cluster/outputs.tf line 66, in output "cloudwatch_log_group_arn":
│   66:   value       = element(concat(aws_cloudwatch_log_group.this[*].arn, list("")), 0)
│
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
.........

As described in the Terraform docs, the list() and map() function are deprecated starting with version v015.x - https://www.terraform.io/language/upgrade-guides/0-15 .

Configuration:

.terraform.lock.hcl has the following content

provider "registry.terraform.io/hashicorp/kubernetes" {
  version     = "2.11.0"
  constraints = "~> 2.11.0"
  hashes = [
    "h1:T65SZhN/tQgsAsHe/G5PCgpjofi+aTKPZ+nZg6WOJpc=",
    "zh:143a19dd0ea3b07fc5e3d9231f3c2d01f92894385c98a67327de74c76c715843",
    "zh:1fc757d209e09c3cf7848e4274daa32408c07743698fbed10ee52a4a479b62b6",
    "zh:22dfebd0685749c51a8f765d51a1090a259778960ac1cd4f32021a325b2b9b72",
    "zh:3039b3b76e870cd8fc404cf75a29c66b171c6ba9b6182e131b6ae2ca648ec7c0",
    "zh:3af0a15562fcab4b5684b18802e0239371b2b8ff9197ed069ff4827f795a002b",
    "zh:50aaf20336d1296a73315adb66f7687f75bd5c6b1f93a894b95c75cc142810ec",
    "zh:682064fabff895ec351860b4fe0321290bbbb17c2a410b62c9bea0039400650e",
    "zh:70ac914d5830b3371a2679d8f77cc20c419a6e12925145afae6c977c8eb90934",
    "zh:710aa02cccf7b0f3fb50880d6d2a7a8b8c9435248666616844ba71f74648cddc",
    "zh:88e418118cd5afbdec4984944c7ab36950bf48e8d3e09e090232e55eecfb470b",
    "zh:9cef159377bf23fa331f8724fdc6ce27ad39a217a4bae6df3b1ca408fc643da6",
    "zh:f569b65999264a9416862bca5cd2a6177d94ccb0424f3a4ef424428912b9cb3c",
  ]
}

**Comment by alexsomesan** [comment]
Is the error message not clear about what is the problem is? This is a serious question as we'd like to properly calibrate the user-facing messages.

**Comment by ovidiu-trandafir-kbc-be** [comment]
Yes, the issue is clear now. Was in the module, not in the provider and was fixed in https://github.com/terraform-aws-modules/terraform-aws-eks/releases/tag/v15.1.0 for future reference.
Thanks.
