### ISSUE TITLE
Can't create Secret for Service Account

### ISSUE THREAD

**Issue by MICHAL53Q** [hashicorp/terraform-provider-kubernetes#1714]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.7
Kubernetes provider version: v2.11.0
Kubernetes version: 1.22.6
```

### Affected Resource(s)
- kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_service_account" "example" {
  metadata {
    name = "terraform-example"
    namespace = "default"
  }
}

resource "kubernetes_secret" "example" {
  metadata {
    name = "terraform-example-token"
    namespace = "default"
    annotations = {
      "kubernetes.io/service-account.name" = "terraform-example"
    }
  }

  type = "kubernetes.io/service-account-token"
}
```

### Debug Output
Error: Provider produced inconsistent result after apply
"provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: Root resource was present, but now absent.

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
Create kubernetes secret for service account

### Actual Behavior
Secret is not created and terraform execution failed with error (see Debug Output)

### References
- GH-1355

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MICHAL53Q** [comment]
Hello,

IMO problem is with secret name, after creation, Kubernetes add random string to end of secret (etc.: terraform-example-token-ndfqg)

**Comment by arybolovlev** [comment]
Hi @MICHAL53Q,

I have tried to reproduce this issue with the code you have provided but couldn't. Could you please provide debug output to better understand what exactly happened?

Thank you.

**Comment by MICHAL53Q** [comment]
Hi @arybolovlev 

thanks for response,

Im using custom modules and just realized, somewhere there was a problem, I pasted here "cutted part" of it.
When I re-tested code pasted here its working properly.

My appologize, can we please remove original ticket?
