### ISSUE TITLE
Could not retrieve the list of available versions for provider hashicorp/kubernetes: no available releases match the given constraints 2.7.1, ~> 2.10

### ISSUE THREAD

**Issue by tmoulton-aarete** [hashicorp/terraform-provider-kubernetes#1721]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.13
Kubernetes provider version: 2.7.1
Kubernetes version: 2.10.0
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi, you seem to be using a really old Terraform version.
Could you confirm if you are seeing the same issue when using a recent (1.x.x) version of Terraform?

**Comment by tmoulton-aarete** [comment]
Sorry, I've noticed that v21.0.0 of GKE has a dependancy of v2.10 of kubernetes that was causing the issue. I've rolled back to v20.0.0 of GKE for now to keep things moving.
