### ISSUE TITLE
Error: Provider produced inconsistent result after apply -  CSI Driver on AKS

### ISSUE THREAD

**Issue by alessandrogiorgianni** [hashicorp/terraform-provider-kubernetes#1738]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.2.2
Kubernetes provider version: 2.11.0
Kubernetes version: 1.22.6
```

### Affected Resource(s)

- kubernetes_manifest
### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "csi-pod" {
  manifest = {
    apiVersion = "v1"
    kind       = "Pod"
    metadata = {
      name      = "busybox-secrets-store-inline-user-msi"
      namespace = "default"
    }
    spec = {
      containers = [
        {
          command = [
            "/bin/sleep",
            "10000"
          ]
          image = "k8s.gcr.io/e2e-test-images/busybox:1.29-1"
          name  = "busybox"
          volumeMounts = [
            {
              mountPath = "/mnt/secrets-store"
              name      = "secrets-store01-inline"
              readOnly  = true
            }
          ]
        }
      ]
      volumes = [
        {
          csi = {
            driver   = "secrets-store.csi.k8s.io"
            readOnly = true
            volumeAttributes = {
              secretProviderClass = "azure-kvname-user-msi"
            }
          }
          name = "secrets-store01-inline"
        }
      ]
    }
  }
}
```

### Steps to Reproduce

```bash
terraform apply
```
### Expected Behavior
The equivalent kubectl apply succeeds.

### Actual Behavior
```
Error: Provider produced inconsistent result after apply
When applying changes to kubernetes_manifest.csi-pod, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced 
an  unexpected new value: .object: wrong final value type: attribute "spec": attribute "volumes": tuple required.
This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Important Factoids
I am installing the CSI driver for AKS in Azure. 
The pod gets created and the CSI driver works properly. 
However TF detects some drift in the returned object and taints the manifest.
I tried to use `computed_fields` but couldn't get the wanted result.
### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by chrisbalmer** [comment]
Same error on vanilla kubernetes with longhorn storage provider.

> When applying changes to kubernetes_manifest.pod_jira, provider
> "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an
> unexpected new value: .object: wrong final value type: attribute "spec":
> attribute "volumes": tuple required.

**Comment by chrisbalmer** [comment]
Swapping from a kubernetes_manifest resource to a kubernetes_pod_v1 resource fixed the issue for me.

**Comment by scorsi** [comment]
> Swapping from a kubernetes_manifest resource to a kubernetes_pod_v1 resource fixed the issue for me.

Yes it works, thanks !

```hcl
resource "kubernetes_pod" "busybox" {
    metadata {
        name = "busybox-secrets-store-inline"
        namespace = local.namespace
    }

    spec {
      container {
        name = "busybox"
        image = "registry.k8s.io/e2e-test-images/busybox:1.29-1"
        command = ["/bin/sleep", "10000"]
        volume_mount {
          name       = "secrets-store-inline"
          mount_path = "/mnt/secrets-store"
          read_only  = true
        }
      }

      volume {
        name = "secrets-store-inline"
        csi {
          driver = "secrets-store.csi.k8s.io"
          read_only = true
          volume_attributes = {
            secretProviderClass = "azure-sync"
          }
        }
      }
    }
}
```
