### ISSUE TITLE
Job does not support suspend

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform-provider-kubernetes#1739]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: `Terraform v1.1.6`
Kubernetes provider version: latest
Kubernetes version: `1.22.8-gke.201`
```

### Affected Resource(s)

- kubernetes_job_v1

### Terraform Configuration Files
```hcl

resource "kubernetes_job_v1" "integration_test" {
  metadata {
    name      = "integration-test"
    namespace = var.namespace.metadata[0].name
    labels    = var.labels
  }

  spec {
    suspend = true
    template {
      spec {
        container {
          image = local.image
          name  = "test"
        }
        restart_policy = "Never"
      }
    }
  }
}
```

### Actual Behavior
The provider does not expose the argument added in Kubernetes 1.21.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by renatomjr** [comment]
This is still an issue
