### ISSUE TITLE
Autogenerated documentation is misleading.

### ISSUE THREAD

**Issue by w3dev-dk** [hashicorp/terraform-provider-kubernetes#1742]
### Affected Resource(s)
- kubernetes_cluster_role
- kubernetes_role

### Terraform sample
```hcl
resource "kubernetes_cluster_role" "some-name" {
  metadata {
    name = "some-name"
  }
  
  rule {
    api_groups = ["kafka.strimzi.io"]
    resources = ["ResourceAll"]
    verbs = ["VerbAll"]
  }
}
```

### Expected Behavior
`ResourceAll` and `VerbAll` should represent ALL resources and verbs aka `*` like documented here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/cluster_role#resources

### Actual Behavior
Grants access to the string literal of `ResourceAll` and/or `VerbAll` instead of expand to `*`. The issue is that the documentation is autogenerated from https://github.com/apprenda-kismatic/kubernetes-rbac/blob/master/api/types.go#L38 which is valid for programming but not for terraform and text based manifests.

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue. We should fix the documentation for this. 

It has actually been fixed in the latest Kubernetes Documentation:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#policyrule-v1-rbac-authorization-k8s-io
