### ISSUE TITLE
kubernetes_mutating_webhook_configuration without ca_bundle keeps requesting changing it back to null.

### ISSUE THREAD

**Issue by firefixmaarten** [hashicorp/terraform-provider-kubernetes#1746]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.2.3
Kubernetes provider version: v2.11.0
Kubernetes version: v1.23.5
```

### Affected Resource(s)
- kubernetes_mutating_webhook_configuration_v1
- kubernetes_mutating_webhook_configuration

### Terraform Configuration Files
```hcl
resource "kubernetes_mutating_webhook_configuration_v1" "example-injector-cfg" {
  metadata {
    name = "example-injector-cfg"
    labels = {
      name = "example-injector"
    }
  }

  webhook {
    name                      = "example"
    failure_policy            = "Ignore"
    match_policy              = "Exact"
    timeout_seconds           = 30
    admission_review_versions = ["v1", "v1beta1"]

    client_config {
      service {
        namespace = var.example_namespace
        name      = "example-injector-svc"
        path      = "/mutate"
      }
    }

    rule {
      api_groups   = [""]
      api_versions = ["v1"]
      operations   = ["CREATE", "UPDATE"]
      resources    = ["pods"]
    }
    side_effects = "None"

    namespace_selector {
      match_labels = {}
      match_expressions {
        key      = "control-plane"
        operator = "DoesNotExist"
        values   = []
      }
    }

    object_selector {
      match_expressions {
        key      = "name"
        operator = "NotIn"
        values   = ["example-injector"]
      }
    }
  }
}

```
### Steps to Reproduce
1. terraform apply
2. terraform apply (after initial create)

### Expected Behavior
No changes to apply

### Actual Behavior
I don't supply the ca_bundle (in client_config in webhook) as this is not needed and it will auto trust the k8s CA.
However it reads the ca_bundle that has been set in k8s and tries to set it back to null every time.
There is no option to ignore changes to this ca_bundle so that It does not try to do this every time, or is there ?
Can the provider ignore changes if the object does not specify ca_bundle ?

```sh
Terraform will perform the following actions:

  # module.vault.kubernetes_mutating_webhook_configuration_v1.example-injector-cfg will be updated in-place
  ~ resource "kubernetes_mutating_webhook_configuration_v1" "example-injector-cfg" {
        id = "example-injector-cfg"


      ~ webhook {
            name                      = "example"
            # (6 unchanged attributes hidden)

          ~ client_config {
              - ca_bundle = <<-EOT
                    -----BEGIN CERTIFICATE-----
                   REDACTED
                    -----END CERTIFICATE-----
                EOT -> null

                # (1 unchanged block hidden)
            }



            # (3 unchanged blocks hidden)
        }
        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
It looks like the `ca_bundle` attributed should be marked as "computed" the provider's schema definitions. We're working to fix this.
