### ISSUE TITLE
Default timeout when creating a service account is too short.

### ISSUE THREAD

**Issue by megumish** [hashicorp/terraform-provider-kubernetes#1755]
https://github.com/hashicorp/terraform-provider-kubernetes/blob/0d55c07fe4ec208795d573485f08e96735df253b/kubernetes/resource_kubernetes_service_account.go#L32

The code shows a timeout period of 30 seconds.
When I run it in terraform cloud, it sometimes times out.(It is displayed as context deadline execeeded.)

Is it possible to extend the default timeout time?

Or is it possible to use something other than this value?

**Comment by megumish** [comment]
I will try to see if that method works.

Thank you.

**Comment by kahirokunn** [comment]
I think it would be useful when using modules, etc., if the default timeout could be changed from the provider's settings.

**Comment by megumish** [comment]
@arybolovlev 

I tried this method, but the timeout time did not change.
                                                                                                                                                https://github.com/hashicorp/terraform-provider-kubernetes/blob/b3bb4a42abce665685725a67090b74e338ec9627/kubernetes/resource_kubernetes_service_account.go#L32

I looked at the source code, and it seems like the timeouts block stuff in the terraform resource is set higher up ( golang context ) than the settings here, so

I still think I need to change the schema.ResourceTimeout to solve my problem.

**Comment by kahirokunn** [comment]
The timeouts block has been set up.

```terraform
resource "kubernetes_service_account_v1" "irsa" {
  count = var.create_kubernetes_service_account ? 1 : 0
  metadata {
    name        = var.kubernetes_service_account
    namespace   = var.kubernetes_namespace
    annotations = var.irsa_iam_policies != null ? { "eks.amazonaws.com/role-arn" : aws_iam_role.irsa[0].arn } : null
  }

  automount_service_account_token = true

  timeouts {
    create = "10m"
    update = "10m"
    delete = "10m"
  }
}
```

However, the 30s timeout was not extended to 10 minutes.
You can see this error when you look at it. `Creation errored after 35s`

```json
{
  "@level": "info",
  "@message": "module.eks_blueprints_kubernetes_addons.module.cluster_autoscaler[0].module.helm_addon.module.irsa[0].kubernetes_service_account_v1.irsa[0]: Creation errored after 35s",
  "@module": "terraform.ui",
  "@timestamp": "2022-06-30T06:58:47.435921Z",
  "hook": {
    "resource": {
      "addr": "module.eks_blueprints_kubernetes_addons.module.cluster_autoscaler[0].module.helm_addon.module.irsa[0].kubernetes_service_account_v1.irsa[0]",
      "module": "module.eks_blueprints_kubernetes_addons.module.cluster_autoscaler[0].module.helm_addon.module.irsa[0]",
      "resource": "kubernetes_service_account_v1.irsa[0]",
      "implied_provider": "kubernetes",
      "resource_type": "kubernetes_service_account_v1",
      "resource_name": "irsa",
      "resource_key": 0
    },
    "action": "create",
    "elapsed_seconds": 35
  },
  "type": "apply_errored"
}
```

There seems to be no code anywhere that passes timeouts for the following part.

https://github.com/hashicorp/terraform-provider-kubernetes/blob/b3bb4a42abce665685725a67090b74e338ec9627/kubernetes/resource_kubernetes_service_account.go#L32

**Comment by kahirokunn** [comment]
My network environment is slow, only 64 kbps. 😢 
Unfortunately, the Kubernetes cluster to be operated is on the other side of the globe.
It will not complete in 30 seconds, which is very troubling.
How can I extend the timeouts from 30 seconds?

**Comment by kahirokunn** [comment]
Same issue here.
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1672

**Comment by arybolovlev** [comment]
@kahirokunn I have double checked and the creation timeout works as expected. Moreover, your code example cannot be execute because you are passing unknown timeouts like `update` and `delete`. The resource `kubernetes_service_account_v1` supports only `create` timeout. Since these timeouts are not matching schema, Terraform will through an error when you try to execute your code.

Here is my simplified version of your code example:
```hcl
resource "kubernetes_service_account_v1" "irsa" {
  metadata {
    name        = "name"
    namespace   = "korp"
  }

  automount_service_account_token = true

  timeouts {
    create = "10m"
    update = "10m"
    delete = "10m"
  }
}
```

I use the latest version of the Terraform and provider:
```
# terraform providers --version
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/kubernetes v2.12.0
```

Then I run validate and Terraform returns some errors related to the timeouts:
```
│ Error: Unsupported argument
│
│   on main.tf line 11, in resource "kubernetes_service_account_v1" "irsa":
│   11:     update = "10m"
│
│ An argument named "update" is not expected here.
╵
╷
│ Error: Unsupported argument
│
│   on main.tf line 12, in resource "kubernetes_service_account_v1" "irsa":
│   12:     delete = "10m"
│
│ An argument named "delete" is not expected here.
```

**Comment by arybolovlev** [comment]
@megumish, the following code is just describes a schema and a default value of the parameter:
```
Create: schema.DefaultTimeout(30 * time.Second)
```
As I mentioned earlier, you can override it your Terraform code like this:

```hcl
resource "kubernetes_service_account_v1" "this" {
  ...
  timeouts {
    create = "10m"
  }
}
```

I have tested this code and it works as expected.

The way how it works is the following:
- provider sends a request to your Kubernetes cluster to create a service account. [Line 93](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/resource_kubernetes_service_account.go#L93)
- if no error was returned, provider is waiting for "default secret" to be created and attached to the service account that you have just created and that is the place where create timeout plays its role. [Line 100](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/resource_kubernetes_service_account.go#L100)

The default secret concept exist in Kubernetes till the version `v1.24` where it was deprecated. You can find more details in the Kubernetes change log [here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes).

Please share more details about your issue:
- Terraform and provider versions: `terraform providers --version`
- Kubernetes cluster version: `kubectl version`
- Terraform code that causes an issue
- Terraform debug outputs: https://www.terraform.io/internals/debugging
- Any additional details that you think can be useful here

Thank you.
