### ISSUE TITLE
Implement `timeZone` field in `CronJob`

### ISSUE THREAD

**Issue by SPodjasek** [hashicorp/terraform-provider-kubernetes#1760]
### Description

Latest Alpha feature introduced by `CronJobTimeZone` feature gate allows you to set desired time zone in which `CronJob` should be scheduled. This field is missing in current provider.

### Potential Terraform Configuration

```hcl
resource "kubernetes_cron_job_v1" "time_zone_test" {
  metadata {
    name      = "time-zone-test"
    namespace = kubernetes_namespace.namespace.metadata[0].name
  }
  spec {
    schedule                  = "10 1 * * *"
    time_zone                 = "Etc/UTC"
    job_template {
      metadata {}
      spec {
        template {
          metadata {}
          spec {
            container {
              name  = "test"
              image = "busybox:stable"

              command = ["/bin/sh", "-c", "echo hello world"]
            }
          }
        }
      }
    }
  }
}
```

### References

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones

https://github.com/kubernetes/api/blob/988d7a1d2141e6cdb6b4d3c1a0652471928351aa/batch/v1/types.go#L378-L382

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Closing this issue since #1971 resolves this.
