### ISSUE TITLE
New data source: `kubernetes_server_version`

### ISSUE THREAD

**Issue by matheusfm** [hashicorp/terraform-provider-kubernetes#1767]
### Description

Would like to be able to have access to server version.

### Potential Terraform Configuration

```hcl
data "kubernetes_server_version" "current" { }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello! Thank you for opening this request, can you comment on what you would be using this feature for?

**Comment by flynnhandley** [comment]
@BBBmau, I'd like to give this one a go, are you happy for me to raise a PR?
