### ISSUE TITLE
Kubernetes secret with json 

### ISSUE THREAD

**Issue by munir94** [hashicorp/terraform-provider-kubernetes#1801]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Kubernetes Provider version:
Kubernetes version:
```
## Terraform configuration

```hcl
resource "kubernetes_secret" "cloud01" {
    metadata {
      name = "cloud01"
      namespace = kubernetes_namespace.kubecost.metadata[0].name
    }
    type = "Opaque"
    data = jsonencode({  
    "azure": [
        {
          "azureSubscriptionID": "${var.sub-id}",
          "azureStorageAccount": "${var.saname}",
          "azureStorageAccessKey": "${var.sakey}",
          "azureStorageContainer": "${var.sacontainer}",
          "azureContainerPath": "${var.sapath}",
          "azureCloud": "${var.azcloud}"
        }
    ]
     
    })   
}
```
## Question

Enter your question here.
Hi , 
I would like to ask if the a netter way to create a secret in kubernetes as in like this format shared

i manage to manually create using kubectl command like this but not with terraform 
kubectl create secret generic cloud01 --from-file=cloud-integration.json

hope anyone can share some guidance

**Comment by alexsomesan** [comment]
This is actually the recommended way to generate JSON payloads for resources attributes. Does the example you shared already work for you as you expect it?

**Comment by munir94** [comment]
no it does not , this error come out after i run terraform apply 
![image](https://user-images.githubusercontent.com/39366930/184042990-f40d08cf-2e0e-4cb3-8f83-ae38fe541cbf.png)

**Comment by arybolovlev** [comment]
Hi @munir94,

Could you please try the following code and let us know if that works?

```hcl
resource "kubernetes_secret" "cloud01" {
  metadata {
    name      = "cloud01"
    namespace = kubernetes_namespace.kubecost.metadata[0].name
  }
  type = "Opaque"
  data = {
    "azure" = jsonencode({
      "azure" : [
        {
          "azureSubscriptionID" : "${var.sub-id}",
          "azureStorageAccount" : "${var.saname}",
          "azureStorageAccessKey" : "${var.sakey}",
          "azureStorageContainer" : "${var.sacontainer}",
          "azureContainerPath" : "${var.sapath}",
          "azureCloud" : "${var.azcloud}"
        }
      ]
    })
  }
}
```

I hope that helps.

Thank you!

**Comment by munir94** [comment]
works for me , thanks a lot

**Comment by arybolovlev** [comment]
I am not sure if I get your question right, but when you pass anything to `kubernetes_secret.data` -- it will be automatically encoded into base64, so you do not need to do that explicitly.

Here is my simplified version of your code:
```hcl
variable "sub_id" {
  default = "hello"
}

variable "saname" {
  default = "hello"
}

resource "kubernetes_secret" "cloud01" {
  metadata {
    name      = "cloud01"
    namespace = "this"
  }
  type = "Opaque"
  data = {
    "cloud-integration.json" = jsonencode({
      "azure" : [
        {
          "azureSubscriptionID" : var.sub_id,
          "azureStorageAccount" : var.saname,
        }
      ]
    })
  }
}
```

Here is the output:
```yaml
# k -n this get secrets cloud01 -o yaml                                                                                                                          ⎈ kind-korp4
apiVersion: v1
data:
  azure: eyJhenVyZSI6W3siYXp1cmVTdG9yYWdlQWNjb3VudCI6ImhlbGxvIiwiYXp1cmVTdWJzY3JpcHRpb25JRCI6ImhlbGxvIn1dfQ==
kind: Secret
metadata:
  creationTimestamp: "2022-08-11T07:31:23Z"
  name: cloud01
  namespace: this
  resourceVersion: "267825"
  uid: db320dc3-5543-483f-8e29-31f89849d6c3
type: Opaque
```

Here is the decode result:
```json
# echo -n "eyJhenVyZSI6W3siYXp1cmVTdG9yYWdlQWNjb3VudCI6ImhlbGxvIiwiYXp1cmVTdWJzY3JpcHRpb25JRCI6ImhlbGxvIn1dfQ==" | base64 -d | jq                                       ✘ INT
{
  "azure": [
    {
      "azureStorageAccount": "hello",
      "azureSubscriptionID": "hello"
    }
  ]
}
```

**Comment by munir94** [comment]
thanks again.. really appreciate that

**Comment by munir94** [comment]
here is the update that works for me , it a bit complicated as it need new line and space 
resource "kubernetes_secret" "kubecost_sec" {
  metadata {
    name      = "kubecost-sec"
    namespace = kubernetes_namespace.kubecost.metadata[0].name
  }
  data = {
      "cloud-integration.json" = "\r\n{\r\n    \"azure\": [\r\n        {\r\n          \"azureSubscriptionID\": \"${var.sub-id}\",\r\n          \"azureStorageAccount\": \"${var.saname}\",\r\n          \"azureStorageAccessKey\": \"${var.sakey}\",\r\n          \"azureStorageContainer\": \"${var.sacontainer}\",\r\n          \"azureContainerPath\": \"${var.sapath}\",\r\n          \"azureCloud\": \"${var.azcloud}\"\r\n        }\r\n    ]\r\n}"
   
  }
  type = "Opaque"
}
