### ISSUE TITLE
Terraform does not detect change when setting property in kubernetes_secret to emtpty string 

### ISSUE THREAD

**Issue by rychuhardy** [hashicorp/terraform-provider-kubernetes#1803]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v1.2.6
Kubernetes provider version: v2.12.1
Kubernetes version: 1.22.6
```

### Affected Resource(s)
- kubernetes_secret

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.12.1"
    }
  }
}

provider "kubernetes" {
  config_context = "test-k8s-admin"
  config_path = "~/.kube/config"
}

variable "DB_PASSWORD" {
  
}

resource "kubernetes_secret" "db_secret" {
  metadata {
    name = "db-secret"
  }

  data = {
    "PASSWORD" = var.DB_PASSWORD
  }
}
```

### Debug Output
https://gist.github.com/rychuhardy/76f5b5fc41374dbf7f9279c327fa1fa4

### Steps to Reproduce
1. `terraform init`
2. `export TF_VAR_DB_PASSWORD="abc"`
3. `terraform apply -auto-approve`
4. `export TF_VAR_DB_PASSWORD=""`
5. `terraform plan`

### Expected Behavior
Change to kubernetes_secret should be detected.

### Actual Behavior
No changes. Your infrastructure matches the configuration.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Terrafrom SDK related issue: https://github.com/hashicorp/terraform-plugin-sdk/issues/282
