### ISSUE TITLE
ownerReferences is Unsupported argument

### ISSUE THREAD

**Issue by OmerKahani** [hashicorp/terraform-provider-kubernetes#1809]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform v1.2.5
Kubernetes provider version: v2.12.1
Kubernetes version: 1.21
```

### Affected Resource(s)

- kubernetes_secret
- And all the others

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "secret" {
  metadata {
    name      = "name"
    namespace = "namespace"
    ownerReferences = {
      apiVersion = "api"
      kind = "kind"
      name = "name"
      uid = "uid"
    }
  }
  ...
}
```

### Output
```
│ Error: Unsupported argument
│
│   on k8s-secrets.tf line 15, in resource "kubernetes_secret" "secret":
│   15:     ownerReferences = {
│
│ An argument named "ownerReferences" is not expected here.
```

### Steps to Reproduce
1. `terraform plan`

### Expected Behavior
[ownerReferences](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) is part of the K8s [metadata object](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#System) and
should be supported

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @OmerKahani,

Could you please share some more information about the need to manage `ownerReferences` by terraform? Usually `ownerReferences` is set up by one of the controllers.

Thank you.

P.S.: I have updated your initial post and added the Community Note part.

**Comment by OmerKahani** [comment]
We are using it from a controller. We use https://github.com/hashicorp/terraform-k8s to run terraform inside the cluster.
So we also want to add `ownerReferences` so we can track the resources that was created

**Comment by arybolovlev** [comment]
This sounds more like a task for labels or annotations, rather than owner reference. It would be helpful if you can share a more concrete example in case I am missing something here.

Thank you.

**Comment by OmerKahani** [comment]
The terraform K8s operator, also part of HashiCorp, is using a CRD in the cluster. That CRD is pointing to a TF module, in our case, that TF module will create more resources in the cluster.

We want those resources to be linked to the workspace, so other tools we use (like ArgoCD) will be able to show that they are managed by that workspace. ArgoCD understand `ownerReferences` by default
