### ISSUE TITLE
Add `groups` param to kubernetes_certificate_signing_request :pen: 

### ISSUE THREAD

**Issue by yuriy-yarosh** [hashicorp/terraform-provider-kubernetes#1814]
### Description

K8S CSR's for `kubernetes.io/kubelet-serving` signer have groups param, and it's [a part](https://docs.openshift.com/container-platform/4.11/rest_api/security_apis/certificatesigningrequest-certificates-k8s-io-v1.html) of the CSR spec.

It's missing in `kubernetes_certificate_signing_request` resource.

### Potential Terraform Configuration

```hcl
# For Vault Standalone TLS certs provisioning according to 
# https://www.vaultproject.io/docs/platform/k8s/helm/examples/standalone-tls

resource "kubernetes_certificate_signing_request" "tls" {
  metadata {
    name = "vault-csr"
  }

  auto_approve = true

  spec {
    usages      = ["digital signature", "key encipherment", "server auth"]
    signer_name = "kubernetes.io/kubelet-serving"
    request     = tls_cert_request.csr.cert_request_pem
    groups      = ["system:authenticated"]
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by MicheleArturo** [comment]
Are there any plans to address this request?
