### ISSUE TITLE
Destroy operations do not seem to be idempotent

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform-provider-kubernetes#1822]
If the namespace doesn't exist, I would expect the destroy operation to be fully idempotent and carry on. The current behavior fails with ` namespaces "monitoring" not found`

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.2.5
Kubernetes provider version: 2.13.1
Kubernetes version: 1.21 (EKS)
```

### References
* https://hashicorp.github.io/terraform-provider-aws/running-and-writing-acceptance-tests/#disappears-acceptance-tests

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
This seems to be default behaviour for most resources, not just namespaces. That being said, we agree this doesn't feel quite right from a UX perspective. A better choice would be to surface this as a warning and complete the operation normally.

**Comment by c4milo** [comment]
@alexsomesan, yes, we also started to see issues with `kubernetes_manifest` resources.

**Comment by c4milo** [comment]
To give more context, this is not only a UX issue but a reliability issue when Terraform is used as a core tool to orchestrate infrastructure for managed services such as Managed Consuls, Managed Vaults, Managed nameyourservice.

**Comment by c4milo** [comment]
@alexsomesan, any guidance on how one would go about testing idempotent destroys? The current terraform-plugin-sdk seems to be mostly designed to test the full lifecycle, it is not very clear how to tell it to run destroy twice.

**Comment by c4milo** [comment]
FWIW, this is potentially also caused by lack of idempotency in the provider: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1455. My team ran into it today.
