### ISSUE TITLE
Terraform pvc invalid spec error

### ISSUE THREAD

**Issue by snehlata08** [hashicorp/terraform-provider-kubernetes#1837]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.2.2
Kubernetes version: 1.21.9
```

## Question
I was getting error of Error No. 37 No locks available. So I tried to update resources and pvc. The pvc was of size 1Gi. 
I updated it manually to 5Gi. Then terraform started giving error.
 ```Error: cannot patch "web-error-volume-claim" with kind PersistentVolumeClaim: PersistentVolumeClaim "web-error-volume-claim" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value```
 Now there is no error in pvc and I rolled it back to 1Gi. Still terraform is stuck.

**Comment by arybolovlev** [comment]
Hi @snehlata08,

I am not quite sure if I understand your question. Could you please be more specific?

Thank you.
