### ISSUE TITLE
bug inconsistent values for sensitive attribute with new 2.14 provider version

### ISSUE THREAD

**Issue by dominik-ba** [hashicorp/terraform-provider-kubernetes#1860]
Hi folks,

since today we get this error message:

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.abc.kubernetes_secret.xyz to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/kubernetes" produced an invalid new value
│ for .data: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

Do you need more data from my side?

**Comment by jrhouston** [comment]
Thanks for opening this @dominik-ba – could you share a sample of your config that reproduces the error, so we can investigate?

**Comment by jrhouston** [comment]
I tried your config but I couldn't reproduce the error. Which Kubernetes version are you using? Is this a fresh apply or do you have pre-existing state?

**Comment by dominik-ba** [comment]
There is a pre-existing state and we use kubernetes 1.21 (with AWS EKS actually)

**Comment by my-gitgit** [comment]
experiencing the same error building new aws eks cluster

terraform: 1.2.5 / 1.3.2
cluster: 1.21.14
k8 provider:  2.14.0 (upgraded from 2.12.1)
aws provider: 4.34 (upgraded from 4.23.0)

cluster created daily at 7am and destroyed by 10pm

Error: Provider produced inconsistent final plan

When expanding the plan for
module.eks_deployment.kubernetes_secret.k8s_dashboard_csrf to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/kubernetes" produced an invalid new value
for .data: inconsistent values for sensitive attribute.

This is a bug in the provider, which should be reported in the provider's
own issue tracker.

**Comment by romanbakaleyko** [comment]
I am experiencing same problem, going to try to roll back to 2.12.1 like @my-gitgit suggested.

**Comment by romanbakaleyko** [comment]
figured why I was getting the error, in my case it is unrelated to the provider.

**Comment by uvwildos** [comment]
> figured why I was getting the error, in my case it is unrelated to the provider.

and you didnt share with us?     mmmhhh

**Comment by AnkitaBarbi** [comment]
> figured why I was getting the error, in my case it is unrelated to the provider.

@romanbakaleyko  can you share what was the cause for it and what approach you took? It might help in addressing the issue.

**Comment by AnkitaBarbi** [comment]
I tried this approach and it worked for me https://github.com/hashicorp/terraform-provider-kubernetes/issues/782#issuecomment-854185696, just in case if anyone is still having issue with it.
