### ISSUE TITLE
docker_password containing certain characters are considered invalid

### ISSUE THREAD

**Issue by renatoathaydes** [hashicorp/terraform-provider-kubernetes#1866]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.3.1
on darwin_arm64
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2
+ provider registry.terraform.io/hashicorp/helm v2.7.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.14.0
```

### Steps to Reproduce

1. `terraform apply -var="docker_username=xxx" -var="docker_password=yyy"`

where the password contains the `{` character amongst other less offensive ones.

The password is used like this:

```
resource "kubernetes_secret" "docker-registry" {
  metadata {
    name = "dockerhub"
    namespace = kubernetes_namespace.curity_ns.metadata[0].name
  }

  data = {
    ".dockerconfigjson" = templatefile("${path.cwd}/config-files/docker-config.json", {
      docker-username           = var.docker_username
      docker-password           = var.docker_password
      docker-server             = "https://index.docker.io/v1/"
      auth                      = base64encode("...")
    })
  }

  type = "kubernetes.io/dockerconfigjson"
}
```

### Expected Behavior
It should not care about the password value as long as it matches.

### Actual Behavior

```
╷
│ Error: Secret "dockerhub" is invalid: data[.dockerconfigjson]: Invalid value: "<secret contents redacted>": invalid character '{' after object key:value pair
│ 
│   with kubernetes_secret.docker-registry,
│   on deploy-curity.tf line 25, in resource "kubernetes_secret" "docker-registry":
│   25: resource "kubernetes_secret" "docker-registry" {
│ 
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @renatoathaydes I'm not able to reproduce this with just the config you sent me – can you share the template file you're using?

**Comment by renatoathaydes** [comment]
`docker-config.json`:

```json
{"auths":{"${docker-server}":{"username":"${docker-username}","password":"${docker-password}","auth":"${auth}"}}}
```

**Comment by renatoathaydes** [comment]
I've recycled the password.... it looked something like this: `n1\"{I2:a"` (the double quote is escaped for the shell)
