### ISSUE TITLE
kubernetes_manifest - Failed to determine GroupVersionResource for manifest

### ISSUE THREAD

**Issue by papanito** [hashicorp/terraform-provider-kubernetes#1873]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.2
Kubernetes provider version: v2.11.0
Kubernetes version: 1.23
```

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "opa-podmonitor" {
  manifest = {
    apiVersion = "monitoring.coreos.com/v1"
    kind = " PodMonitor"
    metadata = {
      name = "opa-pod-monitor"
      namespace = "cattle-gatekeeper-system"
      labels = {
          team = "skywalkers"
      }
    }
    spec = {
      selector = {
        matchLabels = {
          "gatekeeper.sh/operation" = "audit"
        }
      }
      podMetricsEndpoints = {
        
      }
    }
  }
}
```

### Debug Output

TBD

### Steps to Reproduce

1. `terraform plan` 

### Expected Behavior

Terraform plan just runs fine

### Actual Behavior

Error when running `terraform plan`

```
│ Error: Failed to determine GroupVersionResource for manifest
│
│   with kubernetes_manifest.opa-podmonitor,
│   on gatekeeper.tf line 12, in resource "kubernetes_manifest" "opa-podmonitor":
│   12: resource "kubernetes_manifest" "opa-podmonitor" {
│
│ no matches for kind " PodMonitor" in group "monitoring.coreos.com"
```

### Important Factoids

APIs are there

```
$ kubectl get apiservices | grep monit
v1.monitoring.coreos.com                     Local                                                            True        19h
v1alpha1.monitoring.coreos.com               Local                                                            True        19h
v1alpha1.monitoring.kiali.io                 Local    
```

I can manually add it using the Rancher UI
![image](https://user-images.githubusercontent.com/15034009/195819157-dd73ebcd-6b46-4ae3-b4f5-0b1a35c3f21a.png)

### References

- [GH-1448](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1448)
- [GH-1583](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1583)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
I see there's some stray whitespace here:

```
 kind = " PodMonitor"
 ```
 
 Could you try removing it and see if you get the error? We might need to add some whitespace stripping somewhere for kind.

**Comment by papanito** [comment]
@jrhouston thanks that was it -  was probably too tired on Friday to see it :-P
