### ISSUE TITLE
Removing container CPU resource limit is undetected by Terraform

### ISSUE THREAD

**Issue by dsoyet** [hashicorp/terraform-provider-kubernetes#1876]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.2.9
Kubernetes provider version:  v2.14.0
Kubernetes version: 1.21.0
```

### Affected Resource(s)
- kubernetes_deployment

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "local-example" {
  metadata {
    name = "local-example"
    namespace = "default"
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        test = "local-example"
      }
    }

    template {
      metadata {
        labels = {
          test = "local-example"
        }
      }

      spec {
        container {
          # image = "${var.addresses[0]}:5000/rancher/mirrored-library-nginx:1.21.1-alpine"
          image = "rancher/mirrored-library-nginx:1.21.1-alpine"
          name  = "example"

          resources {
            limits = {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests = {
              cpu    = "250m"
              memory = "50Mi"
            }
          }
          liveness_probe {
            http_get {
              path = "/"
              port = 80

              http_header {
                name  = "X-Custom-Header"
                value = "Awesome"
              }
            }

            initial_delay_seconds = 3
            period_seconds        = 3
          }
        }
      }
    }
  }
}

terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.14.0"
    }
  }
}

provider "kubernetes" {
  config_path = "kube_config_cluster.yml"
}


```

### Debug Output
when I comment out the resources {} block, the deployment didn't updated

### Steps to Reproduce
1. `terraform apply` 
2. comment out the resources {} block
3. `terraform apply`

### Expected Behavior
the deployment should remove his resources block

### Actual Behavior
`terraform apply` output
No changes. Your infrastructure matches the configuration.

### References
- GH-754

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by dsoyet** [comment]
when I change the resources block to 
```hcl
          resources {
            limits = {
            }
            requests = {
            }
          }
```
it works as expected

**Comment by BBBmau** [comment]
Hello @dsoyet ! Thank you opening this issue, like you stated in your comment the resources block needs to have the attributes set in order for any change to happen since it is expecting some sort of value to be provided.

**Comment by jan4984** [comment]
> Hello @dsoyet ! Thank you opening this issue, like you stated in your comment the resources block needs to have the attributes set in order for any change to happen since it is expecting some sort of value to be provided.

Hello @BBBmau I think it is a bug, just like https://github.com/hashicorp/terraform-provider-kubernetes/issues/754. How a user know "the resources block needs to have the attributes set" ?
