### ISSUE TITLE
Avoid `kubernetes_secret(_v1).wait_for_service_account_token` to trigger resource update when omitted and not applying (cf. #1833)

### ISSUE THREAD

**Issue by loganmzz** [hashicorp/terraform-provider-kubernetes#1877]
### Description

Since PR #1833, a new field `kubernetes_secret(_v1).wait_for_service_account_token` has been added with default value `true`. Triggering an update on all `kubernetes_secret(_v1)` resources even if they aren't of type `kubernetes.io/service-account-token` (the only case where this new field apply).

Is it possible to omit field if `type` doesn't match when returning its "state" to Terraform ? :pray: 

### Potential Terraform Configuration

N/A

### References

https://github.com/hashicorp/terraform-provider-kubernetes/pull/1833

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello @loganmzz ! Thank you for opening this issue, could you provide us with the output from `TF_LOG=debug terraform plan`?

**Comment by dsiebel** [comment]
It also causes issues when using `generate_name` on the `kubernetes_secret` because it requires you to "turn around" the dependency between Service Account and Secret:

```
resource "kubernetes_service_account" "manager" {
  metadata {
    name      = var.service_account_name
    namespace = var.namespace
  }
  secret {
    name = kubernetes_secret.manager_token.metadata.0.name
  }
}

resource "kubernetes_secret" "manager_token" {
  metadata {
    generate_name = var.secret_name_prefix
    namespace     = var.namespace
    annotations = {
      "kubernetes.io/service-account.name" = var.service_account_name
    }
  }
  type = "kubernetes.io/service-account-token"
}
```

results in

```
kubernetes_secret.manager_token: Creating...
╷
│ Error: secrets "manager-zqmcm" not found
│ 
│   with kubernetes_secret.manager_token,
│   on main.tf line XY, in resource "kubernetes_secret" "manager_token":
│   39: resource "kubernetes_secret" "manager_token" {
│ 
╵
```

Defaulting to `true` requires the Service Account to be created _before_ the secret.

**Comment by arybolovlev** [comment]
Hi @dsiebel,

I think you question is different and it is answered [here](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1943#issuecomment-1369546028). In short, you don't need refer to the secret in your service account resource. Kubernetes does it automagically for you based on `"kubernetes.io/service-account.name" = var.service_account_name` in your secret resource.

**Comment by dsiebel** [comment]
I am currently not 100% sure of that and need to do some more testing. The Kubernetes documentation of `secrets` attribute states:

> Secrets is the list of secrets allowed to be used by pods running using this ServiceAccount

(source: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#serviceaccount-v1-core)

Based on that it _might_ have an implication on Pods using the Service Account to access the Kube API.

I mentioned this here, because it wasn't an issue before `wait_for_service_account_token = true` was introduced and it can be fixed by setting `wait_for_service_account_token = false`.
