### ISSUE TITLE
Shrödinger's deprecation? default_secret_name

### ISSUE THREAD

**Issue by gwkunze** [hashicorp/terraform-provider-kubernetes#1878]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.1
Kubernetes provider version: 2.14.0
Kubernetes version: 1.19.12
```

When running a stack that utilizes the `default_secret_name` attribute of the `kubernetes_secret_account` resource you get a deprecation notice in the terraform output:

```
│ Warning: Deprecated attribute
│ 
│   on .terraform/modules/k8s/service-account.tf line 11, in data "kubernetes_secret" "secret":
│   11:     name      = kubernetes_service_account.secret.default_secret_name
│ 
│ The attribute "default_secret_name" is deprecated. Refer to the provider documentation for details.

```

Yet when you consult the documentation of the [kubernetes_service_account resource](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/service_account) there is nothing documented about any kind of deprecation. There is a notice about it potentially being `null` in newer Kubernetes versions which you can handle so shouldn't warrant a deprecation warning imho.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @gwkunze,

Thank you for opening this issue. I will update our documentation.

**Comment by lindhe** [comment]
I'm not using the `default_secret_name` attribute, yet I'm getting the same warning... :/

**Comment by carlosrmendes** [comment]
> I'm not using the `default_secret_name` attribute, yet I'm getting the same warning... :/

same here, this warning does not make any sense if you're not referring the `default_secret_name` attribute anywhere

**Comment by mogggggg** [comment]
Ditto, also getting this warning and I'm not using `default_secret_name` anywhere.

**Comment by lindhe** [comment]
@arybolovlev Why did you close this? There's clearly a bug here, not just documentation inconsistency...
