### ISSUE TITLE
Failed deployments and jobs do not rollback/retry

### ISSUE THREAD

**Issue by KDanisme** [hashicorp/terraform-provider-kubernetes#1884]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:
Kubernetes provider version: 2.11.0
Kubernetes version: 1.24.1
```

### Affected Resource(s)
- kubernetes_deployment_v1
- kubernetes_job_v1

### Steps to Reproduce
1. Create job or deployment that fails to run/rollout and fails on timeout
2. apply terraform
3. wait for timeout due to failure to deploy deployment/job
4. rerun terraform

### Expected Behavior
the deployment should have been reverted, or it should have somehow retried the deployment/job

### Actual Behavior
terraform thinks these resources exists (which is not wrong, the deployment exists, but it is failing)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi,

I would like to learn more about why you would expect Terraform to roll back deployments automatically. 
AFAIK, none of the common K8s tools do this by default (starting with kubectl).

**Comment by KDanisme** [comment]
Hi @alexsomesan, A rollback is not really necessary, i think there sude at least be a way to know that the deployment did not run successfully in the next apply. from an outside perspective, terrarorm fails, and rerunning it fixes the issue, but that simply hides the error.

**Comment by alexsomesan** [comment]
What would a better UX for you in this case?

**Comment by KDanisme** [comment]
Ideally, the state would be tied to the healthcheck of the deployment, so that the next run of terraform, it would check the deployment healthcheck to see if it succeeded.
