### ISSUE TITLE
Follow Go module convention in v2

### ISSUE THREAD

**Issue by XieGuochao** [hashicorp/terraform-provider-kubernetes#1888]
## Question

I would like to import this repository as a Go Module. However, in [pkg.go.dev](https://pkg.go.dev/github.com/hashicorp/terraform-provider-kubernetes), it is only sync to v1.13.4. The issue is that from v2+, the Go module requires a v2 directory. Would anyone like to resolve this issue? Reference: https://go.dev/blog/v2-go-modules

**Comment by jrhouston** [comment]
Hey @XieGuochao thanks for opening this. We don't really maintain this project to be used as a dependency, just as a plugin for Terraform. Could you share what your use-case is for using the project as a Go module?

**Comment by jan4984** [comment]
will fork and `replace` in go.mod work?

**Comment by XieGuochao** [comment]
> Hey @XieGuochao thanks for opening this. We don't really maintain this project to be used as a dependency, just as a plugin for Terraform. Could you share what your use-case is for using the project as a Go module?

I am trying some experiments to wrap the Provider. Since it's still an experiment and may fail, I can do a local fork and `replace` for now.

**Comment by XieGuochao** [comment]
> will fork and `replace` in go.mod work?

Indeed it works :)
