### ISSUE TITLE
kubernetes_manifest - Error: Failed to determine GroupVersionResource for manifest - cannot select exact GV from REST mapper

### ISSUE THREAD

**Issue by MrCoffey** [hashicorp/terraform-provider-kubernetes#1894]
```
terraform --version
Terraform v1.2.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.5.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)
`kubernetes_manifest`

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "mwaa" {
  metadata {
    annotations = {
      name = "mwaa"
    }
    name = "mwaa"
  }
}

resource "kubernetes_manifest" "mwaa_role" {

  manifest = {
    "apiVersion" = "rbac.authorization.k8s.io/v1"
    "kind"       = "Role"
    "metadata" = {
      "name"      = "mwaa-role"
      "namespace" = "mwaa"
    }
    "rules" = [
      {
        "apiGroups" = [
          "",
          "apps",
          "batch",
          "extensions",
        ]
        "resources" = [
          "jobs",
          "pods",
          "pods/attach",
          "pods/exec",
          "pods/log",
          "pods/portforward",
          "secrets",
          "services",
        ]
        "verbs" = [
          "create",
          "delete",
          "describe",
          "get",
          "list",
          "patch",
          "update",
        ]
      },
    ]
  }

  depends_on = [
    kubernetes_namespace.mwaa
  ]
}
```

### Debug Output
```hcl
TF_LOG=TRACE

[ERROR] vertex "kubernetes_manifest.mwaa_role_binding" error: Failed to determine GroupVersionResource for manifest
[TRACE] vertex "kubernetes_manifest.mwaa_role_binding": visit complete, with errors
[DEBUG] provider.terraform-provider-kubernetes-alpha_v0.5.0_x5:     "get"
[ERROR] vertex "kubernetes_manifest.mwaa_role (expand)" error: Failed to determine GroupVersionResource for manifest
[TRACE] vertex "kubernetes_manifest.mwaa_role_binding (expand)": dynamic subgraph encountered errors: Failed to determine GroupVersionResource for manifest
[TRACE] vertex "kubernetes_manifest.mwaa_role (expand)": visit complete, with errors
[ERROR] vertex "kubernetes_manifest.mwaa_role_binding (expand)" error: Failed to determine GroupVersionResource for manifest
[DEBUG] provider.terraform-provider-kubernetes-alpha_v0.5.0_x5:    ]
[TRACE] vertex "kubernetes_manifest.mwaa_role_binding (expand)": visit complete, with errors
```

### Steps to Reproduce

1. `terraform apply` -->

### Expected Behavior
Kubernetes object should be created.

### Actual Behavior
Provider fails with the following error:

```
│ Error: Failed to determine GroupVersionResource for manifest
│ 
│   with kubernetes_manifest.mwaa_role_binding,
│   on main.tf line 77, in resource "kubernetes_manifest" "mwaa_role_binding":
│   77: resource "kubernetes_manifest" "mwaa_role_binding" {
│ 
│ cannot select exact GV from REST mapper
```

Api versions are available.

```hcl
kubectl get apiservices  | grep authorization

v1.authorization.k8s.io                Local     True        2d2h
v1.rbac.authorization.k8s.io           Local     True        2d2h
```

### References

- GH-1583

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue, could you explain why k8s alpha is present in the provider list? Could you also attempt this again with the latest version of the k8s provider.

**Comment by MrCoffey** [comment]
Hi, thanks for taking a look.

At that time we were using the two Kubernetes providers it looked like a duplication so we removed and used only kubernetes provider v2.3.2 instead of kubernetes-alpha.

Neither of them worked in the end, even after deleting the cache. We decided to replace `resource "kubernetes_manifest"` with `"resource "kubectl_manifest"` to resolve our issue.

**Comment by arybolovlev** [comment]
Hi @MrCoffey,

`v2.3.2` is quite old. Please try the latest version `v2.16.0`.

Thanks.

**Comment by Monachawla1712** [comment]
> Hi, thanks for taking a look.
> 
> At that time we were using the two Kubernetes providers it looked like a duplication so we removed and used only kubernetes provider v2.3.2 instead of kubernetes-alpha.
> 
> Neither of them worked in the end, even after deleting the cache. We decided to replace `resource "kubernetes_manifest"` with `"resource "kubectl_manifest"` to resolve our issue.

i want to know if you used kubectl_manifest resource, it properly worked or not ?
