### ISSUE TITLE
Timeout not accepted: Waiting for rollout to finish

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [hashicorp/terraform-provider-kubernetes#1896]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.2.9
Kubernetes provider version: v2.13.0
Kubernetes version: 1.23.12-gke.1600
```

### Affected Resource(s)

kubernetes_deployment_v1

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment_v1" "default" {
  ...
  spec {
    ...
    progress_deadline_seconds = 1200
  }
  timeouts {
    update = "20m"
  }
}

```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
It should wait 20 minutes for rollout to succeed.

### Actual Behavior
It timed out after 10 minutes.

```
kubernetes_deployment_v1.default: Still modifying... [id=foo, 10m0s elapsed]
╷
│ Error: Waiting for rollout to finish: 2 out of 4 new replicas have been updated...
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue, could you provide us with the debug log from running `TF_LOG=debug`
