### ISSUE TITLE
Volumes are not being destroyed

### ISSUE THREAD

**Issue by ohadzer** [hashicorp/terraform-provider-kubernetes#1897]
Terraform version: 1.2.4
Kubernetes provider version: 4.41.0
Kubernetes version: 1.23.8-gke.1900

Hi,
I cannot make terraform remove my volume mount from a deployment.
When running the TF code from scratch the deployment is done without the volume, when running the upgrade I can see TF is recognize the volume in the deployment and mark it as "destroy" but the volume is not being destroyed. When running the TF code again I'm getting "No changes. Your infrastructure matches the configuration"   

Expected behaviour for terraform apply:
terraform removes the volumes

Actual behaviour:
terraform says nothing to change

Doing the same with kubectl works as expected.

### References
https://github.com/hashicorp/terraform-provider-kubernetes/issues/870

**Comment by BBBmau** [comment]
Hello, can you please reopen this issue following the issue template?
