### ISSUE TITLE
AWS eks kubernetes_config_map method failing in 2.15.0 

### ISSUE THREAD

**Issue by shilpagupta-axtria** [hashicorp/terraform-provider-kubernetes#1900]
provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks_cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth.token

}

resource "kubernetes_config_map" "aws-auth-configmap" {

  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }
}

kubernetes_config_map.aws-auth-configmap: Creating...
╷
│ Error: Post "https://<<OPENID>>.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF
│
│   with kubernetes_config_map.aws-auth-configmap,
│   on MAIN.tf line 202, in resource "kubernetes_config_map" "aws-auth-configmap":
│  202: resource "kubernetes_config_map" "aws-auth-configmap" {

**Comment by shilpagupta-axtria** [comment]
Any update? Its blocker

**Comment by BBBmau** [comment]
Hello, can you please reopen this issue following the issue template?
