### ISSUE TITLE
AWS eks kubernetes_config_map method failing in 2.15.0 

### ISSUE THREAD

**Issue by shilpagupta-axtria** [hashicorp/terraform-provider-kubernetes#1901]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:1.2.1
Kubernetes provider version:2.15.0
Kubernetes version:1.23
```

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks_cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth.token

}
```

### Debug Output

I'm not comfortable sharing this publicly since I'm not sure what (if any) sensitive info it has in it. Can provide it privately on request.

### Panic Output

╷
│ Error: Post "https://XXXX.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF
│
│ with kubernetes_config_map.aws-auth-configmap,
│ on MAIN.tf line 202, in resource "kubernetes_config_map" "aws-auth-configmap":
│ 202: resource "kubernetes_config_map" "aws-auth-configmap" {

### Steps to Reproduce

terraform apply

### Expected Behavior
What should have happened?
Should work... EKS cluster Infra created by the terraform should able to give RBAC permission to other users/roles using configmap

### Actual Behavior
What actually happened?
EKS cluster Infra created by the terraform is not able to give RBAC permission to other users/roles using configmap-->
kubernetes_config_map.aws-auth-configmap: Creating...
╷
│ Error: Post "https://857F43E63E69E8AA04D7C9897904440F.yl4.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF
│
│   with kubernetes_config_map.aws-auth-configmap,
│   on MAIN.tf line 202, in resource "kubernetes_config_map" "aws-auth-configmap":
│  202: resource "kubernetes_config_map" "aws-auth-configmap" {

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by shilpagupta-axtria** [comment]
Any update?

**Comment by shilpagupta-axtria** [comment]
provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

**Comment by arybolovlev** [comment]
Hi @shilpagupta-axtria,

Please share the configuration of `kubernetes_config_map.aws-auth-configmap` that is failing so we can try to reproduce it. Without this information it not possible to say what might go wrong here.

Thank you.

**Comment by shilpagupta-axtria** [comment]
@arybolovlev -
resource "kubernetes_config_map" "aws-auth-configmap" {

  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }
}

**Comment by arybolovlev** [comment]
I couldn't reproduce this issue.

Here is the configuration I am applying to a brand new EKS cluster:

```hcl
variable "cluster_name" {
    default = "test-cluster-fEgvh5aQ"
}
data "aws_eks_cluster" "eks_cluster" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "cluster_auth" {
  name = var.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.eks_cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks_cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster_auth.token

}

resource "kubernetes_config_map" "aws-auth-configmap" {
  metadata {
    name      = "aws-auth"
    namespace = "kube-system"
  }
}
```

It either creates the CM with no issues or reports that CM already exists(it looks like it gets automatically created once I add a new node group).
The CM `aws-auth` has [special meaning](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) for EKS and I assume the issue you observed might be related to permissions.

I would advise validating whether you can create any other resources in this cluster, like a pod or a new namespace, as well as a config map, but not in the system namespace(create a new NS and then a new CM in it).

As of now, I don't see any provider related issues.

Thanks.

**Comment by shilpagupta-axtria** [comment]
Can we discuss on call?

**Comment by shilpagupta-axtria** [comment]
My response-

It either creates the CM with no issues or reports that CM already exists(it looks like it gets automatically created once I add a new node group). - **_How can I check if CM already exists in TF? also then how can I add roles/users in the existing one? Also NG code is not present_**

The CM aws-auth has [special meaning](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) for EKS and I assume the issue you observed might be related to permissions.- **_If EKS cluster is created to the user used by TF, then there should not permission issue for same user._**

I would advise validating whether you can create any other resources in this cluster, like a pod or a new namespace, as well as a config map, but not in the system namespace(create a new NS and then a new CM in it). - **_Not able to create NS. getting error com/api/v1/namespaces": EOF_**

**_[ERROR] provider.terraform-provider-kubernetes_v2.14.0_x5: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="Post "https://XXX.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF" tf_proto_version=5.3 tf_req_id=0f3d79be-136a-9259-f228-3de452a663b9 tf_resource_type=kubernetes_config_map tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto tf_provider_addr=registry.terraform.io/hashicorp/kubernetes timestamp=2022-11-21T19:57:13.572+0530
2022-11-21T19:57:13.577+0530 [ERROR] vertex "kubernetes_config_map.aws-auth-configmap" error: Post "https://87EC0691B40DAC4C134B788F37D33C1D.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF_**

**Comment by shilpagupta-axtria** [comment]
@arybolovlev 
My response-

It either creates the CM with no issues or reports that CM already exists(it looks like it gets automatically created once I add a new node group). - **_How can I check if CM already exists in TF? also then how can I add roles/users in the existing one? Also NG code is not present_**

The CM aws-auth has [special meaning](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) for EKS and I assume the issue you observed might be related to permissions.- **_If EKS cluster is created to the user used by TF, then there should not permission issue for same user._**

I would advise validating whether you can create any other resources in this cluster, like a pod or a new namespace, as well as a config map, but not in the system namespace(create a new NS and then a new CM in it). - ****_Not able to create NS. getting error com/api/v1/namespaces": EOF_**

**_[ERROR] provider.terraform-provider-kubernetes_v2.14.0_x5: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="Post "https://xxx.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF" tf_proto_version=5.3 tf_req_id=0f3d79be-136a-9259-f228-3de452a663b9 tf_resource_type=kubernetes_config_map tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto tf_provider_addr=registry.terraform.io/hashicorp/kubernetes timestamp=2022-11-21T19:57:13.572+0530
2022-11-21T19:57:13.577+0530 [ERROR] vertex "kubernetes_config_map.aws-auth-configmap" error: Post "https://87ec0691b40dac4c134b788f37d33c1d.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps": EOF**_**

**Comment by arybolovlev** [comment]
If you are not able to create any resources in your cluster, then it is definitely permissions or configurations that you pass to the provider. A similar issue was raised a while ago: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1155

Please read provider documentation to better understand configuration options: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/getting-started

If any on-call assistance is required, please reach out HashiCorp support team. This issue tracker is for provider-related issues.

**Comment by shilpagupta-axtria** [comment]
@arybolovlev  - not mentioned what permissions or config issues can be ?

**Comment by shilpagupta-axtria** [comment]
Any help?
