### ISSUE TITLE
Warning about `default_secret_name` deprecation

### ISSUE THREAD

**Issue by carlosrmendes** [hashicorp/terraform-provider-kubernetes#1905]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v1.3.4
Kubernetes provider version: v2.15.0
Kubernetes version: v1.24.7
```

Every time I run terraform I'm getting a warning about `default_secret_name` deprecation. The terraform module only contains one kubernetes service account and that attribute is not being referenced anywhere, so this warning makes any sense and should only be displayed if the `default_secret_name` attribute is used.

Warning message:
```
│ Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.0 and above
│
│ Starting from version 1.24.0 Kubernetes does not automatically generate a token for service accounts, in this case, "default_secret_name" will be empty


Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

I don't want to be warned about some attribute that I'm not using/referencing.

### References
- GH-1878

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @carlosrmendes,

Thank you for raising this question. There is no mechanism that we can use to show this warning message only in the case you refer to the attribute somewhere in your code. Terraform prints out all warnings coming from the provider.

We made this message intentionally for the users who are not aware of the recent changes in the Kubernetes API and use the `default_secret_name` attribute in their code.

The warning message will stay with the provider for a few releases until we fully remove support for the attribute `default_secret_name`.

Thank you.

**Comment by carlosrmendes** [comment]
But showing warnings on a very clean, newly and perfectly created terraform module, using every last new features, configuration, providers versions and attributes is a little bit weird. Still doesn't make sense to me, warnings are to **warn** the user of something that he may be using improperly or something that he is using that may become deprecated.
