### ISSUE TITLE
kubernetes_cron_job annotations are not applied at job_template level

### ISSUE THREAD

**Issue by i2dcarrasco** [hashicorp/terraform-provider-kubernetes#1910]
Hello, I don't know if this is made intentionally, but the annotations added at job_template level are not applied correctly.

When applied, they just are not updated and then it always tries to apply the annotations again at every run. I have noticed that the annotations added at kubernetes_cron_job.metadata level are also applied to kubernetes_cron_job.spec.job_template.metadata level, but if not added there in the configuration tf, it tries to remove it at every run. Is like they are linked in any way in one side but separated in the other side.

Those annotations can be added manually to the kubernetes_cron_job.spec.job_template.metadata level using kubectl without any kind of problem and even without have to add it to the main metadata level. The problem is that are ignored, so even adding it manually using kubectl doesn't avoid the problem.

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.5
Kubernetes provider version: v2.16.0
Kubernetes version: 1.22.12-gke.2300
```

### Affected Resource(s)
- kubernetes_cron_job

### Terraform Configuration Files
```hcl
resource "kubernetes_cron_job" "cronjob" {
  for_each = local.cronjobs
  metadata {
    name      = "cronjob-${replace(each.key, "_", "-")}"
    namespace = "example"
    labels = {
      app = "dbbackup-cronjob-${each.key}"
    }
  }

  spec {
    concurrency_policy            = "Forbid"
    schedule                      = "0 * * * *"
    starting_deadline_seconds     = 60
    successful_jobs_history_limit = 3
    failed_jobs_history_limit     = 5

    job_template {
      metadata {
        annotations = {
          "cluster-autoscaler.kubernetes.io/safe-to-evict" = "false"
          "controller.kubernetes.io/pod-deletion-cost" = 10000
        }
      }
      spec {
        backoff_limit              = 5
        ttl_seconds_after_finished = 20

        template {
          metadata {
            labels = {
              app = "cronjob-${each.key}"
            }
          }

          spec {
            automount_service_account_token = false
            restart_policy                  = "Never"

            container {
              image = "image:latest"
              name  = "${replace(each.key, "_", "-")}"

              image_pull_policy = "Always"
              command           = ["/bin/bash", "-c", "/tools/entrypoint.sh ; echo \"Waiting for logs to be written\" && sleep 10"]
          }
        }
      }
    }
  }
}
```

### Steps to Reproduce
1. Configure a cronjob with the above configuration
2. `terraform apply`
3. Check with kubectl that the annotations were not added
4. Apply again and it will tell you that changes were detected

### Expected Behavior
Apply the annotations at job_template level

### Actual Behavior
The annotations are not applied and then it says that will be added every time. When I add it manually, are ignored and it always say that they must be added.

### Important Factoids
Running in a GKE cluster

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @i2dcarrasco,

Thank you for reporting this issue. That happens because we are cutting out "internal" Kubernetes annotations. Basically, almost everything that ends with `kubernetes.io` with some exceptions. Here is the [reference](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/structures.go#L185) to our code.

It looks like we need to change logic and cut metadata from objects, but not from templates. We are going to keep this issue open til we address the issue.

Thank you!
