### ISSUE TITLE
secrets not found when creating service-account-token secret

### ISSUE THREAD

**Issue by shubb30** [hashicorp/terraform-provider-kubernetes#1943]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.3.6
Kubernetes provider version: 2.16.1
Kubernetes version: 1.21.13
```

### Affected Resource(s)
- kubernetes_secret
- kubernetes_service_account

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "token" {
  metadata {
    annotations = {
      "kubernetes.io/service-account.name"      = local.k8s_sa_name
      "kubernetes.io/service-account.namespace" = var.namespace
    }
    namespace     = var.namespace
    generate_name = "${local.k8s_sa_name}-token-"
  }
  type                           = "kubernetes.io/service-account-token"
  wait_for_service_account_token = true
}

resource "kubernetes_service_account" "k8s_sa" {
  metadata {
    name      = local.k8s_sa_name
    namespace = var.namespace
  }
  secret {
    name = kubernetes_secret.token.metadata[0].name
  }
  depends_on = [kubernetes_secret.token]
}
```

### Output
```
Error: secrets "my-workload-token-h2dr7" not found
 
   with module.my_workload.module.vault_init.module.service_account.kubernetes_secret.token,
   on .terraform/modules/my_workload.vault_init.service_account/main.tf line 15, in resource "kubernetes_secret" "token":
   15: resource "kubernetes_secret" "token" {
```

### Steps to Reproduce
1. `terraform apply` -->

### Expected Behavior
When viewing the secrets in Kubernetes, I can see that the secret is created, but the service account does not get created.
I expect that the token secret and the service account should be created.

### Actual Behavior
I get the above error, and then the token secrets are destroyed.

### References
I found 2 other issues, but they were resolved from configuration changes, that I already have in my hcl.
#1879 
#1714

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by asaphe** [comment]
Happens with Terraform 1.3.5 when using either `kubernetes_secret_v1` or `kubernetes_secret` and `type = "kubernetes.io/service-account-token"`

**Comment by arybolovlev** [comment]
Hi @shubb30,

This is expected behavior not only with the provider, but with Kubernetes itself. This is sort of a garbage collection. In your case, you create a token that refers to a service account that does not exist yet. In this case, the token won't be created, that is why you get not found error message when create a service account and refer to a secret what does not exist.

In order to fix that issue, you need to first created a service account and then create a token secret. The token will be automatically associated with the service account that is described in the annotations. It worth mentioning here that you don't need to to the token in your service account resource as a secret. When you specify your secret type as `kubernetes.io/service-account-token` it will be automatically associated with the corresponding service account as a token.

Here is an example:

```hcl
variable "namespace" {
  default = "default"
}

variable "service_account" {
  default = "1943"
}

resource "kubernetes_secret" "this" {
  metadata {
    annotations = {
      "kubernetes.io/service-account.name" = kubernetes_service_account.this.metadata.0.name
    }
    namespace     = var.namespace
    generate_name = "${kubernetes_service_account.this.metadata.0.name}-token-"
  }

  type                           = "kubernetes.io/service-account-token"
  wait_for_service_account_token = true
}

resource "kubernetes_service_account" "this" {
  metadata {
    name      = var.service_account
    namespace = var.namespace
  }
}
```

Result:
```console
$ kubectl get secret
NAME               TYPE                                  DATA   AGE
1943-token-85b64   kubernetes.io/service-account-token   3      21s

$ kubectl describe secret 1943-token-85b64
Name:         1943-token-85b64
Namespace:    default
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: 1943
              kubernetes.io/service-account.uid: 5837acf5-c9e3-4218-b4b6-f62234abc160

Type:  kubernetes.io/service-account-token
...

$ kubectl get serviceaccount 1943
NAME   SECRETS   AGE
1943   0         2m26s

$ kubectl describe serviceaccount 1943
Name:                1943
Namespace:           default
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              1943-token-85b64
Events:              <none>
```

I hope that helps.

Thanks.

**Comment by shubb30** [comment]
Thank you @arybolovlev, this works.

I do see that two service account token secrets are created, but that is because I am still on Kubernetes 1.21, where it creates the token by default.

I also see that the auto-generated one is the one that will be mountable, not the TF one, but I presume that one will go away/adjust when we upgrade to 1.24. 

```
 k describe sa test-service-account                                                                                                                        1 ↵
Name:                test-service-account
Namespace:           default
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   test-service-account-token-kjg8h   << auto-generated
Tokens:              test-service-account-token-8pprd   << terraform-generated
                     test-service-account-token-kjg8h
Events:              <none>
```

**Comment by arybolovlev** [comment]
You are welcome!

I honestly don't know what will happen with the auto-generated tokens once you upgrade your cluster. Theoretically, they will stay.

Here is some of my observation regarding this feature prior to version 1.24:
- once you create a new service account, Kubernetes will automatically generate a token for this account;
- you still can create your own token and attach it to the service account;
- if you delete the token, Kubernetes will check whether the service account has another token or not.
  - If no, it will be auto-generated again, in this case, the service account always has a token;
  - If so(you have created it yourself), a new one won't be auto-generated;
- there is no way to say which token was generated by a user and which one by Kubernetes(the name is not a reliable option here).

I will go ahead and close this issue.

Thank you!
