### ISSUE TITLE
kubernetes_manifest calculated fields doesn't allow for field to be recalculated even if specified

### ISSUE THREAD

**Issue by txomon** [hashicorp/terraform-provider-kubernetes#1945]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.3.4
Kubernetes provider version: v2.7.1
Kubernetes version: 1.21
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "test" {
  field_manager {
    force_conflicts = true
  }
  computed_fields = [
    "spec.template.metadata.annotations",
    "metadata.annotations",
  ]
    manifest = {
    "apiVersion" = "serving.knative.dev/v1"
    "kind"       = "Service"
    "metadata" = {
      "name"      = "test"
      "namespace" = "default"
    }
    "spec" = {
      "template" = {
        "metadata" = {
          "annotations" = {
}}}}}
```

### Steps to Reproduce

If the controller of the resource generates a new value, kubernetes_manifest should just accept whatever comes there as new truth instead of complaining.

### Expected Behavior
What should have happened?

The

### Actual Behavior
What actually happened?

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to kubernetes_manifest.test, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value:
│ .object.metadata.annotations["serving.knative.dev/lastModifier"]: was cty.StringVal("user@gcp-service-account."), but now cty.StringVal("1111111111111111111111111").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
```

### Important Factoids

Using kubernetes_template for knative services in this case

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @txomon,

I am not able to reproduce this issue. Could you please share more information?

These will be helpful:
- `kubectl get ksvc` output as soon as you have created a new service
- `object.value.metadata.annotations` part of the Terraform state file as soon as you have created a new service
- Terraform debug output during the second apply

Before that, I would strongly advise you to try out the latest provider version, since the one you use is quite old.

Thank you.

**Comment by txomon** [comment]
Hello @arybolovlev,

Thanks for your response.

1. I can't upgrade to the latest version because of #1893 which makes the kubernetes provider incapable of not recreating the manifest every apply.
2. I had to upgrade the clusters I was working on and the kubernetes_manifest version because it failed with kubernetes 1.24, so I am currently upgrading to the latest provider plugin and trying to fix 1893 by myself given that no one seems to be looking at it.

I will try to deal with this issue at the same time and report back.

Sorry for the radio silence!

**Comment by txomon** [comment]
Hello @arybolovlev,

I have done all the steps and minified our service to reproduce it. The issue happens when using different users to apply than to update manually the service.

See the following gist for reproduction and logs https://gist.github.com/txomon/73e647b7567dda5de9e0d3881bfe36c1
