### ISSUE TITLE
Way to access kubeconfig used by provider

### ISSUE THREAD

**Issue by salzig** [hashicorp/terraform-provider-kubernetes#1948]
### Description

It would be helpful to have access to the config used when configured using `config_path`.  E.g. in situations where you need to pass the API uri as part of a Kubeconfig to gitlab. 

Would it be possible to expose those information via the provider object? Or would it be better to introduce a kubeconfig data object like so:
```hcl
data "kubernetes_config" "example_k8s_local" {
  config_path    = "~/.kube/config"
  config_context = "example.k8s.local"
}
provider "kubernetes" {
  host = data.kubernetes_config.example_k8s_local.host

  client_certificate     = data.kubernetes_config.example_k8s_local.client_cert
  client_key             = data.kubernetes_config.example_k8s_local.client_key
  cluster_ca_certificate = data.kubernetes_config.example_k8s_local.ca_cert
}
```

### Potential Terraform Configuration

```hcl
provider "kubernetes" {
  config_path    = "~/.kube/config"
  config_context = "example.k8s.local"
  alias = "example_k8s_local"
}

resource "kubernetes_secret" "token" {
  metadata {
    name = var.gitlab_project.name
    namespace = var.kubernetes_namespace.id
    annotations = {
      "kubernetes.io/service-account.name" = var.gitlab_project.name
    }
  }
  type = "kubernetes.io/service-account-token"
}

data "kubernetes_secret" "token" {
  metadata {
    name      = var.gitlab_project.name
    namespace = var.kubernetes_namespace.id
  }

  depends_on = [
    kubernetes_secret.token
  ]
}

resource "kubernetes_role_binding" "role_binding" {
  metadata {
    name      = var.gitlab_project.name
    namespace = var.kubernetes_namespace.id
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = "edit"
  }
  subject {
    kind      = "ServiceAccount"
    name      = var.gitlab_project.name
    namespace = var.kubernetes_namespace.id
  }
}

# here we need the Kubernetes API uri.
resource "gitlab_project_variable" "variable" {
  project   = var.gitlab_project.id
  key       = "KUBECONFIG_EXAMPLE"
  protected = false
  variable_type = "file"
  value     = <<EOT
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: ${base64encode(nonsensitive(lookup(data.kubernetes_secret.token.data, "ca.crt")))}
    server: ${kubernetes.example_k8s_local.host} # via data? on provider? 
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: ${var.kubernetes_namespace.id}
    user: default-user
current-context: default-context
users:
- name: default-user
  user:
    token: ${nonsensitive(data.kubernetes_secret.token.data.token)}
EOT
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @salzig,

Thank you for opening this issue. At this moment we do not have any plans to implement additional resources to work explicitly with the Kubernetes configuration file.

However, since the configuration file is a YAML file, I would advise you to look at `yamldecode` [Terraform function](https://developer.hashicorp.com/terraform/language/functions/yamldecode) to parse it and fetch all the necessary information you need.

I will go ahead and close this issue.

Thank you.

**Comment by salzig** [comment]
I do it that way right now, but it is still a pain in the butt. 

ps: i don't get the point of closing Issues, when they will be auto locked after a given time. That will result in the same issues created again and again.
