### ISSUE TITLE
What's the difference between kubernetes_secret_v1 and kubernetes_secret

### ISSUE THREAD

**Issue by AbdullahAki** [hashicorp/terraform-provider-kubernetes#1956]
## Question

Hi, I couldn't see any explanation for the difference between kubernetes_secret_v1 and kubernetes_secret. What are the differences between them? When I looked at the source code I didn't see any difference. Why are there 2 different resources?

**Comment by arybolovlev** [comment]
Hi @AbdullahAki,

These 2 resources are equal, in the end, they call the same function, [code reference](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/provider.go#LL252-L253C72).

You can find more information about the motivation behind making resources versioned [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources). I would recommend you use versioned resources whenever possible.

I hope that helps.

Thank you.
