### ISSUE TITLE
`kubernetes_namespace` throws error when there is a forward slash in a labels key

### ISSUE THREAD

**Issue by sgutwein** [hashicorp/terraform-provider-kubernetes#1960]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.3.7
Kubernetes provider version: 2.16.1
Kubernetes version: 1.24.6
```

### Affected Resource(s)
- kubernetes_namespace

### Steps to Reproduce

1. Run `terraform apply` on this
```
resource "kubernetes_namespace" "namespaces" {
  provider = kubernetes
  for_each = var.namespaces
  metadata {
    name = each.key

    labels = {
      istio-injection           = "enabled"
      toolkit.fluxcd.io/tenant  = "test"
    }
  }
}
```

### Expected Behavior
The namespace should be created with the labels.

### Actual Behavior
```
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 135, in resource "kubernetes_namespace" "namespaces":
│  135:       toolkit.fluxcd.io/tenant = "test"
│ 
│ A managed resource "toolkit" "fluxcd" has not been declared in the root
│ module.
```

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue @sgutwein. Can you attempt the same config but instead replace the affected label with `"toolkit.fluxcd.io/tenant"`, label keys that have slashes are possible when including it in quotation marks.
