### ISSUE TITLE
Provider seems to ignore aliases passed to a module and reverts back to default

### ISSUE THREAD

**Issue by max-weaver-cts** [hashicorp/terraform-provider-kubernetes#1970]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:  1.3.7
Kubernetes provider version: 2.17.0
Kubernetes version: 1.24.8-gke.2000
```

### Affected Resource(s)
I've created a module to deploy some core kubernetes resources into a GKE cluster. This module accepts two alias configurations in order to manage two gke clusters, however when I pass through the alias's to the module the kubernetes provider ignores them and defaults to localhost.

I am using this same technique with other providers and it works as expected

### Terraform Configuration Files
`./module/main.tf`
```hcl
resource "kubernetes_service_account" "argocd" {
  provider = kubernetes.source
  metadata {
    name      = var.source_sa_name
    namespace = var.source_namespace
  }
}

resource "kubernetes_service_account" "argocd" {
  provider = kubernetes.destination
  metadata {
    name      = var.source_sa_name
    namespace = var.source_namespace
  }
}
```

`./module/versions.tf`
```hcl
terraform {
  required_version = ">= 1.2.0"
  required_providers {
    google = {
      version = ">= 3.10.0, < 5.0.0"
    }
    kubernetes = {
      source                = "hashicorp/kubernetes"
      version               = "2.17.0"
      configuration_aliases = [kubernetes.source, kubernetes.destination]
    }
  }
}
```

`./main.tf`
```hcl
module "argocd_core" {
  source = "./module"
  providers = {
    kubernetes.destination = kubernetes.dest
    kubernetes.source = kubernetes.src
  }
  
   # List of input vars truncated
}
```

`./versions.tf`
```hcl
terraform {
  required_version = ">= 1.3.7"
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
    }
  }
}

data "google_client_config" "provider" {}

data "google_container_cluster" "src_cluster" {}

data "google_container_cluster" "dest_cluster" {}

provider "kubernetes" {
  alias = "src"
  host  = "https://${data.google_container_cluster.src_cluster.endpoint}"
  token = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.src_cluster.master_auth[0].cluster_ca_certificate,
  )
}

provider "kubernetes" {
  alias = "dest"
  host  = "https://${data.google_container_cluster.dest_cluster.endpoint}"
  token = data.google_client_config.provider.access_token
  cluster_ca_certificate = base64decode(
    data.google_container_cluster.argocd_cluster.master_auth[0].cluster_ca_certificate,
  )
}
```

### Debug Output
I do not wish to paste any debug output for fear of inadvertently exposing customer data, instead I'll say that the following info/debug were within the debug logs: https://gist.github.com/max-weaver-cts/44ddb3ce2ed973d28358851b67e3fed1

### Panic Output
n/a

### Steps to Reproduce
1. Create a module that deploys Kubernetes resources and uses aliases within resources to deploy to different clusters
2. Use that module and provide aliased providers to the module's `providers` block
3. Run a `terraform init` and `terraform plan` as usual

### Expected Behavior
The module plans out the creation or modification of resources in the appropriate clusters using passed in alias'

### Actual Behavior
No alias is seen or passed into the module. Instead Terraform falls back on default, `localhost` settings for a kubernetes resource that has no provider config set:

```╷
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/serviceaccounts/foo": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│ 
╵
╷
│ Error: Get "http://localhost/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/foo": dial tcp 127.0.0.1:80: connect: connection refused
│ 
│ 
```

### Important Factoids
Running inside a devcontainer, but I've also tried inside a gitlab-ci pipeline that uses containers to run terraform, so architecture  or platform doesn't seem to be affecting this.

As I said at the top of this report we are using multi-aliases in modules elsewhere without issue. The only difference these are passing in google provider aliases as opposed to kubernetes.

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
It looks like you're not configuring the datasources for `dest_cluster` and `src_cluster` with the name of the actual clusters. This is a required argument, according to the docs: https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/container_cluster
Without it, the datasource cannot extract data from the cluster, including its API endpoint.

**Comment by max-weaver-cts** [comment]
thanks @alexsomesan that was actually me just omitting it in the example more than anything. It was definitely configured correctly in my actual code

**Comment by max-weaver-cts** [comment]
I believe I have "fixed" this issue by wiping out my state via a `terraform state rm ..` and re-importing resources. All I can assume is that within the existing state there were references to a provider alias that didn't exist - although I find this strange. This is obviously an issue with migrating existing state over to a module that I wasn't prepared for.

Leaving this comment here for posterity in case anyone else has the same issue.
