### ISSUE TITLE
Discussion on #1646: Why CRDs with preserve unknown fields forces recreation?

### ISSUE THREAD

**Issue by txomon** [hashicorp/terraform-provider-kubernetes#1974]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Kubernetes Provider version: main( c9182af92723d4b1c801a8018c244100ebdc122c )
Kubernetes version: 1.23 and 1.24
```

## Question

I have seen that the code does the assumption that just because a field has changed from a previous state and has the `x-kubernetes-preserve-unknown-fields` annotation in the CRD, the provider now forces replacement.

This introduces several bugs regarding re-creation, which overlap with another issue on imports not populating the manifests.

What is the reasoning behind this change? What logic is being followed to force recreation?

**Comment by alexsomesan** [comment]
Hi, please see my response on your PR for the explanation of why things are this way and cannot be changed.
