### ISSUE TITLE
Provider configuration not propagating to sub modules on refresh state

### ISSUE THREAD

**Issue by mballoni** [hashicorp/terraform-provider-kubernetes#1977]
Hi folks!
I'm separating this EKS cluster setup into a few different modules.
Currently we are using terraform-aws-eks-blueprint and I've managed to create it after configuring this provider as expected.

However after that it always fails to refresh state on subsequent executions.

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.2
Kubernetes provider version: v2.17.0
Kubernetes version: 1.24
```

### Affected Resource(s)
kubernetes_config_map

### Debug Output 
Thats the error I'm getting:
```
│ Error: Get "http://localhost/api/v1/namespaces/kube-system/configmaps/aws-auth": read tcp 127.0.0.1:48386->127.0.0.1:80: read: connection reset by peer - error from a previous attempt: read tcp 127.0.0.1:48374->127.0.0.1:80: read: connection reset by peer
│ 
│   with module.karpenter_cluster.module.eks.kubernetes_config_map.aws_auth[0],
│   on .terraform/modules/karpenter_cluster.eks/aws-auth-configmap.tf line 1, in resource "kubernetes_config_map" "aws_auth":
│    1: resource "kubernetes_config_map" "aws_auth" {

```

### Steps to Reproduce

I have the following folders setup:

root
--terraform
----main.tf
----modules
------eks
--------main.tf

On my main.tf at the root folder:
```
provider "kubernetes" {
  host                   = module.karpenter_cluster.eks_cluster_endpoint
  cluster_ca_certificate = base64decode(module.karpenter_cluster.eks_cluster_certificate_authority_data)
  token                  = data.aws_eks_cluster_auth.this_karpenter_cluster.token
  experiments {
    manifest_resource = true
  }
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = ["eks", "get-token", "--cluster-name", module.karpenter_cluster.cluster_name]
    command     = "aws"
  }
}

data "aws_eks_cluster_auth" "this_karpenter_cluster" {
  name = module.karpenter_cluster.eks_cluster_id
}

module "karpenter_cluster" {
  source                   = "./modules/eks"
  account                  = var.account
  application_id           = "cluster_c"
...
}
```

The main.tf at modules/eks:
```

module "eks" {
  source = "github.com/aws-ia/terraform-aws-eks-blueprints?ref=v4.21.0"

  cluster_name              = local.name
...
```

I already tried with tons of additional code, either by adding required_providers, different aliases, etc... none works.

It seems as if the original kubernetes provider configuration is not being used and/or being passed to submodules.

I also reported this here: https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1380 thinking it could be an issue with eks blue prints projec but facts are pointing to provider configuration propagation.

**Comment by arybolovlev** [comment]
Hi @mballoni,

That happens because Terraform initializes all providers in use at the very beginning of the plan/apply. It means that with your setup, the cluster is not up and running at the moment when Terraform passes configuration to the Kubernetes provider and thus it turns into "default" localhost mode. As of now, you need to separate your code in order to first create a cluster and then apply resources to it. This question seems to be asked quite frequently, and I think we will update our FAQ to cover this use case.

Thank you.

**Comment by mballoni** [comment]
Hi @arybolovlev !
Thank you for your response.

Thats whats troubling me, when I moved the cluster creation to the terraform main root file it worked as expected. What could explain this behaviour?

On a second thought I also keep thinking that the eks-terraform-blueprints may not be following these good practices given it will invoke some kubertes operations at the same cluster creation when creating node groups (it needs to change a ConfigMap).

Is this assumption corret?

Thank you!!

**Comment by arybolovlev** [comment]
Hi @mballoni,

I can speak on behalf of our provider only. We recommend separating Kubernetes cluster creation and configuration code into different modules and executing them separately, i.e. run `terraform apply` for each module. In this case, you will avoid the issue you have faced.

I will close this issue.

Thank you.
