### ISSUE TITLE
PVC in WairForConsumer state blocks deployment

### ISSUE THREAD

**Issue by kaffarell** [hashicorp/terraform-provider-kubernetes#1986]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.3.4
Kubernetes provider version: v2.15.0
Kubernetes version: v1.25.6
```

### Affected Resource(s)
- kubernetes_persistent_volume_claim
- kubernetes_deployment

### Terraform Configuration Files
```hcl
resource "kubernetes_persistent_volume_claim" "grafana-configuration" {
  metadata {
    name = "grafana-configuration"

    labels = {
      "io.kompose.service" = "grafana-configuration"
    }
  }

  spec {
    access_modes = ["ReadWriteOnce"]
    storage_class_name = "local-path"
    resources {
      requests = {
        storage = "1Gi"
      }
    }
    volume_name = "grafana-configuration"
  }
}

resource "kubernetes_persistent_volume" "grafana-configuration" {
  metadata {
    name = "grafana-configuration"
  }
  spec {
    storage_class_name = "local-path"
    access_modes = ["ReadWriteOnce"]
    capacity = {
      storage = "1Gi"
    }
    node_affinity {
      required {
        node_selector_term {
          match_expressions {
            key = "node-role.kubernetes.io/master"
            operator = "In"
            values = ["true"]
          }
        }
      } 
    }
    persistent_volume_source {
      local {
        path = "/home/administrator/Metrics.Infrastructure/grafana/"
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim" "grafana-data" {
  metadata {
    name = "grafana-data"

    labels = {
      "io.kompose.service" = "grafana-data"
    }
  }

  spec {
    access_modes = ["ReadWriteOnce"]
    storage_class_name = "local-path"
    resources {
      requests = {
        storage = "5Gi"
      }
    }
  }
}

resource "kubernetes_deployment" "grafana" {
  metadata {
    name = "grafana"

    labels = {
      "io.kompose.service" = "grafana"
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        "io.kompose.service" = "grafana"
      }
    }

    template {
      metadata {
        labels = {
          "io.kompose.service" = "grafana"
        }
      }

      spec {
        volume {
          name = "grafana-configuration"
          persistent_volume_claim {
            claim_name = "grafana-configuration"
          }
        }

        volume {
          name = "grafana-data"

          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.grafana-data.metadata.0.name
          }
        }

        container {
          name  = "grafana"
          image = "grafana/grafana:9.2.4"

          port {
            container_port = 3000
          }

          volume_mount {
            name       = "grafana-configuration"
            mount_path = "/etc/grafana"
          }
          volume_mount {
            name       = "grafana-data"
            mount_path = "/var/lib/grafana"
          }
        }

        restart_policy = "Always"
      }
    }

    strategy {
      type = "Recreate"
    }
  }
}

```

### Steps to Reproduce
1. `terraform apply` 

### Expected Behavior
The apply should work

### Actual Behavior
The apply enters an infinite loop and times out.

If I execute terraform apply on this config file it enters an infinite loop and eventually times out. I am on k3s which has the local-path storage provier installed. It dynamically provisions a pv for a pvc (The grafana-configuration pvc works, the grafana-data pvc instead doesn't). The local-path storageclass provided by k3s has `VolumeBindingMode: WaitForConsumer`. 

What happens is that because of this piece in the deployment resource:
```
persistent_volume_claim {
  claim_name = kubernetes_persistent_volume_claim.grafana-data.metadata.0.name
}
```
terraform waits for the persistent volume (for the pvc) to be created before creating the deployment. The problem is that the pvc stays in the WaitForConsumer state and never creates a pv until a pod is scheduled. A pod though is never scheduled because the pv is missing.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @kaffarell,

Can you please provide more information regarding the issue you experience? I would suggest doing troubleshooting step by step to isolate where the issue is. For instance, for now, it looks like something is wrong with PV/PVC. Comment out everything but PV/PVC `garafana-configuration`. Once you make it work, move on and uncomment PV/PVC `garafana-data`. Once you make it work, uncomment deployment you have.

Another question here will be -- were you able to make it work with YAML manifests and `kubectl`?

As of now, it doesn't look like the provider issue.

Thanks.

**Comment by kaffarell** [comment]
Ah, it looked like my description in the issue got removed (maybe I didn't save it). However:
The problem is basically that the storage class that I use ([rancher local-path](https://github.com/rancher/local-path-provisioner), automatically provisioned by k3s) has `volumeBindingMode: WaitForConsumer`. This means that when I create the pvc, it waits for the first consumer (pod) to be scheduled before it automatically provides the pv. **BUT** as terraform detects the dependency between pod and pvc, it waits for the pvc to be in the "Ready" state (with the pv existing) although that is never happening, because the pv is never created (terraform never schedules the pod before the pvc is ready). This creates an infinite loop until `terraform apply` times out.

**Comment by arybolovlev** [comment]
Hi @kaffarell,

Thank you for the clarification. I have two questions here:

1. Can you please try to set `wait_until_bound` in your PVC resource to `false`? In this case, the provider will not wait till it is moved into the `Bound` state to mark the resource as created. More information [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/persistent_volume_claim#wait_until_bound).

2. Could please share `kubectl get ... -o yaml` outputs of the StorageClass, PV, and PVC when the issue is there? That will help me to understand if it can be addresses on the provider level.

Thanks.

**Comment by kaffarell** [comment]
Hey @arybolovlev, I was not aware of `wait_until_bound`, thanks. This fixed the issue.
