### ISSUE TITLE
Kubernetes Ingress for extensions and networking/v1

### ISSUE THREAD

**Issue by jdziat** [hashicorp/terraform-provider-kubernetes#1987]
### Description

I feel like the community has created a lot of modules or uses the `kubernetes_ingress` resource which is no longer suitable for newer kubernetes versions. However the schema and overall features don't diverge drastically and the resources automatically get translated to the newer version if you upgrade. It would be nice to have the `kubernetes_ingress` resource be capable of handling beta to networking/v1 upgrades. Otherwise you need to import all the translated resources and update any modules for compatibility. Then going forward if you want to explicitly define the resource version you can pick it based off of the versions you're using.

### Potential Terraform Configuration

```hcl
// Current extensions resource
resource "kubernetes_ingress" "example_route" {
  metadata {
    name        = var.name
    namespace   = var.namespace
    labels      = local.labels
    annotations = var.ingress_annotations
  }
  spec {
    dynamic "rule" {
      for_each = var.ingress_rules
      content {
        host = rule.value["host"]
        http {
          path {
            path = rule.value["path"]
            backend {
              service_name = rule.value["service_name"] == "" ? var.name : rule.value["service_name"]
              service_port = rule.value["service_port"] == "" ? "http" : rule.value["service_port"]
            }
          }
        }
      }
    }
  }
}

// ingress_v1 resource
resource "kubernetes_ingress_v1" "example_route" {
  metadata {
    name        = var.name
    namespace   = var.namespace
    labels      = local.labels
    annotations = var.ingress_annotations
  }
  spec {
    dynamic "rule" {
      for_each = var.ingress_rules
      content {
        host = rule.value["host"]
        http {
          path {
            path = rule.value["path"]
            backend {
              service {
                name = rule.value["service_name"] == "" ? var.name : rule.value["service_name"]
                port {
                  name = rule.value["service_port"] == "" ? "http" : rule.value["service_port"]
                }
              }
            }
          }
        }
      }
    }
  }
}

//Go Forward Common Interface
resource "kubernetes_ingress" "example_route" {
  metadata {
    name        = var.name
    namespace   = var.namespace
    labels      = local.labels
    annotations = var.ingress_annotations
  }
  spec {
    dynamic "rule" {
      for_each = var.ingress_rules
      content {
        host = rule.value["host"]
        http {
          path {
            path = rule.value["path"]
            backend {
              service_name = rule.value["service_name"] == "" ? var.name : rule.value["service_name"]
              service_port = rule.value["service_port"] == "" ? "http" : rule.value["service_port"]
            }
          }
        }
      }
    }
  }
}
// or
resource "kubernetes_ingress" "example_route" {
  metadata {
    name        = var.name
    namespace   = var.namespace
    labels      = local.labels
    annotations = var.ingress_annotations
  }
 spec {
    dynamic "rule" {
      for_each = var.ingress_rules
      content {
        host = rule.value["host"]
        http {
          path {
            path = rule.value["path"]
            backend {
              service {
                name = rule.value["service_name"] == "" ? var.name : rule.value["service_name"]
                port {
                  name = rule.value["service_port"] == "" ? "http" : rule.value["service_port"]
                }
              }
            }
          }
        }
      }
    }
  }
}



```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @jdziat,

`kubernetes_ingress` implements `extensions/v1beta1` and `kubernetes_ingress_v1` implements `networking.k8s.io/v1`, this separation was made intentionally. You should chose the one that works for your set up.

More information is [here](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources).

I will go ahead and close this issue.

Thank you.

**Comment by jdziat** [comment]
@arybolovlev I understand that it's more explicit. However having something named kubernetes_ingress and it in fact being kubernetes_ingress_beta_v1 isn't the most user friendly thing in the world. especially since kubernetes/helm already does the translation between versions and deprecations.
