### ISSUE TITLE
Irrelevant warning about default_secret_name

### ISSUE THREAD

**Issue by Indigenuity** [hashicorp/terraform-provider-kubernetes#1990]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.0
Kubernetes provider version: 2.17.0
Kubernetes version: 1.24
```

### Affected Resource(s)

- kubernetes_default_service_account

### Terraform Configuration Files
```hcl
resource "kubernetes_default_service_account" "default" {
  metadata {
    namespace   = "default"
  }
}
```

### Output
```
│ Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.0 and above
│ 
│   with kubernetes_default_service_account.default,
│   on root.tf line 59, in resource "kubernetes_default_service_account" "default":
│   59: resource "kubernetes_default_service_account" "default" {
│ 
│ Starting from version 1.24.0 Kubernetes does not automatically generate a token for service accounts, in this case,
│ "default_secret_name" will be empty
```
### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
No warnings

### Actual Behavior
Warning given about irrelevant feature.  There are no references to the default secret, and in fact the warning persists even when following the[ recommended pattern](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret_v1#example-usage-service-account-token) for dealing with the deprecation.

### References
[This ticket](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1905) is locked so I cannot vote with a 👍 .  That same ticket mentions the proposed solution:
> The warning message will stay with the provider for a few releases

It's been a few releases since 2.13.  Can we please remove this warning?  It seemed an inappropriate warning in the first place, so prolonging its stay is even less desirable.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by angelcharge** [comment]
This warning is for every service account creation, it is confusing and wrong because everything is as expected, starting from kubernetes 1.24 there is no secrets for SA needed anymore, SA token is mounted to pods over projected volume by kubelet.

**Comment by BBBmau** [comment]
Hello, thank you for opening this issue @Indigenuity. As of right now we won't be removing the warning message since most cloud providers are still supporting versions older than 1.24.

Once versions that are older than 1.24 are not supported anymore, we will then remove this warning message.

**Comment by kbolino** [comment]
@BBBmau there needs to be a way to suppress this warning! If it doesn't apply to me, I shouldn't see it. Always showing a warning that is not relevant causes headaches and encourages people to ignore warnings in general.

Even if this means adding an argument "suppress_default_secret_warning = true", it would be better than nothing.

**Comment by Indigenuity** [comment]
> encourages people to ignore warnings in general.

I personally have missed another warning due to the need to ignore this warning every time terraform runs

**Comment by otherguy** [comment]
I'm adding my voice for an option like `suppress_default_secret_warning = true` to disable this warning.

**Comment by elongl** [comment]
Would upgrading my cluster to v1.25 or v1.26 stop this warning?

**Comment by otherguy** [comment]
@elongl no. My clusters are all 1.26.

**Comment by sticksen** [comment]
It´s OpenSource, forking might be a workable way to show our needs.

**Comment by devguydavid** [comment]
"Warning" implies that there is something wrong, which it sounds like in many cases there isn't. Maybe this needs to be an "Info" level message.

**Comment by gambl3** [comment]
This "Warning" is very frustrating. I'm glad I found this post because this issue has been driving me nuts for weeks.

**Comment by Indigenuity** [comment]
Thanks @BBBmau for the time and attention you gave this.  It'll be nice to use this next update.
