### ISSUE TITLE
Error: invalid version, 1.16 is no longer supported, supported values: 1.21, 1.22, 1.23, 1.24

### ISSUE THREAD

**Issue by joykellandra** [hashicorp/terraform-provider-kubernetes#1998]
- name: Install Terraform
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.1.7

     - name: Set up EKS on Fargate Environment
       uses: aws-actions/amazon-eks-fargate@v0.1.1
       with:
         terraform_version: 1.1.7
         working-directory: ./fargate-deployment/terraform/
         tf_actions_command: apply

When running my workflow, it stops at this stage returning the Error: invalid version, 1.16 is no longer supported, supported values: 1.21, 1.22, 1.23, 1.24

**Comment by alexsomesan** [comment]
Please fill out the issue according to the template and include all the requested versions for your environment.
