### ISSUE TITLE
Create additional API tokens not working for Kubernetes1.24

### ISSUE THREAD

**Issue by ademar59** [hashicorp/terraform-provider-kubernetes#2001]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.6
Kubernetes provider version: 2.17.0
Kubernetes version: 1.24.6
```

### Affected Resource(s)

- kubernetes_secret

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "gitlab" {
  metadata {
    name      = "gitlab"
    namespace = var.namespace
    annotations = {
      "kubernetes.io/service-account.name" = "gitlab"
    }
  }
}

resource "kubernetes_service_account" "gitlab" {
  metadata {
    name      = "gitlab"
    namespace = var.namespace
  }
  automount_service_account_token = false

  depends_on = [kubernetes_namespace.namespace]
}
```

### Expected Behavior
In kubernetes 1.24, secret are not created anymore for service account.

According to the [kubernetes documentation](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token), we can create secret with permanent token.

Using terraform ressource, secret are created but without any token.

Using kubectl apply with manifests, secret with token are created.

### Actual Behavior
No token in secret.

### References
https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Hello! Thank you for opening this issue @ademar59, I was able to reproduce this issue and you are right, with the current config file no token is produced. However if we set the `type` attribute to `kubernetes.io/service-account-token` we then get a [token](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret_v1#example-usage).

**Comment by streamnsight** [comment]
your secret needs the 
```
type = "kubernetes.io/service-account-token"
```
