### ISSUE TITLE
Same name on different resource types: Error: Cannot create resource that already exists

### ISSUE THREAD

**Issue by hterik** [hashicorp/terraform-provider-kubernetes#2003]
### Terraform Version, Provider Version and Kubernetes Version
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.18.0

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "configmap_alertmanager" {
  manifest = {
    "apiVersion" = "v1"
    "kind"       = "ConfigMap"
    "metadata" = {
      "name"      = "alertmanager"
      "namespace" = "services"
    }
    "data" = {
      ...
    }
  }
}

resource "kubernetes_manifest" "deployment_alertmanager" {
  manifest = {
    "apiVersion" = "apps/v1"
    "kind"       = "Deployment"
    "metadata" = {
      "name"      = "alertmanager"
      "namespace" = "services"
    }
    "spec" = {
      ...
```

### Steps to Reproduce
1. `terraform apply` -->

### Expected Behavior
Kubernetes manifests are deployed 

### Actual Behavior
```
│ Error: Cannot create resource that already exists
│ 
│   with kubernetes_manifest.configmap_alertmanager,
│   on alertmanager.tf line 29, in resource "kubernetes_manifest" "configmap_alertmanager":
│   29: resource "kubernetes_manifest" "configmap_alertmanager" {
│ 
│ resource "services/alertmanager" already exists
╵
│ Error: Cannot create resource that already exists
│ 
│   with kubernetes_manifest.deployment_alertmanager,
│   on alertmanager.tf line 43, in resource "kubernetes_manifest" "deployment_alertmanager":
│   43: resource "kubernetes_manifest" "deployment_alertmanager" {
│ 
│ resource "services/alertmanager" already exists
```

### Important Factoids
These manifests have worked before, and also work in a different environment, now suddenly it refuses to apply in one of our staging environments but not the other. 

### References
According to https://kubernetes.io/docs/concepts/overview/working-with-objects/names/, different type of resource are allowed to have same name: 
> _Only one object **of a given kind** can have a given name at a time._ 

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@hterik the configuration that you shared does in fact attribute the same name and namespace to the two resources. The provider correctly reports them as such. This is valid since resources of different Kinds can in fact have the same name.

The issue here seems to be that copies of those resources already exist on the target API. Once you clean them up you should be up and running.

**Comment by hterik** [comment]
After long and tedious manual work using `terraform import` on every resource it started working again.
These resources have been created by terraform before so this is all very strange. Sadly it is far from first time this happens and every time it is inexplicable why, i just thought i found one reason above but turns out it was mystery again. 

To get out of these situations it would be very convenient if this provider had a force-overwrite flag, since kubernetes manifests are anyway designed to be reconciling by their own control-loop. But i've seen all the other rejected tickets about that feature request so will not push that any further here. 
Closing this as not able to reproducible.
