### ISSUE TITLE
Default secret no longer being generated for service account, with Kubernetes 1.24.0

### ISSUE THREAD

**Issue by jamshaidishaque** [hashicorp/terraform-provider-kubernetes#2004]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: Terraform v0.14.7
Kubernetes provider version: 2.18.0
Kubernetes version: 1.24.9
```

### Terraform Configuration Files
```
resource "kubernetes_secret" "service_account_secret" {
  metadata {
    name      = "${var.service_account_name}-token-secret"
    namespace = var.service_account_namespace
  }
  data = {
    token = var.crm_service_account_token
  }
  type = "kubernetes.io/service-account-token"
}

resource "kubernetes_service_account" "service_account" {
  # Default k8s behaviour is to automount - convenient because then pods can use AWS auth from
  # ServiceAccounts with no extra work. However, TF sets it to false by default.
  automount_service_account_token = false

  metadata {
    name      = var.service_account_name
    namespace = var.service_account_namespace
    annotations = {
      "eks.amazonaws.com/role-arn" = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${aws_iam_role.external-secrets.name}"
    }
  }
  secret {
    name = "${kubernetes_secret.service_account_secret.metadata.0.name}"
  }
}
```
### Steps to Reproduce
1. `terraform apply` 

### Expected Behavior
Kubernetes service account created successfully.

### Actual Behavior
Waiting for default secret to appear

### References
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1724

**Comment by alexsomesan** [comment]
@jamshaidishaque is this referencing a different issue than what is reported in #2005 ? Feels like a duplicate to me.
My explanation [over in #2005](https://github.com/hashicorp/terraform-provider-kubernetes/issues/2005#issuecomment-1439946519) should cover this case too. Can you confirm?

**Comment by jamshaidishaque** [comment]
Yes, your explanation is enough for this issue as well.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
