### ISSUE TITLE
feat: Enable AWS IAM role for authentication of k8s provider

### ISSUE THREAD

**Issue by jebbens** [hashicorp/terraform-provider-kubernetes#2009]
### Description

When you create an Amazon EKS cluster, the IAM principal that creates the cluster is automatically granted `system:masters` permissions in the cluster's role-based access control (RBAC) configuration in the Amazon EKS control plane. Therefore, this principal can be used to interact with the cluster to create and manage any Kubernetes resources. This feature request is to enable using an AWS IAM role ARN, e.g. the IAM role that created the cluster, as another option for authenticating the Terraform Kubernetes provider.

### Potential Terraform Configuration

```hcl
provider "kubernetes" {
  alias = "eks-admin"
  host = var.cluster_endpoint
  assume_role {
    role_arn     = "arn:aws:iam::111111111111:role/eks-admin"
    session_name = "ApplyClusterConfigs"
  }
}
```

### References
[Enabling IAM principal access to your cluster](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
You can already accomplish this today without any changes to the provider.
Just make use of the auth plugin functionality, as described here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins

You can pass the role to the `get-token` command by adding a `--role-arn` argument in the `args` list. Documented here: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/eks/get-token.html#options
