### ISSUE TITLE
Inconsistent "getting credentials: exec: executable aws failed with exit code 1" errors

### ISSUE THREAD

**Issue by stephenmelrose** [hashicorp/terraform-provider-kubernetes#2011]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.3.7 (Terraform Cloud)
Kubernetes Provider version: 2.18.0
Kubernetes version: EKS 1.24
```
## Terraform configuration
```hcl
provider "kubernetes" {
  host                   = module.eks_main.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks_main.cluster_certificate_authority_data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.eks_main.cluster_name]
  }
}
```

## Question

Today while setting up an AWS EKS cluster using Terraform Cloud I started the get errors similar to the following within Terraform Cloud,

```
Error: Get "https://REDACTED.gr7.us-east-2.eks.amazonaws.com/api/v1/namespaces/REDACTED": getting credentials: exec: executable aws failed with exit code 1
```
```
Error: Kubernetes cluster unreachable: Get "https://REDACTED.gr7.us-east-2.eks.amazonaws.com/version": getting credentials: exec: executable aws failed with exit code 1
```

The reason I saw I'm getting errors _similar_ to the above is because the errors we're getting are very inconsistent. Sometimes plans succeed (more on local than within TF cloud), sometimes they error out with a variation of the above. It's never the same URL/resource it errors out on, and sometimes it's one and sometimes it's multiple (parallelism related maybe?).

We have our Kubernetes provider setup as above.

My _gut_ feeling here is that we're hitting some kind of rate limiting. Either within AWS' API, or within Kubernetes, or specifically EKS' control plane.

I've checked our CloudTrail logs, no sign of failed requests. I've checked our EKS logs, no sign of failed requests. I've enabled TRACE logging within TF Cloud and while I can see the error, I see nothing around specific detail as to the underlying cause.

Has anyone had this error before? Any ideas as to what's causing it and how we can resolve it?

**Comment by stephenmelrose** [comment]
We did many runs with all the log types set to `TRACE` and there was nothing in there that showed what the error would be.

On a more positive note, HashiCorp responded to our support ticket and it looks like its a known issue for them. I've included it below, but I think we can close out this issue with it not being a provider bug.

---

Hi Steve,
 
Thank you for getting back to us.
 
Based on the provided configuration, it seems that you are affected by a bug in Terraform Cloud where in some circumstances when using that authentication method the `awscli` executable which should be installed on Terraform Cloud agent node gets installed slower making it unavailable at the time of `awscli` command execution. This is the reason why sometimes the run is successful, but sometimes it fails.
 
This is a known issue and the Terraform Cloud Development team is working on a solution within an internal bug (id: `IPL-1608`) related to this kind of authentication.
 
Until this is addressed, as a workaround, you can use the following type of authentication that would mitigate the pointed issue:

``` 
data "aws_eks_cluster" "cluster" {
  name = "The name of the cluster"
}

data "aws_eks_cluster_auth" "example" {
  name = "The name of the cluster"
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(local.eks_cluster_certificate_authority)
  token                  = data.aws_eks_cluster_auth.example.token
  load_config_file       = false
}

provider "helm" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(local.eks_cluster_certificate_authority)
  token                  = data.aws_eks_cluster_auth.example.token
  load_config_file       = false
}
```

**Comment by awasilyev** [comment]
another workaround:

`
$ cat get_eks_creds.sh
#!/bin/sh
while ! aws eks get-token --cluster-name $1 >creds; do
  sleep 1
done
cat creds
`

`
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    args        = [var.stack]
    command     = "./get_eks_creds.sh"
  }
}
`

**Comment by CarlosPintoWindsor** [comment]
> ./get_eks_creds.sh

Where should i put this file?

**Comment by aryangosling** [comment]
@CarlosPintoWindsor any solution for this?
