### ISSUE TITLE
Get services by label

### ISSUE THREAD

**Issue by sergiomcalzada** [hashicorp/terraform-provider-kubernetes#2013]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.3.6
Kubernetes Provider version: 2.17.0
Kubernetes version: 1.22.11
```
## Terraform configuration
```hcl
data "kubernetes_service_v1" "services" {
  metadata {
    labels = {
      "app.kubernetes.io/instance" = "example"
    }
  }
}

output "kubernetes_services_v1" {
  value = [for service in data.kubernetes_service_v1.services : "${service.metadata.0.name}.${service.metadata.0.namespace}"]
}
```

## Question
```
Is there a way to list all the services by label?
As is done with "nodes"

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/nodes
```

**Comment by jrhouston** [comment]
There isn't a data source specifically for listing services. However there is a generic [kubernetes_resources](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/resources) data source for querying any resource by label or field selector. You can use it for Service like this:

```hcl
data kubernetes_resources svc_example {
  api_version = "v1"
  kind        = "Service"

  label_selector = "app.kubernetes.io/instance=example"
}

output "kubernetes_services_v1" {
  value = [
    for svc in data.kubernetes_resources.svc_example.objects : 
    "${svc.metadata.name}.${svc.metadata.namespace}"
  ]
}
```

**Comment by sergiomcalzada** [comment]
Hi @jrhouston 

Thanks you for the tip. Just would like to add the doc page 

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/resources

And  notify that there is another two issues:

* doc is "wrong" as in the example it says `kubernetes_resource` but that is the single generic resource.

* the `kubernetes_resources` is missed from the provider (the plural one)

```
╷
│ Error: Invalid data source
│ 
│   on test.tf line 4, in data "kubernetes_resources" "ravendb_svc_example":
│    4: data "kubernetes_resources" "ravendb_svc_example" {  
│ 
│ The provider hashicorp/kubernetes does not support data source
│ "kubernetes_resources". **Did you mean "kubernetes_resource"?**
```

**Comment by jrhouston** [comment]
Thanks for reporting back @sergiomcalzada – we'll fix the docs page for the resource.
