### ISSUE TITLE
Error with `kubernetes_secret` datasource when secret contains `metadata.generateName`

### ISSUE THREAD

**Issue by kirkiris** [hashicorp/terraform-provider-kubernetes#2014]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.3.7
Kubernetes provider version: v2.18.1
Kubernetes version: 1.24.9
```

### Affected Resource(s)

- kubernetes_secret
- kubernetes_secret_v1

### Terraform Configuration Files
```hcl
data "kubernetes_secret" "this" {
  metadata {
    name      = "sealed-secrets-keybrfhz"
    namespace = "extra-services"
  }
}
```

### Debug Output

[Debug Output](https://gist.githubusercontent.com/kirkiris/7858425df6e9e867d6dfdd033d32f597/raw/bc6f6880004d22fb85e22136a91a2d40befca862/terraform_plan.log)
### Steps to Reproduce

1. Use kubernetes_secret data resource to query for k8s secret containing `metadata.generateName`
2. `terraform plan`
### Expected Behavior
`plan`/`apply` should execute successfully

### Actual Behavior
Plan fails with:
```
Error: Invalid address to set: []string{"metadata", "0", "generate_name"}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonwtech** [comment]
Looks like the same issue as https://github.com/hashicorp/terraform-provider-kubernetes/issues/1954

**Comment by kirkiris** [comment]
Yep, need to improve my Google-fu 😅
