### ISSUE TITLE
Use dynamic in kubernetes_manifest spec

### ISSUE THREAD

**Issue by KlemenDanfoss** [hashicorp/terraform-provider-kubernetes#2016]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: latest
Kubernetes Provider version: latest
Kubernetes version: 1.22
```

## Question
```
I wan't to use dynamic variables in kubernetes_manifest spec is that possible? Are there any examples?
```

**Comment by shiny-zero** [comment]
following. I'm interested in moving my templates away from the `kubectl` provider because I wanted to make use of the `wait_for` block that `kubernetes_manifest` has, but I digress.

I wanted something like this for `kubernetes_manifest`, but I can't seem to find it documented anywhere.
```
resource "kubectl_manifest" "kube2iam_service_account" {
  yaml_body = templatefile("${path.module}/manifests/kube2iam_service_account.yaml",
    {
      Namespace = var.namespace
      Kube2Iam  = var.kube2iam
    }
  )
}
```

**Comment by jrhouston** [comment]
The `dynamic` block is for generating nested blocks so unfortunately it wont be possible to use this within the spec of a `kubernetes_manifest` resource as this resource uses a typed object, rather than a nested block.
