### ISSUE TITLE
Support generic ephemeral volumes with volumeClaimTemplate on pods/deployments

### ISSUE THREAD

**Issue by willhughes-au** [hashicorp/terraform-provider-kubernetes#2032]
### Description

As of Kubernetes 1.23, deployments can have generic ephemeral volumes by using volumeClaimTemplate. 

Currently it does not appear to be possible to configure this within either a `kubernetes_pod_v1` or `kubernetes_deployment_v1` resource. Both resources should ephemeral volumes like this available. 

### Potential Terraform Configuration

This example is just for a pod resource, [as per the example from the kubernetes documentation](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes)

```hcl
resource "kubernetes_pod_v1" "name" {
  spec { 
    volume {
      name =  "scratch-volume"
      ephemeral {
        volume_claim_template {
          spec {
            access_modes = [ "ReadWriteOnce" ]
            resources {
              requests {
                storage = "10Gi"
              }
            }
            storage_class_name = "scratch-storage-class"
            volume_mode = "FileSystem"
          }
        }
    }
  }
}
```

### References

Kubernetes ephemeral volumes documentation: https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jbg** [comment]
> @BBBmau  The linked issue #2183 only seems to resolve ephemeral volumes for pod spec. I don't believe it will work for deployments still.  Also possibly stateful sets, cronjobs/jobs, etc. 
> 
> 
> 
> Could you please re-open this issue if it's not fixed for those, too? 

The PodSpec within a deployment, statefulset, job, daemonset etc is the same object, and the code for PodSpec isn't duplicated everywhere a PodSpec is used, so it should fix it everywhere.
