### ISSUE TITLE
Keep getting a timeout in eks after 15 minutes

### ISSUE THREAD

**Issue by dreinhardt-terminus** [hashicorp/terraform-provider-kubernetes#2047]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.2.9
Kubernetes Provider version: 2.18.1.
Kubernetes version: 1.22
```
## Terraform configuration
```hcl
provider "kubernetes" {
  experiments {
    manifest_resource = true
  }
  host                   = data.aws_eks_cluster.selected.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.selected.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.selected.token
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", local.eks_cluster_name]
  }
}
```

## Question
```
In my kubernetes provider block I get the host, cluster_ca_certificate, and token via data sources. I always ran into a timeout issue during a long plan if terraform tried to interact with any kubernetes objects after 15 minutes. According to the documentation the below exec block is supposed to fix this. Do I have the setup wrong?
```

**Comment by alexsomesan** [comment]
Hi,

as explained here: https://github.com/hashicorp/terraform-provider-aws/issues/16415 this is actually a hard limit of AWS and apparently not easy to address.

My suggestion would be to use the AWS IAM authentication plugin: https://github.com/kubernetes-sigs/aws-iam-authenticator. This mechanism is managed directly by the Kubernetes client library and should refresh the token transparently as required.

**Comment by alexsomesan** [comment]
Also, I just noticed that you're using both `token` and the `exec` plugin mechanism at the same time.
Since they both supply credentials, only one of the two should be used at any one time. Please remove the `token` attribute and try again and let us know if it improves things.

**Comment by dreinhardt-terminus** [comment]
@alexsomesan removing the `token` attribute gives `Error: Kubernetes cluster unreachable`

**Comment by dreinhardt-terminus** [comment]
Found a solution to this. For anybody else having the same issue my problem was not setting the role in the plugin.

```hcl
provider "kubernetes" {
  host                   = module.eks[0].cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks[0].cluster_certificate_authority_data)
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", local.eks_cluster_name, "--role", "arn:aws:iam::${var.aws_account_id}:role/<role_name>"]
  }
}
```
