### ISSUE TITLE
[Feature Request] allow override namespace in kubernetes_manifest

### ISSUE THREAD

**Issue by yongzhang** [hashicorp/terraform-provider-kubernetes#2069]
### Description

Currently seems like we can only add namespace inside `manifest` attribute, it would be useful if we can override namespace so we can template `manifest` without worrying about forgetting the namespace field.

### Potential Terraform Configuration

```hcl
resource "kubernetes_manifest" "test-configmap" {
  manifest = {
    "apiVersion" = "v1"
    "kind"       = "ConfigMap"
    "metadata" = {
      "name"      = "test-config"
    }
    "data" = {
      "foo" = "bar"
    }
  }

  override_namespace = "staging"
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
Hi @yongzhang, while this possible to do it may be cause more harm than good. A preferred work around that would give better results and is easier to implement would be to create namespace using a variable and use that same variable when referencing the namespace. Here's an example of how you could do this: 

```
variable "namespace" {
  default = "default"
}

resource "kubernetes_manifest" "test-configmap" {
  manifest = {
    "apiVersion" = "v1"
    "kind"       = "ConfigMap"
    "metadata" = {
      "name"      = "test-config"
      "namespace" = var.namespace
    }
    "data" = {
      "foo" = "bar"
    }
  }
}  
```
You may also reference our documentation [here](https://developer.hashicorp.com/terraform/language/values/variables) that further explains how you can implement this!

**Comment by CameronHudson8** [comment]
I found that I could override the namespace of a `kubernetes_manifest` in a readable way like this:
```
data "http" "alert_rules" {
  url = "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/v0.13.0/manifests/kubernetesControlPlane-prometheusRule.yaml"
}

resource "kubernetes_manifest" "alert_rules" {
  manifest = merge(
    yamldecode(data.http.alert_rules.response_body),
    {
      metadata = {
        namespace = "my-namespace"
      }
    }
  )
}

```
However, I would be surprised if this approach works for a mix of namespaced and unnamespaced resources.

**Comment by kpoos** [comment]
What can you do, if you use the kubernetes_manifest  with yamldecode and you need to override the namespace for example to prod or test? 

resource "kubernetes_manifest" "cert_manager" {
  for_each = fileset(var.cert_manager_manifests_dir, "*.yaml")
  manifest = yamldecode(file("${var.cert_manager_manifests_dir}/${each.value}"))
}
