### ISSUE TITLE
kubernetes_cronjob broken after update to 1.25

### ISSUE THREAD

**Issue by dcarrion87** [hashicorp/terraform-provider-kubernetes#2075]
### Terraform Version, Provider Version and Kubernetes Version

```
Kubernetes provider version: 2.19
Kubernetes version: 1.25.7
```

### Affected Resource(s)

Since updating to Kubernetes 1.25 we're getting these errors when applying kubernetes_cron_job resources.

### Debug Output

Terraform indicates resources will be created and then fails with:

```
╷
│ Error: the server could not find the requested resource
│ 
│   with module.rotator["one"].kubernetes_cron_job.this,
│   on ../../../../tf-modules/the-thing/k8s.tf line 70, in resource "kubernetes_cron_job" "this":
│   70: resource "kubernetes_cron_job" "this" {
│ 
╵
╷
│ Error: the server could not find the requested resource
│ 
│   with module.rotator["two"].kubernetes_cron_job.this,
│   on ../../../../tf-modules/the-thing/k8s.tf line 70, in resource "kubernetes_cron_job" "this":
│   70: resource "kubernetes_cron_job" "this" {
│ 
╵
╷
│ Error: the server could not find the requested resource
│ 
│   with module.rotator["three"].kubernetes_cron_job.this,
│   on ../../../../tf-modules/the-thing/k8s.tf line 70, in resource "kubernetes_cron_job" "this":
│   70: resource "kubernetes_cron_job" "this" {
│ 
╵
```

**Comment by dcarrion87** [comment]
Potentially related:

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125


Seeing call to:

```
/apis/batch/v1beta1/namespaces/.../cronjobs
```

**Comment by arybolovlev** [comment]
Hi @dcarrion87,

The resource `kubernetes_cron_job` uses API `BatchV1beta1`. The resource `kubernetes_cron_job_v1` uses API `kubernetes_cron_job_v1`. For the clusters running 1.25+, you need to use/migrate existing resources to `kubernetes_cron_job_v1`.

I hope that helps.

Thank you.

**Comment by achref-riahi** [comment]
Hi @dcarrion87, after using kubernetes_cron_job_v1, this issue is fixed for me as well. However, now when we run **terraform plan**, Terraform tries to create the resource again, as if it doesn't exist. As I mentioned before, the resource already exists, so the **terraform apply** is rejected.

**Comment by mpatou** [comment]
You will need to move the resource from the old name to the new name
