### ISSUE TITLE
kubernetes_manifest imported resources are recreated not updated 

### ISSUE THREAD

**Issue by comozo** [hashicorp/terraform-provider-kubernetes#2076]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.4.5
Kubernetes provider version: 2.19.0
Kubernetes version: 1.25.7
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "kubernetes_manifest" "helmchart_kube_system_prometheus_node_exporter" {
  manifest = {
    "apiVersion" = "helm.cattle.io/v1"
    "kind"       = "HelmChart"
    "metadata" = {
      "name"      = "prometheus-node-exporter"
      "namespace" = "kube-system"
    }
    "spec" = {
      "chart"           = "prometheus-node-exporter"
      "repo"            = "https://prometheus-community.github.io/helm-charts/"
      "targetNamespace" = "monitoring"
      "version"         = "4.5.0"
    }
  }
}

```

### Steps to Reproduce

1. Create Terraform file main.tf with the content with
```hcl
resource "kubernetes_manifest" "helmchart_kube_system_prometheus_node_exporter" {
   manifest = {
    "apiVersion" = "helm.cattle.io/v1"
    "kind"       = "HelmChart"
    "metadata" = {
      "name"      = "prometheus-node-exporter"
      "namespace" = "kube-system"
    }
    "spec" = {
      "chart"           = "prometheus-node-exporter"
      "repo"            = "https://prometheus-community.github.io/helm-charts/"
      "targetNamespace" = "monitoring"
      "version"         = "4.5.0"
    }
  }
}
```
3. Import resource 
```shell
terraform import kubernetes_manifest.helmchart_kube_system_prometheus_node_exporter "apiVersion=helm.cattle.io/v1,kind=HelmChart,namespace=kube-system,name=prometheus-node-exporter"
```

### Expected Behavior
What should have happened?
Terraform should **update in place** the resource.

### Actual Behavior
What actually happened?
The resource is successfully imported but when running a `terraform plan` the resource is planned for a delete and replace instead of update.

```hcl
-/+ resource "kubernetes_manifest" "helmchart_kube_system_prometheus_node_exporter" {
      + manifest = {
          + apiVersion = "helm.cattle.io/v1"
          + kind       = "HelmChart"
          + metadata   = {
              + name      = "prometheus-node-exporter"
              + namespace = "kube-system"
            }
          + spec       = {
              + chart           = "prometheus-node-exporter"
              + repo            = "https://prometheus-community.github.io/helm-charts/"
              + targetNamespace = "monitoring"
              + version         = "4.5.0"
            }
        }
      ~ object   = {
          ~ metadata   = {
              - annotations                = {
                 .....
                }
                ....
                # (1 unchanged attribute hidden)
            }
            # (3 unchanged attributes hidden)
        }
    }
Plan: 1 to add, 0 to change, 1 to destroy.
```

### Important Factoids

* Downgrading to v2.8.0 of the provider results in the correct expected behavior.

* Importing resource with provider version >2.8.0 results re-creation of the resource

* Importing resource with provider version =2.8.0 works as expected - resource is updated in-place

### References

- This bug seems to be a regression as a similar bug has been opened: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1712#issue-1228954786

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @comozo,

In this particular case this is expected behavior.

Here is the CRD of the `HelmChart` kind(I copy only the part that is important for this case):

```yaml
spec:
  conversion:
    strategy: None
  group: helm.cattle.io
  names:
    kind: HelmChart
    listKind: HelmChartList
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
```

Since the entire `spec` has the `x-kubernetes-preserve-unknown-fields` attribute set to `true` it causes resource recreation rather than the update.

Here is the more detailed explanation of the observed behavior: https://github.com/hashicorp/terraform-provider-kubernetes/issues/1928#issuecomment-1341043424.

I hope that helps.

**Comment by comozo** [comment]
@arybolovlev Thank you it makes sense.
