### ISSUE TITLE
Using resource outputs as input for Kubernetes provider causing issue

### ISSUE THREAD

**Issue by radirobi** [hashicorp/terraform-provider-kubernetes#2095]
I have my own module for creating a Kubernetes cluster in Azure. This module has an output (called _aks_public_fqdn_), which contains the FQDN of the api-server. Once the cluster is ready, I would like to create some namespaces on it. 

## Terraform version, Kubernetes provider version
```
Terraform version: 1.4.6
Kubernetes Provider version: 2.20.0
```
## Terraform configuration
```hcl
module "aks" {
  source = "./aks"

  environment        = local.environment
  region             = local.region
  instance_id        = local.workload_id
  application        = local.workload_name
  resource_group     = local.rg
  kubernetes_version = local.kubernetes_version
}

provider "kubernetes" {
  host = "https://${module.aks.aks_public_fqdn}"
  insecure = true

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args = [
      "get-token",
      "--environment",
      "AzurePublicCloud",
      "--server-id",
      "4368-4678-4368-4368", 
      "--login",
      "azurecli"
    ]
  }
}

resource "kubernetes_namespace" "demo" {
  depends_on = [module.aks]
  metadata {
    name = "demo"
  }
}
```

## Question
The public FQDN is known only after apply. When I try to create a terraform plan, I get:
```
│ Error: Provider configuration: cannot load Kubernetes client config
│ 
│   with provider["registry.terraform.io/hashicorp/kubernetes"],
│   on versions.tf line 27, in provider "kubernetes":
│   27: provider "kubernetes" {
│ 
│ invalid configuration: default cluster has no server defined
```
How could I solve this? The same is working with Kubernetes provider with version of 2.3.2. Why is that?

**Comment by radirobi** [comment]
The same is working with Kubernetes provider with version of 2.3.2. Why is that?

**Comment by BBBmau** [comment]
Hello thank you for opening this issue @radirobi. It's recommended to split your provider configuration and cluster configuration into two separate applies. It's explained more [here.](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources)
