### ISSUE TITLE
statefulsetNot performing as expected

### ISSUE THREAD

**Issue by yangly6207** [hashicorp/terraform-provider-kubernetes#2105]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Kubernetes Provider version:
Kubernetes version:
```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question
```
Enter your question here.
```

**Comment by jrhouston** [comment]
@yangly6207 I'm closing this as the description is just the unedited issue template so we don't know what your issue is. Please open again and give as much detail as you can in the issue description so we can investigate.
