### ISSUE TITLE
Update rbac/v1 documentation with Attribute reference

### ISSUE THREAD

**Issue by nprashiyer** [hashicorp/terraform-provider-kubernetes#2108]
### Description

The following `rbac/v1` resources export `id` as an attribute. Update the documentation for these resources to have Attribute reference section.

```
kubernetes_cluster_role
kubernetes_cluster_role_binding
kubernetes_cluster_role_binding_v1
kubernetes_cluster_role_v1
kubernetes_role
kubernetes_role_binding
kubernetes_role_binding_v1
kubernetes_role_v1
```

I would like to work on this.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @nprashiyer thanks for opening an issue. I'm not sure I understand your request. All terraform resources have an `id` attribute as all resources need to have an id in the state. It is usually not documented because it is implicit to all terraform resources.
