### ISSUE TITLE
kubernetes_job_v1 succeeds if job is deleted during apply

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hashicorp/terraform-provider-kubernetes#2111]
No sure if it is intentional, but if job gets deleted during apply, terraform reports succeeded. Looks like a bug to me, because if you do this trick to deployment terraform fails

**Comment by jrhouston** [comment]
Thanks for opening this @vladimirtiukhtin. This behaviour is deliberate to account for jobs that have a TTL of zero, i.e. Jobs that are removed as soon as they are complete. We could perhaps make the code smarter by checking if the `ttl_seconds_after_finished` attribute has been set. 

Code for this behaviour is here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/80e852091e8f4c7bdbd67afaead3ee21ea910df3/kubernetes/resource_kubernetes_job.go#L292-L294
