### ISSUE TITLE
New provider version release

### ISSUE THREAD

**Issue by dosilyoun** [hashicorp/terraform-provider-kubernetes#2120]
Hi guys!

Can you tell me that there is any available release calendar? I am waiting long time for c1408ac. I don't wanna fork the repo and maintain my own version.

Thanks for any reply regarding any information about the schedule of provider release.

Best regards,
Charles

**Comment by alexsomesan** [comment]
Hi, we don't have a fixed interval release schedule. The current gap to the last release is a bit wider due to some company events we took part in during May. We will be cutting a new release in the upcoming few days.

**Comment by alexsomesan** [comment]
Release v2.21.0 is now out.
