### ISSUE TITLE
Include node addresses info at node schema

### ISSUE THREAD

**Issue by axcosta** [hashicorp/terraform-provider-kubernetes#2124]
### Description

data."kubernetes_nodes" currently does not get information about addresses of each Kubernetes cluster node. This should address this

### Potential Terraform Configuration

file `kubernetes/schema_node_spec.go`:

```go
func nodeStatusFields() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"addresses": {
			Type:        schema.TypeList,
			Computed:    true,
			Description: "Set of IP addresses assigned to the node. More info: https://kubernetes.io/docs/concepts/architecture/nodes/#addresses/node/#info",
			Elem: &schema.Resource{
				Schema: map[string]*schema.Schema{
					"address: {
						Type: schema.TypeString,
						Computed: true,
					},
					"type: {
						Type: schema.TypeString,
						Computed: true,
					},			
				},
			},
		}
(...)
```

Example of use in Terraform:
```hcl
data "kubernetes_nodes" "info" {}
output "kind_cluster_node_0_addresses" { 
  description = "Addresses assigned to node[0] of cluster"
  value = data.kubernetes_nodes.info.nodes[0].status[0].addresses
}
```

### References

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@axcosta Thanks for spotting this and also going through the work of determining what needs to change. We'd love it if you could open a PR with those changes you proposed in the issue description. Thanks!
