### ISSUE TITLE
Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.+, but no  attribute "default_secret_name" was used

### ISSUE THREAD

**Issue by SehiiRohoza** [hashicorp/terraform-provider-kubernetes#2130]
Hello,

I'm able to create k8s Service Account and I'm aware about  PR #1792, meanwhile I want to get back to the [author comment](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1792#issuecomment-1218110185) and to the [unanswered question](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1792#issuecomment-1219142552):

**The code is not using the `default_secret_name` attribute, so why is it showing a warning?**

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.4.4
Kubernetes provider version: 2.20.0
Kubernetes version: 1.24.11-gke.1000
```

### Affected Resource(s)

Kubernetes SA

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "kubernetes_service_account" "ksa" {
  metadata {
    name      = "ksa"
    namespace = kubernetes_namespace.sync[0].metadata[0].name
    annotations = {
      "iam.gke.io/gcp-service-account" : "gcp-sa@somename-${var.environment}.iam.gserviceaccount.com"
    }
  }
}
```

### Debug Output

```
Step #3 - "tf apply": │ Warning: "default_secret_name" is no longer applicable for Kubernetes v1.24.0 and above
Step #3 - "tf apply": │ 
Step #3 - "tf apply": │   with kubernetes_service_account.ksa[0],
Step #3 - "tf apply": │   on k8s_service_accounts.tf line 1, in resource "kubernetes_service_account" "ksa":
Step #3 - "tf apply": │    1: resource "kubernetes_service_account" "ksa" {
Step #3 - "tf apply": │ 
Step #3 - "tf apply": │ Starting from version 1.24.0 Kubernetes does not automatically generate a
Step #3 - "tf apply": │ token for service accounts, in this case, "default_secret_name" will be
Step #3 - "tf apply": │ empty
Step #3 - "tf apply": ╵
```

### Expected Behavior
What should have happened?
Terraform should apply changes without warning messages.

### Actual Behavior
What actually happened?
Terraform is showing the warning message despite the code is not using the `default_secret_name` attribute.

### References

- PR #1792

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by grzegorzlyczba** [comment]
@SehiiRohoza please check release few hours ago version 2.21.0 where https://github.com/hashicorp/terraform-provider-kubernetes/pull/2085 was included. I don't see this warning anymore.

**Comment by SehiiRohoza** [comment]
> @SehiiRohoza please check release few hours ago version 2.21.0 where #2085 was included. I don't see this warning anymore.

That works for me as well. Thanks!
