### ISSUE TITLE
I did create a Daemonset using terraform and I Want to get the name of the pod and use it as Variable. 

### ISSUE THREAD

**Issue by ashishreddyaleti** [hashicorp/terraform-provider-kubernetes#2148]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Kubernetes Provider version:
Kubernetes version:
```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question
```
Enter your question here.
```

**Comment by BBBmau** [comment]
Hello @ashishreddyaleti , could you provide more context to your question by following the issue template. Things like terraform version, tf config, and what you're getting instead of what you want will help us better.

From my understanding you are wanting to grab the name of the pod that the deployment used. Did you try using one of the data sources?

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/pod_v1

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment_v1

**Comment by ashishreddyaleti** [comment]
Actually I am trying to Implement the following steps in Automation(https://github.com/Azure/azure-workload-identity/blob/main/docs/book/src/topics/self-managed-clusters/service-account-key-rotation.md).

Terraform version 1.0.10
Kubernetes provider  2.20.0
 
main.tf 
#######
 terraform {
  required_version = ">= 1.0.10"
  required_providers {
    kubernetes = {
        source = "hashicorp/kubernetes"
        version = "2.20.0"
    }
  }
}
provider "kubernetes" {
    config_path = "~/.kube/config"

}

resource.tf 
###########
resource "kubernetes_daemonset" "jump_pod" {
  metadata {
    name = "jump"
    labels = {
      k8s-app = "jump"
     }
   }
  spec {
    selector {
      match_labels = {
        name = "jump"
       }
     }
    template {
      metadata {
        labels = {
          name = "jump"
        }
      }
      spec {
        container {
          image = "busybox"
          name  = "busybox"
          command = ["sleep", "3600"]
          volume_mount {
            mount_path = "/tmp"
            name       = "etc-kubernetes-pki"
          }
        }
      volume {
        name = "etc-kubernetes-pki"
        host_path  {
          path = "/tmp"
        }
      }
    }
  }
 }
}
resource "null_resource" "example" {
  provisioner "local-exec" {
    interpreter = [ "/bin/bash", "-c" ]
    working_dir = "${path.module}"
    command = "export PODNAME=$(kubectl get po -l name=jump -ojson | jq -r '.items[0].metadata.name')"
  }
  provisioner "local-exec" {
    interpreter = ["/bin/bash", "-c"]
    working_dir = "${path.module}"
    command = "kubectl cp default/${POD_NAME}:etc/kubernetes/ssl/apiserver-key.pem sa-old.pub"
  }
}


When  I run Terraform Plan it gives me an error as  

 Error: Invalid reference
│
│   on resources.tf line 51, in resource "null_resource" "example":
│   51:     command = "kubectl cp default/${POD_NAME}:etc/kubernetes/ssl/apiserver-key.pem sa-old.pub"
│
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.

This method is Not working. 

So after Daemonset get created I need the name of the Pod to run commands ?

**Comment by BBBmau** [comment]
Hello @ashishreddyaleti, you may be able to grab the pod name from the daemon set using `kubernetes_resources` data source where you can grab the pod name using the field_selector referencing the `ownerReferences` in the daemon set

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/resources#example-get-a-list-of-namespaces-excluding-kube-system-using-field_selector

**Comment by ashishreddyaleti** [comment]
Hello @BBBmau  Thanks for the info.

Can you Suggest  What resources can I use to Copy a file from the pod (/etc/kubernetes/ssl/apiserver-key.pem) to local ? 

I tried provision local-exec with kubectl cp command it failes with Authenctication. 

Also is there a way to get kubeconfig file of Kubernets cluster and pass to above command for authentication ?
