### ISSUE TITLE
Deleting Pods to Migrate to New Worker Nodes

### ISSUE THREAD

**Issue by devryan** [hashicorp/terraform-provider-kubernetes#2152]
**Terraform Version:** 
Terraform v1.5.0

**Provider:** 
hashicorp/kubernetes
Version: v2.21.1

**Affected Resource(s):**
kubernetes_pod_v1

**Question:**
I am trying to handle (self-managed) eks worker node updates and pod migration to the new worker nodes; the plan is: Creating a new EC2 Autoscaling Group, and setting up worker nodes there with an updated AMI, then trying to handle pod migration from the old autoscaling group to the new.  Plan is: Once the new autoscaling group is up with new EKS Worker Nodes, and the old tainted with NoSchedule, to delete the old pods one by one in a specific order in order to get them created on the new Worker Nodes.

Because I'm not using EKS Managed Nodes I was looking for the native kubernetes terraform resources to try and handle this.

How do we handle deletion of a pod in a native manner with this provider, or with kubernetes_pod_v1?  I did not see anything about the pod where I could specify the name of the pod and an action to take such as delete; I know having a resource just to delete it may seem odd, but I want to handle this with native resources vs just doing a null_resource with a local-exec.  I'd be using a "count" on it so the deletion only occurs when a specific local is set.

**Comment by alexsomesan** [comment]
Hi @devryan, 

You are on the right track with your assumption. Using `count` with a conditional value is the recommended way to turn a resource "on" or "off" and thus have it be created or delete depending on the truth value of the condition.
