### ISSUE TITLE
kubernetes_manifest Provides Inconsistent result after apply

### ISSUE THREAD

**Issue by srikanth2302** [hashicorp/terraform-provider-kubernetes#2167]
Hi,
```
Terraform version: 1.4.8
Kubernetes provider version: 2.21.1
Azure Kubernetes version: 1.14.6
```

### Affected Resource(s)
- kubernetes_manifest

I'm trying to create a persistent volume in AKS Cluster using kubernetes_manifest(I have yaml passed as input to this resource instead of having multiple kubernetes resources written like kuberenetes_persistent_valume etc)... THis Resource Works well with secrets/Clusterrole/Clusterrolebindings Kind resources but throwing an inconsistent state when we provide persistent volume configuration.

### Yaml for Persistent Volume

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "<name>"
  namespace: <namespace>
spec:
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    secretNamespace: <Secret Namespace>
    shareName: <FileShare Name>
    readOnly: false 

### Error:
When applying changes to .kubernetes_manifest.label["PersistentVolume"], provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.spec.azureFile.readOnly: was cty.False, but now null.

**Comment by alexsomesan** [comment]
It's likely that you need to set `spec.azureFile.readOnly` attribute as "computed", by adding
```
resource "kubernetes_manifest" "foobar" {
  computed_fields = ["spec.azureFile.readOnly"]
...
```

Also, if you would like us to try to reproduce your issue, do you mind posting the YAML document with it's actual indentation? You can use code block markup for that, as explained [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Comment by srikanth2302** [comment]
Adding computed_fields as mentioned has fixed the issue.. Thank You!!!
