### ISSUE TITLE
unexpected new value: .object: wrong final value type: incorrect object │ attributes.

### ISSUE THREAD

**Issue by gviswalingam** [hashicorp/terraform-provider-kubernetes#2177]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform v1.4.5
Kubernetes version 1.24

```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question
```
Enter your question here.
```
Am getting the below error 

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ kubernetes_manifest.k8sallowedrepos_allow_only_private_registry, provider
│ "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an
│ unexpected new value: .object: wrong final value type: incorrect object
│ attributes.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

my code is  and when apply this , I get the error 

```
resource "kubernetes_manifest" "k8sallowedrepos_allow_only_private_registry" {
  manifest = {
    "apiVersion" = "constraints.gatekeeper.sh/v1beta1"
    "kind" = var.gatekeeper_template
    "metadata" = {
      "name" = "allow-only-private-registry"
    }
    "spec" = {
      "enforcementAction" = "warn"
      "match" = {
        "kinds" = [
          {
            "apiGroups" = [
              "",
            ]
            "kinds" = [
              "Pod",
            ]
          },
        ]
      }
      "parameters" = {
        "repos" = var.repo_list
      }
    }
  }
}

```

I tried to add computed_fields as below 

` computed_fields = ["spec.enforcementAction", "spec.match", "spec.parameters"]  `

I still get the same error below 

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ kubernetes_manifest.k8sallowedrepos_allow_only_private_registry, provider
│ "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an
│ unexpected new value: .object: wrong final value type: incorrect object
│ attributes.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

Note: Plan runs fine

Any idea guys ?

**Comment by arybolovlev** [comment]
Hi @gviswalingam,

What is the provider version you use? Please share `var.gatekeeper_template` and `var.repo_list`. Please share a working YAML manifest example.

Thank you.

**Comment by gviswalingam** [comment]
Issue is fixed . Fix is below

 "parameters" = {
        "repos" = jsondecode(var.repo_list)
