### ISSUE TITLE
How to use EKS provider with EKS module in CI/CD?

### ISSUE THREAD

**Issue by jslusher** [hashicorp/terraform-provider-kubernetes#2212]
```
Terraform version: 1.5.4
Kubernetes Provider version: latest
Kubernetes version: 1.27
```
## Terraform configuration
```hcl
data "aws_eks_cluster" "eks-lab" {
  name = var.cluster_name
}

data "aws_eks_cluster_auth" "eks-lab" {
  name = var.cluster_name
}

provider "kubernetes" {
  host                   = data.aws_eks_cluster.default.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.default.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.default.token
}
```

## Question
I'm trying to apply [your documentation](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources) to our use case of a Github Actions hosted terraform EKS module, regarding the EKS module's `aws-auth` configmap resource in particular. In the past, we've had problems especially around deleting clusters. Since it can't reference the EKS module being deleted, cluster cert and name information needs to be hard-coded to delete them. This is the best case, the worst case is that the provider doesn't run and there's a confusing permission error to the aforementioned configmap.

Your [current example](https://github.com/hashicorp/terraform-provider-kubernetes/tree/main/_examples/eks) shows two separate state buckets and terraform applies, using data resources. There is a chicken and egg problem with this, however, because the data resources don't exist before the cluster is created, and the cluster won't be created without the provider, at least when creating one using the EKS module and the `manage_aws_auth_configmap = true` option in it.

We've worked around this issue in the past, either by removing the auth-map configmap from terraform state or as I was saying by hard-coding the cluster values at the time of deletion. The example in the EKS module itself is what we've tried in the past. What is the most sane way to use this provider with the EKS module managing the auth-map configmap?

**Comment by sheneska** [comment]
Hi @jslusher are you doing this in a single `apply` step?

**Comment by jslusher** [comment]
@sheneska I've been working through this the last couple of days, and here's where I landed:

First, the two important details of our setup that are causing us problems with the suggested setup of the provider:
- We're running our Terraform in Github Actions
- We're using the terraform registry EKS module, and it manages our `auth-map` Configmap

I tried setting up a GHA workflow that separated our Terraform into two separate state buckets and applies, one for the provider and one for the EKS cluster. There's a chicken/egg problem with this setup:
- The kubernetes provider is using `data.aws_eks_cluster` and `data.aws_eks_cluster_auth`, but if there's no cluster, there's nothing for it to reference and so it fails. 
- If the module exists in a separate state bucket but hasn't run yet, there's no way to even reference the module for these values.
- In the GHA workflow, even if there was a workaround to reference a yet-to-exist cluster, the apply of the EKS cluster would need to run first so that these values exist, but every time after that we would want the provider to run first

My solution is this:
- Same apply, same state
- Separate the provider into its own file
- Use `module.eks` references in the provider to create the cluster
- Use `data.aws_eks_cluster` references in the provider to delete the cluster

```
# Uncomment these and comment references to the module when destroying the cluster.
#data "aws_eks_cluster" "eks-lab" {
#  name = local.cluster_name
#}
#
#data "aws_eks_cluster_auth" "eks-lab" {
#  name = local.cluster_name
#}

provider "kubernetes" {
  # use these to create and maintain an EKS cluster
  host                   = module.eks.cluster_endpoint
  cluster_ca_certificate = base64decode(module.eks.cluster_certificate_authority_data)

  # use these to destroy the cluster
  #host                   = data.aws_eks_cluster.eks-lab.endpoint
  #cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks-lab.certificate_authority[0].data)

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    # This requires the awscli to be installed locally where Terraform is executed
    args = ["eks", "get-token", "--cluster-name", local.cluster_name, "--region", local.region]
  }
}
```

**Comment by sheneska** [comment]
Hi @jslusher, this is a good work around, however do keep in mind though that creating the cluster in a separate `apply` first would be better and lead to less issues later on.
