### ISSUE TITLE
Dead Link: On Kubernetes Deployment Doc

### ISSUE THREAD

**Issue by tlchaffi** [hashicorp/terraform-provider-kubernetes#2218]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: N/A
Kubernetes provider version: N/A
Kubernetes version: N/A
```

### Affected Resource(s)

Terraform Doc Page: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#node_selector

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Steps to Reproduce
1. Go to Terraform Kubernetes documentation: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#node_selector
2. Select the "Kubernetes reference"
3. Dead links to a 404.

### Expected Behavior
What should have happened?
* We should be presented with the relevant Kubernetes reference and documentation.

### Actual Behavior
What actually happened?
* Presented with a 404 response.

### Important Factoids
N/A

### References

- Not at this time.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @tlchaffi,

Thank you for reporting this issue. This was not the only broken link, we have updated the majority. Please let us know if you notice any other broken links. The documentation will be updated with the upcoming release.

Thanks!
