### ISSUE TITLE
config_map_v1_data  same for secret_v1_data 

### ISSUE THREAD

**Issue by Davidffry** [hashicorp/terraform-provider-kubernetes#2233]
### Description

config_map_v1_data  same for secret_v1_data 

### Potential Terraform Configuration

```hcl
resource "kubernetes_secret_v1_data" "example" {
  metadata {
    name = "my-config"
  }
  data = {
    "owner" = "myteam"
  }
}
```

### References

Seems no References

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
@Davidffry Hello thank you for opening this issue. Looking at the current `config_map_v1_data` resource, you can actually copy the existing code and have it do the same operation but for `secret` by changing certain `config_map` values to `secret`. You can certainly open a PR adding this `secret_v1_data` resource if you'd like.
