### ISSUE TITLE
Bug in documentation for Pod Security Policies

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [hashicorp/terraform-provider-kubernetes#2234]
Hello, 

auditor scanned our eks, and found that we are not using PSP. 

in modules i found that it is exist and there are no warnings, that it is decomissioned on kubernetes side: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod_security_policy_v1beta1

so, would it be possible to add some kind of warning, that resource is not working anymore?

it is applicable for:
* https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod_security_policy_v1beta1
* https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod_security_policy

**Comment by BBBmau** [comment]
Hello thank you for opening this issue @iaroslav-nakonechnikov 

We've decided to keep the `PodSecurityPolicy` resource until it is not supported on the [k8s client go](https://pkg.go.dev/k8s.io/client-go/kubernetes)

We will however include warning messages for the resource advising users that it is deprecated and will not work after v1.25
