### ISSUE TITLE
`kubernetes_node_taints` causing overwrite when applying with `kubernetes_labels`

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-kubernetes#2247]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.4.5
Kubernetes provider version: v2.23.0
Kubernetes version: v1.25.3
```

### Affected Resource(s)
- `kubernetes_labels`
- `kubernetes_node_taints`

### Terraform Configuration Files
```hcl
resource "kubernetes_node_taint" "taint_workers_dcc" {
  metadata {
    name = "minikube"
  }
  taint {
    key    = "zone"
    value  = "onprem-dcc"
    effect = "NoSchedule"
  }
}

resource "kubernetes_labels" "nodes" {
  api_version = "v1"
  kind        = "Node"

  metadata {
    name = "minikube" 
  }

  labels = {
    test = "test"
  }

}

```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Expected Behavior
What should have happened?

Should apply resource successfully after first apply and not attempt to apply on the second apply

### Actual Behavior
What actually happened?

on second apply it will apply the node taints despite already creating it in the first apply.

The third apply will result in the labels from `kubernetes_labels` to be missing leading it needing to be created once more

### References

- [GH-1234](https://github.com/hashicorp/terraform-provider-kubernetes/issues/2023)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redsux** [comment]
As a workaround I modify the `field_manager` on one of those resources.  
Seems to be enough to avoid overwriting the `managedFields` in K8S.
