### ISSUE TITLE
`kubernetes_pod_v1` considers Pod's final status `Completed` as failure

### ISSUE THREAD

**Issue by drmoeller** [hashicorp/terraform-provider-kubernetes#2249]
Hi there,

I've configured Terraform resource of type `kubernetes_pod_v1` with field

  `spec.restart_policy = "OnFailure"`

After application I'm confronted with Terraform error message

```
Error: unexpected state 'Succeeded', wanted target 'Running'. last error: %!s(<nil>)
```

Maybe this Pod's command executes that quickly that Terraform Provider "only" sees final state `Completed`, and not something like `Running` in between. So, as a workaround, adding some `sleep` command might "trick" the Provider with expected, but very ephemeral `Running` state.

Nevertheless, I think, in this context a final state `Completed` is totally valid (Kubernetes seems to agree on this), so the Provider should accept it; especially--or maybe **only**?--if `restart_policy` has been configured to `OnFailure`.

### Terraform Version, Provider Version and Kubernetes Version

```
$ terraform -version
Terraform v1.5.6
on linux_amd64
[...]
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0


$ kubectl --context [...] version --short
[...]
Server Version: v1.25.11
```

### Affected Resource(s)

- `kubernetes_pod_v1`

### Steps to Reproduce

```
terraform apply

[...]

kubernetes_pod_v1.FOO: Creating...
╷
│ Error: unexpected state 'Succeeded', wanted target 'Running'. last error: %!s(<nil>)
│    * secret-grabbing-workaround (Pod): PolicyViolation: policy require-run-as-nonroot/run-as-non-root fail: validation error: Running as root is not allowed. Either the field spec.securityContext.runAsNonRoot must be set to `true`, or the fields spec.containers[*].securityContext.runAsNonRoot, spec.initContainers[*].securityContext.runAsNonRoot, and spec.ephemeralContainers[*].securityContext.runAsNonRoot must be set to `true`. rule run-as-non-root[0] failed at path /spec/securityContext/runAsNonRoot/ rule run-as-non-root[1] failed at path /spec/containers/0/securityContext/
│ 
│   with kubernetes_pod_v1.FOO,
│   on alerting_attempt.tf line 184, in resource "kubernetes_pod_v1" "FOO":
│  184: resource "kubernetes_pod_v1" "FOO" {
│
```

### Expected Behavior

Accepting final state `Completed` of Kubernetes Pod (maybe depending on Pod's `restart_policy` configuration).

### Actual Behavior

Only accepting Pod's final state `Running` as valid outcome.

**Comment by arybolovlev** [comment]
Hi @drmoeller,

There are 5 valid values for a Pod phase: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase

By default, the provider expects it to be `Running`, however, you can change it with the [target_state](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod_v1#target_state) argument. This enhancement has been added in version 2.23.0.

Usage example:

```hcl
resource "kubernetes_pod_v1" "this" {
  metadata {
    name = "this"
  }
  spec {
    container {
      image = "image"
      name  = "this"
    }
  }
  target_state = [
    "Succeeded",
  ]
}
```
