### ISSUE TITLE
kubernetes_manifest for Karpenter Provisioner CRD throws "Error: Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by ecerulm** [hashicorp/terraform-provider-kubernetes#2264]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.5.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.15.0
+ provider registry.terraform.io/hashicorp/helm v2.11.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0

Your version of Terraform is out of date! The latest version
is 1.5.6. You can update by downloading from https://www.terraform.io/downloads.html

```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
# https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest
resource "kubernetes_manifest" "dataiku-provisioner" {
  manifest = {
    apiVersion = "karpenter.sh/v1alpha5"
    kind       = "Provisioner"
    metadata = {
      name = "dataiku"
    }
    spec = {
      limits = {
        resources = {
          cpu    = "100"
          memory = "500Gi"
        }
      }
      providerRef = {
        name = kubernetes_manifest.dataiku-nodetemplate.manifest.metadata.name
      }
      consolidation = {
               enabled = false
      }
      taints = [
        {
          key    = "example.com/dataiku"
          effect = "NoSchedule"
        }
      ]

      annotations = {
        "example.com/owner" = "dataiku"
      }

      requirements = [
        {
          key      = "karpenter.k8.aws/instance-category"
          operator = "In"
          values   = ["c", "m", "r"] # c = compute optimized, t=general purpose
        },
        {
          key      = "karpenter.k8s.aws/instance-generation"
          operator = "Gt"
          values   = ["2"]
        },
        {
          key      = "kubernetes.io/arch"
          operator = "In"
          values   = ["amd64"]
        },
        {
          key      = "karpenter.sh/capacity-type"
          operator = "In"
          values   = ["spot", "on-demand"]
        },
      ]
      ttlSecondsUntilExpired = 172800 #  43200 = 12 hours, 86400 = 1 day, 172800 = 2 days
      ttlSecondsAfterEmpty   = 900    # 900s = 15 minutes, 3600s = 1hour,
    }
  }
  depends_on = [helm_release.karpenter]
}
```

### Expected Behavior
What should have happened?

### Actual Behavior
terraform apply failed with 

```
terraform apply latest.tfplan
kubernetes_manifest.dataiku-provisioner: Destroying...
kubernetes_manifest.dataiku-provisioner: Destruction complete after 0s
kubernetes_manifest.dataiku-provisioner: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to kubernetes_manifest.dataiku-provisioner, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.spec.requirements: new element 4
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Important Factoids

Provisioner is a CRD defined at https://github.com/aws/karpenter/blob/main/pkg/apis/crds/karpenter.sh_provisioners.yaml 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jasonhuling** [comment]
I'm getting the same error in a similar situation using custom resources. My error is specifically for a custom operator using the kopf python framework on the annotation:
```
When applying changes to kubernetes_manifest.foo, provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.metadata.annotations["kopf.zalando.org/last-handled-configuration"]: 
```
I'm also using `provider registry.terraform.io/hashicorp/kubernetes v2.23.0`.

I tried to workaround it by adding an ignore changes lifecycle but that didn't work:
```
  lifecycle {
    ignore_changes = [
      manifest.metadata[0].annotations["kopf.zalando.org/last-handled-configuration"]
    ]
  }
```

**Comment by shysank** [comment]
You'll need to add those fields to `computed_fields` https://github.com/hashicorp/terraform-provider-kubernetes/issues/1587#issuecomment-1028282978

**Comment by ecerulm** [comment]
But in my case ` unexpected new value: .object.spec.requirements: new element 4` what is happening is that although the `.spec.requirements` that I'm providing has 4 elements, a fifth element is been added automatically

```
        {
          key      = "kubernetes.io/os"
          operator = "In"
          values   = ["linux"]
        }
``` 

I don't know how ignore such addition via `computed_fields`, I solved by actually adding the 5th element to `.spec.requirements`, But what will be the most appropriate way to deal with this? Am I supposed to mark the whole `.spec.requirements` as a computed field?

**Comment by alexsomesan** [comment]
@ecerulm The recommended approach is, as suggested above, to mark the filed `spec.requirements` as computed, like this:
```
resource "kubernetes_manifest" "dataiku-provisioner" {
 computed_fields = ["spec.requirements"]
...
```

Let us know if that resolves your issue.

**Comment by ecerulm** [comment]
Yes, that resolves the issue too. I wrote https://github.com/hashicorp/terraform-provider-kubernetes/pull/2279 to add some mention of `Error: Provider produced inconsistent result after apply` and `unexpected new value` in the documentation page for [kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#computed-fields)
