### ISSUE TITLE
Support spec.persistentVolumeClaimRetentionPolicy in `kubernetes_stateful_set`

### ISSUE THREAD

**Issue by jclangst** [hashicorp/terraform-provider-kubernetes#2282]
### Description
Support spec.persistentVolumeClaimRetentionPolicy in `kubernetes_stateful_set`

### Potential Terraform Configuration

```hcl
resource "kubernetes_stateful_set" "example" {
  spec {
    persistent_volume_claim_retention_policy   = {
     when_deleted = "Delete/Retain"
     when_scaled = "Delete/Retain"
   }
 }
}
```

### References

[Kubernetes docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by renzedj** [comment]
Ran across this same issue this morning, will likely be using a `kubernetes_manifest` as a workaround for now.
