### ISSUE TITLE
Provider configuration is ignored and wrong cluster is modified on apply

### ISSUE THREAD

**Issue by oferca** [hashicorp/terraform-provider-kubernetes#2295]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.3.9, 1.5.7
Kubernetes provider version: v1.13.4
Kubernetes version: Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GoVersion:"go1.19.4",  Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-2d98532", GoVersion:"go1.19.6", Platform:"linux/amd64"}
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 1.1.9"
  required_providers {
  aws = {
    source  = "hashicorp/aws"
    version = "4.48.0"
  }
}
}
// Note that NEITHER local.eks_cluster_name nor data.aws_eks_cluster exist in root module, they exist in completely unrelated folder with different cluster config. **This should have resulted in validation error**
provider "kubernetes" {
  alias                  = "v1beta1"
  host                   = data.aws_eks_cluster.staging.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.staging.certificate_authority[0].data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  load_config_file       = false
  version                = "~> 1.9"
  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "aws"
    args = ["eks", "get-token", "--cluster-name", local.eks_cluster_name]
  }
}
resource "kubernetes_config_map" "aws_auth" {
    binary_data = {}
    data        = {
        "mapRoles" = var.map_roles
        "mapUsers" = var.map_users
    }
    metadata {
        name             = "aws-auth"
        namespace        = "kube-system"
    }
  }
```

### Debug Output
module.karpenter_infra.module.config_map_aws_auth[0].kubernetes_config_map.aws_auth will be updated in-place
  ~ resource "kubernetes_config_map" "aws_auth" {
      ~ data        = {
          ~ "mapRoles" = <<-EOT
                - groups:
                  - system:masters
                  rolearn: arn:aws:iam::account_1:role/AWSReservedSSO_FullAdmin_xxx
                  username: devops:{{SessionName}}
             ....
              + - groups:
                  - system:bootstrappers
                  - system:nodes
              -   rolearn: arn:aws:iam::account_1:role/eksctl-**WRONG_CLUSTER**-eks-node-NodeInstanceRole-xxxxxxx
              +   rolearn: arn:aws:iam::account_1:role/eksctl-**TARGET_CLUSTER**-ek-NodeInstanceRole-xxxxxxxx
                ....

### Steps to Reproduce
1. `kubectl config use-context WRONG_CLUSTER` 

2. `terraform apply` in folder with TARGET_CLUSTER provider configuration --> WRONG_CLUSTER configuration gets modified

### Expected Behavior
Validation error as neither local.eks_cluster_name nor data.aws_eks_cluster exist. 

### Actual Behavior
Config map aws-auth  in **an unrelated (cached ?) cluster** got modified

**Comment by BBBmau** [comment]
Hello @oferca thank you for opening this issue. Could you provide more context to this issue by including a trace of when you get the output? This can be done by running `TF_LOG=trace terraform apply`

**Comment by oferca** [comment]
@BBBmau I have gained additional insight to the issue.
It appears that the bug is that modules **must use [providers meta argument](https://developer.hashicorp.com/terraform/language/meta-arguments/module-providers#default-behavior-inherit-default-providers)** when leveraging kubernetes resources.
Without a provider's block the kubernetes context is taken from kubectl, **in contradiction with [terraform's provider inheritence pattern](https://developer.hashicorp.com/terraform/language/meta-arguments/module-providers#default-behavior-inherit-default-providers)** which specifies it should be taken from the root module.
```
module "some-k8s-module" {
    source = "../modules/k8s-module"\
    
     // The bug: without below provider meta argument k8s context is wrongly taken from kubectl and not from root provider
     providers = {
        kubernetes = kubernetes.v1beta1
    }
}
```

**Comment by alexsomesan** [comment]
@oferca There is a small difference between your use-case and what is described in [terraform's provider inheritence pattern](https://developer.hashicorp.com/terraform/language/meta-arguments/module-providers#default-behavior-inherit-default-providers). That documentation states that only default providers (ones without an alias) will be inherited in case no `providers` block is present on the module. In your case, the configuration that you shared shows a provider block WITH an alias, thus not subject to that rule.

Not related to the above, the Kubernetes provider will not automatically pick up any configuration present in a kubeconfig file unless explicitly instructed so by either setting the `config_path` attribute or the `KUBE_CONFIG_PATH` environment variable. Can you please confirm that your environment does not include any variables specific to the Kubernetes provider?
