### ISSUE TITLE
emptyDir with medium hugepages is not supported

### ISSUE THREAD

**Issue by trunet** [hashicorp/terraform-provider-kubernetes#2302]
As defined here: 
https://github.com/hashicorp/terraform-provider-kubernetes/blob/32a58d2a6acf5443c35b6d8a0c5e5294a60740a6/kubernetes/schema_pod_spec.go#L676

I got when defining medium HugePages-2Mi:
`│ Error: "spec.0.template.0.spec.0.volume.2.empty_dir.0.medium" must contain a value from []string{"", "Memory"}, got "HugePages-2Mi"`

This is allowed as showed here: https://kubernetes.io/docs/tasks/manage-hugepages/scheduling-hugepages/

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.5.7
Kubernetes provider version: v2.23.0
Kubernetes version: 1.28.2
```

### Affected Resource(s)

- kubernetes_deployment_v1

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment_v1" "foo" {
  metadata {
    name      = "foo"
    namespace = "foo"

    labels = {
      "app.kubernetes.io/name" = "foo"
    }
  }

  spec {
    replicas = 1

    strategy {
      type = "Recreate"
    }

    selector {
      match_labels = {
        "app.kubernetes.io/name" = "foo"
      }
    }

    template {
      metadata {
        labels = {
          "app.kubernetes.io/name" = "foo"
        }
      }

      spec {
        container {
          name              = "foo"
          image             = "alpine:latest"
          resources {
            requests = {
              hugepages-2Mi = "500Mi"
              memory = "500Mi"
            }
            limits = {
              hugepages-2Mi = "500Mi"
              memory = "1Gi"
            }
          }
          volume_mount {
            name      = "hugepages"
            mount_path = "/dev/hugepages"
          }
        }
        volume {
          name = "hugepages"
          empty_dir {
            medium = "HugePages-2Mi"
          }
        }
      }
    }
  }
}
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
It should create /dev/hugepages

### Actual Behavior
It fails to apply

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sheneska** [comment]
Hi @trunet, The reason this is throwing an error is because implementing `validateAttributeValueIsInAndContain` in this way may be too imprecise as values that should match exactly might match as sub-strings and vice versa. Ideally the `ValidateFunc` should take two lists as arguments: one for exact matches and one for prefix (not sub-string) matches. For prefixes, it's good to ensure that they actually use [prefix matches](https://pkg.go.dev/strings#HasPrefix) instead of strings.
