### ISSUE TITLE
Add equivalent of `kubectl rollout restart`

### ISSUE THREAD

**Issue by foosinn** [hashicorp/terraform-provider-kubernetes#2304]
### Description

This would allow terraform to restart deployments. Especially useful after deploying other things

### Potential Terraform Configuration

```hcl
resource "kubernetes_rollout_restart" "restart_applciation" {
  apiVersion = "apps/v1"
  kind = "Deployment"

  metadata = {
    "name": "nginx"
    "namespace": "myapp"
  }

  restart_on_create = true  # default value
  restart_on_destroy = true  # default value
}
```

### References

This would provide a much cleaner alternative to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/master/modules/acm/creds.tf#L85-L99, that also respects current context and network settings.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
The way `kubectl rollout restart` works is by patching the deployment template with the `kubectl.kubernetes.io/restartedAt` annotation. Rather than adding a new resource for this, you could use the [kubernetes_annotations](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/annotations) resource to do the same thing:

```terraform
resource "time_static" "restarted_at" {}

resource "kubernetes_annotations" "example" {
  api_version = "apps/v1"
  kind        = "Deployment"
  metadata {
    name = "nginx-deployment"
  }
  template_annotations = {
    "kubectl.kubernetes.io/restartedAt" = time_static.restarted_at.rfc3339
  }
}
```
