### ISSUE TITLE
Kubernetes Resource Replacement Logic

### ISSUE THREAD

**Issue by erezblm** [hashicorp/terraform-provider-kubernetes#2325]
## Question

Hey all,

I was wondering what is the logic that dictates whether a certain Kubernetes resource will be replaced, or modified in place.
Specifically intended for a kubernetes_manifest of a custom resource, but generally for any other Kubernetes resource as well.

My context is using the "kubernetes_manifest" for deploying a Kafka topic through a custom resource (provided by Strimzi). The resource is required to be replaced after any configuration change i'm about to make, and i'm not sure that it is necessary at all. 
Such replacement will cause the deletion of the topic storage which is a highly destructive action.

Thanks, Erez.

**Comment by arybolovlev** [comment]
Hi @erezblm,

When it comes to standard resources(non-customs) resources, you can refer to the resource schema in our source code. If an attribute has field [`ForceNew`](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#forcenew) set to `true`, then any change of this attribute will trigger resource replacement. A basic example here would be [`metadata.name`](https://github.com/hashicorp/terraform-provider-kubernetes/blob/main/kubernetes/schema_metadata.go#L37). In all other cases, the provider will patch/update resources in place, or in other words, will update only the changed attribute.

`kubernetes_manifest` renders schema on flight and if any of CRD attributes with `x-kubernetes-preserve-unknown-fields: true` then Terraform will replace a CR if any of the fields were changed. [Here](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1928#issuecomment-1341043424) you can find a more detailed answer.

I hope that helps.

Thanks.

**Comment by erezblm** [comment]
Thanks @arybolovlev , it was very helpful
you helped me to understand the reason for replacing the resources which is 'x-kubernetes-preserve-unknown-fields'
