### ISSUE TITLE
kubernetes_cron_job_v1 creates Jobs with apiVersion batch/v1beta1

### ISSUE THREAD

**Issue by ppaulis** [hashicorp/terraform-provider-kubernetes#2370]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.6.6
Kubernetes Provider version: 2.24.0
Kubernetes version: 1.24.10
```
## Terraform configuration
```hcl
resource "kubernetes_cron_job_v1" "my_cronjob" {
  metadata {
    name = "my-cronjob"
    namespace = "my-workspace"
  }
  spec {
    concurrency_policy            = "Replace"
    failed_jobs_history_limit     = 1
    schedule                      = "0 5 * * *"
    starting_deadline_seconds     = 10
    successful_jobs_history_limit = 1
    job_template {
      metadata {}
      spec {
        backoff_limit              = 2
        ttl_seconds_after_finished = 10
        template {
          metadata {}
          spec {
            volume {
              name = "secrets"
              secret {
                secret_name = "phing"
                default_mode = "0400"
              }
            }

            container {
              image = "..."
              name = "..."
              image_pull_policy = "Always"
              command = ["..."]

              volume_mount {
                mount_path = "/etc/secrets"
                name = "secrets"
                read_only = true
              }
            }
          }
        }
      }
    }
  }
}
```

## Question
I need to upgrade my AKS cluster from **1.24.10** to at least **1.25.x**. Before doing this, I need to replace all cronjobs with apiVersion `batch/v1beta1`.

I thought I could do this by using the resource `kubernetes_cron_job_v1` instead of `kubernetes_cron_job`. But the created jobs still have the old `batch/v1beta1` api version. I renamed the jobs to make sure, that it's not a replacement issue.

Here's an example of the output :
```
kind: CronJob
apiVersion: batch/v1beta1                  <================= apiVersion remains incorrect
metadata:
  name: ...
  namespace: ...
  uid: 57c9e07e-...
  resourceVersion: '...'
  generation: 1
  creationTimestamp: '2023-12-18T11:41:45Z'
  managedFields:
    - manager: HashiCorp
      operation: Update
      apiVersion: batch/v1                  <================ apiVersion is now correct
      time: '2023-12-18T11:41:45Z'
      fieldsType: FieldsV1
...
```

If someone could help me out here, that would be greatly appreciated :-)
Thanks,
Pascal

**Comment by BBBmau** [comment]
Hello @ppaulis, I'm unsure of your question since you are wanting to replace all cronjobs with `batch/v1beta1` however you are already using the resource that creates `batch/v1beta1` by using `kubernetes_cron_job`

Also a headsup that the use of `batch/v1beta1` has been deprecated in k8s since v1.21 and was completely removed from serving as of v1.25

https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-25#cronjob-v125

I'll update the docs to include this.

**Comment by ppaulis** [comment]
Hi @BBBmau !
I was trying to get rid of the `v1beta1` by replacing `kubernetes_cron_job` with `kubernetes_cron_job_v1`. Initially I thought, that this didn't work. But it seems that this is related to the Kubernetes Dashboard. Displaying a v1-cronjob on my cluster through the Dashboard still shows `v1beta1`, whereas displaying the resource through `kubectl` shows that it's fine. In addition to this, AKS Monitoring confirmed now, that the `v1beta1` is gone, despite the Kubernetes Dashboard still showing `v1beta1`. So, finding out why the dashboard shows something, is the next step. But that's not for here :-)

So, sorry for the unnecessary issue and thanks for the help!
