### ISSUE TITLE
Support `JobBackoffLimitPerIndex` feature gate fields

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-kubernetes#2398]
### Description

Several fields should be added with `JobBackoffLimitPerIndex` graduating to Beta in v1.29

Fields

JobSpec

- [ ] backoffLimitPerIndex
- [ ] maxFailedIndexes

JobStatus
- [ ] failedIndexes

[Related PR
](https://github.com/kubernetes/kubernetes/pull/121356)

### Potential Terraform Configuration

[Reference to v1.29 Release Note
](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#v1290:~:text=Graduated%20Job%20BackoffLimitPerIndex%20feature%20to%20beta.%20(%23121356%2C%20%40mimowo))

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by theloneexplorerquest** [comment]
\assign

**Comment by theloneexplorerquest** [comment]
I would like to work on this one :smiley:
