### ISSUE TITLE
Use of `template_file` preventing init on M1/2 Mac

### ISSUE THREAD

**Issue by aneal** [hashicorp/terraform-provider-kubernetes#2420]
### Terraform, Provider, Kubernetes and Helm Versions

```
Terraform version: 1.5.5
Terragrunt: 0.48.0
Provider version: helm 2.12.1
Kubernetes version: 1.27.9
```

### Affected Resource(s)
Terraform/terragrunt init won't complete

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
- build_cluster in ../../modules/eks_worker_nodes
- eks_auth in ../../modules/eks_auth
- software in ../../modules/eks_software
Downloading git::ssh://git@github.com/turnercode/cp-terraform-modules.git?ref=remove_old_modules for software.efs_kms_key...
- software.efs_kms_key in .terraform/modules/software.efs_kms_key/kms

Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 4.0.0, ~> 5.0"...
- Finding hashicorp/kubernetes versions matching "~> 2.25.2"...
- Finding hashicorp/helm versions matching "~> 2.12.1"...
- Finding latest version of hashicorp/template...
- Installing hashicorp/aws v5.36.0...
- Installed hashicorp/aws v5.36.0 (signed by HashiCorp)
- Installing hashicorp/kubernetes v2.25.2...
- Installed hashicorp/kubernetes v2.25.2 (signed by HashiCorp)
- Installing hashicorp/helm v2.12.1...
- Installed hashicorp/helm v2.12.1 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

### Code loading provider `hashicorp/template`

https://github.com/hashicorp/terraform-provider-kubernetes/blob/v2.25.2/_examples/google-gke-nfs-filestore/main.tf#L95-L112

### Steps to Reproduce

1. `terraform init` on any M1/2/3 Apple Macbook

### Expected Behavior
template_file should no longer be used as the provider is old and only available for intel platforms.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Thanks for opening this issue @aneal. This was a good catch and we'll be working on updating the gke example to use `templatefile()` function as discussed in [`hashicorp/template` provider repo](https://github.com/hashicorp/terraform-provider-template/issues/85)
