### ISSUE TITLE
kubernetes_manifest applies null resources

### ISSUE THREAD

**Issue by rwe-dtroup** [hashicorp/terraform-provider-kubernetes#2427]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:  v1.7.3
Kubernetes Provider version: v2.26.0
Kubernetes version: v1.28
```
## Terraform configuration
```hcl
...
"blockDeviceMappings" = [
        for mapping in local.final_block_device_mappings : {
          "deviceName" = mapping.device_name
          "ebs" = {
            "volumeSize"          = mapping.ebs.volume_size
            "volumeType"          = mapping.ebs.volume_type
            "iops"                = tonumber(mapping.ebs.iops)
            "encrypted"           = true
            "kmsKeyID"            = mapping.ebs.kms_key_id
            "deleteOnTermination" = tobool(mapping.ebs.delete_on_termination)
            "throughput"          = tonumber(mapping.ebs.throughput)
            "snapshotID"          = try(mapping.ebs.snapshot_id, null)
          }
        }
      ]
...
```

## Question

When using the kubernetes_manifest resource, the snapshotID is always passed as a null resource, this is not recorded in the manifest in the cluster and is not stored in the statefile so this is seen as a change every time terraform runs. Is it possible to not pass this option at all if it's null?

```hcl
~ blockDeviceMappings        = [
                  ~ {
                      ~ ebs        = {
                          + snapshotID          = null
                            # (7 unchanged attributes hidden)
                        }
```

**Comment by wombat** [comment]
I am having the same problem when provisioning Openshift Subscriptions.

My Terraform object variable looks like this:
```
env = optional(list(object({
  name  = string
  value = optional(string)
  valueFrom = optional(object({
    configMapKeyRef = object({
      key      = string
      name     = optional(string)
      optional = optional(bool)
    })
  }))
  })))
```

Terraform apply shows:
```
+ env       = [
                      + {
                          + name      = "WATCH_NAMESPACE"
                          + value     = "*"
                          + valueFrom = null
                        },
                    ]
```

After applying the Subscription it looks like this, which results in an error from the operator:
```
  config:
    env:
      - name: WATCH_NAMESPACE
        value: '*'
        valueFrom: {}
    resources: {}
```

**Comment by sheneska** [comment]
Hi @rwe-dtroup, what is the intended behavior of the `snapshot ID` attribute? Should a `null` value be passed with each `apply` ?

**Comment by rwe-dtroup** [comment]
> Hi @rwe-dtroup, what is the intended behavior of the `snapshot ID` attribute with the `try` expression? Should a `null` value be passed with each `apply` ?

No, if the value is null it should not be applying that attribute. TBH, I've moved away from this resource as not being able to use this when the cluster is not already built makes life more problematic than it needs to be.
