### ISSUE TITLE
kubernetes_stateful_set_v1 min_ready_seconds

### ISSUE THREAD

**Issue by tekicode** [hashicorp/terraform-provider-kubernetes#2469]
### Description

add min_ready_seconds to kubernetes_stateful_set_v1

### References

This is a stable feature since [Kubernetes v1.25](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#minimum-ready-seconds)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aayushsss1** [comment]
Hey I can take this up!
