### ISSUE TITLE
`kubernetes_namespace` data attribute not failing plan when passed a list of invalid namespaces

### ISSUE THREAD

**Issue by alekhrycaiko** [hashicorp/terraform-provider-kubernetes#2511]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.9
Kubernetes provider version: 2.30.0
Kubernetes version: 1.27
```

### Terraform Configuration Files
I've attached a simplified example of what I'm using

```hcl
locals {
# mix of invalid and valid namespaces.
 namespaces = [
    "test1235-namespacedoesntexist",
    "namespacealsodoesntexist"
    "valid-ns" 
 ] 
}
data "kubernetes_namespace" "namespaces" {
  for_each = toset(local.namespaces)
  metadata {
    name = each.key
  }
}
# passed into subsequent resources with for_each loop
# e.g.
resource "kubernetes_role_binding" "developer_role_binding" {
  for_each = toset([for item in data.kubernetes_namespace.namespaces : item.metadata[0].name])
   metadata {
      name = "unique-name-${each.value}" 
      namespace = each.value
  }
 role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "Role"
    name      = unique-name-${each.value}"
  }
  subject {
    kind      = "Group"
    name      = "test-role"
    api_group = "rbac.authorization.k8s.io"
  }
}
```

### Expected Behavior

When the data block is passed a mix of valid and invalid namespace names, I'd expect Terraform to fail at plan time because the resource does not exist.

### Actual Behavior

Terraform did not error out at plan time. Instead, a speculative plan was built with the anticipated namespace names being used for the kubernetes role binding. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by appilon** [comment]
Hello @alekhrycaiko ,

The datasource is working as intended, albeit a contentious topic on whether to error when something is not found in datasources. We have flip-flopped on it and recently [reverted a change](https://github.com/hashicorp/terraform-provider-kubernetes/pull/2464) that would have scenarios like this error. For now this will be the intended experience.

**Comment by alekhrycaiko** [comment]
@appilon thanks for getting back to me about this. Any chance there's an RFC, documentation or a thread somewhere discussing that design change?  Would it also be possible to get this behaviour documented in the provider documentation? Since many providers don't function this way, the explicit behaviour documented would've been helpful (it certainly would've saved me time). 

And on the above note, I'm curious what's stopping this behaviour from being a user choice (e.g. through a flag on the data resource itself).
