### ISSUE TITLE
│ Error: Post "https://1C699EDDF386B763D5BB53DC0FFDB7AB.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces/kube-system/serviceaccounts": dial tcp: lookup 1C699EDDF386BBAGTHNJKMAC0FFDB7AB.gr7.us-east-1.eks.amazonaws.com on 00.00.000.00:53: no such host

### ISSUE THREAD

**Issue by shashi559** [hashicorp/terraform-provider-kubernetes#2543]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version:
Kubernetes Provider version:
Kubernetes version:
```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question
```
Enter your question here.
```

**Comment by shashi559** [comment]
Cluster unreachable showing please updates if any resolution after terraform apply its throwing this error again if i give terraform apply it will success

**Comment by appilon** [comment]
Hello @shashi559 Unfortunately there is not nearly enough information to go on. I'd recommend a more appropriate title in the future and saving the error message details for the body of the issue. Please try and follow our template and provide relevant information, I'm going to close this issue, I'd recommend the community [Slack](https://kubernetes.slack.com/messages/CJY6ATQH4) for help
