### ISSUE TITLE
Run acceptance tests across multiple versions of Kubernetes

### ISSUE THREAD

**Issue by coryflucas** [hashicorp/terraform-provider-kubernetes#2562]
### Description

Per the discussion in [PR 2561](https://github.com/hashicorp/terraform-provider-kubernetes/pull/2561#issuecomment-2261450070) it'd be good to run the acceptance tests against multiple versions of Kubernetes to ensure that changes work across the different versions.

A couple questions I have with regards to this:
- What range of versions do we want to test against? My suggestion would be to a newer version of kind and use the latest minor versions supported by that version.  As an example we could use [kind v0.23.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.23.0) and Kubernetes versions 1.25-1.30.
- Do we want to make this change to the acceptance tests run against cloud providers? Given those have a cost associated and the kind tests should be covering roughly the same thing I would expect not.  If we do, what version range? If we don't, should we increase the version used in those?

pinging @BBBmau from the PR discussion.

### References

PR with initial discussion: [PR 2561](https://github.com/hashicorp/terraform-provider-kubernetes/pull/2561#issuecomment-2261450070)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
> What range of versions do we want to test against? My suggestion would be to a newer version of kind and use the latest minor versions supported by that version. As an example we could use [kind v0.23.0](https://github.com/kubernetes-sigs/kind/releases/tag/v0.23.0) and Kubernetes versions 1.25-1.30.

we actually have a range already when testing the manifest resource so we can have it match what already covers it there:
https://github.com/hashicorp/terraform-provider-kubernetes/blob/ef67d17661a4bab5fb34b2bf6e2f7829eb3b85ac/.github/workflows/manifest_acc.yaml#L28-L35

> Do we want to make this change to the acceptance tests run against cloud providers? Given those have a cost associated and the kind tests should be covering roughly the same thing I would expect not. If we do, what version range? If we don't, should we increase the version used in those?

Agreed that wouldn't do the multiple k8s test on the cloud provider tests, kind tests are sufficient.

Thanks for opening this @coryflucas !
