### ISSUE TITLE
remove `cephfs volume` support

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-kubernetes#2582]
### Description

The release of `v1.31` included the removal of `cephfs` volume support which was marked as deprecated in `v1.28`

`v1.31` mention: https://kubernetes.io/blog/2024/08/13/kubernetes-v1-31-release/#removal-of-cephfs-volume-plugin

https://github.com/hashicorp/terraform-provider-kubernetes/blob/65f1a7dd7d46d6e371e083f3e5ed0b0abca09daa/kubernetes/structure_persistent_volume_spec.go#L70-L89

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by JaylonmcShan03** [comment]
@BBBmau I can take this on for Q4 :)
