### ISSUE TITLE
"restart_policy" is wrongly documented at least for kubernetes_deployment resource

### ISSUE THREAD

**Issue by daniel-dona** [hashicorp/terraform-provider-kubernetes#2591]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: -
Kubernetes provider version: 2.32.0
Kubernetes version: -
```

### Affected Resource(s)
- documentation

### Important Factoids
This seems to start in a pretty old ticket https://github.com/kubernetes/kubernetes/issues/24725 as not all restart policies are supported depending on the resource kind. But this is not clear in the documentation, that just list the options but not if they apply to that resource type.

People then are facing a confusing error message like this one: 
`Unsupported value: "OnFailure": supported values: "Always"`

For me doesn't make a lot of sense to have an option that only have one valid value. But I think is more critical to proper document that. Lot's of frustrated people with this...

### References
- https://github.com/hashicorp/terraform-provider-kubernetes/blob/9d6074c763ed9d112c3f6145e30235a9b0758c4c/docs/resources/deployment.md?plain=1#L114
- https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#restart_policy

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Thanks for catching this. A fix is on the way.
