### ISSUE TITLE
kubernetes_namespace reads ~/.kube/config on startup, not after minikube has started

### ISSUE THREAD

**Issue by stephenwithav** [hashicorp/terraform-provider-kubernetes#2599]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.9.7-dev
Kubernetes provider version: 2.32.0 
Kubernetes version: 1.34.0
```

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "null_resource" "minikube_start" {
  provisioner "local-exec" {
    command = "minikube start"

    environment = {
      MINIKUBE_PROFILE = "flixtube"
    }
  }
}

resource "null_resource" "enable_registry" {
  depends_on = [null_resource.minikube_start]

  provisioner "local-exec" {
    command = "minikube addons enable registry"

    environment = {
      MINIKUBE_PROFILE = "flixtube"
    }
  }
}

resource "null_resource" "minikube_stop" {
  provisioner "local-exec" {
    when    = destroy
    command = "minikube delete"

    environment = {
      MINIKUBE_PROFILE = "flixtube"
    }
  }
}

resource "kubernetes_namespace" "flixtube" {
  depends_on = [null_resource.enable_registry]

  metadata {
    name = "flixtube"
  }
}
```

### Debug Output
https://gist.github.com/stephenwithav/c82414095f910c1be89b3b7c318006a8

### Steps to Reproduce
```
terraform init
terraform apply
```

### Expected Behavior
The `kubernetes_namespace` module shouldn't read `~/.kube/config` until after the `null_resource` blocks run.  Everything works if I start minikube first, but I'd love for the reading of `~/.kube/config` to be deferred.

### Actual Behavior
`kubernetes_namespace` attempts to access localhost instead of the minikube server at `192.168.x.x`.

### Important Factoids
Ubuntu 22.04.3

**Comment by arybolovlev** [comment]
Hi @stephenwithav,

This is not a bug. Terraform initialized all providers at start and Kubernetes cluster should be accessible at this stage. You need to separate cluster creation and KUbernetes resources management.
