### ISSUE TITLE
Manually deleting the service account token breaks state

### ISSUE THREAD

**Issue by rmb938** [hashicorp/terraform-provider-kubernetes#292]
### Terraform Version
```
Terraform v0.11.7
terraform-provider-kubernetes 1.5.0
```

### Affected Resource(s)
- kubernetes_service_account

### Terraform Configuration Files
```hcl
resource "kubernetes_service_account" "coordinator_sa" {
  metadata {
    name      = "es-coordinator-sa"
    namespace = "default"
  }
  automount_service_account_token = true
}
```

### Expected Behavior

No diff to be shown and nothing applied in kubernetes because nothing changed. Yes the service account token was deleted however that is dynamically generated from kubernetes and there is no way for terraform to manage that. Terraform should ignore service account secrets that have the annotation `kubernetes.io/service-account.name` since those are usually tokens managed by kubernetes.

An alternative would be make the `secret` list a computed value so even if it changes terraform won't care about it.

### Actual Behavior

```
~ kubernetes_service_account.coordinator_sa
secret.#:                    "1" => "0"
secret.1496436170.name: "es-coordinator-sa-token-s986p" => ""
```

A change diff is shown and the kubernetes service account is updated to have no secrets, this makes kubernetes generate a new token secret for the service account every time an apply happens.

### Steps to Reproduce

1. Delete the service account token for `es-coordinator-sa`
1. Run `terraform apply`
1. The diff for the service account will always show changes forever and the resource will constantly be updated creating tons of additional tokens.

**Comment by 23doors** [comment]
Just ran into this. As a workaround:
`terraform state pull > state`
edit it manually, find `kubernetes_service_account` that produces diff, remove both `secret.*` keys from it. And then:
`terraform state push state`

**Comment by 23doors** [comment]
Just ran into this. As a workaround had to:
1. edit service account in k8s directly - removed all secrets but 1
2. pulled TF state to file
3. in state: removed `state.*` keys of kubernetes_service_account that caused issues, changed `default_secret_name` to secret name that I left
4. pushed state
5. removed in k8s from secrets extra tokens that got created

Pretty nasty, but this is probably the only way to not requiring to re-create SA through TF (which isn't always an option).

**Comment by rmb938** [comment]
@alexsomesan Could you take a look at this? It still bites us every now and then so it would be useful if the provider could handle thing.

**Comment by abgm** [comment]
Do you guys already try to add 
`
lifecycle {
     ignore_changes = [secret]
}
`

Or something similar

**Comment by endzyme** [comment]
I would love for this to get some attention. If you rotate static secret tokens on service accounts (for security) then this causes lots of Terraform drift which can only be reconciled with either state surgery or recreation. You cannot get out of this loop by just applying TF state unfortunately.

**Comment by JordanP** [comment]
@endzyme does `lifecycle { ignore_changes = [secret] }` fix static secret tokens rotation for you ?

@abgm I think I am considering this too, since Mar 23 and your comment, do you still recommend that `ignore_changes` ?

**Comment by endzyme** [comment]
> @endzyme does `lifecycle { ignore_changes = [secret] }` fix static secret tokens rotation for you ?
> 
> @abgm I think I am considering this too, since Mar 23 and your comment, do you still recommend that `ignore_changes` ?

I would be hesitant to use the word "fix" for this workaround. Using ignore changes squelches the output, as noted above but really the provider should be able to detect the default secret based on what's set in the service account definition. 

The `ignore_changes` wasn't ideal in our scenario so we've opted not to go that route.
