### ISSUE TITLE
Feature Request: data kubernetes_service by labels selector(s)

### ISSUE THREAD

**Issue by trajakovic** [hashicorp/terraform-provider-kubernetes#308]
### Terraform Version
Terraform v0.11.11

### Affected Resource(s)
provider "kubernetes" (1.5.0)
- data kubernetes_service

### Terraform Configuration Files
```hcl
variable "kubectl_context_name" {
  type = "string"
}

provider "kubernetes" {
  config_context = "${var.kubectl_context_name}"
}


data "kubernetes_service" "elasticsearch" {
  "metadata" {
    namespace = "elasticsearch"

    labels {
      app = "elasticsearch"
      component = "client"
    }
  }
}

output "service_name" {
  value = "${data.kubernetes_service.elasticsearch.metadata.0.name}"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior

It would be beneficial that probably all datasources from kubernetes are selectable via labels, not by just names (i.e. some k8s parts are installed via helm_release, some not, and resource name is not under dev's control, but labels has some helm convention(s)).

### Actual Behavior
```
Error: Error refreshing state: 1 error(s) occurred:

* data.kubernetes_service.elasticsearch: 1 error(s) occurred:

* data.kubernetes_service.elasticsearch: data.kubernetes_service.elasticsearch: resource name may not be empty
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by ooraini** [comment]
Can this be reopened?
