### ISSUE TITLE
Feature Request: PodSecurityPolicies

### ISSUE THREAD

**Issue by xinau** [hashicorp/terraform-provider-kubernetes#362]
It would be nice to specify [PodSecurityPolicies](https://kubernetes.io/docs/concepts/policy/pod-security-policy/) from terraform.

**Comment by edward2a** [comment]
Slow wip...
https://github.com/edward2a/terraform-provider-kubernetes/tree/feature/add-pod-security-policy

**Comment by aareet** [comment]
This was implemented in https://github.com/hashicorp/terraform-provider-kubernetes/pull/861

**Comment by aareet** [comment]
Closing since this is already implemented.
