### ISSUE TITLE
Feature: Pod Security Policies

### ISSUE THREAD

**Issue by mitchellmaler** [hashicorp/terraform-provider-kubernetes#374]
Currently, there is not a way to manage Pod Security Policies using this provider.

**Comment by edward2a** [comment]
WIP - builds and apply/destroy seem to work.
Please test.
I have to adjust some parameter names to match the rest of the module and add tests/docs. 

https://github.com/edward2a/terraform-provider-kubernetes

**Comment by PaulWBrassard** [comment]
@edward2a Can we get an update on when this might get PR'ed?

**Comment by edward2a** [comment]
Hi @PaulWBrassard , someone else was working in a similar implementation which has a pending MR which follows a newer API and is pretty complete so I guess there is no need to finish the work I was doing.
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/624

**Comment by DrFaust92** [comment]
duplicate of #362

**Comment by aareet** [comment]
Closing in favour of #362 - we will track progress there.
