### ISSUE TITLE
Feature: allowed_topologies field in kubernetes storage class

### ISSUE THREAD

**Issue by tokiwong** [hashicorp/terraform-provider-kubernetes#391]
### Terraform Version
Terraform v0.11.11

### Kubernetes Version
Kubernetes 1.12.7, eks.1

### Affected Resource(s)
- kubernetes_storage_class

### Important Factoids
The `zone` and `zones` parameters have been deprecated as of kubernetes 1.13, and have been replaced with [allowedTopologies](https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies)

### Example
```
resource "kubernetes_storage_class" "example" {
  metadata {
    name = "terraform-example"
  }
  storage_provisioner = "kubernetes.io/aws-ebs"
  volume_binding_mode = "WaitForFirstConsumer"
  reclaim_policy = "Retain"
  parameters {
    type = "gp2"
  }
  allowed_topologies {
    match_label_expressions {
      key = "failure-domain.beta.kubernetes.io/zone"
      values = [
        "us-east-1a",
        "us-east-1b"
      ]
    }
  }
}
```

**Comment by rdelcampog** [comment]
Need this 😇

**Comment by dak1n1** [comment]
Closing since this was released some time ago.
