### ISSUE TITLE
New Resource: kubernetes_certificate_signing_request for TLS

### ISSUE THREAD

**Issue by dijitali** [hashicorp/terraform-provider-kubernetes#447]
We use TLS certificates generated by the K8s CA to secure traffic to several `ClusterIP` services and trust them within the cluster.

We'd like to manage this from Terraform but would need the CertificateSigningRequest resource to be supported and a method of approving it similar to: `kubectl certificate approve`.  

Perhaps these would be best combined into a single Terraform resource with a boolean toggle option for auto-approval?

Example configuration:

```
resource "tls_cert_request" "my-service-csr" {
  key_algorithm   = "ECDSA"
  private_key_pem = "${file("private_key.pem")}"

  subject {
    common_name  = "my-service.default.svc.cluster.local"
    organization = "ACME Examples, Inc"
  }
}

resource "kubernetes_certificate_signing_request" "my-cert" {
  name        = "my-cert"
  request     = "${tls_cert_request.my-service-csr}"
  usages      = ["digital signature", "key encipherment", "server auth"]
  autoapprove = true
}
```

Relevant Links:
- [CertificateSigningRequest  API documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#certificatesigningrequest-v1beta1-certificates-k8s-io)
- [Kubernetes Guide: Manage TLS Certificates in a Cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)

**Comment by irpaglide** [comment]
If it results useful for anyone, this is my current workaround:
https://gist.github.com/irpaglide/3cd093c7f2188a1002afec2734425a8d

**Comment by jmgalvez** [comment]
Yes, it would be nice to have such as feature. 

Currently we have to use a bash script instead of terraform resources.

**Comment by dak1n1** [comment]
Closing since the fixed merged. It should be released later this week.

**Comment by devurandom** [comment]
Provider version 1.13 contains a kubernetes_certificate_signing_request resource. But how do I get the actual signed certificate?

**Comment by devurandom** [comment]
> Provider version 1.13 contains a kubernetes_certificate_signing_request resource. But how do I get the actual signed certificate?

The resource has an undocumented `certificate` attribute.

**Comment by dak1n1** [comment]
Good catch! I just updated the docs with an example that will show how to use it:

https://github.com/hashicorp/terraform-provider-kubernetes/blob/34cb0d9678f2ebddbcbb9288ee32397948e4fd01/website/docs/r/certificate_signing_request.html.markdown

**Comment by dak1n1** [comment]
Closing since this resource has been implemented.
