### ISSUE TITLE
Feature request: Support requests.ephemeral_storage

### ISSUE THREAD

**Issue by dambrisco** [hashicorp/terraform-provider-kubernetes#528]
Per https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage, the feature is currently in beta, but it's been around since Kubernetes 1.8. Completely understand if this would need to wait until the feature is officially out of beta (although it *is* mentioned in the v1 docs that this project has vendored here: https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/vendor/k8s.io/api/core/v1/types.go).

### Terraform Version
Terraform v0.12.2

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment
- anything that creates a kubernetes_pod

**Comment by rossigee** [comment]
Now that I've (manually) had to add the following to one of my deployments, I get an error when I attempt to manage the resource:

```yaml
        resources:
          limits:
            ephemeral-storage: 30Gi
          requests:
            ephemeral-storage: 20Gi
```

The error it gives me when I `terraform apply`...

```
Error: Invalid address to set: []string{"spec", "0", "template", "0", "spec", "0", "container", "0", "resources", "0", "limits", "0", "ephemeral-storage"}
```

Is there any way we can get it to at least just ignore the unsupported resource limits until they leave beta?

I tried the following on the off chance, but no such luck...

```yaml
  lifecycle {
    ignore_changes = [
      spec[0].template[0].spec[0].container[0].resources,
    ]
  }
```

**Comment by yzargari** [comment]
+1

**Comment by jerem991** [comment]
Any update ?

**Comment by kibnelbachyr** [comment]
Any updates on this, please?

**Comment by gemas** [comment]
Any news on this?

**Comment by monfardineL** [comment]
@aareet can't at least the hold be removed?

**Comment by dak1n1** [comment]
Closing since feature was released with version 2.x. Tested with this example:

```
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.3.1"
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "kubernetes_deployment" "example" {
  metadata {
    name = "terraform-example"
    labels = {
      test = "MyExampleApp"
    }
  }
  spec {
    replicas = 1
    selector {
      match_labels = {
        test = "MyExampleApp"
      }
    }
    template {
      metadata {
        labels = {
          test = "MyExampleApp"
        }
      }
      spec {
        container {
          name  = "example"
          image = "bash"
          command = ["/bin/sleep"]
          args = ["120s"]

          resources {
            limits = {
              "ephemeral-storage" = "2Gi"
            }
            requests = {
              "ephemeral-storage" = "1Gi"
            }
          }
        }
      }
    }
  }
}
```
