### ISSUE TITLE
kubernetes_horizontal_pod_autoscaler for a deployment

### ISSUE THREAD

**Issue by worldspawn** [hashicorp/terraform-provider-kubernetes#562]
### Terraform Version
0.12.3

### Affected Resource(s)
- kubernetes_horizontal_pod_autoscaler

### Terraform Configuration Files
```hcl
resource "kubernetes_horizontal_pod_autoscaler" "source-file-processing" {
  metadata {
    name = "${terraform.workspace}-drawboard-services-source-file-processing"
  }
  spec {
    max_replicas = 3
    min_replicas = 2
    target_cpu_utilization_percentage = 50
    scale_target_ref {
      kind = "Deployment"
      name = "${terraform.workspace}-drawboard-services-source-file-processing"
    }
  }
}
```

### Expected Behavior
(from  kubectl.exe describe hpa)
```
 AbleToScale    True    SucceededRescale  the HPA controller was able to update the target scale to 2
```

### Actual Behavior
I get an autoscaler that doesn't work
(from  kubectl.exe describe hpa)
```
 AbleToScale  False   FailedGetScale  the HPA controller was unable to get the target's current scale: no matches for kind "Deployment" in group ""
```

### Steps to Reproduce
Try and setup an autoscaler for a resource of type Deployment. Do not specify api_version

### Important Factoids
Kubernetes is in my case running on azure.

When i set up the same using the cli I got something that worked. So I exported the yaml of two the resources created a different way and found the terraform one had in the scale target no apiVersion defined. The resource created by the command line had `apiVersion: extensions/v1beta1`. So i explicitly set that in my terraform config and i got a working resource.

I don't know if this is a bug per-se, my high degree of ignorance or perhaps this is a quirk of Azure's kubernetes offering but couldn't the provider have set the (optional) api_version field for me? Or maybe a hint in the docs?

**Comment by bdronneau** [comment]
In `scale_target_ref` object add `api_version = "extensions/v1beta1"`

```hcl
scale_target_ref {
      api_version = "extensions/v1beta1"
      kind = "deployment"
      name = "${terraform.workspace}-drawboard-services-source-file-processing"
    }
```

Ensure in your deployment you have `resources` block on `container` https://www.terraform.io/docs/providers/kubernetes/r/deployment.html#resources-1

**Comment by masinger** [comment]
+1

**Comment by lucaskjaero** [comment]
If you're coming across this in google now, you might also want to try `apps/v1` as the `api_version`.

**Comment by aareet** [comment]
Closing since the question appears to have been answered here.
