### ISSUE TITLE
Provider hangs during resource refresh against AKS

### ISSUE THREAD

**Issue by landro** [hashicorp/terraform-provider-kubernetes#606]
### Terraform Version

Terraform v0.12.6
provider.kubernetes 1.9.0

### Affected Resource(s)
all kubernetes resources

### Terraform Configuration Files
```hcl

provider "kubernetes" {
  version                  = "1.9.0"
  config_context_auth_info = "clusterUser_whatever_mycluster"
  config_context_cluster   = "mycluster"
}

```

### Debug Output
Error: rpc error: code = Unavailable desc = transport is closing

Error: Get https://mycluster-whatever-xxxxxxx.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/mynamespace/configmaps/mymap: acquiring a token for authorization header: acquiring a new fresh token: waiting for device code authentication to complete: autorest/adal/devicetoken: Error while retrieving OAuth token: Code Expired

### Expected Behavior
I should have been asked to log in, since kubectl would have done that.

### Actual Behavior
terraform hung, and I had to kill it

### Steps to Reproduce

Any terraform operation that performs a call against the kubernetes API

### References
It seems like terraform-provider-kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go tries to output a device code to os.Stderr, but I never see it, since os.Stderr belongs to the provider, and not terraform itself.

The relevant line of code:

    _, err = fmt.Fprintln(os.Stderr, *deviceCode.Message)

**Comment by marty2bell** [comment]
I seem to have the same issue, is there a fix or workaround for this?
I'm completely blocked trying to update an AKS cluster?

**Comment by sergiupantiru** [comment]
How I managed to work around this:
1. You fetch the AKS credentials before you run terraform and then you try any kubectl cmd. This way you will manage to auth.
2. when you fetch credentials for AKS, fetch the admin ones(param --admin). The admin account does not need to register, or at least in my case.

Hope it helps :)
