### ISSUE TITLE
Add service attribute that would return name of a NEG

### ISSUE THREAD

**Issue by jaceq** [hashicorp/terraform-provider-kubernetes#668]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.12

### Affected Resource(s)
kubernetes_service

### Expected Behavior
After defining a service and adding annotation that creates a standalone NEG (or in-fact a ingress NEG): 
```cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'```
 I'd like to able to fetch name of created NEG as an attribute. 
I mean something similar to attribute: kubernetes_service.some_name.load_balancer_ingress.0.ip

This would enable using standalone NEGs as a backend for HTTP(S) Load balancers.

Nam of created NEG is available as annotation right after creation (and is port specific):
```
      metadata.0.annotations.cloud.google.com/neg-status: "{\"network_endpoint_groups\":{\"80\":\"k8s1-71f753e6-default-example-80-9b3d0709\"},\"zones\":[\"europe-west1-b\",\"europe-west1-c\",\"europe-west1-d\"]}" => "
```
So it's 'k8s1-71f753e6-default-example-80-9b3d0709' in above example.

**Comment by JordanP** [comment]
That annotation looks like a JSON string, maybe you could use the [jsondecode](https://www.terraform.io/docs/configuration/functions/jsondecode.html) function.

**Comment by jaceq** [comment]
@JordanP Sure I can. It's not about being able to transform it, it's about being able to read it.

Basically flow I'd like to achieve is:
1. Create service with stand alone NEG
2. Use output from service - NEG name - in order to assign it as Load Balancer backend.

Now I cannot do it, as there is no way to read (well I found a 80% of time working hacky way but that is bad) that status annotation at the same run when service is created.

**Comment by alexsomesan** [comment]
Would it help to re-read the service using a kubernetes_service data-source?

See here for details: https://www.terraform.io/docs/providers/kubernetes/d/service.html

**Comment by alexsomesan** [comment]
#830 should improve the situation. After the create completes you should see the annotation on the service.

**Comment by jaceq** [comment]
@alexsomesan re-reading with data source requires either second run of TF or some workaround - as I understand normally resources are read prior to creation...
