### ISSUE TITLE
Apply annotations / labels to existing resources

### ISSUE THREAD

**Issue by jon-walton** [hashicorp/terraform-provider-kubernetes#692]
### Terraform Version
Terraform v0.12.15
+ provider.kubernetes v1.9.0

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_namespace
- most other kubernetes resources

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "kube_system_labels" {
  metadata {
    name        = "kube-system"
    annotations = {
      "linkerd.io/inject": "disabled"
    }
    labels      = {
      "config.linkerd.io/admission-webhooks": "disabled"
    }
  }
}
```

### Debug Output
```shell
Error: namespaces "kube-system" already exists

  on ..\modules\aks\kubernetes.tf line 35, in resource "kubernetes_namespace" "kube_system_labels":
  35: resource "kubernetes_namespace" "kube_system_labels" {
```

### Expected Behavior
I would like to apply annotations / labels to an existing namespace (kube-system). However I cannot use the `kubernetes_namespace` resource because the namespace already exists.

While I could import the namespace, or use kubectl to apply the annotation / label, that feels fragile, I also prefer not to call out to other executables within my terraform config

I would like to propose 2 new resources

- `kubernetes_annotation`
- `kubernetes_label`

which can be applied to any kubernetes resource

### Actual Behavior
Error due to the namespace already existing (which is actually also expected)

**Comment by pdecat** [comment]
Somewhat related to #238.

**Comment by atikhono** [comment]
Hi, I'm really looking forward to this feature. It is particularly useful when you need to configure Azure's OMS agent for scraping Prometheus metrics from kube-system Pods ini AKS: set `prometheus.io/scrape: "true"` annotation on existing coredns Deployment.

**Comment by mrpaws** [comment]
Does using the namespace data source to lookup the kubernetes namespace work? If known in advance it could work?

**Comment by bryankaraffa** [comment]
👍  on this... I tried getting around using `kubernetes_all_namespaces` datasources and `contains()` to check if namespace exists, and only create if not [with the labels provided]... but it only mitigates/prevents running into that namespace doesn't exist error if the namespace exists already during plan. It doesn't allow adding labels to an existing namespace like kube-system, or if two modules attempt to create the same namespace I presume it would fail as well:

```terraform
data "kubernetes_all_namespaces" "allns" {}

resource "kubernetes_namespace" "release_namespace" {
  # Only create namespace if namespace from var.release_namespace does not exist
  count = contains(data.kubernetes_all_namespaces.allns, var.release_namespace) ? 0 : 1
  metadata {
    name   = var.release_namespace
    labels = var.release_namespace_labels
  }
}
```

Agree an additional resource like `kubernetes_labels` or `kubernetes_annotations` would be helpful.  [AWS provider has a concept where certain resources have a *_tag resource as well to manage tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#managing-individual-resource-tags)

**Comment by den-is** [comment]
The same thing is required for configuring [CNI Add-on for AWS EKS using IAM Role for Service Account](https://docs.aws.amazon.com/eks/latest/userguide/cni-iam-role.html) (IRSA).
You need to annotate the `aws-node` service account with the newly created dedicated IAM Role ARN

**Comment by theFong** [comment]
Wanted add additional uses for this feature. I was looking to add annotation to services after running into issues deploying [ory/hydra via helm behind a GCE Load Balancer/ingress](https://github.com/ory/k8s/issues/113) and hoped there was a terraform resource for doing so. Current work around uses kubectl but definitely fragile/stop gap.

**Comment by aareet** [comment]
We'll investigate this when investigating https://github.com/hashicorp/terraform-provider-kubernetes/issues/723

**Comment by gingerhelp** [comment]
For anybody looking for a way to accomplish this while awaiting the proposed enhancement, here is what has worked well for me:

```
resource "null_resource" "default-namespace" {
  provisioner "local-exec" {
  command = <<EOT
set -e
mkdir -p ~/.kube/
mkdir -p $HOME/bin
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.7/bin/linux/amd64/kubectl
chmod +x kubectl
cp ./kubectl $HOME/bin/
export PATH=$PATH:$HOME/bin
az aks get-credentials --name ${var.env_name}-k8s --overwrite-existing --resource-group ${azurerm_resource_group.pyp.name}
**kubectl label namespaces default role=platform
kubectl annotate namespaces default test=123**
EOT
  }
}
```

**Comment by simongottschlag** [comment]
Hi!

I have started working on this in regards to adding labels to existing resources: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1562

If this PR goes through, adding annotations should be quite easy since it's just about the same logic.

Any feedback on the PR is appriciated, still working on the acceptance tests as of now and when they are done I'll move it from draft.

**Comment by GrigorievNick** [comment]
HI, I have a similar request, which I believe is very common for EKS users.
I need to change the default storage class from gp2 to something else(gp3 in my case)
The issue is that EKS creates storage class gp2 and makes it default, on their own.
So In kubectl, no issue, just call `kubectl annotate storage class gp2 storageclass.kubernetes.io/is-default-class=false`.
But there is no way to do it in terraform.

**Comment by GrigorievNick** [comment]
The same thing is required to change the default Storage class for EKS.
EKS does not give the ability do not create it from version 1.11.

**Comment by jrhouston** [comment]
I have open #1616 to address the labels part of this issue. I'd appreciate if anyone could build the branch and try it out and confirm that the resource makes sense for their workflow.
