### ISSUE TITLE
Support enableServiceLinks in PodSpec

### ISSUE THREAD

**Issue by JPMoresmau** [hashicorp/terraform-provider-kubernetes#693]
### Terraform Version
Terraform v0.12.7
+ provider.kubernetes v1.10.0

### Affected Resource(s)
- kubernetes_deployment
- kubernetes_pod

### Expected Behavior
Have a way to use enable_service_links in a deployment/pod spec

### Actual Behavior
`An argument named "enable_service_links" is not expected here.`

### References
https://github.com/kubernetes/kubernetes/pull/68754

Since environment variables can wreak havoc with some programs (most notably Apache Java apps), turning them off was requested.
Note that I can see enableServiceLinks in https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go

**Comment by abrzozowski-ITM** [comment]
StatefulSet is also affected.

**Comment by MathyV** [comment]
@aareet any chance of getting that PR reviewed?

**Comment by shd4** [comment]
Any updates on this? enableServiceLinks not being disabled produces a lot of pain...

**Comment by aareet** [comment]
The PR is waiting on an acceptance test being added.

**Comment by dak1n1** [comment]
It looks like we implemented this a while back but didn't update this issue. The `enable_service_links` option is present in the PodSpec now: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/pod#enable_service_links
