### ISSUE TITLE
Support backend_services as output in kubernetes_ingress

### ISSUE THREAD

**Issue by shaulishaked** [hashicorp/terraform-provider-kubernetes#709]
Hi there,

### Terraform Version
Terraform v0.12.2
+ provider.google v2.20.1
+ provider.google-beta v2.20.1
+ provider.kubernetes v1.9.0

### Affected Resource(s)
- kubernetes_ingress
- google_compute_backend_service

### Expected Behavior
When creating a K8s ingress, the backend-services are auto-generated with some different IDs.

Since there are features that we can enable on the backend services (security policies for example), it will be great if the backend services would be an output of the ingress.

### Actual Behavior
I cannot find a way to get the backend services created for the specific ingress, without a complex shell script.

### Steps to Reproduce
Try enabling security policies on backend services.

### Important Factoids
 - Google cloud infra.
 - (If there's another way to implement security policies via Terraform, that would be good too).

**Comment by JordanP** [comment]
You may want to control the service backend with GKE-specific service annotation: https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

**Comment by shaulishaked** [comment]
Hi :) Thanks for the quick reply.

How is this supported in Terraform? I didn't see the option of configuring a created backend-services to ingress resource.

Thanks,

**Comment by JordanP** [comment]
Yeah, I think I missed your point ! Sorry.

**Comment by shaulishaked** [comment]
No problem. I will be happy to get new ideas / other solutions as well.

Thanks,

**Comment by shaulishaked** [comment]
There are multiple configurations that can be configured only on the backend-service and not on the Ingres itself.
From WAF rules to Timeouts, we need to know the backend service auto-generated name to configure those stuff via Terraform, and currently, it's not supported from what I understand, right?

**Comment by mehdicopter** [comment]
Any update on this?
How did you do it @shaulishaked ?

**Comment by pdecat** [comment]
FWIW, there's a work-around for getting the backend services using the `kubernetes_ingress` datasource, e.g. for setting IAM policies:

```
data "google_iam_policy" "myapp" {
  binding {
    role = "roles/iap.httpsResourceAccessor"
    members = [
      "group:myteam@mydomain.com",
    ]
  }
}

data "kubernetes_ingress" "myapp" {
  metadata {
    namespace = "mynamespace"
    name      = "myapp"
    annotations = {
      # Internal annotations are removed if not defined in configuration
      "ingress.kubernetes.io/backends" = ""
    }
  }
}

resource "google_iap_web_backend_service_iam_policy" "policy" {
  for_each = toset([for backend in keys(jsondecode(data.kubernetes_ingress.myapp.metadata.0.annotations["ingress.kubernetes.io/backends"])) : backend if length(regexall("^k8s1.*", backend)) > 0])
  web_backend_service = each.value
  policy_data         = data.google_iam_policy.myapp.policy_data
}
```

**Comment by shaulishaked** [comment]
> Any update on this?
> How did you do it @shaulishaked ?

@mehdicopter I used a script to get the backend services and do the actions on them, using a "null_resource" to run it. However, I'd prefer to remove this code and use only Terraform resources.

> FWIW, there's a work-around for getting the backend services using the `kubernetes_ingress` datasource, e.g. for setting IAM policies:
> 
> ```
> data "google_iam_policy" "myapp" {
>   binding {
>     role = "roles/iap.httpsResourceAccessor"
>     members = [
>       "group:myteam@mydomain.com",
>     ]
>   }
> }
> 
> data "kubernetes_ingress" "myapp" {
>   metadata {
>     namespace = "mynamespace"
>     name      = "myapp"
>     annotations = {
>       # Internal annotations are removed if not defined in configuration
>       "ingress.kubernetes.io/backends" = ""
>     }
>   }
> }
> 
> resource "google_iap_web_backend_service_iam_policy" "policy" {
>   for_each = toset([for backend in keys(jsondecode(data.kubernetes_ingress.myapp.metadata.0.annotations["ingress.kubernetes.io/backends"])) : backend if length(regexall("^k8s1.*", backend)) > 0])
>   web_backend_service = each.value
>   policy_data         = data.google_iam_policy.myapp.policy_data
> }
> ```

@pdecat I'll check. Thanks for sharing your workaround :)

**Comment by dak1n1** [comment]
We're looking into adding a provider-level annotation ignore/allow list, which should fix the issue described here. Let's track this over here: https://github.com/hashicorp/terraform-provider-kubernetes/issues/746
