### ISSUE TITLE
Labels/annotations not being imported through terraform import

### ISSUE THREAD

**Issue by mixedCase** [hashicorp/terraform-provider-kubernetes#722]
Running `terraform import` on a bunch of resources does not import metadata labels nor annotations to state.

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0
+ provider.kubernetes v1.10.0

### Affected Resource(s)

I just reproduced it with kubernetes_cluster_role, kubernetes_cluster_role_binding, kubernetes_config_map, kubernetes_deployment, kubernetes_namespace, kubernetes_role, kubernetes_role_binding, kubernetes_service and kubernetes_service_account. But I assume it affects all resources with labels in metadata.

### Terraform Configuration Files

Partial example:

```hcl
locals {
  ingress_name = "ingress-nginx"
  ingress_labels = {
    "app.kubernetes.io/name"    = "ingress-nginx"
    "app.kubernetes.io/part-of" = "ingress-nginx"
  }
}

resource "kubernetes_namespace" "ingress_nginx" {
  metadata {
    name   = local.ingress_name
    labels = local.ingress_labels
  }
}
```

### Expected Behavior

Terraform import should've included label and annotation metadata in state.

### Actual Behavior

It didn't. JSON screenshot comparing some of the state of one of the resources in the environment where I initially created it, and to the right, the one where I tried to terraform import it:

![2020-01-02-15:38:24-screenshot](https://user-images.githubusercontent.com/9408318/71685108-1b8f7a00-2d76-11ea-8663-2cf8170abace.png)

### Steps to Reproduce

Instantiate the resource in one environment, try to import it in another one. Label metadata will be missing.

### Important Factoids

Not really important, but just in case it's useful as a testing scenario or w/e: this was found during a refactor where an environment controlled resources that were to be shared with another environment. As a solution, a separate (shared) environment was created and the resources imported to it so that terraform_remote_state could be used in each user environment.

NOTE: This was edited to add annotations after the fact, as I just noticed a resource that missed its annotations as well.

**Comment by elkbullwinkle** [comment]
I bumped into the same thing, I believe that it's related to the original stand that `kubernetes.io` labels are ignored, however with a recent change if those have been explicitly defined in the terraform file, these should be respected during import as well, otherwise after importing the resource on the next run it tries to modify the resource with explicitly defined labels, even though they already exist, just missing from the state files.

**Comment by DrFaust92** [comment]
Maybe we can filter well known labels like as specified here: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/ ?

similar to what is proposed here with tolerations https://github.com/hashicorp/terraform-provider-kubernetes/issues/955#issuecomment-681022027

I opened a PR for tolerations #978

**Comment by ixevix** [comment]
Running into this as well.

Terraform v0.12.29
