### ISSUE TITLE
Feature: have the possibility to have the YAML as output

### ISSUE THREAD

**Issue by flmmartins** [hashicorp/terraform-provider-kubernetes#738]
Hello all,

Some commands in kubectl can only be done if you have the YAML file like kubectl diff & etc...
So for us to not loose these features when we use terraform... I think it would be interesting to have the yaml files as output.

At least we can output it and later perform commands that require files.

**Comment by jrhouston** [comment]
Hi @flmmartins thanks for opening this issue. I'm not exactly sure what you mean when you say have the YAML files as output. Could you give me an example of how you would use this feature if it were implemented already?

The provider itself doesn't actually generate any YAML files, it makes calls directly to the kubernetes API based on what is written in HCL. Are you suggesting having an attribute on the resource, that could be used as an output, that would be equivalent to `kubectl get <resource> <name> -o yaml` ?

**Comment by curtbushko** [comment]
Hi,

This is doable in some go code but I don't really think it belongs in the terraform-provider-kubernetes. It sounds more like a tool to convert from terraform to yaml.

If using golang, you can use the hcl package for taking an HCL formatted file, what a terraform file is, creating a parseTree and then decoding the Object. Something like

`
result := &KubernetesObject{}

	hclParseTree, err := hcl.Parse(hclText)
	if err != nil {
		return nil, fmt.Errorf("error: could not parse text. %s", err)
	}

	if err := hcl.DecodeObject(&result, hclParseTree); err != nil {
		return nil, fmt.Errorf("error: could not decode object. %s", err)
	}

	return result, nil
`

and then you'd marshal the object into yaml using the "gopkg.in/yaml.v2" package.

**Comment by flmmartins** [comment]
> Hi @flmmartins thanks for opening this issue. I'm not exactly sure what you mean when you say have the YAML files as output. Could you give me an example of how you would use this feature if it were implemented already?
> 
> The provider itself doesn't actually generate any YAML files, it makes calls directly to the kubernetes API based on what is written in HCL. Are you suggesting having an attribute on the resource, that could be used as an output, that would be equivalent to `kubectl get <resource> <name> -o yaml` ?

Hello
Yes, like `kubectl get <resource> <name> -o yaml`  but instead of issuing this command after the pod/thing is deployed I want to have that YAML as output of the provider.

So I would use something like

```
output my_yaml {
    value = "${kubernetes_deployment.mydeploy.yaml}"
}
```
