### ISSUE TITLE
Feature: Provider level annotation ignore-list

### ISSUE THREAD

**Issue by hughobrien** [hashicorp/terraform-provider-kubernetes#746]
As per this PR https://github.com/terraform-providers/terraform-provider-kubernetes/pull/741 there are a number of possible automatically applied annotations that might trigger an unwanted diff.

Rather than call out 'kubernetes.io' for special mention in the code (e.g. here https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/structures.go#L161) would it be possible to pass a list of hostnames at the provider level?

Thank you

**Comment by benweint** [comment]
This is something I'd love to see as well. There are a number of tools (Calico, as referenced in https://github.com/terraform-providers/terraform-provider-kubernetes/pull/741 and also Spinnaker, which is relevant to my use case) that automatically apply annotations onto various K8s objects, and it's not generally practical or desirable to manage those annotations via TF (though managing the rest of the resource might be).

**Comment by dak1n1** [comment]
We have a few issues tracking specific annotations:
``` 
    ingress.kubernetes.io/backends
    cloud.google.com/neg
    ingress.kubernetes.io/backends
    ingress.kubernetes.io/forwarding-rule
    ingress.kubernetes.io/target-proxy
    ingress.kubernetes.io/url-map
```

I think these issues will be solved when we add a provider-level annotation ignore/allow list.

https://github.com/hashicorp/terraform-provider-kubernetes/issues/874
https://github.com/hashicorp/terraform-provider-kubernetes/issues/668
https://github.com/hashicorp/terraform-provider-kubernetes/issues/668

We'll track progress here.

**Comment by nightlyone** [comment]
Another possible implementation is to allow complete ignorance of annotations or labels per resource.

For example it often is only necessary that a e.g. namespace has been created, so you can attach kubernetes resources to it and `depend_on` its existence. But what that namespace looks like is often irrelevant how that namespace looks like and details will be managed by other tooling (e.g. kubernetes controllers).

**Comment by arybolovlev** [comment]
Hi,

I am going to close this issue since `ignore_annotations` and `ignore_labels` attributes were added to the provider level. Please keep an eye on release notes.

Thank you.
