### ISSUE TITLE
Enable kubernetes_service_account resource to manipulate the default account

### ISSUE THREAD

**Issue by Comradin** [hashicorp/terraform-provider-kubernetes#749]
Hello,

I've got an issue with an edge case for the kubernetes_service_account resource. My requirement is that I must annotate the service account "default" in a namespace after its creation. But this isn't possible with the kubernetes_service_account.

### Terraform Version
0.12.20, but I guess all versions will fail

### Affected Resource(s)
- kubernetes_service_account

### Debug Output
```
Error: serviceaccounts "default" already exists

  on ../modules/k8s/managed_namespace/main.tf line 13, in resource "kubernetes_service_account" "default":
  13: resource "kubernetes_service_account" "default" {

```

### Actual Behavior
The provider failes as the ressource isn't under terraform control and thus stops the execution with the above error message. It cannot find the service account in the state file and tries to create the requested resource. This can only fail as the default account in a namespace is being created automatically by the service account controller when the namespace is created.

For every other service account in a namespace creating and annotating that account will work. Its just the 'default' one which brakes.

### Expected Behavior
I guess this is more a feature request than a bug report. It would be great if the edge case 'default' could be manipulated.

My current workaround is the following, code being used in a module and kind of abusing the kubernetes_namespace resource and a local-exec provisioner. This is kind of hacky and unreliable as the local-exec won't trigger on a change of the role for the drive-by-managed service account:

```
resource "kubernetes_namespace" "example" {
  metadata {
    name   = var.name
    labels = var.additional_labels
  }

  provisioner "local-exec" {
    command = format("kubectl annotate sa default -n %s annotation=arn:aws:iam::%s:role/example",
            var.name,
            data.aws_caller_identity.current.account_id
    )
  }
}
```

**Comment by lawliet89** [comment]
A solution is to create a new resource to manage the default service account with the namespace. (e.g. `kubernetes_default_service_account`.

**Comment by Comradin** [comment]
Good point, Ill look into this and try to come up with a PR

**Comment by alexsomesan** [comment]
@Comradin special provider resources that make assumptions about certain cluster resources or any other cluster state are a bit of an anti-pattern.

Have you had a look at importing the `default` service account first so that Terraform tracks it? That would be the prefered solution. Please see if it applies to you before submitting any PRs with a special resource.

**Comment by lawliet89** [comment]
@alexsomesan The default service account is always created when the namespace is created. There's no other way to manage it. The Google provider and AWS providers both have resources to manage these kind of "special" resources so I don't see why this is a problem.

**Comment by alexsomesan** [comment]
The provider now offers a default service account resource. Please have a look here: https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/default_service_account
