### ISSUE TITLE
Kubernetes target_memory_utilization_percentage not present in resource "kubernetes_horizontal_pod_autoscaler"

### ISSUE THREAD

**Issue by ravikiranbg** [hashicorp/terraform-provider-kubernetes#761]
Hi there,

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)

- kubernetes_horizontal_pod_autoscaler

### Terraform Configuration Files
```hcl
resource "kubernetes_horizontal_pod_autoscaler" "pod_scaler" {
  metadata {
    name = "${var.deployment_name}"
  }

  spec {
    max_replicas                         = 6
    min_replicas                         = 2
    target_memory_utilization_percentage = 70

    scale_target_ref {
      api_version = "extensions/v2beta2"
      kind = "Deployment"
      name = "${var.deployment_name}"
    }
  }
}
```

### Debug Output
Error: module.ext3p_hpa.kubernetes_horizontal_pod_autoscaler.pod_scaler: spec.0: invalid or unknown key: target_memory_utilization_percentage

### Panic Output
None

### Expected Behavior
run a successful plan

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
Missing specs in hpa 
https://github.com/terraform-providers/terraform-provider-kubernetes/blob/master/kubernetes/resource_kubernetes_horizontal_pod_autoscaler.go

**Comment by jrhouston** [comment]
Hi @ravikiranbg - as far as I can see the HorizontalPodAutoscaler API spec does support the field you've described. Perhaps you are looking to scale on a custom metric using the `metric` block? See [here](https://www.terraform.io/docs/providers/kubernetes/r/horizontal_pod_autoscaler.html#example-usage-with-metric).

**Comment by aareet** [comment]
Closing since it has been a few months awaiting response.
