### ISSUE TITLE
Add support for `volumeMode` in `kubernetes_persistent_volume` and `kubernetes_persistent_volume_claim` and other volume specs

### ISSUE THREAD

**Issue by jamesongithub** [hashicorp/terraform-provider-kubernetes#770]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
- Terraform v0.12.18

### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_persistent_volume
- kubernetes_persistent_volume_claim

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support
- https://kubernetes.io/blog/2019/03/07/raw-block-volume-support-to-beta/
- https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

**Comment by alexsomesan** [comment]
We'd be grateful for a contribution porting the changes made to PV here https://github.com/hashicorp/terraform-provider-kubernetes/pull/939 into the PVC resource.

**Comment by jamesongithub** [comment]
bump..

**Comment by jamesongithub** [comment]
@alexsomesan are you able to reopen?
