### ISSUE TITLE
Feature Request: Add a data source for pods & deployments

### ISSUE THREAD

**Issue by rbustami** [hashicorp/terraform-provider-kubernetes#786]
Looks like there is a PR for pods that's been open for the past 3 months: https://github.com/terraform-providers/terraform-provider-kubernetes/pull/715

**Comment by timorkal** [comment]
waiting for this also

**Comment by rbustami** [comment]
Looks like pod was added to this PR:
https://github.com/terraform-providers/terraform-provider-kubernetes/pull/715

**Comment by dak1n1** [comment]
The pod data source has been released in version [1.11.4](https://github.com/hashicorp/terraform-provider-kubernetes/releases/tag/v1.11.4).

**Comment by alexsomesan** [comment]
Deployments are missing. Reopening.

**Comment by iBrandyJackson** [comment]
This issue is now resolved. If you have found a problem that seems related to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further. This helps our maintainers find and focus on the active issues. Thanks!
