### ISSUE TITLE
Feature Request: support binary_data in kubernetes_secret like in kubernetes_config_map

### ISSUE THREAD

**Issue by thomas-riccardi** [hashicorp/terraform-provider-kubernetes#789]
### Terraform Version
```
Terraform v0.12.20
+ provider.kubernetes v1.11.0
```

### Affected Resource(s)
- `kubernetes_secret`

### Terraform Configuration Files
```hcl
resource "kubernetes_secret" "example" {
  metadata {
    name = "my-secret"
  }
  binary_data = {
    "my_payload.bin" = filebase64("${path.module}/my_payload.bin")
  }
}
```

### Expected Behavior
I'd like `binary_data` to be supported in `kubernetes_secret` like it is in `kubernetes_config_map` since #400.

Indeed, both ConfigMap and Secrets are very similar in Kubernetes, I was expecting to have feature parity between the two.

### Actual Behavior
```
Error: Unsupported argument

  on resources.tf line 248, in resource "kubernetes_secret" "example":
 248:   binary_data = {

An argument named "binary_data" is not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
- #400

**Comment by albertorm95** [comment]
I think replicating the solution from #400 but in the secret code would resolve this issue

**Comment by thomas-riccardi** [comment]
@albertorm95 you are right that at k8s-api-level Secret doesn't have BinaryData as ConfigMap has, but in fact k8s-api Secret `data` is expected to be base64 encoded of binary data, like k8s-api ConfigMap `binaryData`.
The issue is that terraform secret changed the semantic of the `data` field vs k8s-api by automatically doing the base64 encoding.
So manually encoding to base64 before giving it to terraform secret `data` won't work: i assume there would be a double base64 encoding, breaking everything.

From that, I see 2 possible paths:
- either normalizing to k8s-api semanting: terraform `kubernetes_secret` `data` now take already-base64-encoded: it would be up to the user to do the encoding, that's a breaking change though
- or normalize to terraform `kubernetes_configmap` and introduce the `binary_data` as I initially suggested: no breaking change.

Another way to see things is that terraform doesn't support binary data (as far as I know) as a standard type:
- `file()` reads the content as a utf-8 encoded string, so cannot be used to read raw binary data
- `filebase64()` reads the content as raw binary data, and then serializes it to a string with base64
=> always (unicode) strings.
If terraform did support binary data, we could have a ~`filebinary()` returning binary data, and pass that directory to terraform `kubernetes_secret` `data` values, and this issue would be resolved too.

**Comment by pdecat** [comment]
Related https://github.com/hashicorp/terraform-provider-kubernetes/pull/704

**Comment by dak1n1** [comment]
Thanks, everyone, for your contributions to this bug report! I've consolidated the information we have regarding this and we're now tracking it here: https://github.com/hashicorp/terraform-provider-kubernetes/issues/901.
