### ISSUE TITLE
Cannot create a namespace

### ISSUE THREAD

**Issue by john-morsley** [hashicorp/terraform-provider-kubernetes#790]
Hi,

When I try and create a namespace I get the following error:

Error: the server could not find the requested resource (post namespace)

Can you advise, or is this an issue?

I'm using Terraform 0.12.23

Many thanks,

John

**Comment by dak1n1** [comment]
There is likely a mismatch between the version of the namespace API that the provider supports vs the version your Kubernetes cluster supports. Could you post a Terraform config that reproduces the problem, and the output of `kubectl version`? For example, here is the config that worked for me:

```
$ cat main.tf 
resource "kubernetes_namespace" "example" {
  metadata {
    name = "example"
  }
}
```

And this is the version I'm running:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aareet** [comment]
Closing since it has been a few months awaiting response. Please reopen if this is still an issue.
