### ISSUE TITLE
support for pod readinessGates when using kubernetes_deployment

### ISSUE THREAD

**Issue by assafcoh** [hashicorp/terraform-provider-kubernetes#811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We use terraform resource "kubernetes_deployment" to deploy our pods. Our pods have readiness probes, but these probes are not good enough because we need external feedback to decide if a pod is ready. In our case, a pod is ready only after external program creates a file in aws S3 bucket, and this is a manual step, which may be completed at random time (can be several days/weeks) so readiness probe is not good, becuase it will fail and leave our pod in "unready" state. We understand kubernetes 1.14 introduced something called readiness-gate. See https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-readiness-gate However it seems terraform resource "kubernetes_deployment" does not support pod readiness-gates.

Note that we prefer using kubernetes deployment (rather than defining pods directly) because we need rolling update strategy.

It would be great if resource "kubernetes_deployment" supported readinessGates for pods

**Comment by slobo** [comment]
Another use case for `ReadinessGates` is 0-downtime deployments when using ALB Ingress Controller as described here: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/ingress/pod-conditions.md

It's nice that provider does strict validation of deployment arguments, but is there a foot-gun we could use in the meantime to inject `readinessGates` into our job specifications?
