### ISSUE TITLE
Support for specifying projected volume for Kubernetes deployments

### ISSUE THREAD

**Issue by rakrup** [hashicorp/terraform-provider-kubernetes#818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kubernetes allows users to specify projected volumes for kubernetes deployment. 
Ref : [Kubernetes service account token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection)
Currently kubernetes deployment via terraform-provider-kubernetes doesn't support this configuration. It would be great if we integrate this to enable users to configure projected volumes for their deployment  

### Potential Terraform Configuration

```hcl

# Should look similar to this in the deployment volume section.
volume {
      name = "my-token"
      
     projected {
           sources = [
           {
                 service_account_token = {
                      path  = "my-token"
                      expiration_seconds = 43200
                      audience = "my-audience"
                  }
           }
       ]
}
```

**Comment by aybabtme** [comment]
Support for this would help when setting up a k8s cluster [for use with Spire](https://github.com/spiffe/spire/blob/master/doc/plugin_agent_nodeattestor_k8s_psat.md).

**Comment by seguidor777** [comment]
Hello, is this still a work in progress?

**Comment by aybabtme** [comment]
@seguidor777 I sent a PR that implements it but haven't had any feedback.

**Comment by seguidor777** [comment]
Ok, thanks

**Comment by rakrup** [comment]
Bumping this thread for @aareet or someone from Hashicorp to look into as @aybabtme has already raised a PR adding this feature. If all looks good - Can we review and close this at the earliest ? Thanks.

**Comment by alexsomesan** [comment]
I've had a look at this and tried to test it, but both the included test and a manual interactive Terraform run fail to complete and get stuck at the Pod resource in "Creating" state.

**Comment by aybabtme** [comment]
@alexsomesan I've been trying to debug this (see the comment in my PR's headline) and asked for help figuring out what's up. Do you have any insight?

**Comment by eddy-curv** [comment]
Supporting projected volumes will allow [mTLS with Istio service mesh for Ambassador ](https://www.getambassador.io/docs/latest/howtos/istio/#istio-mutual-tls)
