### ISSUE TITLE
Creating kubernetes_namespace has contradicticting warning/error

### ISSUE THREAD

**Issue by jimusbobus** [hashicorp/terraform-provider-kubernetes#828]
Hi there,

I'm writing terratest tests for our IaC, we have a section where i create a namespace then install a service using helm into the k8s cluster, i've been working on clearing all WARN from the logs (Ignoring  [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.)

I'm getting contradicting info out of the kubernetes_namespace, if i create the basics test below (test1) then i get the warning, but if I add the default empty sting for "generate_name" then the whole thing errors out, this seems to be contradictory.... maybe :)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

Terraform version: 0.12.24
terraform-provider-kubernetes_v1.11.1_x4

### Affected Resource(s)

kubernetes_namespace
kubernetes_secret (just added this cos it has the same issue)

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

# Test 1 
provider "kubernetes" {
  version = "~> 1.9"
}


resource "kubernetes_namespace" "namespace" {
  metadata {
    name          = "test1"
  }
}

# Test2
provider "kubernetes" {
  version = "~> 1.9"
}


resource "kubernetes_namespace" "namespace" {
  metadata {
    name          = "test2"
    generate_name = ""
  }
}

```

### Expected Behavior
Create test1 without warnings
OR
Create test2 without error

### Actual Behavior
Test1 output
```
kubernetes_namespace.namespace: Creating...
2020/04/23 10:49:31 [WARN] Provider "registry.terraform.io/-/kubernetes" produced an unexpected new value for kubernetes_namespace.namespace, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .metadata[0].generate_name: was null, but now cty.StringVal("")
kubernetes_namespace.namespace: Creation complete after 0s [id=test1]
```
Test2 output
```
2020/04/23 10:53:16 [ERROR] <root>: eval: *terraform.EvalSequence, err: 2 problems:
- "metadata.0.generate_name": conflicts with metadata.0.name
- "metadata.0.name": conflicts with metadata.0.generate_name
Error: "metadata.0.generate_name": conflicts with metadata.0.name
  on main.tf line 6, in resource "kubernetes_namespace" "namespace":
   6: resource "kubernetes_namespace" "namespace" {
Error: "metadata.0.name": conflicts with metadata.0.generate_name

  on main.tf line 6, in resource "kubernetes_namespace" "namespace":
   6: resource "kubernetes_namespace" "namespace" {
```

### Steps to Reproduce
1. `terraform apply`

**Comment by dak1n1** [comment]
`generate_name` is used to provide a prefix for the namespace, so it's expecting a non-empty string. It also requires that `name` be omitted (see [docs](https://www.terraform.io/docs/providers/kubernetes/r/namespace.html#generate_name)). For example:

```
[dakini@dax namespace]$ cat  main.tf 
resource "kubernetes_namespace" "example" {
  metadata {
    generate_name = "test"
  }
}

[dakini@dax namespace]$ TF_LOG=trace terraform apply --auto-approve &> log

[dakini@dax namespace]$ kubectl get namespace |grep test
testrzh4l         Active   116s
```

However, it is still a bit noisy with the WARN messages, even when it succeeds.
```
[dakini@dax namespace]$ grep WARN logfile
2020-07-21T16:31:40.742-0700 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2020-07-21T16:31:41.051-0700 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2020-07-21T16:31:41.407-0700 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
2020-07-21T16:31:41.706-0700 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
```
