### ISSUE TITLE
Validate Terraform 0.13 compatibility

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-provider-kubernetes#839]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When Terraform 0.13 is available, we need to verify the compatibility of the provider with 0.13 and make any associated fixes.

### References
* https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md

**Comment by mstrejczek** [comment]
I have problems when using Kubernetes provider 1.11.3 for `terraform destroy` operation with Terraform 0.13.0-beta3.
My provider configuration is:
```
data "azurerm_kubernetes_cluster" "aks" {
  name                = var.aks_cluster_name
  resource_group_name = var.aks_rg_name
}

provider "kubernetes" {
  version = "1.11.3"

  load_config_file       = false
  host                   = data.azurerm_kubernetes_cluster.aks.kube_config.0.host
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)
}

provider "helm" {
  version = "1.2.3"

  kubernetes {
    load_config_file       = false
    host                   = data.azurerm_kubernetes_cluster.aks.kube_config.0.host
    client_certificate     = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate)
    client_key             = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.client_key)
    cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)
  }
}
```

**Comment by dak1n1** [comment]
Closing since we've been using Terraform 0.13 for some time now.
