### ISSUE TITLE
kubernetes_deployment fails if container not ready

### ISSUE THREAD

**Issue by assafcoh** [hashicorp/terraform-provider-kubernetes#863]
We use terraform resource "kubernetes_deployment" to deploy our containers. Each pod is composed of two containers. Both containers have readiness probes. One of the container's readiness probe returns 200 **only** if a certain file exists on S3 bucket. This is by design. Once the file is created on S3 (a manual process which can be completed after several days) then readiness probe will returns 200.
The problem is that resource kubernetes_deployment times out and fails after 10 minutes because file does not exist on S3 and so container is in "not ready" state.

Is there any fix or workaround so that deployment can complete successfully?

### Terraform Version and Provider Version
terraform v0.12.24
kubernetes provider 1.11.3

### Affected Resource(s)
kubernetes_deployment

### Expected Behavior
kubernetes deployment should complete successfully. If one of the containers is in "not ready" this should not fail the deployment. The idea behind readiness probes is that a pod can automatically change it state between "not ready" and "ready"  according to response of readiness probe.

### Actual Behavior
kubernetes_deployment timed out after 10 minutes

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by josephmilla** [comment]
Also seeing this issue:
```
Terraform v0.12.28
+ provider.kubernetes v1.11.3
+ provider.template v2.1.2
```

**Comment by pasali** [comment]
I am having the same problem. IMHO we should be able to bypass waiting by setting a parameter like `wait_for_to_be_ready` to `false`. `kubectl` works with same logic and doesn't wait pod to be get ready.

**Comment by dsymonds** [comment]
Related to #605.
