### ISSUE TITLE
Cannot remove volume_mount

### ISSUE THREAD

**Issue by Unichron** [hashicorp/terraform-provider-kubernetes#870]
Hi,
I cannot seem to make terraform remove my volume mount from a deployment/daemonset.

Versions:
tf 0.12.25
kubernetes provider 1.11.3

Before modification:
```hcl
resource "kubernetes_deployment" "this" {
  metadata {
    name      = "test"
    namespace = "default"
  }
  spec {
    selector {
      match_labels = {
        "app" = "test"
      }
    }
    template {
      metadata {
        labels = {
          "app" = "test"
        }
      }
      spec {
        container {
          name  = "test"
          image = "nginx"
          volume_mount {
            name       = "test"
            mount_path = "/tmp/test"
            sub_path   = "test"
          }
        }
        volume {
          name = "test"
          empty_dir {}
        }
      }
    }
  }
}
```

Remove volume and volume mount:
```hcl
resource "kubernetes_deployment" "this" {
  metadata {
    name      = "test"
    namespace = "default"
  }
  spec {
    selector {
      match_labels = {
        "app" = "test"
      }
    }
    template {
      metadata {
        labels = {
          "app" = "test"
        }
      }
      spec {
        container {
          name  = "test"
          image = "nginx"
        }
      }
    }
  }
}
```

Expected behaviour for terraform apply:
terraform removes the volume and volume mount

Actual behaviour:
terraform says nothing to change

Doing the same with kubectl works as expected.

UPDATE:
So I played a bit more with it. If there are more than 1 volume mounts, then removing is possible (if you have at least 1 remaining after removal), although a bit arbitrary because it potentially wants to modify the remaining volumes. For example if you have 2 volumes, you remove the first, the diff shows that first one is going to be updated to the second's values and the second is removed. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by robinvdvleuten** [comment]
Same issue with deployment volumes
