### ISSUE TITLE
mutating_webhook_configuration forces service block in client config when url is used

### ISSUE THREAD

**Issue by kfh** [hashicorp/terraform-provider-kubernetes#882]
Terraform version: v0.12.26
Provider: v1.11.3

This is easily reproducable, just use the example in the docs as foundation:

```
resource "kubernetes_mutating_webhook_configuration" "example" {
  metadata {
    name = "test.terraform.io"
  }

  webhook {
    name = "test.terraform.io"

    admission_review_versions = ["v1", "v1beta1"]

    client_config {
      url = "my-url"  
      #service {
      #   namespace = "example-namespace"
      #    name = "example-service"
      # }
    }

    rule {
      api_groups = ["apps"]
      api_versions = ["v1"]
      operations = ["CREATE"]
      resources = ["deployments"]
      scope = "Namespaced"
    }

    reinvocation_policy = "IfNeeded"
    side_effects = "None"
  }
}
```

As can be seen above i have commented out the service block and only want to use the url which should be valid configuration according to the docs:

> url - (Optional) Gives the location of the webhook, in standard URL form (scheme://host:port/path). Exactly one of url or service must be specified

The current output i'm seeing when run with only the url specified:

> "webhook.0.client_config.0.service": required field is not set

Funny enough if i set both the url and service terraform passes but of course if will fail when deploying to Kubernetes since this is an invalid state. I've also tried a couple of workarounds that almost got me there, for instance configuring the service block with _name_ and _namespace_ set to empty strings which seems to make the fields go away but there will be set a default port anyway so this won't work either. That is probably also a bug since i end up with a service block with only a port defined as:

```
service {
  port = 443
}
```

If there are any known workarounds that would be appreciated.

**Comment by jrhouston** [comment]
Re-opened because of https://github.com/hashicorp/terraform-provider-kubernetes/issues/943

I can see the problem is [here](https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/kubernetes/structures_admissionregistration.go#L83). The attribute is optional, but we are not checking that the list length is greater than 1 before populating the API request, so it is adding an empty object. We also should add a regression test for this.
