### ISSUE TITLE
Terraform apply to fail faster

### ISSUE THREAD

**Issue by davidvuong** [hashicorp/terraform-provider-kubernetes#884]
I couldn't find docs for this so please point me in the right direction if this already exists. 

1. Create a `kubernetes_deployment` resource. It's perfectly valid.
1. Run `terraform apply`. It's working and waiting for a success response `... Still creating... [1m50s elapsed]`
1. Run `kubectl get pods` and notice the underlying pod has a `CrashLoopBackOff` status
1. Quickly debug, running `kubectl logs <...>` to figure out the problem (an environment variable was missing)
1. Notice that `terraform apply` is still running and now I'm stuck waiting for it to give up. At this point I can `ctrl+c` twice to force an exit but I'd have to deal with the locking clean up manually.

Can the amount of time spent polling for a successful deploy be configurable? Perhaps something that can be set in the provider if there isn't already something like this.

```hcl
provider "kubernetes" {
  timeout = xxx
}
```

**Comment by jrhouston** [comment]
Hi @davidvuong you can configure the create timeout for this resource to make it shorter. See here: https://www.terraform.io/docs/configuration/resources.html#operation-timeouts

**Comment by davidvuong** [comment]
Hi @jrhouston thanks for sending over that link. I've configured a few `kubernetes_deployment` resources to have timeouts. I haven't tried to reproduce or have encountered anything crashing as of yet. However, a `terraform plan` succeeds with `No changes. Infrastructure is up-to-date.`. If the issue persists, I'll re-open this issue.
