### ISSUE TITLE
'Optional' field is missing from container/pod schema ('secret' and 'config_map' affected)

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform-provider-kubernetes#892]
### Description

This bug report is a consolidation of multiple bug reports regarding container/pod schema attributes missing the `optional` field.

### Terraform Version and Provider Version

Terraform v0.12.26
+ provider.kubernetes v1.11.3

### Affected Resource(s)

Anything that has a `Container` (and specifically a [ConfigMapVolumeSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#configmapvolumesource-v1-core), [ConfigMapEnvSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#configmapenvsource-v1-core), or [SecretEnvSource](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#secretenvsource-v1-core), is potentially affected by the missing "optional" field.

- kubernetes_cron_job
- kubernetes_daemonset
- kubernetes_deployment
- kubernetes_job
- kubernetes_pod
- kubernetes_replication_controller
- kubernetes_stateful_set

### Terraform Configuration Files

```hcl
resource "kubernetes_pod" "main" {
  metadata {
    name = "test-pod"
  }
  spec {
    container {
      name = "default"
      image = "alpine:latest"
      command = ["cat", "/etc/test/config.json"]
      volume_mount {
        mount_path = "/etc/test"
        name = "test"
      }
    }
    volume {
      name = "test"
      config_map {
        name = "test-config"
        optional = true # this field is missing
      }
    }
  }
}
```

### Debug Output

```
$ terraform apply

Error: Unsupported argument

  on main.tf line 19, in resource "kubernetes_pod" "main":
  19:         optional = true # this field is missing

An argument named "optional" is not expected here.
```

### Expected Behavior

The provider should allow the `optional` field here, since the Kubernetes API supports it.

### Actual Behavior

Provider errors if the `optional` argument is specified.

### Steps to Reproduce

1. Use the Terraform config provided above, or try to create any of the affected resources with a volume source of type `config_map`; or an `env.value_from` using `config_map_key_ref` or `secret_key_ref` for an environment variable source.

2. Add `optional = true` as an argument to `config_map_key_ref`, `secret_key_ref`, or  `config_map`.

2. `terraform apply`

### Important Factoids

It looks like the `optional` field needs to be added here:

- https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/kubernetes/schema_container.go#L245
- https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/kubernetes/schema_container.go#L305
- https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/kubernetes/schema_pod_spec.go#L360

### References

- https://github.com/hashicorp/terraform-provider-kubernetes/issues/655
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/531
- https://github.com/hashicorp/terraform-provider-kubernetes/issues/240

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mbarrien** [comment]
Note that I have open PRs #823 and #824 (open for 2 months so far) which will address both parts of the issue here. The failures in the builds for those PRs appear unrelated to the code.

**Comment by dak1n1** [comment]
Thanks, I'm working on testing those PRs.
