### ISSUE TITLE
Provider appears to not honor `load_config_file = false`.

### ISSUE THREAD

**Issue by jharshman** [hashicorp/terraform-provider-kubernetes#896]
### Terraform Version and Provider Version

```
Terraform v0.12.6
+ provider.google v3.11.0
+ provider.google-beta v3.11.0
+ provider.kubernetes v.1.11.3
```

### Affected Resource(s)

This issue appears to affect the Kubernetes provider and how it establishes a connection to the Kubernetes cluster.

### Terraform Configuration Files
```hcl
data "google_client_config" "bitly-gcp-prod" {}
data "google_container_cluster" "k8s-us-east4-02" {
  name = "k8s-us-east4-02"
  region = "us-east4"
}

provider "kubernetes" {
  alias = "k8s-us-east4-02
  load_config_file = false
  host = "https://${data.google_container_cluster.k8s-us-east4-02.endpoint}"
  token = "${data.google_client_config.bitly-gcp-prod.access_token}"
  cluster_ca_certificate = "${base64decode(data.google_container_cluster.k8s-us-east4-02.master_auth[0].cluster_ca_certificate)}"
  version = "1.11.3"
}

module "k8s-us-east4-02-post" {
  source = "../modules/gke/post"
  namespaces = "${local.k8s_namespaces}"
  providers = {
     default = "kubernetes.k8s-us-east4-02
  }
}
```

### Debug Output

https://gist.github.com/jharshman/6df3fe2abc5e4c93995f4a69a8738fbc

### Expected Behavior
The Kubernetes provider honors `load_config_file = false` and does not attempt to load the kubernetes config.
The static configuration described [here](https://www.terraform.io/docs/providers/google/d/datasource_client_config.html#example-usage-configure-kubernetes-provider-with-oauth2-access-token) is used to connect to the Kubernetes cluster.

### Actual Behavior
The trace logs indicate that the provider attempts to load the default Kubernetes configuration. Failing to do that, the Kubernetes host is defaulted to `localhost`.

### Steps to Reproduce

1.  `terraform plan -out /tmp/tf.plan`
2.  `terraform apply /tmp/tf.plan`

### References

- https://www.terraform.io/docs/providers/google/d/datasource_client_config.html#example-usage-configure-kubernetes-provider-with-oauth2-access-token
- https://www.terraform.io/docs/providers/kubernetes/index.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bendrucker** [comment]
This has to do with the `providers` argument to your module as opposed to functionality in this provider. It's not that the provider isn't handling the argument correctly, it's that the modules are using a copy of the provider with empty configuration. In Terraform 0.12, your configuration should look like this:

```tf
module "k8s-us-east4-02-post" {
  providers = {
    kubernetes = kubernetes.k8s-us-east4-02
  }
}
```

Note:

* The keys in the map are provider instance keys, which include are `${provider}.${alias}`. `kubernetes.default` might work but you never need to specify `default` in configuration.
* The values are identifiers, not strings

Terraform 0.12 should print some warnings about unnecessary quotations and Terraform 0.13 will start returning errors for some (`"${foo}"`).

**Comment by jharshman** [comment]
@bendrucker thanks! This solved my issue.
