### ISSUE TITLE
Terrform kubernetes provider doesn't work with multiple namespaces

### ISSUE THREAD

**Issue by Jyoti492** [hashicorp/terraform-provider-kubernetes#898]
### Terraform Version and Provider Version
Terraform version:0.12.26
terraform kubernetes provider:1.11.3

### Affected Resource(s)
kubernetes_namespace

### Terraform Configuration Files
```
variable "custom_namespaces" {
  type        = list(string)
}
resource "kubernetes_namespace" "create_namespaces" {
  for_each = {for namespace in var.custom_namespaces : namespace => namespace}
  metadata {
    name = each.value
  }
}
```

### Debug Output
Error: metadata.0.name a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
TestMCPResources 2020-06-30T14:55:06Z logger.go:66: 
TestMCPResources 2020-06-30T14:55:06Z logger.go:66:   on ../../modules/kubernetes/main.tf line 18, in resource "kubernetes_namespace" "create_namespaces":
TestMCPResources 2020-06-30T14:55:06Z logger.go:66:   18: resource "kubernetes_namespace" "create_namespaces" {
TestMCPResources 2020-06-30T14:55:06Z logger.go:66: 
TestMCPResources 2020-06-30T14:55:06Z logger.go:66: 
TestMCPResources 2020-06-30T14:55:06Z retry.go:80: Returning due to fatal error: FatalError{Underlying: exit status 1}
    TestMCPResources: apply.go:13: 
        	Error Trace:	apply.go:13
        	            				mcp_resources_test.go:34

**Comment by jrhouston** [comment]
👋  @Jyoti492 - can you share the namespaces you supplied as the value of the variable? I copied and pasted your example and it worked for me.

The error message you got indicates that you tried to create a namespace with a name that isn't valid.

**Comment by aareet** [comment]
Closing since it has been a few months awaiting response. Please reopen if this is still an issue.
