### ISSUE TITLE
Parsing kubeconfig data as a data source with kubernetes provider

### ISSUE THREAD

**Issue by linuxbsdfreak** [hashicorp/terraform-provider-kubernetes#917]
### Terraform Version
```
Terraform v0.13.0-beta2

terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/tls]
├── provider[registry.terraform.io/hashicorp/kubernetes] ~> 1.11.3
└── provider[registry.terraform.io/hashicorp/local]

Providers required by state:

    provider[registry.terraform.io/hashicorp/kubernetes]

    provider[registry.terraform.io/hashicorp/local]

    provider[registry.terraform.io/hashicorp/tls]

```

### Terraform Configuration Files
```
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    kubernetes = "~> 1.11.3"
  }
}

provider "kubernetes"{
  alias = "robotaccount"
  config_patj = "/tmp/robot.kubeconfig"
  load_config_file = "true"
}

data "kubernetes_secret" "test" {
  provider = kubernetes.robotaccount
  metadata {
    name = "test.kubeconfig"
    namespace = "test-ns"
  }
}
resource "local_file" "credentials" {
    content     = data.kubernetes_secret.test.data.kubeconfig
    filename = "credentials.kubeconfig"
}

provider "kubernetes"{
  alias = "target"
  //config_path = data.kubernetes_secret.test.data.kubeconfig
  config_path = "/tmp/credentials.kubeconfig"
  load_config_file = "true"
}

resource "kubernetes_namespace" "example" {
  provider = kubernetes.target
  metadata {
    annotations = {
      name = "example-annotation"
    }

    labels = {
      mylabel = "label-value"
    }
    name = "terraform-example-namespace"
  }
}

```

### Debug Output

This works by saving the credentials to a temporary file. However it does not work with using the below directly

**config_path = data.kubernetes_secret.test.data.kubeconfig**

### Crash Output

With the **config_path = data.kubernetes_secret.test.data.kubeconfig** set i get the below output.

```
Error: Get "http://localhost/api/v1/namespaces/terraform-example-namespace": dial tcp 127.0.0.1:80: connect: connection refused
```

### Expected Behavior
It should i have taken the contents of the kubeconfig in memory and created the connection with the data value.

### Actual Behavior
The file creation step had to added and then load the config

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by linuxbsdfreak** [comment]
Any feedback regarding this or anywork around ?

**Comment by alexsomesan** [comment]
Hi. As things stand right now, the `config_path` attribute expects a path to a kubeconfig as a value and not the contents of the file itself.

You can try setting `config_path` like this instead:
```
config_path = local_file.credentials.filename
```

**Comment by linuxbsdfreak** [comment]
Hi @alexsomesan ,

Thanks for the update. I had two Questions. 

1. How are people using the plugin in a CI/CD scenario? Or is it meant to be used only local ?
2. Is there a possibility to load the kubeconfig file from S3 bucket? Do you have any sample examples ?

As you see in my template. I have a robot kubeconfig (base K8s cluster) which is needed to get the target K8s kubeconfig for the cluster.  

Kevin

**Comment by linuxbsdfreak** [comment]
@alexsomesan 

Any feedback to regarding the usage with CI/CD with Jenkins ?

Kevin

**Comment by linuxbsdfreak** [comment]
@alexsomesan 

Any inputs on how I can use the provider without saving it to a local file ?

Kevin

**Comment by alexsomesan** [comment]
It looks like you're running into a corner case here that Terraform doesn't support. Passing attributes on the provider block that are sourced from other resources in the same configuration is not a valid configuration.

Could you please provide a bit more detail as to the workflow you're trying to model. Maybe we can suggest a workaround.

**Comment by linuxbsdfreak** [comment]
Hi @alexsomesan,

I would like to a store  a Kubeconfig yaml in Hashicorp vault to be used later with the kubernetes TF provider. At the moment i am doing the following to save the file locally to be used by the K8s provider

```
terraform {
  required_providers {
    vault = "~> 2.12"
  }
}

provider "vault" {
  alias      = "base_namespace"
  address    = var.vault_address
  token      = var.vault_token
  namespace  = var.vault_base_namespace
}

resource "vault_namespace" "child_namespace" {
  provider = vault.base_namespace
  path = var.vault_child_namespace
}

provider "vault" {
  alias = "child_namespace"
  address    = var.vault_address
  token      = var.vault_token
  namespace = trimsuffix(vault_namespace.child_namespace.id, "/")
}

resource "vault_mount" "kvv2" {
  provider = vault.child_namespace
  path = var.kvv2_secret_path
  type = "kv"
  options = {
    version = "2"
  }
  depends_on = [ vault_namespace.child_namespace ]
}

data "vault_generic_secret" "k8s_config_3" {
  provider = vault.child_namespace
  path = join("/", [ var.kvv2_secret_path, "config3" ])
}

data "local_file" "input" {
    filename = var.shoot_kubeconfig_path
}

resource "vault_generic_secret" "vault_secret_kvv2_new_2" {
  provider = vault.child_namespace
  path = join("/", [ var.kvv2_secret_path, "config3" ])

  data_json = jsonencode({
      config = data.local_file.input.content
  })

  depends_on = [ vault_mount.kvv2 ]
}

resource "local_file" "robotK8sconfig_vault" {
    filename = "robotk8_vault_read.kubeconfig"
    sensitive_content  = data.vault_generic_secret.k8s_config_3.data.config
    file_permission = "644"
}
```

The above would work by saving the file locally to the TF run. I was expecting to happen it more transparently pulling the secret direct from vault and avoiding the local file saving steps. 

Something like below using the vault provider

```
provider "kubernetes"{
  alias = "target"
  config_path = data.vault_generic_secret.k8s_config_3.data.config
  load_config_file = "true"
}

```

Kevin

**Comment by alexsomesan** [comment]
Kevin, 

The parsing of a kubeconfig is easily done via the built-in `yamldecode()` function, as documented [here](https://www.terraform.io/docs/configuration/functions/yamldecode.html)

Here's a simple example of that:
```
locals {
    kubeconfig = <<EOF
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/alex/.minikube/ca.crt
    server: https://192.168.39.111:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/alex/.minikube/profiles/minikube/client.crt
    client-key: /home/alex/.minikube/profiles/minikube/client.key
EOF
}

output "kubeconfig" {
    value = yamldecode(local.kubeconfig)
}

output "kubeconfig-host" {
    value = yamldecode(local.kubeconfig).clusters[0].cluster.server
}

output "kubeconfig-ca" {
    value = file(yamldecode(local.kubeconfig).clusters[0].cluster.certificate-authority)
}
```

However, I must continue to advise against sourcing the kubeconfig content from a resource created in the same configuration as the one where the Kubernetes provider will consume it. This is uncharted territory that Terraform doesn't support. It may work, but it may just as well fail arbitrarily with confusing errors.
It should be safe to use a datasource, or just make sure that the resource providing the kubeconfig is already present in the state from a previous apply. Or is sourced from a separate state via the remote state datasource.

**Comment by linuxbsdfreak** [comment]
ok understood @alexsomesan

**Comment by aareet** [comment]
I'll close this question out now, please reopen if you need to
