### ISSUE TITLE
kubernetes resources skip existence checking

### ISSUE THREAD

**Issue by RyanSiu1995** [hashicorp/terraform-provider-kubernetes#926]
### Description
In my case, I have a configmap being installed by the helm chart.
I want to manually override it by applying another configmap.
But it just failed because of the existence checking of the resources in the cluster.
I think it is possible for us to allow the user to do the force apply/update to the existing resources with terraform kubernetes module.
This is also the desired behavior in `kubectl apply -f resource-already-exist.yaml`

### Potential Terraform Configuration
The flag apply_in_force is by default with a false value.
The user need to manually define it in order to get the apply in force active

```hcl
resource "kubernetes_config_map" "test" {
  metadata {
    name = "resource-already-existed"
  }
  data = {
    my-new-data = "test"
  }
  
  apply_in_force = true
}
```

### References
[kubectl-apply](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tholcman** [comment]
I guess a similar question or request is popping up very often.

It is possible to manually import the resource, but this workaround doesn't work well in fully auto CI/CD environments. We are creating and configuring clusters automatically regularly.

in CI/CD we can use something like
```
terraform init
terraform state show kubernetes_config_map.kube_dns || terraform import kubernetes_config_map.kube_dns kube-system/kube-dns
```
I think any GKE user will hit the use-case with `kube-dns` and `kube-dns-autoscaler`

There already is something similar on `aws_route53_record` - `allow_overwrite` parameter. Would it be possible to add something like that also to `kubernetes_*` resources.

https://github.com/hashicorp/terraform-provider-kubernetes/issues/221#issuecomment-544863342

**Comment by unacceptable** [comment]
A good example of a solid use case around this would be overwriting a cloud provider's default storage class.

**Comment by lawliet89** [comment]
Not stale. I am interested in this too.

**Comment by jmalloc** [comment]
This would also be useful to allow replacing the default `aws-auth` configmap added by Amazon EKS.
