### ISSUE TITLE
node_selector argument must not be quoted

### ISSUE THREAD

**Issue by reschex** [hashicorp/terraform-provider-kubernetes#928]
### Terraform Version and Provider Version
```
Terraform v0.12.26
+ provider.aws v2.70.0
+ provider.kubernetes v1.11.4
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)
- kubernetes_deployment
I suspect it will affect every resource that's trying to use node_selector

### Terraform Configuration Files
```hcl
resource "kubernetes_deployment" "cluster-autoscaler" {
    depends_on = [null_resource.wait_for_nodes]

    metadata {
        name        = "cluster-autoscaler"
        namespace   = "kube-system"
        labels      = {
            app = "cluster-autoscaler"
        }
    }
    spec {
        replicas = 1
        selector {
            match_labels = {
                app = "cluster-autoscaler"
            }
        }
        template {
            metadata {
                labels = {
                    app = "cluster-autoscaler"
                }
            }
            spec {
                node_selector {
                    "kubernetes.io/lifecycle" = "normal"
                }
                service_account_name = "cluster-autoscaler"
                container {
                [...]
```

### Expected Behavior
the node_selector key/value pair should be accepted

### Actual Behavior
```
Error: Invalid argument name

On .terraform/modules/k8s-cluster/incubator/aws-eks/cluster_autoscaler.tf line
196: Argument names must not be quoted.
```
or alternatively, if I don't quite the argument:
```
Error: Argument or block definition required

On .terraform/modules/k8s-cluster/incubator/aws-eks/cluster_autoscaler.tf line
196: An argument or block definition is required here. To set an argument, use
the equals sign "=" to introduce the argument value.
```
and lastly, if I try to escape the `.` and `/`, since I'm not allowed to quote, I get
```
Error: Invalid character

On .terraform/modules/k8s-cluster/incubator/aws-eks/cluster_autoscaler.tf line
196: This character is not used within the language.


Error: Invalid character

On .terraform/modules/k8s-cluster/incubator/aws-eks/cluster_autoscaler.tf line
196: This character is not used within the language.


Error: Argument or block definition required

On .terraform/modules/k8s-cluster/incubator/aws-eks/cluster_autoscaler.tf line
196: An argument or block definition is required here. To set an argument, use
the equals sign "=" to introduce the argument value.
```

### Steps to Reproduce
- create a module using a kubernetes_deployment resource that is using template.spec.node_selector
- `tf init` or `tf get --update` 

### Important Factoids
Relevant documentation of the option is here: https://www.terraform.io/docs/providers/kubernetes/r/deployment.html#node_selector and less than helpful.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by reschex** [comment]
A curious observation in the meantime:
My workaround is to patch the deployment post tf like so:
```
kubectl -n kube-system patch deployment cluster-autoscaler -p '{"spec": {"template": {"spec": {"nodeSelector": {"node.kubernetes.io/lifecycle": "normal"}}}}}'
```
which works fine - but when I then tf apply later, the suggested update is:
```hcl
                  ~ node_selector                    = {
                      - "node.kubernetes.io/lifecycle" = "normal" -> null
                    }
```
note that terraform itself displays the key in quotes.

Bonus:
If anybody has any ideas how I can lifecycle ignore_changes the `spec.template.spec.node_selector`, that'd be great too :)

**Comment by jrhouston** [comment]
Thanks for opening this @reschex. `node_selector` is a map but in your example it seems to be specified as a block. You'll want to use it like this:

```hcl
node_selector = {
  "node.kubernetes.io/lifecycle" = "normal"
}
```

**Comment by reschex** [comment]
Thanks @jrhouston, so it is! That makes a lot of sense. Might be worth calling that our somewhere as it wasn't obvious to me from the documentation - but that could just be me :)
