### ISSUE TITLE
kubernetes_validating_webhook_configuration namespace is not supported in schema

### ISSUE THREAD

**Issue by jcreager** [hashicorp/terraform-provider-kubernetes#933]
### Terraform Version and Provider Version

Terraform v0.12.29
provider.kubernetes: version = "~> 1.11"
kubernetes version 1.15.11

### Affected Resource(s)

- kubernetes_validating_webhook_configuration

### Terraform Configuration Files
```hcl
resource "kubernetes_validating_webhook_configuration" "ingress-nginx" {
  metadata {
    name = "ingress-nginx-admission"
    namespace = "ingress-nginx"
    labels = {
      "app.kubernetes.io/component" = "admission-webhook"

      "app.kubernetes.io/instance" = "ingress-nginx"

      "app.kubernetes.io/managed-by" = "Helm"

      "app.kubernetes.io/name" = "ingress-nginx"

      "app.kubernetes.io/version" = "0.34.1"

      "helm.sh/chart" = "ingress-nginx-2.11.1"
    }
  }

  webhook {
    name = "validate.nginx.ingress.kubernetes.io"

    admission_review_versions = ["v1", "v1beta1"]

    client_config {
      service {
        namespace = "ingress-nginx"
        name = "ingress-nginx-controller-admission"
        path = "/extensions/v1beta1/ingresses"
      }
    }

    rule {
      api_groups = ["extensions", "networking.k8s.io"]
      api_versions = ["v1beta1"]
      operations = ["CREATE", "UPDATE"]
      resources = ["ingress"]
    }

    side_effects = "None"
    failure_policy = "Fail"
  }
}
```

### Debug Output

https://gist.github.com/jcreager/27c73e475f39e71b1e45a3d6978e08b0

### Panic Output

n/a

### Expected Behavior
kubernetes_validating_webhook_configuration accepts metadata.namespace argument.

```hcl
resource "kubernetes_validating_webhook_configuration" "ingress-nginx" {
  metadata {
...
```

### Actual Behavior
kubernetes_validating_webhook_configuration does not accept metadata.namespace argument.

```
Error: Unsupported argument

  on main.tf line 531, in resource "kubernetes_validating_webhook_configuration" "ingress-nginx":
 531:     namespace = "ingress-nginx"

An argument named "namespace" is not expected here.
```

### Steps to Reproduce

1. `terraform apply` -->
1. Create a .tf file with a resource "kubernetes_validating_webhook_configuration" and include a metadata.namespace argument in the resource.
1. `terraform apply`

### Important Factoids

I believe the metadata.name argument should be allowed in the resource kubernetes_validating_webhook_configuration.  Inspecting a kubernetes_validating_webhook_configuration resource without the metadata.name argument will produce the following in kubernetes.

```
kubectl describe validatingwebhookconfigurations.admissionregistration.k8s.io ingress-nginx-admission
```
```
Name:         ingress-nginx-admission
Namespace:
```

Note that the `Namespace` is blank and that no metadata.name argument was supplied.

Additionally, I investigated the k8s API docs and found that ValidatingWebhookConfiguration has a metadata argument.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#validatingwebhookconfiguration-v1-admissionregistration-k8s-io

> Standard object metadata; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata.

After inspecting the metadata object allowed in ValidatingWebhookConfiguration I found that this object does accept a `namespace`.  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#objectmeta-v1-meta

I came across this issue while trying to convert the `ingress-nginx` manifests to hcl using k2tf.  https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.34.1/deploy/static/provider/cloud/deploy.yaml

In this manifest, the ValidatingWebhookConfiguration provides a metadata.namespace argument.  I was able to successfully apply the manifest to create an ingress-controller.  ~However, I am unable to deploy an ingress controller with the converted manifests using terraform and it appears this is due to the missing metadata.namespace argument which was omitted to pass the validation check by terraform.~  Edit: my issue related to deploying an ingress controller described above was resolved by adding `automount_service_account_token = true` to my deployment.  See https://github.com/hashicorp/terraform-provider-kubernetes/issues/424.  It appears the namespace is not required for ValidatingWebhookConfiguration in this instance, however, I believe based on the API docs for Kubernetes that a namespace can still be applied.

### References

- https://github.com/hashicorp/terraform-provider-kubernetes/issues/846

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
> After inspecting the metadata object allowed in ValidatingWebhookConfiguration I found that this object does accept a namespace. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#objectmeta-v1-meta

Hi @jcreager, while the namespace is accepted, the ValidatingWebhookConfiguration cannot be namespaced as we indicated in #846 so this is expected behaviour. I'll close this for now, please let us know if we're mistaken.
