### ISSUE TITLE
Add support for kubernetes_cluster_role data source

### ISSUE THREAD

**Issue by cann0nf0dder** [hashicorp/terraform-provider-kubernetes#934]
### Description

Error: Invalid data source

```
  on main.tf line 5, in data "kubernetes_cluster_role" "view":
   5: data "kubernetes_cluster_role" "view" {

The provider provider.kubernetes does not support data source
"kubernetes_cluster_role".
```

The only workaround currently I know of is to import the cluster role.

### Potential Terraform Configuration

unknown

### References

https://www.terraform.io/docs/providers/kubernetes/r/cluster_role.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jverce** [comment]
@jrhouston there's already an open PR that addresses this issue.
Is it possible to bump this so that it gets merged?
Thanks!
