### ISSUE TITLE
data.kubernetes_ingress, get the arguments needed for the Route53 Alias record

### ISSUE THREAD

**Issue by davorceman** [hashicorp/terraform-provider-kubernetes#942]
### Description

I would like to use kubernetes_ingress data resorurce, and pass its arguments to the Route53 resource to create alias record.

I have problem with using just terraform providers for fully automation. The problem is that if AWS ALB is provisioned via k8s ingress, then I can't recognize that via terraform to deploy Route53 record or CloudFront.

I tried with data.kubernetes_ingress but for creating Route53 Alias record I would need Alias Zone ID as well.

Something like this
```hcl
data "kubernetes_ingress" "vault" {
  metadata {
    name = "vault"
    namespace = "vault"
  }
}

resource "aws_route53_record" "vault_record" {
  zone_id = aws_route53_zone.zone.zone_id
  name    = format("vault.dev.%s", var.dns_zone_name[terraform.workspace])
  type    = "A"

  alias {
    name                   = data.kubernetes_ingress.vault.load_balancer_ingress.0.hostname
    zone_id                = ??????????
    evaluate_target_health = true
  }

  depends_on = [
    helm_release.vault
  ]
}
```

Or at least to get LB name with the data.kubernetes_ingress, then I could pass it to the data.aws_lb resource
For example

```hcl
data "kubernetes_ingress" "vault" {
  metadata {
    name = "vault"
    namespace = "vault"
  }
}

 data "aws_lb" "vault_loadbalancer" {
   name = data.kubernetes_ingress.vault.????????

   depends_on = [
     helm_release.vault
   ]
 }

resource "aws_route53_record" "vault_record" {
  zone_id = aws_route53_zone.zone.zone_id
  name    = format("vault.dev.%s", var.dns_zone_name[terraform.workspace])
  type    = "A"

  alias {
    name                   = data.aws_lb.vault_loadbalancer.dns_name
    zone_id                = data.aws_lb.vault_loadbalancer.zone_id
    evaluate_target_health = true
  }

  depends_on = [
    helm_release.vault
  ]
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by svrakitin** [comment]
The way I usually work around this is extracting this hostname from ingress controller service. 

Something like this from my module which provisions ingress-nginx and keeps its hostname in the output:
```hcl
data "kubernetes_service" "ingress_nginx" {
  metadata {
    name      = "${helm_release.ingress_nginx.name}-nginx-ingress-controller"
    namespace = kubernetes_namespace.ingress_nginx.metadata[0].name
  }
}

output "ingress_hostname" {
  value = data.kubernetes_service.ingress_nginx.load_balancer_ingress[0].hostname
}
```

**Comment by jrhouston** [comment]
I had a look into this, and it seems that this information doesn't get populated anywhere on the K8s side, either in the annotations or the status field - so there isn't much we can do inside the kubernetes provider. 

A possible workaround I thought of was using the hostname to query for the alb using the hostname, but the aws_lb resource doesn't seem to allow you to query by hostname.

A possible solution here would be to have the aws ingress controller add an annotation containing the zone id to the ingress on creation, but this is an issue we would have to open on their [repository](https://github.com/kubernetes-sigs/aws-alb-ingress-controller).

**Comment by jbg** [comment]
Not sure if it's always the case, but the first part of the DNS hostname seems to be the load balancer name. Even when the ingress name gets truncated, it's truncated in both.

For example in `k8s-default-foo-abcdef-000000.eu-central-1.elb.amazonaws.com` the load balancer name is `k8s-default-foo-abcdef`.

So... this hack does work:

```
locals {
  lb_name_parts = split("-", split(".", kubernetes_ingress.foobar.load_balancer_ingress.0.hostname).0)
}

data "aws_lb" "foobar" {
  name = join("-", slice(local.lb_name_parts, 0, length(local.lb_name_parts) - 1))
}

// now you can access the zone_id as data.aws_lb.foobar.zone_id
```

**Comment by cslinuxfr** [comment]
> Not sure if it's always the case, but the first part of the DNS hostname seems to be the load balancer name. Even when the ingress name gets truncated, it's truncated in both.
> 
> For example in `k8s-default-foo-abcdef-000000.eu-central-1.elb.amazonaws.com` the load balancer name is `k8s-default-foo-abcdef`.
> 
> So... this hack does work:
> 
> ```
> locals {
>   lb_name_parts = split("-", split(".", kubernetes_ingress.foobar.load_balancer_ingress.0.hostname).0)
> }
> 
> data "aws_lb" "foobar" {
>   name = join("-", slice(local.lb_name_parts, 0, length(local.lb_name_parts) - 1))
> }
> 
> // now you can access the zone_id as data.aws_lb.foobar.zone_id
> ```

perfect tips, thx mate !!

**Comment by uripre** [comment]
@jbg How do you address the problem that the AWS load balancer might take some time to be created?

For me, it returns a LoadBalancerNotFound 400 error (since the LB doesn't exist yet) and stops the plan. Do you only add this configuration after the LB has been independently created? I see no way to depend_on the LB since it's created asynchronously by the helm controller.

**Comment by jbg** [comment]
Terraform in general doesn't have the ability to handle that kind of dependency. You have to either add the `data` instance after creating the load balancer, or use `-target=` on the first apply to only apply the LB.

Another option is to follow the general advice to have separate states for each 'layer' of your infra. Then the `kubernetes_ingress` would exist in your k8s state, and you would use a `data` instance in another state to get its hostname to parse according to the snippet I pasted above. This is a very tidy way to handle very large Terraform-managed infra, but is probably overkill for anything small/medium sized.

**Comment by jbg** [comment]
It's maybe also worth mentioning here for anyone who is not aware, that the hosted zone IDs for AWS load balancers are fixed per-region and [documented here](https://docs.aws.amazon.com/general/latest/gr/elb.html), so another option if you don't want to use the hack I provided above is to just use the relevant zone ID from the table in the documentation.

**Comment by domeales-paloit** [comment]
I have found that as long as the `Service` has been deployed and the Load Balancer is ready you can use the following method:

```hcl
locals {
  ingress_svc_name      = "ingress-nginx-controller"
  ingress_svc_namespace = "ingress-nginx"
  ingress_load_balancer_tags = {
    "service.k8s.aws/resource" = "LoadBalancer"
    "service.k8s.aws/stack"    = "${local.ingress_svc_namespace}/${local.ingress_svc_name}"
    "elbv2.k8s.aws/cluster"    = var.cluster_id
  }
}

data "aws_lb" "ingress_load_balancer" {
  tags = local.ingress_load_balancer_tags
}

resource "aws_route53_record" "ingress_alias" {
  zone_id = var.hosted_zone_id
  name    = var.ingress_subdomain
  type    = "A"

  alias {
    name                   = "dualstack.${data.aws_lb.ingress_load_balancer[0].dns_name}"
    zone_id                = data.aws_lb.ingress_load_balancer[0].zone_id
    evaluate_target_health = true
  }
}
```

Note that the tags to use to find the Load Balancer are different depending on the type of LB and which ingress class created it, so it is good to check what the tags look like and model your tf code based on that.

Also all of this is dependent on the Load Balancer being ready when this code is run (which is my biggest issue at the moment).

**Comment by jbg** [comment]
Thanks for this @domeales-paloit, that is far cleaner than the string munging method that I've been using!

As for the LB being ready, sometimes `wait_for_load_balancer = true` on the `kubernetes_ingress` resource is sufficient, but if for any reason Terraform needs to read the `aws_lb` data source during the plan phase before the ingress is created, that won't work.

In that situation, same as any time you have an apply -> plan dependency, you have only a few options: either plan+apply twice, using `-target` the first time (workable but not great), or split your TF config into separate configs for separate "layers" to model those dependencies accurately (better, but overkill for most smaller configs).

**Comment by domeales-paloit** [comment]
@jbg Yeah I have used that `wait_for_load_balancer` before, but unfortunately in my case the ingress controller (and therefore Load Balancer) are created by ArgoCD in a separately controlled process. 

I have just added this issue on the Terraform AWS provider to see if it would be possible to co-ordinate the two processes by using a timeout on the data resource. https://github.com/hashicorp/terraform-provider-aws/issues/26026
