### ISSUE TITLE
Please reopen #882 - still not working properly

### ISSUE THREAD

**Issue by kfh** [hashicorp/terraform-provider-kubernetes#943]
Unfortunately issue #882 needs to be reopened, it still doesn't work properly. I've just tried it out with the latest provider version 1.12.0.

To reproduce use the same example as provided in #882. `terraform plan` runs this time and the expected output looks good, but when running `terraform apply` and trying to deploy to Kubernetes if fails with `webhooks[0].clientConfig: Required value: exactly one of url or service is required`. To see what's actually beeing sent over the wire i've turned on `trace logging` and to my surprise an `empty service block` has been added silently, like the following:

```
"service": {
     "namespace": "",
      "name": ""
}
```

I've also had a quick poke into the tests that should cover the mutating webhook as found here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/79621fc5b9f7092968312ca53e06fc02c0965e47/kubernetes/resource_kubernetes_mutating_webhook_configuration_test.go and can't really see where the url-functionality is verfied.

**Comment by jrhouston** [comment]
Thanks for opening this @kfh - I will reopen the previous issue.
