### ISSUE TITLE
service resource doesn't support `timeout - create`

### ISSUE THREAD

**Issue by peteroneilljr** [hashicorp/terraform-provider-kubernetes#963]
### Description

It would be helpful if the service resource supported the `create` timeout. This is helpful in case something is wrong with the config, waiting 10 min to say the creation failed can be quite annoying :) 

Other resources such as deployment allow for custom timeouts.
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment

### References

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/service

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @peteroneilljr this actually is supported by this resource if you look at the code here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/kubernetes/resource_kubernetes_service.go#L28

This is just a gap in the documentation that we need to fix.
