### ISSUE TITLE
Compile release binaries with CGO_ENABLED=1 for macos DNS resolution

### ISSUE THREAD

**Issue by mvgijssel** [hashicorp/terraform-provider-kubernetes#969]
### Description

Using `terraform-provider-kubernetes` on macos I run into the issue of https://github.com/hashicorp/terraform/issues/3536 where the plugin cannot find my kubernetes cluster. If I compile the plugin with the `CGO_ENABLED=1` on macos the plugin works as expected.

There's a cool repository which enables cross comping golang projects using a docker container https://github.com/crazy-max/xgo. Running the following commands resulted in a working binary with improved macos dns resolution:

```bash
git clone https://github.com/hashicorp/terraform-provider-kubernetes.git
go get github.com/crazy-max/xgo
xgo --targets=darwin/amd64 terraform-provider-kubernetes
```

Because it's using docker this should be pretty simple to implement in a CI job!

### References

https://github.com/hashicorp/terraform/issues/3536
https://github.com/crazy-max/xgo

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mvgijssel** [comment]
Anybody running into this should check out https://github.com/greenboxal/dns-heaven, which fixes the DNS resolution for golang programs (and others) compiled with `CGO_ENABLED=0`!

**Comment by aareet** [comment]
Thanks for this @mvgijssel, we'll need to explore a solution that works for all our providers without any other side effects in order to make this shift. Tagging this as upstream so the solution can be explored at that level.
