### ISSUE TITLE
Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

### ISSUE THREAD

**Issue by modevops** [hashicorp/terraform-provider-kubernetes#988]
### Terraform Version and Provider Version
 terraform -v
Terraform v0.12.24
+ provider.google v3.36.0
+ provider.helm v1.3.0
+ provider.kubernetes v1.13.1
+ provider.null v2.1.2
+ provider.random v2.3.0

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this. -->

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

kubernetes_namespace.nargocd: Creating...
kubernetes_namespace.prome: Creating...
kubernetes_namespace.istio-sys: Creating...

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

  on kubernetes.tf line 3, in resource "kubernetes_namespace" "prome":
   3: resource "kubernetes_namespace" "prome" {

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

  on kubernetes.tf line 15, in resource "kubernetes_namespace" "istio-sys":
  15: resource "kubernetes_namespace" "istio-sys" {

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

  on kubernetes.tf line 26, in resource "kubernetes_namespace" "nargocd":
  26: resource "kubernetes_namespace" "nargocd" {

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce

Terraform will perform the following actions:

  # helm_release.promeopt will be created
  + resource "helm_release" "promeopt" {
      + atomic                     = false
      + chart                      = "stable/prometheus-operator"
      + cleanup_on_fail            = false
      + create_namespace           = false
      + dependency_update          = false
      + disable_crd_hooks          = false
      + disable_openapi_validation = false
      + disable_webhooks           = false
      + force_update               = false
      + id                         = (known after apply)
      + lint                       = false
      + max_history                = 0
      + metadata                   = (known after apply)
      + name                       = "prometheus-operator"
      + namespace                  = "monitoring"
      + recreate_pods              = false
      + render_subchart_notes      = true
      + replace                    = false
      + reset_values               = false
      + reuse_values               = false
      + skip_crds                  = false
      + status                     = "deployed"
      + timeout                    = 300
      + verify                     = false
      + version                    = "8.13.8"
      + wait                       = true
    }

  # kubernetes_namespace.istio-sys will be created
  + resource "kubernetes_namespace" "istio-sys" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "istio-system"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

  # kubernetes_namespace.nargocd will be created
  + resource "kubernetes_namespace" "nargocd" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "istio-system"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

  # kubernetes_namespace.prome will be created
  + resource "kubernetes_namespace" "prome" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "monitoring"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

  # null_resource.argocd will be created
  + resource "null_resource" "argocd" {
      + id = (known after apply)
    }

  # null_resource.istio will be created
  + resource "null_resource" "istio" {
      + id = (known after apply)
    }

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

  on kubernetes.tf line 3, in resource "kubernetes_namespace" "prome":
   3: resource "kubernetes_namespace" "prome" {

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

  on kubernetes.tf line 15, in resource "kubernetes_namespace" "istio-sys":
  15: resource "kubernetes_namespace" "istio-sys" {

Error: Post "http://localhost/api/v1/namespaces": dial tcp [::1]:80: connect: connection refused

  on kubernetes.tf line 26, in resource "kubernetes_namespace" "nargocd":
  26: resource "kubernetes_namespace" "nargocd" {

Why is not using my current context  in kubectl to create the namespaces?  I cannot put additional information in the provider because the purpose is to build and add essential services to cluster.

**Comment by aareet** [comment]
@modevops can you share your TF configuration? we need that to determine why the provider is not picking up the context.

**Comment by adamrushuk** [comment]
I've also seen similar errors using azurerm `2.27.0` with the following versions of this `kubernetes` provider:

- `v1.11.4`
- `v1.12.0`
- `v1.13.2`

However, pinning azurerm to `2.26.0`, worked with kubernetes `1.10.0`

**Comment by adamrushuk** [comment]
@modevops I've recreated the same issue and found the fix for me.
You need to ensure you use `load_config_file = false` in the `provider "kubernetes" {}` block, eg:

https://github.com/adamrushuk/aks-nexus-velero/blob/aade3c92ea8d1d2433b43b0b7e24e9d99560edb3/terraform/providers.tf#L32-L39

Hopefully this works for you too.

**Comment by aareet** [comment]
Thanks for your help @adamrushuk , I'll close this for now @modevops, please reopen if this doesn't resolve for you.
