### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform-provider-kubernetes#990]
There are many broken links in the ./website directory. https://gist.githubusercontent.com/dak1n1/e71930a082cbaaef4137a5cc8749697a/raw/7b3ca8a6311c5419ee905fa07bb83620c42a9bc8/gistfile1.txt

Once those are fixed, the links check can be enabled. (See makefile). 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by neha-viswanathan** [comment]
@dak1n1 I'd like to work on this issue.

**Comment by dak1n1** [comment]
@neha-viswanathan  That's great! Thanks for offering. The list above is probably still accurate, but here is a command that optionally could be used to get the current list of broken links, in case anything has changed:

https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/GNUmakefile#L129

You could uncomment that line and run `make website-lint` to run the link check, if you wanted. Either way is ok. Thanks!

**Comment by neha-viswanathan** [comment]
@dak1n1 Hello Stef, There are several references of these links in the go code as well. Should I fix them too?

**Comment by dak1n1** [comment]
@neha-viswanathan For the Go code, you might want to wait until this PR is merged. It touches most of the .go files since it's an SDK upgrade, which would mean potential merge conflicts. https://github.com/hashicorp/terraform-provider-kubernetes/pull/1027 But after it's merged, you're welcome to fix as many links as you like! :smile:

**Comment by dak1n1** [comment]
@neha-viswanathan  Thanks for the PR! I just placed this issue into our queue so the next person on bug-duty can review it. (CC @jrhouston FYI)
