### ISSUE TITLE
kubernetes_pod_security_policy: allowed_host_paths bug

### ISSUE THREAD

**Issue by asychev** [hashicorp/terraform-provider-kubernetes#997]
### Terraform Version and Provider Version
Terraform version: `0.12.29`
Kubenetes Provider version: `1.11.4`

### Affected Resource(s)
- kubernetes_pod_security_policy

### Terraform Configuration Files
```hcl
resource "kubernetes_pod_security_policy" "psp_restricted" {
  metadata {
    name = psp.restricted
  }

  spec {
    privileged                 = false
    allow_privilege_escalation = false

    required_drop_capabilities = ["ALL"]

    allowed_host_paths {
      path_prefix = "/var/run/sds"
      read_only   = true
    }

    volumes = [
      "hostPath",
      "configMap",
      "emptyDir",
      "projected",
      "secret",
      "downwardAPI",
      "persistentVolumeClaim"
    ]

    host_network = false
    host_ipc     = false
    host_pid     = false

    run_as_user {
      rule = "MustRunAsNonRoot"
    }

    se_linux {
      rule = "RunAsAny"
    }

    supplemental_groups {
      rule = "MustRunAs"
      range {
        min = 1
        max = 65535
      }
    }

    fs_group {
      rule = "MustRunAs"
      range {
        min = 1
        max = 65535
      }
    }

    read_only_root_filesystem = false
  }
}
```

### Debug Output

https://gist.github.com/asychev/7e857eea33db6bbd96ae211cfa9250b4

### Expected Behavior

Valid PSP apllied to the kubernetes cluster

### Actual Behavior

`Error: Failed to update PodSecurityPolicy: PodSecurityPolicy.extensions "psp.restricted" is invalid: spec.allowedHostPaths[0]: Required value: is required`

### Steps to Reproduce
1. `terraform apply`

### Important Factoids

We use Kubernetes 1.15

According to the [documentation](https://v1-15.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#allowedhostpath-v1beta1-policy) Kubernetes API expect `pathPrefix` and `readOnly` fields, but got `path_prefix` and `read_only`. Bug should be somewhere [here](https://github.com/hashicorp/terraform-provider-kubernetes/blob/4ffad95ca115c78233a1eb737ebc5e5fc48615d4/kubernetes/structure_pod_security_policy_spec.go#L321).

Also It is worth mentioning that this syntax is a bit confusing for me:
```hcl
allowed_host_paths {
  path_prefix = "/one"
  read_only   = true
}

allowed_host_paths {
  path_prefix = "/two"
  read_only   = false
}
```
Better if it would be:
```hcl
allowed_host_path {
  path_prefix = "/one"
  read_only   = true
}

allowed_host_path {
  path_prefix = "/two"
  read_only   = false
}
```
or something like
```hcl
allowed_host_paths = [
  {
    path_prefix = "/one"
    read_only   = true
  },
  {
    path_prefix = "/two"
    read_only   = false
  }
]
```
### References

None

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by asychev** [comment]
Could somebody take a look please?

**Comment by asychev** [comment]
@paultyng Could you please help with this?

**Comment by alexsomesan** [comment]
@asychev As a matter of fact @paultyng is not involved with the Kubernetes provider anymore.

As you may have noticed from the activity log, this issue has been processed through our triage process and is awaiting scheduling on a sprint. You can find more about the process here: https://github.com/hashicorp/terraform-provider-kubernetes/blob/master/_about/ISSUES.md

I can confirm this is a bug and was able to reproduce it also on K8s 1.19. Please bear with us while we find the a slot for it in our sprint planning. Alternatively, we welcome a PR with a fix if you wish to do so.
